// 合併「規則變位引擎」與「不規則動詞資料表」，產生單一動詞的完整變位結果，
// 並提供動詞搜尋與「變位形式反查原形」的功能。

import {
  conjugateRegular, buildSubjuntivoImperfecto, buildCompound, buildImperativo,
  buildFuturoSimple, buildCondicionalSimple, HABER_AUX,
} from "./conjugationEngine";
import { IRREGULAR_VERBS } from "./irregularVerbs";
import { VERB_INDEX } from "./verbIndex";

const INCOMPLETE = "（此時態資料稍後加入）";
const INCOMPLETE_SIX = { yo: INCOMPLETE, tu: INCOMPLETE, elEllaUsted: INCOMPLETE, nosotros: INCOMPLETE, vosotros: INCOMPLETE, ellosEllasUstedes: INCOMPLETE };

function stripAccents(text) {
  return text.normalize("NFD").replace(new RegExp("[\\u0300-\\u036f]", "g"), "");
}

function mergeIrregular(base, irr) {
  const presente = irr.presente || INCOMPLETE_SIX;
  const preteritoIndefinido = irr.preteritoIndefinido || INCOMPLETE_SIX;
  const preteritoImperfecto = irr.preteritoImperfecto || base.preteritoImperfecto;
  const subjuntivoPresente = irr.subjuntivoPresente || INCOMPLETE_SIX;
  const participio = irr.participio || base.participio;
  const gerundio = irr.gerundio || base.gerundio;
  const futuroBase = irr.futureStem || base.infinitivo;
  const futuroSimple = buildFuturoSimple(futuroBase);
  const condicionalSimple = buildCondicionalSimple(futuroBase);
  const subjuntivoImperfecto = preteritoIndefinido !== INCOMPLETE_SIX
    ? buildSubjuntivoImperfecto(preteritoIndefinido.ellosEllasUstedes)
    : INCOMPLETE_SIX;
  const imperativo = buildImperativo(presente, subjuntivoPresente, base.infinitivo);
  if (irr.tuAfirmativo) imperativo.afirmativo.tu = irr.tuAfirmativo;

  return {
    infinitivo: base.infinitivo,
    ending: base.ending,
    presente,
    preteritoIndefinido,
    preteritoImperfecto,
    futuroSimple,
    condicionalSimple,
    preteritoPerfecto: buildCompound(HABER_AUX.presente, participio),
    pluscuamperfecto: buildCompound(HABER_AUX.preteritoImperfecto, participio),
    subjuntivoPresente,
    subjuntivoImperfecto,
    subjuntivoPreteritoPerfecto: buildCompound(HABER_AUX.subjuntivoPresente, participio),
    imperativoAfirmativo: imperativo.afirmativo,
    imperativoNegativo: imperativo.negativo,
    gerundio,
    participio,
  };
}

function mergeRegularOverrides(base, overrides) {
  if (!overrides) return base;
  const participio = overrides.participio || base.participio;
  const gerundio = overrides.gerundio || base.gerundio;
  return {
    ...base,
    participio,
    gerundio,
    preteritoPerfecto: buildCompound(HABER_AUX.presente, participio),
    pluscuamperfecto: buildCompound(HABER_AUX.preteritoImperfecto, participio),
    subjuntivoPreteritoPerfecto: buildCompound(HABER_AUX.subjuntivoPresente, participio),
  };
}

// entry: 來自 VERB_INDEX 的一筆資料，或呼叫端自行組出的臨時 entry（用於自動生成規則動詞）。
export function getConjugation(entry) {
  const base = conjugateRegular(entry.infinitive);
  if (!base) return null;
  if (entry.type === "irregular") {
    const irr = IRREGULAR_VERBS[entry.infinitive];
    if (!irr) {
      return { ...base, presente: INCOMPLETE_SIX, preteritoIndefinido: INCOMPLETE_SIX, subjuntivoPresente: INCOMPLETE_SIX };
    }
    return mergeIrregular(base, irr);
  }
  return mergeRegularOverrides(base, entry.overrides);
}

const ENDING_RE = /(ar|er|ir)$/;

// 找不到動詞資料時的解析：先查索引；查不到但看起來像規則動詞（-ar/-er/-ir 結尾）就自動生成。
export function resolveVerb(rawInfinitive) {
  const infinitive = rawInfinitive.trim().toLowerCase();
  const entry = VERB_INDEX.find(v => v.infinitive === infinitive);
  if (entry) {
    return { entry, conjugation: getConjugation(entry), autoGenerated: false, notFound: false };
  }
  if (ENDING_RE.test(infinitive)) {
    const autoEntry = { infinitive, zh: null, en: null, type: "regular", ending: infinitive.slice(-2), level: null };
    return { entry: autoEntry, conjugation: getConjugation(autoEntry), autoGenerated: true, notFound: false };
  }
  return { entry: null, conjugation: null, autoGenerated: false, notFound: true };
}

export function searchVerbs(query) {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const qNoAccent = stripAccents(q);
  return VERB_INDEX.filter(v =>
    v.infinitive.includes(q) ||
    stripAccents(v.infinitive).includes(qNoAccent) ||
    (v.zh && v.zh.includes(query.trim())) ||
    (v.en && v.en.toLowerCase().includes(q))
  ).slice(0, 30);
}

// ─── 反查索引：把每個收錄動詞的完整變位表攤平成 { 變位形式 → [ {infinitive, tense, person} ] } ───

const TENSE_LABELS = {
  presente: "Presente 現在時",
  preteritoIndefinido: "Pretérito indefinido 簡單過去時",
  preteritoImperfecto: "Pretérito imperfecto 未完成過去時",
  futuroSimple: "Futuro simple 簡單將來時",
  condicionalSimple: "Condicional simple 條件式",
  subjuntivoPresente: "Presente de subjuntivo 現在虛擬式",
  subjuntivoImperfecto: "Imperfecto de subjuntivo 未完成過去虛擬式",
};

const PERSON_LABELS_SHORT = {
  yo: "yo（我）", tu: "tú（你）", elEllaUsted: "él / ella / usted（他／她／您）",
  nosotros: "nosotros（我們）", vosotros: "vosotros（你們）", ellosEllasUstedes: "ellos / ellas / ustedes（他們／您們）",
};

let reverseIndexCache = null;

function buildReverseIndex() {
  const index = new Map();
  function add(form, infinitive, tenseLabel, personLabel) {
    if (!form || form === INCOMPLETE) return;
    const key = form.toLowerCase();
    if (!index.has(key)) index.set(key, []);
    index.get(key).push({ infinitive, tenseLabel, personLabel });
  }

  for (const entry of VERB_INDEX) {
    const conj = getConjugation(entry);
    if (!conj) continue;
    for (const [tenseKey, label] of Object.entries(TENSE_LABELS)) {
      const table = conj[tenseKey];
      if (!table) continue;
      for (const personKey of Object.keys(PERSON_LABELS_SHORT)) {
        add(table[personKey], entry.infinitive, label, PERSON_LABELS_SHORT[personKey]);
      }
    }
    // 命令式（去掉否定式的 "no " 前綴後索引）
    if (conj.imperativoAfirmativo) {
      for (const [p, form] of Object.entries(conj.imperativoAfirmativo)) add(form, entry.infinitive, "Imperativo 肯定命令式", p);
    }
    if (conj.imperativoNegativo) {
      for (const [p, form] of Object.entries(conj.imperativoNegativo)) add(form.replace(/^no\s+/, ""), entry.infinitive, "Imperativo 否定命令式", p);
    }
    add(conj.gerundio, entry.infinitive, "Gerundio 現在分詞", "—");
    add(conj.participio, entry.infinitive, "Participio 過去分詞", "—");
  }
  return index;
}

export function reverseLookup(rawForm) {
  if (!reverseIndexCache) reverseIndexCache = buildReverseIndex();
  const form = rawForm.trim().toLowerCase();
  const direct = reverseIndexCache.get(form);
  if (direct && direct.length) return direct;
  // accent-insensitive fallback
  const noAccent = stripAccents(form);
  const hits = [];
  for (const [key, entries] of reverseIndexCache.entries()) {
    if (stripAccents(key) === noAccent) hits.push(...entries);
  }
  return hits;
}
