// 常用形容詞：每筆資料的 forms 顯示陽性單數／陰性單數／陽性複數／陰性複數四種變化。
// 例句盡量各給一個陽性、一個陰性搭配名詞，讓學習者看到性別配合的實際效果。

export const ADJECTIVES_WORDS = [
  {
    id: "bon", word: "bon", displayWord: "bon / bonne", partOfSpeech: "adjective",
    gender: null, forms: { ms: "bon", fs: "bonne", mp: "bons", fp: "bonnes" }, irregular: true, level: "A1", frequencyRank: 1, category: "adjectives",
    meanings: ["好的", "好吃的"],
    usageSummary: "形容人、事、物的品質好，也常用來形容食物好吃。",
    patterns: ["名詞 ＋ être ＋ bon(ne)", "un/une ＋ bon(ne) ＋ 名詞"],
    conjugation: null,
    examples: [
      { french: "C'est un bon restaurant.", chinese: "這是一間好餐廳。", note: "restaurant 是陽性名詞，用 bon。" },
      { french: "Elle est bonne en français.", chinese: "她法語很好。", note: "elle 是陰性，用 bonne。" },
    ],
    usageTip: "bon 大多放在名詞前面，跟大部分形容詞放後面不同。",
    collocations: [{ french: "être bon(ne) en", chinese: "在……方面很好" }],
    commonMistakes: [],
    relatedWords: ["mauvais"],
    tags: ["形容詞", "高頻"], audio: null,
  },
  {
    id: "mauvais", word: "mauvais", displayWord: "mauvais / mauvaise", partOfSpeech: "adjective",
    gender: null, forms: { ms: "mauvais", fs: "mauvaise", mp: "mauvais", fp: "mauvaises" }, irregular: true, level: "A1", frequencyRank: 2, category: "adjectives",
    meanings: ["壞的", "不好的"],
    usageSummary: "bon 的反義詞，形容品質不好、糟糕。",
    patterns: ["名詞 ＋ être ＋ mauvais(e)"],
    conjugation: null,
    examples: [
      { french: "C'est un mauvais film.", chinese: "這是一部糟糕的電影。", note: "" },
      { french: "La nouvelle est mauvaise.", chinese: "這個消息不好。", note: "nouvelle（消息）是陰性名詞。" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["bon"],
    tags: ["形容詞"], audio: null,
  },
  {
    id: "grand", word: "grand", displayWord: "grand / grande", partOfSpeech: "adjective",
    gender: null, forms: { ms: "grand", fs: "grande", mp: "grands", fp: "grandes" }, irregular: false, level: "A1", frequencyRank: 3, category: "adjectives",
    meanings: ["大的", "高的"],
    usageSummary: "形容體積大或身高高，可用於人或物。",
    patterns: ["名詞 ＋ être ＋ grand(e)", "un/une ＋ grand(e) ＋ 名詞"],
    conjugation: null,
    examples: [
      { french: "Un grand appartement.", chinese: "一間大公寓。", note: "" },
      { french: "Une grande maison.", chinese: "一間大房子。", note: "maison 是陰性，用 grande。" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["petit"],
    tags: ["形容詞", "高頻"], audio: null,
  },
  {
    id: "petit", word: "petit", displayWord: "petit / petite", partOfSpeech: "adjective",
    gender: null, forms: { ms: "petit", fs: "petite", mp: "petits", fp: "petites" }, irregular: false, level: "A1", frequencyRank: 4, category: "adjectives",
    meanings: ["小的"],
    usageSummary: "形容體積或年紀小，grand 的反義詞。",
    patterns: ["un/une ＋ petit(e) ＋ 名詞"],
    conjugation: null,
    examples: [
      { french: "Un petit appartement.", chinese: "一間小公寓。", note: "" },
      { french: "Une petite maison.", chinese: "一間小房子。", note: "maison 是陰性，用 petite。" },
    ],
    usageTip: "形容詞通常需要配合名詞的陰陽性和單複數變化。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["grand"],
    tags: ["形容詞", "高頻"], audio: null,
  },
  {
    id: "jeune", word: "jeune", displayWord: "jeune", partOfSpeech: "adjective",
    gender: null, forms: { ms: "jeune", fs: "jeune", mp: "jeunes", fp: "jeunes" }, irregular: false, level: "A1", frequencyRank: 5, category: "adjectives",
    meanings: ["年輕的"],
    usageSummary: "形容年紀小，陰陽性同形，只有單複數變化。",
    patterns: ["名詞 ＋ être ＋ jeune"],
    conjugation: null,
    examples: [
      { french: "Il est jeune.", chinese: "他很年輕。", note: "" },
      { french: "Elle est jeune aussi.", chinese: "她也很年輕。", note: "陰性同形，不加 e。" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["vieux"],
    tags: ["形容詞"], audio: null,
  },
  {
    id: "vieux", word: "vieux", displayWord: "vieux / vieille", partOfSpeech: "adjective",
    gender: null, forms: { ms: "vieux", fs: "vieille", mp: "vieux", fp: "vieilles" }, irregular: true, level: "A1", frequencyRank: 6, category: "adjectives",
    meanings: ["老的", "舊的"],
    usageSummary: "形容年紀大或物品舊，變化不規則。陽性單數在母音或啞音 h 前改用 vieil。",
    patterns: ["un/une ＋ vieux/vieille ＋ 名詞"],
    conjugation: null,
    examples: [
      { french: "Un vieux monsieur.", chinese: "一位年長的先生。", note: "" },
      { french: "Une vieille maison.", chinese: "一間老房子。", note: "" },
      { french: "Un vieil ami.", chinese: "一位老朋友。", note: "ami 母音開頭，vieux 改成 vieil。" },
    ],
    usageTip: "陽性單數在母音／啞音 h 開頭的名詞前要用 vieil，不能用 vieux。",
    collocations: [],
    commonMistakes: [{ wrong: "un vieux ami", correct: "un vieil ami", explanation: "ami 是母音開頭，陽性單數形容詞要改用 vieil。" }],
    relatedWords: ["jeune", "nouveau"],
    tags: ["形容詞", "不規則"], audio: null,
  },
  {
    id: "nouveau", word: "nouveau", displayWord: "nouveau / nouvelle", partOfSpeech: "adjective",
    gender: null, forms: { ms: "nouveau", fs: "nouvelle", mp: "nouveaux", fp: "nouvelles" }, irregular: true, level: "A1", frequencyRank: 7, category: "adjectives",
    meanings: ["新的"],
    usageSummary: "形容新的事物，變化不規則。陽性單數在母音或啞音 h 前改用 nouvel。",
    patterns: ["un/une ＋ nouveau/nouvelle ＋ 名詞"],
    conjugation: null,
    examples: [
      { french: "Un nouveau livre.", chinese: "一本新書。", note: "" },
      { french: "Une nouvelle voiture.", chinese: "一輛新車。", note: "" },
      { french: "Un nouvel ami.", chinese: "一位新朋友。", note: "ami 母音開頭，nouveau 改成 nouvel。" },
    ],
    usageTip: "陽性單數在母音／啞音 h 開頭的名詞前要用 nouvel。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["vieux"],
    tags: ["形容詞", "不規則"], audio: null,
  },
  {
    id: "beau", word: "beau", displayWord: "beau / belle", partOfSpeech: "adjective",
    gender: null, forms: { ms: "beau", fs: "belle", mp: "beaux", fp: "belles" }, irregular: true, level: "A1", frequencyRank: 8, category: "adjectives",
    meanings: ["漂亮的", "英俊的", "美好的"],
    usageSummary: "形容外表好看或天氣好，變化不規則。陽性單數在母音或啞音 h 前改用 bel。",
    patterns: ["un/une ＋ beau/belle ＋ 名詞"],
    conjugation: null,
    examples: [
      { french: "Il fait beau aujourd'hui.", chinese: "今天天氣很好。", note: "固定用法：il fait beau＝天氣好。" },
      { french: "Une belle maison.", chinese: "一間漂亮的房子。", note: "" },
    ],
    usageTip: "",
    collocations: [{ french: "il fait beau", chinese: "天氣好" }],
    commonMistakes: [],
    relatedWords: ["joli"],
    tags: ["形容詞", "不規則", "高頻"], audio: null,
  },
  {
    id: "joli", word: "joli", displayWord: "joli / jolie", partOfSpeech: "adjective",
    gender: null, forms: { ms: "joli", fs: "jolie", mp: "jolis", fp: "jolies" }, irregular: false, level: "A1", frequencyRank: 9, category: "adjectives",
    meanings: ["漂亮的", "可愛的"],
    usageSummary: "形容外表可愛、好看，比 beau 語氣稍微輕巧。",
    patterns: ["un/une ＋ joli(e) ＋ 名詞"],
    conjugation: null,
    examples: [
      { french: "Une jolie robe.", chinese: "一件漂亮的洋裝。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["beau"],
    tags: ["形容詞"], audio: null,
  },
  {
    id: "facile", word: "facile", displayWord: "facile", partOfSpeech: "adjective",
    gender: null, forms: { ms: "facile", fs: "facile", mp: "faciles", fp: "faciles" }, irregular: false, level: "A1", frequencyRank: 10, category: "adjectives",
    meanings: ["容易的"],
    usageSummary: "形容事情簡單、不困難，陰陽性同形。",
    patterns: ["C'est facile.", "名詞 ＋ être ＋ facile"],
    conjugation: null,
    examples: [
      { french: "C'est facile !", chinese: "這很簡單！", note: "" },
      { french: "Cet exercice est facile.", chinese: "這個練習很簡單。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["difficile"],
    tags: ["形容詞", "高頻"], audio: null,
  },
  {
    id: "difficile", word: "difficile", displayWord: "difficile", partOfSpeech: "adjective",
    gender: null, forms: { ms: "difficile", fs: "difficile", mp: "difficiles", fp: "difficiles" }, irregular: false, level: "A1", frequencyRank: 11, category: "adjectives",
    meanings: ["困難的"],
    usageSummary: "facile 的反義詞，形容事情難、複雜，陰陽性同形。",
    patterns: ["C'est difficile.", "名詞 ＋ être ＋ difficile"],
    conjugation: null,
    examples: [
      { french: "Le français, c'est difficile ?", chinese: "法語難嗎？", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["facile"],
    tags: ["形容詞", "高頻"], audio: null,
  },
  {
    id: "important", word: "important", displayWord: "important / importante", partOfSpeech: "adjective",
    gender: null, forms: { ms: "important", fs: "importante", mp: "importants", fp: "importantes" }, irregular: false, level: "A1", frequencyRank: 12, category: "adjectives",
    meanings: ["重要的"],
    usageSummary: "形容事情具有重要性。",
    patterns: ["C'est important.", "名詞 ＋ être ＋ important(e)"],
    conjugation: null,
    examples: [
      { french: "C'est très important pour moi.", chinese: "這對我來說非常重要。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: [],
    tags: ["形容詞"], audio: null,
  },
  {
    id: "possible", word: "possible", displayWord: "possible", partOfSpeech: "adjective",
    gender: null, forms: { ms: "possible", fs: "possible", mp: "possibles", fp: "possibles" }, irregular: false, level: "A1", frequencyRank: 13, category: "adjectives",
    meanings: ["可能的"],
    usageSummary: "形容某事有可能發生或做到，陰陽性同形。",
    patterns: ["C'est possible.", "Il est possible de + 動詞原形"],
    conjugation: null,
    examples: [
      { french: "C'est possible ?", chinese: "這可能嗎？", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: [],
    tags: ["形容詞"], audio: null,
  },
  {
    id: "content", word: "content", displayWord: "content / contente", partOfSpeech: "adjective",
    gender: null, forms: { ms: "content", fs: "contente", mp: "contents", fp: "contentes" }, irregular: false, level: "A1", frequencyRank: 14, category: "adjectives",
    meanings: ["高興的", "滿意的"],
    usageSummary: "形容感到開心、滿意，常搭配 être 使用。",
    patterns: ["主語 ＋ être ＋ content(e)"],
    conjugation: null,
    examples: [
      { french: "Je suis content de te voir.", chinese: "我很高興見到你。", note: "content de + 動詞原形，表示「因……而高興」。" },
      { french: "Elle est contente de son travail.", chinese: "她對自己的工作很滿意。", note: "" },
    ],
    usageTip: "",
    collocations: [{ french: "être content(e) de", chinese: "對……感到高興" }],
    commonMistakes: [],
    relatedWords: [],
    tags: ["形容詞", "高頻"], audio: null,
  },
  {
    id: "fatigue", word: "fatigué", displayWord: "fatigué / fatiguée", partOfSpeech: "adjective",
    gender: null, forms: { ms: "fatigué", fs: "fatiguée", mp: "fatigués", fp: "fatiguées" }, irregular: false, level: "A1", frequencyRank: 15, category: "adjectives",
    meanings: ["疲倦的", "累的"],
    usageSummary: "形容感到疲累，搭配 être 使用。",
    patterns: ["主語 ＋ être ＋ fatigué(e)"],
    conjugation: null,
    examples: [
      { french: "Nous sommes fatigués.", chinese: "我們很累。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: [],
    tags: ["形容詞", "高頻"], audio: null,
  },
  {
    id: "malade", word: "malade", displayWord: "malade", partOfSpeech: "adjective",
    gender: null, forms: { ms: "malade", fs: "malade", mp: "malades", fp: "malades" }, irregular: false, level: "A1", frequencyRank: 16, category: "adjectives",
    meanings: ["生病的"],
    usageSummary: "形容身體不舒服、生病，陰陽性同形。",
    patterns: ["主語 ＋ être ＋ malade"],
    conjugation: null,
    examples: [
      { french: "Il est malade aujourd'hui.", chinese: "他今天生病了。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: [],
    tags: ["形容詞"], audio: null,
  },
  {
    id: "chaud", word: "chaud", displayWord: "chaud / chaude", partOfSpeech: "adjective",
    gender: null, forms: { ms: "chaud", fs: "chaude", mp: "chauds", fp: "chaudes" }, irregular: false, level: "A1", frequencyRank: 17, category: "adjectives",
    meanings: ["熱的", "溫暖的"],
    usageSummary: "形容溫度高，也用於固定用法「il fait chaud」（天氣熱）。",
    patterns: ["名詞 ＋ être ＋ chaud(e)", "il fait chaud"],
    conjugation: null,
    examples: [
      { french: "Le café est chaud.", chinese: "咖啡是熱的。", note: "" },
      { french: "Il fait chaud aujourd'hui.", chinese: "今天天氣很熱。", note: "" },
    ],
    usageTip: "",
    collocations: [{ french: "il fait chaud", chinese: "天氣熱" }],
    commonMistakes: [],
    relatedWords: ["froid"],
    tags: ["形容詞", "高頻"], audio: null,
  },
  {
    id: "froid", word: "froid", displayWord: "froid / froide", partOfSpeech: "adjective",
    gender: null, forms: { ms: "froid", fs: "froide", mp: "froids", fp: "froides" }, irregular: false, level: "A1", frequencyRank: 18, category: "adjectives",
    meanings: ["冷的"],
    usageSummary: "形容溫度低，chaud 的反義詞，也用於固定用法「il fait froid」。",
    patterns: ["名詞 ＋ être ＋ froid(e)", "il fait froid"],
    conjugation: null,
    examples: [
      { french: "L'eau est froide.", chinese: "水是冷的。", note: "" },
      { french: "Il fait froid en hiver.", chinese: "冬天天氣冷。", note: "" },
    ],
    usageTip: "",
    collocations: [{ french: "il fait froid", chinese: "天氣冷" }],
    commonMistakes: [],
    relatedWords: ["chaud"],
    tags: ["形容詞", "高頻"], audio: null,
  },
  {
    id: "cher", word: "cher", displayWord: "cher / chère", partOfSpeech: "adjective",
    gender: null, forms: { ms: "cher", fs: "chère", mp: "chers", fp: "chères" }, irregular: true, level: "A1", frequencyRank: 19, category: "adjectives",
    meanings: ["貴的", "親愛的"],
    usageSummary: "放在名詞後表示「貴」，放在名詞前表示「親愛的」，意思會不同。",
    patterns: ["名詞 ＋ cher/chère（貴）", "cher/chère ＋ 名詞（親愛的）"],
    conjugation: null,
    examples: [
      { french: "Ce restaurant est cher.", chinese: "這間餐廳很貴。", note: "" },
      { french: "Cher client.", chinese: "親愛的顧客。", note: "放在名詞前，意思變成「親愛的」。" },
    ],
    usageTip: "位置會改變意思：放後面＝「貴」，放前面＝「親愛的」。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["gratuit"],
    tags: ["形容詞", "高頻"], audio: null,
  },
  {
    id: "gratuit", word: "gratuit", displayWord: "gratuit / gratuite", partOfSpeech: "adjective",
    gender: null, forms: { ms: "gratuit", fs: "gratuite", mp: "gratuits", fp: "gratuites" }, irregular: false, level: "A1", frequencyRank: 20, category: "adjectives",
    meanings: ["免費的"],
    usageSummary: "形容不需付費，cher 的反義詞。",
    patterns: ["名詞 ＋ être ＋ gratuit(e)"],
    conjugation: null,
    examples: [
      { french: "L'entrée est gratuite.", chinese: "入場是免費的。", note: "entrée 是陰性名詞。" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["cher"],
    tags: ["形容詞"], audio: null,
  },
];
