export const ADVERBS_WORDS = [
  {
    id: "tres", word: "très", displayWord: "très", partOfSpeech: "adverb",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 1, category: "adverbs",
    meanings: ["很", "非常"],
    usageSummary: "放在形容詞或副詞前面加強程度。",
    patterns: ["très ＋ 形容詞／副詞"],
    conjugation: null,
    examples: [
      { french: "Je suis très content.", chinese: "我非常高興。", note: "" },
      { french: "C'est très bien.", chinese: "這非常好。", note: "" },
    ],
    usageTip: "très 不能直接修飾動詞（不能說 j'aime très），要用 beaucoup。",
    collocations: [],
    commonMistakes: [{ wrong: "J'aime très le café.", correct: "J'aime beaucoup le café.", explanation: "très 只能修飾形容詞或副詞，修飾動詞要用 beaucoup。" }],
    relatedWords: ["beaucoup"],
    tags: ["副詞", "高頻"], audio: null,
  },
  {
    id: "bien", word: "bien", displayWord: "bien", partOfSpeech: "adverb",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 2, category: "adverbs",
    meanings: ["好", "順利"],
    usageSummary: "修飾動詞，表示做得好、狀態好。",
    patterns: ["動詞 ＋ bien"],
    conjugation: null,
    examples: [
      { french: "Ça va bien.", chinese: "一切都好。", note: "" },
      { french: "Il parle bien français.", chinese: "他法語說得很好。", note: "" },
    ],
    usageTip: "bien 是副詞，不要跟形容詞 bon 混淆：bon 修飾名詞，bien 修飾動詞。",
    collocations: [],
    commonMistakes: [{ wrong: "Il parle bon français.", correct: "Il parle bien français.", explanation: "修飾動詞 parler 要用副詞 bien，不能用形容詞 bon。" }],
    relatedWords: ["mal", "bon"],
    tags: ["副詞", "高頻"], audio: null,
  },
  {
    id: "mal", word: "mal", displayWord: "mal", partOfSpeech: "adverb",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 3, category: "adverbs",
    meanings: ["不好", "差"],
    usageSummary: "bien 的反義詞，修飾動詞表示做得不好。",
    patterns: ["動詞 ＋ mal"],
    conjugation: null,
    examples: [
      { french: "Il chante mal.", chinese: "他唱歌唱得不好。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["bien"],
    tags: ["副詞"], audio: null,
  },
  {
    id: "beaucoup", word: "beaucoup", displayWord: "beaucoup", partOfSpeech: "adverb",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 4, category: "adverbs",
    meanings: ["很多", "非常"],
    usageSummary: "修飾動詞，表示程度或數量多；跟 de 連用表示「很多的……」。",
    patterns: ["動詞 ＋ beaucoup", "beaucoup de ＋ 名詞"],
    conjugation: null,
    examples: [
      { french: "J'aime beaucoup ce film.", chinese: "我非常喜歡這部電影。", note: "" },
      { french: "Il y a beaucoup de monde.", chinese: "有很多人。", note: "beaucoup de 後面名詞不加冠詞。" },
    ],
    usageTip: "beaucoup de 後面的名詞不加冠詞（不是 beaucoup de la monde）。",
    collocations: [{ french: "beaucoup de", chinese: "很多的……" }],
    commonMistakes: [],
    relatedWords: ["très", "peu"],
    tags: ["副詞", "高頻"], audio: null,
  },
  {
    id: "peu", word: "peu", displayWord: "peu", partOfSpeech: "adverb",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 5, category: "adverbs",
    meanings: ["很少", "一點點"],
    usageSummary: "beaucoup 的反義詞，表示程度或數量少。",
    patterns: ["動詞 ＋ peu", "un peu ＋ 形容詞"],
    conjugation: null,
    examples: [
      { french: "Je dors peu.", chinese: "我睡得很少。", note: "" },
      { french: "Je suis un peu fatigué.", chinese: "我有點累。", note: "un peu＝「有點」，語氣比 peu 溫和。" },
    ],
    usageTip: "un peu（有點）跟 peu（很少）意思不同：un peu 是正面/中性的少量，peu 單獨用通常帶負面語氣。",
    collocations: [{ french: "un peu", chinese: "有點、一點點" }],
    commonMistakes: [],
    relatedWords: ["beaucoup"],
    tags: ["副詞"], audio: null,
  },
  {
    id: "toujours", word: "toujours", displayWord: "toujours", partOfSpeech: "adverb",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 6, category: "adverbs",
    meanings: ["總是", "一直"],
    usageSummary: "表示動作發生的頻率是每次都、一直。",
    patterns: ["主語 ＋ 動詞 ＋ toujours"],
    conjugation: null,
    examples: [
      { french: "Il est toujours en retard.", chinese: "他總是遲到。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["souvent", "jamais"],
    tags: ["副詞", "高頻"], audio: null,
  },
  {
    id: "souvent", word: "souvent", displayWord: "souvent", partOfSpeech: "adverb",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 7, category: "adverbs",
    meanings: ["常常"],
    usageSummary: "表示動作頻率高，但不是每次都發生。",
    patterns: ["主語 ＋ 動詞 ＋ souvent"],
    conjugation: null,
    examples: [
      { french: "Je mange souvent au restaurant.", chinese: "我常常在餐廳吃飯。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["parfois", "toujours"],
    tags: ["副詞", "高頻"], audio: null,
  },
  {
    id: "parfois", word: "parfois", displayWord: "parfois", partOfSpeech: "adverb",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 8, category: "adverbs",
    meanings: ["有時候"],
    usageSummary: "表示動作偶爾發生，頻率比 souvent 低。",
    patterns: ["主語 ＋ 動詞 ＋ parfois", "Parfois, ＋ 句子"],
    conjugation: null,
    examples: [
      { french: "Parfois, je travaille le week-end.", chinese: "我有時候週末也工作。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["souvent"],
    tags: ["副詞"], audio: null,
  },
  {
    id: "jamais", word: "jamais", displayWord: "jamais", partOfSpeech: "adverb",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 9, category: "adverbs",
    meanings: ["從不", "從未"],
    usageSummary: "表示否定的頻率，通常跟 ne 搭配構成 ne...jamais。",
    patterns: ["主語 ＋ ne ＋ 動詞 ＋ jamais"],
    conjugation: null,
    examples: [
      { french: "Je ne mange jamais de viande.", chinese: "我從來不吃肉。", note: "ne...jamais 是固定否定結構。" },
    ],
    usageTip: "jamais 通常要搭配 ne 一起使用（ne...jamais），不能單獨代替 ne pas。",
    collocations: [{ french: "ne...jamais", chinese: "從不……" }],
    commonMistakes: [],
    relatedWords: ["toujours"],
    tags: ["副詞", "高頻"], audio: null,
  },
  {
    id: "deja", word: "déjà", displayWord: "déjà", partOfSpeech: "adverb",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 10, category: "adverbs",
    meanings: ["已經"],
    usageSummary: "表示動作已經完成或發生過。",
    patterns: ["主語 ＋ 動詞 ＋ déjà"],
    conjugation: null,
    examples: [
      { french: "J'ai déjà mangé.", chinese: "我已經吃過了。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["encore"],
    tags: ["副詞"], audio: null,
  },
  {
    id: "encore", word: "encore", displayWord: "encore", partOfSpeech: "adverb",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 11, category: "adverbs",
    meanings: ["還", "再"],
    usageSummary: "表示動作繼續，或請求再來一次。",
    patterns: ["主語 ＋ 動詞 ＋ encore", "encore ＋ un(e) ＋ 名詞"],
    conjugation: null,
    examples: [
      { french: "Il est encore là.", chinese: "他還在那裡。", note: "" },
      { french: "Encore un café, s'il vous plaît.", chinese: "請再來一杯咖啡。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["déjà"],
    tags: ["副詞", "高頻"], audio: null,
  },
  {
    id: "ici", word: "ici", displayWord: "ici", partOfSpeech: "adverb",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 12, category: "adverbs",
    meanings: ["這裡"],
    usageSummary: "表示說話者所在的位置。",
    patterns: ["Ici, + 句子", "主語 ＋ être ＋ ici"],
    conjugation: null,
    examples: [
      { french: "Je suis ici.", chinese: "我在這裡。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["là"],
    tags: ["副詞", "高頻"], audio: null,
  },
  {
    id: "la-adverb", word: "là", displayWord: "là", partOfSpeech: "adverb",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 13, category: "adverbs",
    meanings: ["那裡", "在（強調位置）"],
    usageSummary: "表示比較遠的位置，也常用來確認某人是否在場。",
    patterns: ["主語 ＋ être ＋ là"],
    conjugation: null,
    examples: [
      { french: "Il n'est pas là.", chinese: "他不在。", note: "" },
    ],
    usageTip: "là（那裡，帶重音符號）跟冠詞 la（陰性冠詞，沒有重音符號）拼寫接近，注意分辨。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["ici"],
    tags: ["副詞", "高頻"], audio: null,
  },
  {
    id: "maintenant", word: "maintenant", displayWord: "maintenant", partOfSpeech: "adverb",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 14, category: "adverbs",
    meanings: ["現在"],
    usageSummary: "表示現在這個時間點。",
    patterns: ["Maintenant, + 句子"],
    conjugation: null,
    examples: [
      { french: "Je travaille maintenant.", chinese: "我現在在工作。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["aujourd'hui"],
    tags: ["副詞", "高頻"], audio: null,
  },
  {
    id: "aujourdhui", word: "aujourd'hui", displayWord: "aujourd'hui", partOfSpeech: "adverb",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 15, category: "adverbs",
    meanings: ["今天"],
    usageSummary: "表示說話當天。",
    patterns: ["Aujourd'hui, + 句子"],
    conjugation: null,
    examples: [
      { french: "Aujourd'hui, il fait beau.", chinese: "今天天氣很好。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["demain", "hier"],
    tags: ["副詞", "高頻", "時間"], audio: null,
  },
  {
    id: "demain", word: "demain", displayWord: "demain", partOfSpeech: "adverb",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 16, category: "adverbs",
    meanings: ["明天"],
    usageSummary: "表示說話當天的隔天。",
    patterns: ["Demain, + 句子", "à demain"],
    conjugation: null,
    examples: [
      { french: "À demain !", chinese: "明天見！", note: "常見道別語。" },
    ],
    usageTip: "",
    collocations: [{ french: "à demain", chinese: "明天見" }],
    commonMistakes: [],
    relatedWords: ["aujourd'hui", "hier"],
    tags: ["副詞", "高頻", "時間"], audio: null,
  },
  {
    id: "hier", word: "hier", displayWord: "hier", partOfSpeech: "adverb",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 17, category: "adverbs",
    meanings: ["昨天"],
    usageSummary: "表示說話當天的前一天。",
    patterns: ["Hier, + 句子"],
    conjugation: null,
    examples: [
      { french: "Hier, j'ai travaillé.", chinese: "昨天我工作了。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["aujourd'hui", "demain"],
    tags: ["副詞", "高頻", "時間"], audio: null,
  },
  {
    id: "aussi", word: "aussi", displayWord: "aussi", partOfSpeech: "adverb",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 18, category: "adverbs",
    meanings: ["也"],
    usageSummary: "表示附加、相同的情況，通常放在句尾或動詞後。",
    patterns: ["主語 ＋ 動詞 ＋ aussi", "Moi aussi."],
    conjugation: null,
    examples: [
      { french: "Moi aussi, j'aime le café.", chinese: "我也喜歡咖啡。", note: "" },
      { french: "Moi aussi.", chinese: "我也是。", note: "非常常用的簡短回答。" },
    ],
    usageTip: "",
    collocations: [{ french: "moi aussi", chinese: "我也是" }],
    commonMistakes: [],
    relatedWords: [],
    tags: ["副詞", "高頻"], audio: null,
  },
];
