export const GREETINGS_WORDS = [
  {
    id: "bonjour", word: "bonjour", displayWord: "bonjour", partOfSpeech: "greeting",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 1, category: "greetings",
    meanings: ["你好", "早安", "日安"],
    usageSummary: "通常在早上至傍晚與別人見面時使用。比 salut 正式，適合陌生人、老師、店員和工作場合。",
    patterns: ["Bonjour + 稱呼"],
    conjugation: null,
    examples: [
      { french: "Bonjour, madame.", chinese: "您好，女士。", note: "對女性使用正式招呼時常加 madame。" },
      { french: "Bonjour, comment allez-vous ?", chinese: "您好，您最近怎麼樣？", note: "allez-vous 是禮貌的「你好嗎」問法。" },
    ],
    usageTip: "晚上見面通常改用 bonsoir，不再用 bonjour。",
    collocations: [{ french: "bonjour madame/monsieur", chinese: "您好，女士／先生" }],
    commonMistakes: [],
    relatedWords: ["salut", "bonsoir"],
    tags: ["高頻", "問候"], audio: null,
  },
  {
    id: "salut", word: "salut", displayWord: "salut", partOfSpeech: "greeting",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 2, category: "greetings",
    meanings: ["嗨", "再見"],
    usageSummary: "隨意、不正式的招呼語，可以用來打招呼，也可以用來道別，通常用於朋友、同齡人之間。",
    patterns: ["Salut ＋ 人名（可省略）"],
    conjugation: null,
    examples: [
      { french: "Salut, Marie !", chinese: "嗨，瑪麗！", note: "見面時打招呼。" },
      { french: "Bon, salut, à demain !", chinese: "好啦，再見，明天見！", note: "salut 也可以用來說再見。" },
    ],
    usageTip: "對長輩、陌生人或正式場合不要用 salut，改用 bonjour。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["bonjour", "au revoir"],
    tags: ["口語", "問候"], audio: null,
  },
  {
    id: "bonsoir", word: "bonsoir", displayWord: "bonsoir", partOfSpeech: "greeting",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 3, category: "greetings",
    meanings: ["晚安（見面時）", "晚上好"],
    usageSummary: "傍晚到晚上見面時使用的問候語，跟 bonjour 用法相同，只是時間點不同。",
    patterns: ["Bonsoir + 稱呼"],
    conjugation: null,
    examples: [
      { french: "Bonsoir, tout le monde.", chinese: "大家晚上好。", note: "常用於進入房間、聚會時。" },
      { french: "Bonsoir, monsieur Dupont.", chinese: "晚上好，杜邦先生。", note: "" },
    ],
    usageTip: "bonsoir 是見面時說的「晚上好」，離開／睡前才用 bonne nuit（晚安）。",
    collocations: [],
    commonMistakes: [{ wrong: "Bonsoir 用來道別離開", correct: "離開時用 bonne soirée 或 au revoir", explanation: "bonsoir 是見面時的問候，不是道別語。" }],
    relatedWords: ["bonjour", "bonne nuit"],
    tags: ["問候"], audio: null,
  },
  {
    id: "au-revoir", word: "au revoir", displayWord: "au revoir", partOfSpeech: "greeting",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 4, category: "greetings",
    meanings: ["再見"],
    usageSummary: "最常見、最中性的道別用語，任何場合都適用。",
    patterns: ["Au revoir + 稱呼"],
    conjugation: null,
    examples: [
      { french: "Au revoir, à bientôt !", chinese: "再見，很快再見！", note: "à bientôt 表示「很快再見」。" },
      { french: "Merci, au revoir.", chinese: "謝謝，再見。", note: "" },
    ],
    usageTip: "比 salut 正式，適合對任何人使用，不會顯得失禮。",
    collocations: [{ french: "à bientôt", chinese: "很快再見" }, { french: "à demain", chinese: "明天見" }],
    commonMistakes: [],
    relatedWords: ["salut"],
    tags: ["高頻", "問候"], audio: null,
  },
  {
    id: "merci", word: "merci", displayWord: "merci", partOfSpeech: "greeting",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 5, category: "greetings",
    meanings: ["謝謝"],
    usageSummary: "表達感謝，可單獨使用，也可加強語氣或指明感謝的原因。",
    patterns: ["Merci ＋（beaucoup／原因）"],
    conjugation: null,
    examples: [
      { french: "Merci beaucoup !", chinese: "非常感謝！", note: "beaucoup 加強語氣，等於「非常」。" },
      { french: "Merci pour votre aide.", chinese: "謝謝你的幫忙。", note: "pour 後面接感謝的原因。" },
    ],
    usageTip: "回應別人道謝時可以說「de rien」（不客氣）。",
    collocations: [{ french: "merci beaucoup", chinese: "非常感謝" }, { french: "merci pour...", chinese: "謝謝……" }],
    commonMistakes: [],
    relatedWords: ["de rien"],
    tags: ["高頻", "問候"], audio: null,
  },
  {
    id: "pardon", word: "pardon", displayWord: "pardon", partOfSpeech: "greeting",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 6, category: "greetings",
    meanings: ["不好意思", "請再說一次"],
    usageSummary: "用來引起別人注意、打斷別人、或請對方重複沒聽清楚的話。",
    patterns: ["Pardon, + 問句／請求"],
    conjugation: null,
    examples: [
      { french: "Pardon, où est la gare ?", chinese: "不好意思，請問車站在哪裡？", note: "用來禮貌地打斷、開口問路。" },
      { french: "Pardon ? Vous pouvez répéter ?", chinese: "不好意思？可以再說一次嗎？", note: "沒聽清楚時使用。" },
    ],
    usageTip: "跟 désolé 不同：pardon 較短、較輕，多用於打斷或沒聽清楚；désolé 用於真正道歉。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["désolé"],
    tags: ["禮貌用語"], audio: null,
  },
  {
    id: "desole", word: "désolé", displayWord: "désolé(e)", partOfSpeech: "greeting",
    gender: null, forms: { ms: "désolé", fs: "désolée" }, irregular: null, level: "A1", frequencyRank: 7, category: "greetings",
    meanings: ["抱歉", "對不起"],
    usageSummary: "用來表達真正的歉意，男性說 désolé，女性說 désolée（發音相同）。",
    patterns: ["Je suis désolé(e)（＋原因）"],
    conjugation: null,
    examples: [
      { french: "Désolé, je suis en retard.", chinese: "抱歉，我遲到了。", note: "" },
      { french: "Je suis désolée, je ne comprends pas.", chinese: "對不起，我不明白。（女性說法）", note: "" },
    ],
    usageTip: "désolé 用於真正需要道歉的情況；只是打斷別人或問路請用 pardon。",
    collocations: [{ french: "être désolé(e)", chinese: "感到抱歉" }],
    commonMistakes: [],
    relatedWords: ["pardon"],
    tags: ["禮貌用語"], audio: null,
  },
  {
    id: "bienvenue", word: "bienvenue", displayWord: "bienvenue", partOfSpeech: "greeting",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 8, category: "greetings",
    meanings: ["歡迎"],
    usageSummary: "歡迎別人到某個地方時使用。",
    patterns: ["Bienvenue à／en／dans + 地點"],
    conjugation: null,
    examples: [
      { french: "Bienvenue en France !", chinese: "歡迎來到法國！", note: "en 用於陰性國家名前。" },
      { french: "Bienvenue à Paris.", chinese: "歡迎來到巴黎。", note: "à 用於城市名前。" },
    ],
    usageTip: "也可以單獨回應別人道謝：「Bienvenue !」＝「不客氣！」（加拿大法語常見）。",
    collocations: [],
    commonMistakes: [],
    relatedWords: [],
    tags: ["問候"], audio: null,
  },
  {
    id: "oui", word: "oui", displayWord: "oui", partOfSpeech: "adverb",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 9, category: "greetings",
    meanings: ["是", "對", "好"],
    usageSummary: "表示肯定回答，回應一般問句時使用。",
    patterns: ["Oui, + 補充句子（可省略）"],
    conjugation: null,
    examples: [
      { french: "Tu aimes le café ? — Oui, j'aime beaucoup.", chinese: "你喜歡咖啡嗎？——是的，我很喜歡。", note: "" },
      { french: "Oui, d'accord.", chinese: "好，同意。", note: "" },
    ],
    usageTip: "回答否定問句（如「你不是學生嗎？」）表示肯定時要用 si，不能用 oui。",
    collocations: [],
    commonMistakes: [{ wrong: "Tu n'es pas étudiant ? — Oui.", correct: "Tu n'es pas étudiant ? — Si.", explanation: "回答否定問句表示「不，我是」時要用 si，不能用 oui。" }],
    relatedWords: ["non", "si"],
    tags: ["高頻"], audio: null,
  },
  {
    id: "non", word: "non", displayWord: "non", partOfSpeech: "adverb",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 10, category: "greetings",
    meanings: ["不", "不是"],
    usageSummary: "表示否定回答。",
    patterns: ["Non, + 補充句子（可省略）"],
    conjugation: null,
    examples: [
      { french: "Tu es fatigué ? — Non, ça va.", chinese: "你累了嗎？——不，還好。", note: "" },
      { french: "Non, merci.", chinese: "不用了，謝謝。", note: "禮貌拒絕的常見說法。" },
    ],
    usageTip: "",
    collocations: [{ french: "non merci", chinese: "不用了，謝謝" }],
    commonMistakes: [],
    relatedWords: ["oui"],
    tags: ["高頻"], audio: null,
  },
  {
    id: "daccord", word: "d'accord", displayWord: "d'accord", partOfSpeech: "greeting",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 11, category: "greetings",
    meanings: ["好的", "同意"],
    usageSummary: "表示同意對方的提議或說法，日常對話中非常常用。",
    patterns: ["D'accord.", "être d'accord avec + 人"],
    conjugation: null,
    examples: [
      { french: "On mange à midi ? — D'accord !", chinese: "我們中午吃飯好嗎？——好啊！", note: "" },
      { french: "Je suis d'accord avec toi.", chinese: "我同意你的看法。", note: "être d'accord avec 表示「同意某人」。" },
    ],
    usageTip: "",
    collocations: [{ french: "être d'accord avec", chinese: "同意（某人）" }],
    commonMistakes: [],
    relatedWords: ["oui"],
    tags: ["口語", "高頻"], audio: null,
  },
  {
    id: "sil-vous-plait", word: "s'il vous plaît", displayWord: "s'il vous plaît", partOfSpeech: "greeting",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 12, category: "greetings",
    meanings: ["請", "麻煩你"],
    usageSummary: "禮貌用語，加在請求後面，對不熟的人或正式場合使用；對熟悉的朋友則用 s'il te plaît。",
    patterns: ["請求句 ＋ s'il vous plaît"],
    conjugation: null,
    examples: [
      { french: "Un café, s'il vous plaît.", chinese: "請給我一杯咖啡。", note: "點餐、買東西時常用。" },
      { french: "Fermez la porte, s'il vous plaît.", chinese: "請關門。", note: "" },
    ],
    usageTip: "對朋友、家人用 s'il te plaît（tu 的形式），對陌生人、長輩用 s'il vous plaît（vous 的形式）。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["s'il te plaît"],
    tags: ["禮貌用語", "高頻"], audio: null,
  },
];
