// 常用名詞：每筆資料都用 forms 顯示「不定冠詞單數／定冠詞單數／不定冠詞複數／定冠詞複數」，
// 讓學習者一開始就記住陰陽性和冠詞，而不是只背一個沒有冠詞的單詞。

export const NOUNS_WORDS = [
  {
    id: "personne", word: "personne", displayWord: "une personne", partOfSpeech: "noun",
    gender: "f", forms: { indefiniteSingular: "une personne", definiteSingular: "la personne", indefinitePlural: "des personnes", definitePlural: "les personnes" },
    irregular: null, level: "A1", frequencyRank: 1, category: "family",
    meanings: ["人", "個人"],
    usageSummary: "指一個人，永遠是陰性名詞，即使指男性也一樣。",
    patterns: ["une/la personne"],
    conjugation: null,
    examples: [
      { french: "C'est une personne sympathique.", chinese: "這是一個親切的人。", note: "" },
      { french: "Il y a combien de personnes ?", chinese: "有多少人？", note: "" },
    ],
    usageTip: "personne 永遠用陰性冠詞，即使描述的是男性，例如「un homme est une personne sympathique」。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["homme", "femme"],
    tags: ["名詞", "高頻"], audio: null,
  },
  {
    id: "homme", word: "homme", displayWord: "un homme", partOfSpeech: "noun",
    gender: "m", forms: { indefiniteSingular: "un homme", definiteSingular: "l'homme", indefinitePlural: "des hommes", definitePlural: "les hommes" },
    irregular: null, level: "A1", frequencyRank: 2, category: "family",
    meanings: ["男人"],
    usageSummary: "指成年男性，陽性名詞。h 是啞音，前面的冠詞要縮寫。",
    patterns: ["un/l'homme"],
    conjugation: null,
    examples: [
      { french: "C'est un homme grand.", chinese: "這是一個高大的男人。", note: "" },
    ],
    usageTip: "homme 的 h 是啞音，定冠詞要縮寫成 l'homme，不能說 le homme。",
    collocations: [],
    commonMistakes: [{ wrong: "le homme", correct: "l'homme", explanation: "homme 的 h 是啞音，前面的定冠詞要縮寫。" }],
    relatedWords: ["femme"],
    tags: ["名詞", "高頻"], audio: null,
  },
  {
    id: "femme", word: "femme", displayWord: "une femme", partOfSpeech: "noun",
    gender: "f", forms: { indefiniteSingular: "une femme", definiteSingular: "la femme", indefinitePlural: "des femmes", definitePlural: "les femmes" },
    irregular: null, level: "A1", frequencyRank: 3, category: "family",
    meanings: ["女人", "妻子"],
    usageSummary: "指成年女性，也可以表示「妻子」，陰性名詞。",
    patterns: ["une/la femme"],
    conjugation: null,
    examples: [
      { french: "C'est ma femme.", chinese: "這是我的妻子。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["homme"],
    tags: ["名詞", "高頻"], audio: null,
  },
  {
    id: "enfant", word: "enfant", displayWord: "un/une enfant", partOfSpeech: "noun",
    gender: "m", forms: { indefiniteSingular: "un/une enfant", definiteSingular: "l'enfant", indefinitePlural: "des enfants", definitePlural: "les enfants" },
    irregular: null, level: "A1", frequencyRank: 4, category: "family",
    meanings: ["小孩", "兒童"],
    usageSummary: "拼寫陰陽性同形，只靠冠詞（un/une）分辨男孩或女孩。",
    patterns: ["un/une enfant"],
    conjugation: null,
    examples: [
      { french: "Elle a deux enfants.", chinese: "她有兩個小孩。", note: "" },
    ],
    usageTip: "enfant 這個字本身不分陰陽性，要看冠詞 un（男孩）或 une（女孩）。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["famille"],
    tags: ["名詞", "高頻"], audio: null,
  },
  {
    id: "ami", word: "ami", displayWord: "un ami", partOfSpeech: "noun",
    gender: "m", forms: { indefiniteSingular: "un ami", definiteSingular: "l'ami", indefinitePlural: "des amis", definitePlural: "les amis" },
    irregular: null, level: "A1", frequencyRank: 5, category: "family",
    meanings: ["朋友（男性）"],
    usageSummary: "指男性朋友，女性朋友要說 une amie（多加一個 e）。",
    patterns: ["un ami / une amie"],
    conjugation: null,
    examples: [
      { french: "C'est un ami de Paris.", chinese: "這是一位來自巴黎的朋友。", note: "" },
    ],
    usageTip: "女性朋友要用陰性形式 une amie，發音跟 un ami 不同。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["famille"],
    tags: ["名詞", "高頻"], audio: null,
  },
  {
    id: "famille", word: "famille", displayWord: "une famille", partOfSpeech: "noun",
    gender: "f", forms: { indefiniteSingular: "une famille", definiteSingular: "la famille", indefinitePlural: "des familles", definitePlural: "les familles" },
    irregular: null, level: "A1", frequencyRank: 6, category: "family",
    meanings: ["家庭", "家人"],
    usageSummary: "指家庭或家人整體，陰性名詞。",
    patterns: ["une/la famille"],
    conjugation: null,
    examples: [
      { french: "Ma famille habite à Lyon.", chinese: "我的家人住在里昂。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["enfant", "ami"],
    tags: ["名詞", "高頻"], audio: null,
  },
  {
    id: "maison", word: "maison", displayWord: "une maison", partOfSpeech: "noun",
    gender: "f", forms: { indefiniteSingular: "une maison", definiteSingular: "la maison", indefinitePlural: "des maisons", definitePlural: "les maisons" },
    irregular: null, level: "A1", frequencyRank: 7, category: "home",
    meanings: ["房子", "家"],
    usageSummary: "指獨棟房屋，也常用來泛指「家」。",
    patterns: ["une/la maison", "à la maison"],
    conjugation: null,
    examples: [
      { french: "Je suis à la maison.", chinese: "我在家。", note: "à la maison 是固定用法，表示「在家」。" },
    ],
    usageTip: "",
    collocations: [{ french: "à la maison", chinese: "在家" }],
    commonMistakes: [],
    relatedWords: ["chez"],
    tags: ["名詞", "高頻"], audio: null,
  },
  {
    id: "telephone", word: "téléphone", displayWord: "un téléphone", partOfSpeech: "noun",
    gender: "m", forms: { indefiniteSingular: "un téléphone", definiteSingular: "le téléphone", indefinitePlural: "des téléphones", definitePlural: "les téléphones" },
    irregular: null, level: "A1", frequencyRank: 8, category: "home",
    meanings: ["電話", "手機"],
    usageSummary: "指電話這個物件，陽性名詞。",
    patterns: ["un/le téléphone"],
    conjugation: null,
    examples: [
      { french: "Mon téléphone est sur la table.", chinese: "我的手機在桌上。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: [],
    tags: ["名詞", "高頻"], audio: null,
  },
  {
    id: "ecole", word: "école", displayWord: "une école", partOfSpeech: "noun",
    gender: "f", forms: { indefiniteSingular: "une école", definiteSingular: "l'école", indefinitePlural: "des écoles", definitePlural: "les écoles" },
    irregular: null, level: "A1", frequencyRank: 9, category: "school",
    meanings: ["學校"],
    usageSummary: "陰性名詞，母音開頭，定冠詞要縮寫。",
    patterns: ["une/l'école", "aller à l'école"],
    conjugation: null,
    examples: [
      { french: "Je vais à l'école.", chinese: "我去學校。", note: "" },
    ],
    usageTip: "",
    collocations: [{ french: "aller à l'école", chinese: "去上學" }],
    commonMistakes: [],
    relatedWords: ["travail"],
    tags: ["名詞", "高頻"], audio: null,
  },
  {
    id: "travail", word: "travail", displayWord: "un travail", partOfSpeech: "noun",
    gender: "m", forms: { indefiniteSingular: "un travail", definiteSingular: "le travail", indefinitePlural: "des travaux", definitePlural: "les travaux" },
    irregular: true, level: "A1", frequencyRank: 10, category: "school",
    meanings: ["工作"],
    usageSummary: "指工作，複數形式不規則（travail → travaux）。",
    patterns: ["le travail", "aller au travail"],
    conjugation: null,
    examples: [
      { french: "Je vais au travail.", chinese: "我去上班。", note: "au＝à le 的縮寫。" },
    ],
    usageTip: "複數不規則：travail → travaux，不是 travails。",
    collocations: [{ french: "aller au travail", chinese: "去上班" }],
    commonMistakes: [{ wrong: "des travails", correct: "des travaux", explanation: "travail 的複數是不規則的 travaux。" }],
    relatedWords: ["école"],
    tags: ["名詞", "不規則", "高頻"], audio: null,
  },
  {
    id: "livre", word: "livre", displayWord: "un livre", partOfSpeech: "noun",
    gender: "m", forms: { indefiniteSingular: "un livre", definiteSingular: "le livre", indefinitePlural: "des livres", definitePlural: "les livres" },
    irregular: null, level: "A1", frequencyRank: 11, category: "school",
    meanings: ["書"],
    usageSummary: "指書本，陽性名詞。注意陰性的 une livre 是另一個字（磅、法鎊）。",
    patterns: ["un/le livre"],
    conjugation: null,
    examples: [
      { french: "J'ai un livre.", chinese: "我有一本書。", note: "" },
    ],
    usageTip: "un livre（書，陽性）跟 une livre（磅，陰性）拼寫相同但意思不同，靠冠詞分辨。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["école"],
    tags: ["名詞", "高頻"], audio: null,
  },
  {
    id: "question", word: "question", displayWord: "une question", partOfSpeech: "noun",
    gender: "f", forms: { indefiniteSingular: "une question", definiteSingular: "la question", indefinitePlural: "des questions", definitePlural: "les questions" },
    irregular: null, level: "A1", frequencyRank: 12, category: "school",
    meanings: ["問題（疑問）"],
    usageSummary: "指提出的疑問，不是「困難」的意思（困難是 problème）。",
    patterns: ["poser une question"],
    conjugation: null,
    examples: [
      { french: "J'ai une question.", chinese: "我有一個問題。", note: "" },
    ],
    usageTip: "question 是「疑問」，「麻煩、難題」要用 problème，不要混淆。",
    collocations: [{ french: "poser une question", chinese: "提出問題" }],
    commonMistakes: [],
    relatedWords: ["réponse"],
    tags: ["名詞", "高頻"], audio: null,
  },
  {
    id: "reponse", word: "réponse", displayWord: "une réponse", partOfSpeech: "noun",
    gender: "f", forms: { indefiniteSingular: "une réponse", definiteSingular: "la réponse", indefinitePlural: "des réponses", definitePlural: "les réponses" },
    irregular: null, level: "A1", frequencyRank: 13, category: "school",
    meanings: ["回答", "答案"],
    usageSummary: "question 的對應詞，指回答或答案。",
    patterns: ["donner une réponse"],
    conjugation: null,
    examples: [
      { french: "C'est la bonne réponse.", chinese: "這是正確答案。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["question"],
    tags: ["名詞"], audio: null,
  },
  {
    id: "ville", word: "ville", displayWord: "une ville", partOfSpeech: "noun",
    gender: "f", forms: { indefiniteSingular: "une ville", definiteSingular: "la ville", indefinitePlural: "des villes", definitePlural: "les villes" },
    irregular: null, level: "A1", frequencyRank: 14, category: "places",
    meanings: ["城市"],
    usageSummary: "指城市，陰性名詞。",
    patterns: ["une/la ville"],
    conjugation: null,
    examples: [
      { french: "Paris est une grande ville.", chinese: "巴黎是一座大城市。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["rue", "pays"],
    tags: ["名詞", "高頻"], audio: null,
  },
  {
    id: "rue", word: "rue", displayWord: "une rue", partOfSpeech: "noun",
    gender: "f", forms: { indefiniteSingular: "une rue", definiteSingular: "la rue", indefinitePlural: "des rues", definitePlural: "les rues" },
    irregular: null, level: "A1", frequencyRank: 15, category: "places",
    meanings: ["街道"],
    usageSummary: "指街道，陰性名詞。",
    patterns: ["dans la rue"],
    conjugation: null,
    examples: [
      { french: "J'habite dans cette rue.", chinese: "我住在這條街上。", note: "" },
    ],
    usageTip: "",
    collocations: [{ french: "dans la rue", chinese: "在街上" }],
    commonMistakes: [],
    relatedWords: ["ville"],
    tags: ["名詞"], audio: null,
  },
  {
    id: "pays", word: "pays", displayWord: "un pays", partOfSpeech: "noun",
    gender: "m", forms: { indefiniteSingular: "un pays", definiteSingular: "le pays", indefinitePlural: "des pays", definitePlural: "les pays" },
    irregular: true, level: "A1", frequencyRank: 16, category: "countries",
    meanings: ["國家"],
    usageSummary: "指國家，單複數同形（pays 不變）。",
    patterns: ["un/le pays"],
    conjugation: null,
    examples: [
      { french: "La France est un beau pays.", chinese: "法國是一個美麗的國家。", note: "" },
    ],
    usageTip: "pays 的單複數拼寫相同，不要加 s。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["ville"],
    tags: ["名詞", "不規則"], audio: null,
  },
  {
    id: "jour", word: "jour", displayWord: "un jour", partOfSpeech: "noun",
    gender: "m", forms: { indefiniteSingular: "un jour", definiteSingular: "le jour", indefinitePlural: "des jours", definitePlural: "les jours" },
    irregular: null, level: "A1", frequencyRank: 17, category: "datetime",
    meanings: ["天", "日子"],
    usageSummary: "指一天、日子，陽性名詞。",
    patterns: ["tous les jours"],
    conjugation: null,
    examples: [
      { french: "Quel jour sommes-nous ?", chinese: "今天星期幾？", note: "" },
    ],
    usageTip: "",
    collocations: [{ french: "tous les jours", chinese: "每天" }],
    commonMistakes: [],
    relatedWords: ["semaine", "mois", "année"],
    tags: ["名詞", "高頻", "時間"], audio: null,
  },
  {
    id: "semaine", word: "semaine", displayWord: "une semaine", partOfSpeech: "noun",
    gender: "f", forms: { indefiniteSingular: "une semaine", definiteSingular: "la semaine", indefinitePlural: "des semaines", definitePlural: "les semaines" },
    irregular: null, level: "A1", frequencyRank: 18, category: "datetime",
    meanings: ["星期", "週"],
    usageSummary: "指一週，陰性名詞。",
    patterns: ["cette semaine"],
    conjugation: null,
    examples: [
      { french: "Cette semaine, je travaille beaucoup.", chinese: "這個星期我工作很多。", note: "" },
    ],
    usageTip: "",
    collocations: [{ french: "cette semaine", chinese: "這個星期" }],
    commonMistakes: [],
    relatedWords: ["jour", "mois"],
    tags: ["名詞", "時間"], audio: null,
  },
  {
    id: "mois", word: "mois", displayWord: "un mois", partOfSpeech: "noun",
    gender: "m", forms: { indefiniteSingular: "un mois", definiteSingular: "le mois", indefinitePlural: "des mois", definitePlural: "les mois" },
    irregular: true, level: "A1", frequencyRank: 19, category: "datetime",
    meanings: ["月", "月份"],
    usageSummary: "指月份，單複數同形。",
    patterns: ["ce mois-ci"],
    conjugation: null,
    examples: [
      { french: "Ce mois-ci, il fait froid.", chinese: "這個月天氣冷。", note: "" },
    ],
    usageTip: "mois 的單複數拼寫相同。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["semaine", "année"],
    tags: ["名詞", "時間"], audio: null,
  },
  {
    id: "annee", word: "année", displayWord: "une année", partOfSpeech: "noun",
    gender: "f", forms: { indefiniteSingular: "une année", definiteSingular: "l'année", indefinitePlural: "des années", definitePlural: "les années" },
    irregular: null, level: "A1", frequencyRank: 20, category: "datetime",
    meanings: ["年"],
    usageSummary: "指一年，強調過程或期間，陰性名詞，母音開頭要縮寫冠詞。",
    patterns: ["cette année", "l'année prochaine"],
    conjugation: null,
    examples: [
      { french: "Bonne année !", chinese: "新年快樂！", note: "固定祝賀語。" },
    ],
    usageTip: "",
    collocations: [{ french: "bonne année", chinese: "新年快樂" }, { french: "cette année", chinese: "今年" }],
    commonMistakes: [],
    relatedWords: ["mois", "jour"],
    tags: ["名詞", "時間"], audio: null,
  },
  {
    id: "heure", word: "heure", displayWord: "une heure", partOfSpeech: "noun",
    gender: "f", forms: { indefiniteSingular: "une heure", definiteSingular: "l'heure", indefinitePlural: "des heures", definitePlural: "les heures" },
    irregular: null, level: "A1", frequencyRank: 21, category: "datetime",
    meanings: ["小時", "點鐘"],
    usageSummary: "指時間單位「小時」，也用來詢問幾點鐘，陰性名詞。",
    patterns: ["Quelle heure est-il ?"],
    conjugation: null,
    examples: [
      { french: "Quelle heure est-il ?", chinese: "現在幾點？", note: "" },
      { french: "Il est trois heures.", chinese: "現在三點。", note: "" },
    ],
    usageTip: "",
    collocations: [{ french: "quelle heure est-il", chinese: "現在幾點" }],
    commonMistakes: [],
    relatedWords: ["matin", "soir"],
    tags: ["名詞", "高頻", "時間"], audio: null,
  },
  {
    id: "matin", word: "matin", displayWord: "un matin", partOfSpeech: "noun",
    gender: "m", forms: { indefiniteSingular: "un matin", definiteSingular: "le matin", indefinitePlural: "des matins", definitePlural: "les matins" },
    irregular: null, level: "A1", frequencyRank: 22, category: "datetime",
    meanings: ["早上", "上午"],
    usageSummary: "指一天的早上時段，陽性名詞。",
    patterns: ["le matin"],
    conjugation: null,
    examples: [
      { french: "Le matin, je bois du café.", chinese: "早上我喝咖啡。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["soir", "nuit"],
    tags: ["名詞", "時間"], audio: null,
  },
  {
    id: "soir", word: "soir", displayWord: "un soir", partOfSpeech: "noun",
    gender: "m", forms: { indefiniteSingular: "un soir", definiteSingular: "le soir", indefinitePlural: "des soirs", definitePlural: "les soirs" },
    irregular: null, level: "A1", frequencyRank: 23, category: "datetime",
    meanings: ["晚上", "傍晚"],
    usageSummary: "指一天的晚上時段，陽性名詞。",
    patterns: ["le soir"],
    conjugation: null,
    examples: [
      { french: "Le soir, je regarde la télévision.", chinese: "晚上我看電視。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["matin", "nuit"],
    tags: ["名詞", "時間"], audio: null,
  },
  {
    id: "nuit", word: "nuit", displayWord: "une nuit", partOfSpeech: "noun",
    gender: "f", forms: { indefiniteSingular: "une nuit", definiteSingular: "la nuit", indefinitePlural: "des nuits", definitePlural: "les nuits" },
    irregular: null, level: "A1", frequencyRank: 24, category: "datetime",
    meanings: ["夜晚"],
    usageSummary: "指夜晚、深夜，陰性名詞。",
    patterns: ["bonne nuit"],
    conjugation: null,
    examples: [
      { french: "Bonne nuit !", chinese: "晚安！", note: "睡前道別用語。" },
    ],
    usageTip: "bonne nuit 是睡前說的「晚安」，見面時的「晚上好」要用 bonsoir。",
    collocations: [{ french: "bonne nuit", chinese: "晚安（睡前）" }],
    commonMistakes: [],
    relatedWords: ["soir"],
    tags: ["名詞", "時間"], audio: null,
  },
  {
    id: "eau", word: "eau", displayWord: "de l'eau", partOfSpeech: "noun",
    gender: "f", forms: { indefiniteSingular: "de l'eau", definiteSingular: "l'eau", indefinitePlural: "des eaux", definitePlural: "les eaux" },
    irregular: true, level: "A1", frequencyRank: 25, category: "food",
    meanings: ["水"],
    usageSummary: "不可數名詞，通常用部分冠詞 de l'（一些水），陰性。",
    patterns: ["de l'eau"],
    conjugation: null,
    examples: [
      { french: "Je bois de l'eau.", chinese: "我喝水。", note: "de l' 是陰性部分冠詞，用於不可數名詞。" },
    ],
    usageTip: "水是不可數名詞，一般用「de l'eau」而不是「une eau」。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["café", "pain"],
    tags: ["名詞", "高頻"], audio: null,
  },
  {
    id: "pain", word: "pain", displayWord: "du pain", partOfSpeech: "noun",
    gender: "m", forms: { indefiniteSingular: "du pain", definiteSingular: "le pain", indefinitePlural: "des pains", definitePlural: "les pains" },
    irregular: null, level: "A1", frequencyRank: 26, category: "food",
    meanings: ["麵包"],
    usageSummary: "不可數名詞，通常用部分冠詞 du（一些麵包），陽性。",
    patterns: ["du pain"],
    conjugation: null,
    examples: [
      { french: "Je mange du pain.", chinese: "我吃麵包。", note: "du 是陽性部分冠詞。" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["eau"],
    tags: ["名詞", "高頻"], audio: null,
  },
  {
    id: "cafe", word: "café", displayWord: "un café", partOfSpeech: "noun",
    gender: "m", forms: { indefiniteSingular: "un café", definiteSingular: "le café", indefinitePlural: "des cafés", definitePlural: "les cafés" },
    irregular: null, level: "A1", frequencyRank: 27, category: "food",
    meanings: ["咖啡", "咖啡館"],
    usageSummary: "可以指飲料「咖啡」，也可以指「咖啡館」這個地方，陽性名詞。",
    patterns: ["un café"],
    conjugation: null,
    examples: [
      { french: "Un café, s'il vous plaît.", chinese: "請給我一杯咖啡。", note: "" },
      { french: "On va au café ?", chinese: "我們去咖啡館好嗎？", note: "這裡指咖啡館這個地方。" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["eau", "restaurant"],
    tags: ["名詞", "高頻"], audio: null,
  },
  {
    id: "restaurant", word: "restaurant", displayWord: "un restaurant", partOfSpeech: "noun",
    gender: "m", forms: { indefiniteSingular: "un restaurant", definiteSingular: "le restaurant", indefinitePlural: "des restaurants", definitePlural: "les restaurants" },
    irregular: null, level: "A1", frequencyRank: 28, category: "food",
    meanings: ["餐廳"],
    usageSummary: "指用餐的場所，陽性名詞。",
    patterns: ["au restaurant"],
    conjugation: null,
    examples: [
      { french: "Nous mangeons au restaurant.", chinese: "我們在餐廳吃飯。", note: "" },
    ],
    usageTip: "",
    collocations: [{ french: "au restaurant", chinese: "在餐廳" }],
    commonMistakes: [],
    relatedWords: ["café"],
    tags: ["名詞", "高頻"], audio: null,
  },
  {
    id: "magasin", word: "magasin", displayWord: "un magasin", partOfSpeech: "noun",
    gender: "m", forms: { indefiniteSingular: "un magasin", definiteSingular: "le magasin", indefinitePlural: "des magasins", definitePlural: "les magasins" },
    irregular: null, level: "A1", frequencyRank: 29, category: "shopping",
    meanings: ["商店"],
    usageSummary: "指購物的店鋪，陽性名詞。",
    patterns: ["au magasin"],
    conjugation: null,
    examples: [
      { french: "Je vais au magasin.", chinese: "我要去商店。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["argent"],
    tags: ["名詞", "高頻"], audio: null,
  },
  {
    id: "argent", word: "argent", displayWord: "de l'argent", partOfSpeech: "noun",
    gender: "m", forms: { indefiniteSingular: "de l'argent", definiteSingular: "l'argent", indefinitePlural: null, definitePlural: null },
    irregular: true, level: "A1", frequencyRank: 30, category: "shopping",
    meanings: ["錢", "金錢", "銀"],
    usageSummary: "不可數名詞，通常沒有複數形式，陽性。也可以指金屬「銀」。",
    patterns: ["de l'argent"],
    conjugation: null,
    examples: [
      { french: "J'ai besoin d'argent.", chinese: "我需要錢。", note: "avoir besoin de argent → d'argent（縮寫）。" },
    ],
    usageTip: "argent 一般不用複數形式。",
    collocations: [{ french: "avoir besoin d'argent", chinese: "需要錢" }],
    commonMistakes: [],
    relatedWords: ["magasin"],
    tags: ["名詞", "高頻"], audio: null,
  },
  {
    id: "gare", word: "gare", displayWord: "une gare", partOfSpeech: "noun",
    gender: "f", forms: { indefiniteSingular: "une gare", definiteSingular: "la gare", indefinitePlural: "des gares", definitePlural: "les gares" },
    irregular: null, level: "A1", frequencyRank: 31, category: "transport",
    meanings: ["火車站"],
    usageSummary: "指火車站，陰性名詞。",
    patterns: ["à la gare"],
    conjugation: null,
    examples: [
      { french: "La gare est loin d'ici ?", chinese: "火車站離這裡遠嗎？", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["train", "bus"],
    tags: ["名詞"], audio: null,
  },
  {
    id: "voiture", word: "voiture", displayWord: "une voiture", partOfSpeech: "noun",
    gender: "f", forms: { indefiniteSingular: "une voiture", definiteSingular: "la voiture", indefinitePlural: "des voitures", definitePlural: "les voitures" },
    irregular: null, level: "A1", frequencyRank: 32, category: "transport",
    meanings: ["汽車"],
    usageSummary: "指汽車，陰性名詞。",
    patterns: ["en voiture"],
    conjugation: null,
    examples: [
      { french: "Je vais au travail en voiture.", chinese: "我開車去上班。", note: "en voiture＝「搭車／開車」。" },
    ],
    usageTip: "",
    collocations: [{ french: "en voiture", chinese: "搭車／開車" }],
    commonMistakes: [],
    relatedWords: ["train", "bus"],
    tags: ["名詞", "高頻"], audio: null,
  },
  {
    id: "train", word: "train", displayWord: "un train", partOfSpeech: "noun",
    gender: "m", forms: { indefiniteSingular: "un train", definiteSingular: "le train", indefinitePlural: "des trains", definitePlural: "les trains" },
    irregular: null, level: "A1", frequencyRank: 33, category: "transport",
    meanings: ["火車"],
    usageSummary: "指火車，陽性名詞。",
    patterns: ["en train"],
    conjugation: null,
    examples: [
      { french: "Je prends le train.", chinese: "我搭火車。", note: "prendre le train＝「搭火車」。" },
    ],
    usageTip: "",
    collocations: [{ french: "en train", chinese: "搭火車" }, { french: "prendre le train", chinese: "搭火車" }],
    commonMistakes: [],
    relatedWords: ["gare", "bus"],
    tags: ["名詞", "高頻"], audio: null,
  },
  {
    id: "bus", word: "bus", displayWord: "un bus", partOfSpeech: "noun",
    gender: "m", forms: { indefiniteSingular: "un bus", definiteSingular: "le bus", indefinitePlural: "des bus", definitePlural: "les bus" },
    irregular: true, level: "A1", frequencyRank: 34, category: "transport",
    meanings: ["公車"],
    usageSummary: "指公車，陽性名詞，單複數同形。",
    patterns: ["en bus"],
    conjugation: null,
    examples: [
      { french: "Je vais à l'école en bus.", chinese: "我搭公車去學校。", note: "" },
    ],
    usageTip: "",
    collocations: [{ french: "en bus", chinese: "搭公車" }],
    commonMistakes: [],
    relatedWords: ["train", "voiture"],
    tags: ["名詞", "高頻"], audio: null,
  },
];
