export const PRONOUNS_WORDS = [
  {
    id: "je", word: "je", displayWord: "je", partOfSpeech: "pronoun",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 1, category: "pronouns",
    meanings: ["我"],
    usageSummary: "第一人稱單數主詞代詞，放在動詞前面，遇到母音開頭的動詞要縮寫成 j'。",
    patterns: ["Je ＋ 動詞"],
    conjugation: null,
    examples: [
      { french: "Je m'appelle Paul.", chinese: "我叫保羅。", note: "" },
      { french: "J'habite à Paris.", chinese: "我住在巴黎。", note: "habite 母音開頭，je 要縮寫成 j'。" },
    ],
    usageTip: "je 在母音或啞音 h 開頭的動詞前必須縮寫成 j'，例如 j'aime、j'habite。",
    collocations: [],
    commonMistakes: [{ wrong: "Je aime le café.", correct: "J'aime le café.", explanation: "je 遇到母音開頭的動詞要縮寫成 j'。" }],
    relatedWords: ["moi"],
    tags: ["高頻", "代詞"], audio: null,
  },
  {
    id: "tu", word: "tu", displayWord: "tu", partOfSpeech: "pronoun",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 2, category: "pronouns",
    meanings: ["你（非正式）"],
    usageSummary: "第二人稱單數，用於朋友、家人、同齡人、小孩等熟悉、非正式的關係。",
    patterns: ["Tu ＋ 動詞"],
    conjugation: null,
    examples: [
      { french: "Tu es étudiant ?", chinese: "你是學生嗎？", note: "" },
      { french: "Comment tu t'appelles ?", chinese: "你叫什麼名字？", note: "" },
    ],
    usageTip: "對陌生人、長輩或正式場合要用 vous，不要用 tu，否則顯得不禮貌。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["vous", "toi"],
    tags: ["高頻", "代詞"], audio: null,
  },
  {
    id: "il", word: "il", displayWord: "il", partOfSpeech: "pronoun",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 3, category: "pronouns",
    meanings: ["他", "它（陽性）"],
    usageSummary: "第三人稱單數陽性，指代男性或陽性名詞。",
    patterns: ["Il ＋ 動詞"],
    conjugation: null,
    examples: [
      { french: "Il est français.", chinese: "他是法國人。", note: "" },
      { french: "Le livre ? Il est sur la table.", chinese: "那本書？它在桌上。", note: "il 也可以指代陽性名詞（如 le livre）。" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["elle"],
    tags: ["高頻", "代詞"], audio: null,
  },
  {
    id: "elle", word: "elle", displayWord: "elle", partOfSpeech: "pronoun",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 4, category: "pronouns",
    meanings: ["她", "它（陰性）"],
    usageSummary: "第三人稱單數陰性，指代女性或陰性名詞。",
    patterns: ["Elle ＋ 動詞"],
    conjugation: null,
    examples: [
      { french: "Elle habite à Lyon.", chinese: "她住在里昂。", note: "" },
      { french: "La maison ? Elle est grande.", chinese: "那間房子？它很大。", note: "elle 也可以指代陰性名詞（如 la maison）。" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["il"],
    tags: ["高頻", "代詞"], audio: null,
  },
  {
    id: "on", word: "on", displayWord: "on", partOfSpeech: "pronoun",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 5, category: "pronouns",
    meanings: ["我們（口語）", "人們", "有人"],
    usageSummary: "口語中最常用來代替 nous（我們），文法上使用第三人稱單數變化；也可以表示泛指的「人們」。",
    patterns: ["On ＋ 動詞（第三人稱單數形式）"],
    conjugation: null,
    examples: [
      { french: "On mange à midi ?", chinese: "我們中午吃飯嗎？", note: "口語中 on 幾乎取代了 nous。" },
      { french: "En France, on parle français.", chinese: "在法國，人們說法語。", note: "泛指「人們」。" },
    ],
    usageTip: "on 雖然意思常是「我們」，但動詞變化要用第三人稱單數（跟 il/elle 相同），例如 on mange，不是 on mangeons。",
    collocations: [],
    commonMistakes: [{ wrong: "On mangeons.", correct: "On mange.", explanation: "on 要用第三人稱單數動詞變化，不能用 nous 的變化形式。" }],
    relatedWords: ["nous"],
    tags: ["口語", "高頻", "代詞"], audio: null,
  },
  {
    id: "nous", word: "nous", displayWord: "nous", partOfSpeech: "pronoun",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 6, category: "pronouns",
    meanings: ["我們"],
    usageSummary: "第一人稱複數，正式書寫和口語都可以使用，口語中常被 on 取代。",
    patterns: ["Nous ＋ 動詞"],
    conjugation: null,
    examples: [
      { french: "Nous sommes fatigués.", chinese: "我們很累。", note: "" },
      { french: "Nous habitons à Paris.", chinese: "我們住在巴黎。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["on"],
    tags: ["代詞"], audio: null,
  },
  {
    id: "vous", word: "vous", displayWord: "vous", partOfSpeech: "pronoun",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 7, category: "pronouns",
    meanings: ["你們", "您（禮貌單數）"],
    usageSummary: "第二人稱複數，也是對單一個人表示禮貌、尊重的用法（對陌生人、長輩、正式場合）。",
    patterns: ["Vous ＋ 動詞"],
    conjugation: null,
    examples: [
      { french: "Vous êtes professeur ?", chinese: "您是老師嗎？", note: "禮貌地對一個人使用。" },
      { french: "Vous parlez anglais ?", chinese: "你們會說英語嗎？", note: "對多人使用。" },
    ],
    usageTip: "對不熟悉的人或長輩要用 vous，不要用 tu，這是法語重要的禮貌規則。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["tu"],
    tags: ["高頻", "代詞"], audio: null,
  },
  {
    id: "ils", word: "ils", displayWord: "ils", partOfSpeech: "pronoun",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 8, category: "pronouns",
    meanings: ["他們"],
    usageSummary: "第三人稱複數陽性，指多個男性，或陽性名詞、或男女混合的一群人。",
    patterns: ["Ils ＋ 動詞"],
    conjugation: null,
    examples: [
      { french: "Ils sont étudiants.", chinese: "他們是學生。", note: "" },
      { french: "Ils habitent en France.", chinese: "他們住在法國。", note: "" },
    ],
    usageTip: "即使一群人裡只有一個男生，其餘全是女生，也要用 ils（陽性優先規則）。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["elles"],
    tags: ["代詞"], audio: null,
  },
  {
    id: "elles", word: "elles", displayWord: "elles", partOfSpeech: "pronoun",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 9, category: "pronouns",
    meanings: ["她們"],
    usageSummary: "第三人稱複數陰性，只有在全部都是女性或陰性名詞時使用。",
    patterns: ["Elles ＋ 動詞"],
    conjugation: null,
    examples: [
      { french: "Elles sont françaises.", chinese: "她們是法國人。", note: "" },
      { french: "Mes sœurs ? Elles sont à la maison.", chinese: "我的姊妹？她們在家。", note: "" },
    ],
    usageTip: "只要一群人裡有一個男生，就要改用 ils，不能用 elles。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["ils"],
    tags: ["代詞"], audio: null,
  },
  {
    id: "me", word: "me", displayWord: "me", partOfSpeech: "pronoun",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 10, category: "pronouns",
    meanings: ["我（受詞）", "自己（反身）"],
    usageSummary: "受詞代詞，放在動詞前面，表示「我」是動作的接受者；也用在反身動詞中。母音前縮寫成 m'。",
    patterns: ["主語 ＋ me/m' ＋ 動詞"],
    conjugation: null,
    examples: [
      { french: "Tu me comprends ?", chinese: "你懂我嗎？", note: "me 是「comprendre」的受詞。" },
      { french: "Je m'appelle Julie.", chinese: "我叫茱莉。", note: "反身動詞 s'appeler 的變化，母音前縮寫成 m'。" },
    ],
    usageTip: "me 放在動詞前面，不是後面，跟英文語序不同。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["moi"],
    tags: ["代詞"], audio: null,
  },
  {
    id: "te", word: "te", displayWord: "te", partOfSpeech: "pronoun",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 11, category: "pronouns",
    meanings: ["你（受詞）", "自己（反身）"],
    usageSummary: "受詞代詞，對應 tu，放在動詞前面；母音前縮寫成 t'。",
    patterns: ["主語 ＋ te/t' ＋ 動詞"],
    conjugation: null,
    examples: [
      { french: "Je te comprends.", chinese: "我懂你。", note: "" },
      { french: "Comment tu t'appelles ?", chinese: "你叫什麼名字？", note: "反身動詞 s'appeler，母音前縮寫成 t'。" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["toi"],
    tags: ["代詞"], audio: null,
  },
  {
    id: "se", word: "se", displayWord: "se", partOfSpeech: "pronoun",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 12, category: "pronouns",
    meanings: ["自己（反身，第三人稱）"],
    usageSummary: "第三人稱反身代詞，用在反身動詞中，對應 il/elle/on/ils/elles；母音前縮寫成 s'。",
    patterns: ["Il/Elle ＋ se/s' ＋ 反身動詞"],
    conjugation: null,
    examples: [
      { french: "Il s'appelle Marc.", chinese: "他叫馬克。", note: "s'appeler：自稱、叫做。" },
      { french: "Elle se lève tôt.", chinese: "她很早起床。", note: "se lever：起床。" },
    ],
    usageTip: "se 是反身動詞（如 s'appeler、se lever）的固定搭配，不能省略。",
    collocations: [{ french: "s'appeler", chinese: "名叫" }],
    commonMistakes: [],
    relatedWords: ["me", "te"],
    tags: ["代詞"], audio: null,
  },
  {
    id: "moi", word: "moi", displayWord: "moi", partOfSpeech: "pronoun",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 13, category: "pronouns",
    meanings: ["我（重讀）"],
    usageSummary: "重讀人稱代詞，用於強調、單獨回答問題、介詞後面，或跟 et 連用。",
    patterns: ["Moi, je...", "介詞 ＋ moi"],
    conjugation: null,
    examples: [
      { french: "Moi, je suis étudiant.", chinese: "我呢，我是學生。", note: "強調「我」。" },
      { french: "Tu viens avec moi ?", chinese: "你要跟我一起來嗎？", note: "avec 後面要用重讀代詞 moi，不能用 je。" },
    ],
    usageTip: "介詞（avec、pour、chez 等）後面一定要用 moi，不能用 je。",
    collocations: [{ french: "avec moi", chinese: "跟我一起" }, { french: "chez moi", chinese: "在我家" }],
    commonMistakes: [{ wrong: "chez je", correct: "chez moi", explanation: "介詞後面要用重讀代詞 moi，不能用主詞代詞 je。" }],
    relatedWords: ["je"],
    tags: ["代詞"], audio: null,
  },
  {
    id: "toi", word: "toi", displayWord: "toi", partOfSpeech: "pronoun",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 14, category: "pronouns",
    meanings: ["你（重讀）"],
    usageSummary: "重讀人稱代詞，對應 tu，用於強調、介詞後面，或單獨回答。",
    patterns: ["Et toi ?", "介詞 ＋ toi"],
    conjugation: null,
    examples: [
      { french: "Ça va, et toi ?", chinese: "我很好，你呢？", note: "非常常見的口語問句結尾。" },
      { french: "C'est pour toi.", chinese: "這是給你的。", note: "pour 後面要用重讀代詞 toi。" },
    ],
    usageTip: "",
    collocations: [{ french: "et toi ?", chinese: "你呢？" }, { french: "pour toi", chinese: "給你" }],
    commonMistakes: [],
    relatedWords: ["tu"],
    tags: ["高頻", "代詞"], audio: null,
  },
  {
    id: "lui", word: "lui", displayWord: "lui", partOfSpeech: "pronoun",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 15, category: "pronouns",
    meanings: ["他（重讀）", "他／她（間接受詞）"],
    usageSummary: "重讀代詞對應 il；同時也是第三人稱單數的間接受詞代詞（對他／對她）。",
    patterns: ["介詞 ＋ lui", "主語 ＋ lui ＋ 動詞"],
    conjugation: null,
    examples: [
      { french: "C'est lui.", chinese: "是他。", note: "重讀代詞，單獨指出「他」。" },
      { french: "Je lui parle.", chinese: "我跟他／她說話。", note: "間接受詞，放在動詞前面。" },
    ],
    usageTip: "lui 當間接受詞時男女通用（可以指「他」也可以指「她」），要靠上下文判斷。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["il", "elle"],
    tags: ["代詞"], audio: null,
  },
];
