export const QUESTION_WORDS = [
  {
    id: "qui", word: "qui", displayWord: "qui", partOfSpeech: "question-word",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 1, category: "questionWords",
    meanings: ["誰"],
    usageSummary: "詢問人物身份的疑問詞。",
    patterns: ["Qui ＋ 動詞 ？", "Qui est-ce que ＋ 主語 ＋ 動詞 ？"],
    conjugation: null,
    examples: [
      { french: "Qui est-ce ?", chinese: "這是誰？", note: "" },
      { french: "Qui parle français ici ?", chinese: "這裡誰會說法語？", note: "qui 直接當主語。" },
    ],
    usageTip: "",
    collocations: [{ french: "qui est-ce", chinese: "這是誰" }],
    commonMistakes: [],
    relatedWords: ["que", "quoi"],
    tags: ["疑問詞", "高頻"], audio: null,
  },
  {
    id: "que", word: "que", displayWord: "que", partOfSpeech: "question-word",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 2, category: "questionWords",
    meanings: ["什麼"],
    usageSummary: "詢問事物的疑問詞，用於句首並倒裝動詞，或搭配 est-ce que。母音前縮寫成 qu'。",
    patterns: ["Que ＋ 動詞 ＋ 主語 ？", "Qu'est-ce que ＋ 主語 ＋ 動詞 ？"],
    conjugation: null,
    examples: [
      { french: "Que fais-tu ?", chinese: "你在做什麼？", note: "" },
      { french: "Qu'est-ce que tu veux ?", chinese: "你想要什麼？", note: "口語中最常用的形式。" },
    ],
    usageTip: "口語中通常用 qu'est-ce que 開頭，比 que＋倒裝動詞更自然。",
    collocations: [{ french: "qu'est-ce que", chinese: "……是什麼" }],
    commonMistakes: [],
    relatedWords: ["quoi", "qui"],
    tags: ["疑問詞", "高頻"], audio: null,
  },
  {
    id: "quoi", word: "quoi", displayWord: "quoi", partOfSpeech: "question-word",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 3, category: "questionWords",
    meanings: ["什麼"],
    usageSummary: "口語中單獨使用或放在句尾、介詞後面詢問事物，比 que 更隨意。",
    patterns: ["介詞 ＋ quoi", "句尾 quoi ？"],
    conjugation: null,
    examples: [
      { french: "Tu penses à quoi ?", chinese: "你在想什麼？", note: "介詞 à 後面用 quoi。" },
      { french: "Quoi ?", chinese: "什麼？", note: "口語中單獨使用，表示驚訝或沒聽清楚。" },
    ],
    usageTip: "quoi 不能放在句首當主語問句，句首要用 qu'est-ce qui／que。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["que"],
    tags: ["疑問詞", "口語"], audio: null,
  },
  {
    id: "ou-question", word: "où", displayWord: "où", partOfSpeech: "question-word",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 4, category: "questionWords",
    meanings: ["哪裡"],
    usageSummary: "詢問地點的疑問詞。",
    patterns: ["Où ＋ 動詞 ＋ 主語 ？", "主語 ＋ 動詞 ＋ où ？（口語）"],
    conjugation: null,
    examples: [
      { french: "Où habites-tu ?", chinese: "你住在哪裡？", note: "" },
      { french: "Tu vas où ?", chinese: "你要去哪裡？", note: "口語常把 où 放在句尾。" },
    ],
    usageTip: "où（哪裡，帶重音符號）跟 ou（或者，沒有重音符號）拼寫非常接近，注意不要混淆。",
    collocations: [],
    commonMistakes: [{ wrong: "把 où 和 ou 混用", correct: "où＝哪裡；ou＝或者", explanation: "兩者發音不同、意思完全不同，只差一個重音符號。" }],
    relatedWords: ["ou"],
    tags: ["疑問詞", "高頻"], audio: null,
  },
  {
    id: "quand", word: "quand", displayWord: "quand", partOfSpeech: "question-word",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 5, category: "questionWords",
    meanings: ["什麼時候"],
    usageSummary: "詢問時間的疑問詞。",
    patterns: ["Quand ＋ 動詞 ＋ 主語 ？"],
    conjugation: null,
    examples: [
      { french: "Quand est-ce que tu arrives ?", chinese: "你什麼時候到？", note: "" },
      { french: "Tu pars quand ?", chinese: "你什麼時候出發？", note: "口語常把 quand 放在句尾。" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: [],
    tags: ["疑問詞", "高頻"], audio: null,
  },
  {
    id: "comment", word: "comment", displayWord: "comment", partOfSpeech: "question-word",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 6, category: "questionWords",
    meanings: ["怎麼", "如何"],
    usageSummary: "詢問方式、狀態的疑問詞，也用於問候語「你好嗎」。",
    patterns: ["Comment ＋ 動詞 ＋ 主語 ？"],
    conjugation: null,
    examples: [
      { french: "Comment ça va ?", chinese: "你最近好嗎？", note: "非常常見的問候語。" },
      { french: "Comment tu t'appelles ?", chinese: "你叫什麼名字？", note: "" },
    ],
    usageTip: "",
    collocations: [{ french: "comment ça va", chinese: "你好嗎" }, { french: "comment allez-vous", chinese: "您好嗎（正式）" }],
    commonMistakes: [],
    relatedWords: [],
    tags: ["疑問詞", "高頻"], audio: null,
  },
  {
    id: "pourquoi", word: "pourquoi", displayWord: "pourquoi", partOfSpeech: "question-word",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 7, category: "questionWords",
    meanings: ["為什麼"],
    usageSummary: "詢問原因的疑問詞，回答時常用 parce que（因為）。",
    patterns: ["Pourquoi ＋ 動詞 ＋ 主語 ？"],
    conjugation: null,
    examples: [
      { french: "Pourquoi tu es en retard ?", chinese: "你為什麼遲到？", note: "" },
      { french: "Pourquoi pas ?", chinese: "為什麼不呢？", note: "常用來表示同意提議。" },
    ],
    usageTip: "回答 pourquoi 的問題通常用 parce que 開頭。",
    collocations: [{ french: "pourquoi pas", chinese: "為什麼不呢" }],
    commonMistakes: [],
    relatedWords: ["parce que"],
    tags: ["疑問詞", "高頻"], audio: null,
  },
  {
    id: "combien", word: "combien", displayWord: "combien", partOfSpeech: "question-word",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 8, category: "questionWords",
    meanings: ["多少"],
    usageSummary: "詢問數量或價錢的疑問詞，常搭配 de 接名詞。",
    patterns: ["Combien de ＋ 名詞 ？", "Ça coûte combien ？"],
    conjugation: null,
    examples: [
      { french: "Ça coûte combien ?", chinese: "這個多少錢？", note: "" },
      { french: "Combien de personnes ?", chinese: "有多少人？", note: "combien de 後面直接接名詞，不需要冠詞。" },
    ],
    usageTip: "combien de 後面的名詞不加冠詞，例如 combien de personnes，不是 combien des personnes。",
    collocations: [{ french: "combien de", chinese: "多少……" }, { french: "ça coûte combien", chinese: "這個多少錢" }],
    commonMistakes: [],
    relatedWords: [],
    tags: ["疑問詞", "高頻"], audio: null,
  },
  {
    id: "quel", word: "quel", displayWord: "quel", partOfSpeech: "question-word",
    gender: "m", forms: { ms: "quel", fs: "quelle", mp: "quels", fp: "quelles" }, irregular: null, level: "A1", frequencyRank: 9, category: "questionWords",
    meanings: ["哪個（陽性單數）"],
    usageSummary: "疑問形容詞，用來詢問「哪一個」，必須配合後面名詞的陰陽性和單複數變化。",
    patterns: ["Quel ＋ 陽性單數名詞"],
    conjugation: null,
    examples: [
      { french: "Quel jour sommes-nous ?", chinese: "今天星期幾？", note: "jour 是陽性單數名詞。" },
      { french: "Quel est ton nom ?", chinese: "你叫什麼名字？", note: "" },
    ],
    usageTip: "quel 有四種形式（quel/quelle/quels/quelles），要依照後面名詞的性別和單複數選擇正確形式。",
    collocations: [],
    commonMistakes: [{ wrong: "Quel heure est-il ?", correct: "Quelle heure est-il ?", explanation: "heure 是陰性名詞，要用 quelle，不是 quel。" }],
    relatedWords: ["quelle", "quels", "quelles"],
    tags: ["疑問詞", "高頻"], audio: null,
  },
  {
    id: "quelle", word: "quelle", displayWord: "quelle", partOfSpeech: "question-word",
    gender: "f", forms: { ms: "quel", fs: "quelle", mp: "quels", fp: "quelles" }, irregular: null, level: "A1", frequencyRank: 10, category: "questionWords",
    meanings: ["哪個（陰性單數）"],
    usageSummary: "quel 的陰性單數形式，用在陰性單數名詞前。",
    patterns: ["Quelle ＋ 陰性單數名詞"],
    conjugation: null,
    examples: [
      { french: "Quelle heure est-il ?", chinese: "現在幾點？", note: "heure 是陰性名詞。" },
      { french: "Quelle est ta couleur préférée ?", chinese: "你最喜歡的顏色是什麼？", note: "" },
    ],
    usageTip: "",
    collocations: [{ french: "quelle heure est-il", chinese: "現在幾點" }],
    commonMistakes: [],
    relatedWords: ["quel"],
    tags: ["疑問詞", "高頻"], audio: null,
  },
  {
    id: "quels", word: "quels", displayWord: "quels", partOfSpeech: "question-word",
    gender: "m", forms: { ms: "quel", fs: "quelle", mp: "quels", fp: "quelles" }, irregular: null, level: "A1", frequencyRank: 11, category: "questionWords",
    meanings: ["哪些（陽性複數）"],
    usageSummary: "quel 的陽性複數形式。",
    patterns: ["Quels ＋ 陽性複數名詞"],
    conjugation: null,
    examples: [
      { french: "Quels sont tes loisirs ?", chinese: "你的興趣是什麼？", note: "loisirs 是陽性複數。" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["quel"],
    tags: ["疑問詞"], audio: null,
  },
  {
    id: "quelles", word: "quelles", displayWord: "quelles", partOfSpeech: "question-word",
    gender: "f", forms: { ms: "quel", fs: "quelle", mp: "quels", fp: "quelles" }, irregular: null, level: "A1", frequencyRank: 12, category: "questionWords",
    meanings: ["哪些（陰性複數）"],
    usageSummary: "quel 的陰性複數形式。",
    patterns: ["Quelles ＋ 陰性複數名詞"],
    conjugation: null,
    examples: [
      { french: "Quelles langues tu parles ?", chinese: "你會說哪些語言？", note: "langues 是陰性複數。" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["quelle"],
    tags: ["疑問詞"], audio: null,
  },
  {
    id: "mais", word: "mais", displayWord: "mais", partOfSpeech: "conjunction",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 13, category: "questionWords",
    meanings: ["但是"],
    usageSummary: "連接兩個對比或轉折的句子。",
    patterns: ["句子 ＋ mais ＋ 句子"],
    conjugation: null,
    examples: [
      { french: "J'aime le café, mais pas le thé.", chinese: "我喜歡咖啡，但不喜歡茶。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["et", "ou"],
    tags: ["連接詞", "高頻"], audio: null,
  },
  {
    id: "et", word: "et", displayWord: "et", partOfSpeech: "conjunction",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 14, category: "questionWords",
    meanings: ["和", "然後"],
    usageSummary: "連接詞，表示並列或先後順序。",
    patterns: ["A ＋ et ＋ B"],
    conjugation: null,
    examples: [
      { french: "Je mange et je bois.", chinese: "我吃東西也喝水。", note: "" },
      { french: "Et toi ?", chinese: "你呢？", note: "非常常用的口語問句。" },
    ],
    usageTip: "",
    collocations: [{ french: "et toi ?", chinese: "你呢？" }],
    commonMistakes: [],
    relatedWords: ["ou", "mais"],
    tags: ["連接詞", "高頻"], audio: null,
  },
  {
    id: "ou", word: "ou", displayWord: "ou", partOfSpeech: "conjunction",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 15, category: "questionWords",
    meanings: ["或者"],
    usageSummary: "連接詞，表示選擇。",
    patterns: ["A ＋ ou ＋ B"],
    conjugation: null,
    examples: [
      { french: "Thé ou café ?", chinese: "茶還是咖啡？", note: "" },
    ],
    usageTip: "ou（或者，沒有重音符號）跟 où（哪裡，帶重音符號）發音相同、拼寫接近，靠重音符號區分。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["où"],
    tags: ["連接詞", "高頻"], audio: null,
  },
  {
    id: "parce-que", word: "parce que", displayWord: "parce que", partOfSpeech: "conjunction",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 16, category: "questionWords",
    meanings: ["因為"],
    usageSummary: "用來說明原因，通常用來回答 pourquoi 的問題。母音前縮寫成 parce qu'。",
    patterns: ["句子 ＋ parce que ＋ 原因"],
    conjugation: null,
    examples: [
      { french: "Je suis fatigué parce que je travaille beaucoup.", chinese: "我很累，因為我工作很多。", note: "" },
      { french: "Il est content parce qu'il a réussi.", chinese: "他很高興，因為他成功了。", note: "il 母音開頭，parce que 縮寫成 parce qu'。" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["pourquoi"],
    tags: ["連接詞", "高頻"], audio: null,
  },
  {
    id: "avec", word: "avec", displayWord: "avec", partOfSpeech: "preposition",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 17, category: "questionWords",
    meanings: ["跟……一起", "用"],
    usageSummary: "表示陪伴或使用的工具／方式。",
    patterns: ["avec ＋ 名詞／重讀代詞"],
    conjugation: null,
    examples: [
      { french: "Je viens avec toi.", chinese: "我跟你一起來。", note: "" },
      { french: "Il écrit avec un stylo.", chinese: "他用一支筆寫字。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["sans"],
    tags: ["介詞", "高頻"], audio: null,
  },
  {
    id: "sans", word: "sans", displayWord: "sans", partOfSpeech: "preposition",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 18, category: "questionWords",
    meanings: ["沒有", "不用"],
    usageSummary: "表示缺乏或不使用某物，跟 avec 意思相反。",
    patterns: ["sans ＋ 名詞"],
    conjugation: null,
    examples: [
      { french: "Un café sans sucre, s'il vous plaît.", chinese: "請給我一杯不加糖的咖啡。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["avec"],
    tags: ["介詞"], audio: null,
  },
  {
    id: "pour", word: "pour", displayWord: "pour", partOfSpeech: "preposition",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 19, category: "questionWords",
    meanings: ["為了", "給"],
    usageSummary: "表示目的、對象或用途。",
    patterns: ["pour ＋ 名詞／人", "pour ＋ 動詞原形"],
    conjugation: null,
    examples: [
      { french: "C'est pour toi.", chinese: "這是給你的。", note: "" },
      { french: "Je travaille pour gagner de l'argent.", chinese: "我工作是為了賺錢。", note: "pour 後面接動詞原形表示目的。" },
    ],
    usageTip: "",
    collocations: [{ french: "pour toi", chinese: "給你" }],
    commonMistakes: [],
    relatedWords: [],
    tags: ["介詞", "高頻"], audio: null,
  },
  {
    id: "chez", word: "chez", displayWord: "chez", partOfSpeech: "preposition",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 20, category: "questionWords",
    meanings: ["在……家", "在……那裡（人、商店）"],
    usageSummary: "chez 後面通常接人物、人稱代詞、醫生或商店名稱，表示「在某人那裡」，不能單純理解成「在」。",
    patterns: ["chez ＋ 人物／重讀代詞"],
    conjugation: null,
    examples: [
      { french: "Je suis chez Marie.", chinese: "我在 Marie 家。", note: "" },
      { french: "Je vais chez le médecin.", chinese: "我要去看醫生。", note: "" },
      { french: "Nous mangeons chez mes parents.", chinese: "我們在我父母家吃飯。", note: "" },
    ],
    usageTip: "不能把 chez 單純理解成「在」，它主要表示「在某人那裡」。",
    collocations: [{ french: "chez moi", chinese: "在我家" }, { french: "chez le médecin", chinese: "在醫生那裡" }],
    commonMistakes: [{ wrong: "chez je", correct: "chez moi", explanation: "chez 後面接人稱代詞時要用重讀形式（moi/toi/lui...），不能用 je。" }],
    relatedWords: ["dans"],
    tags: ["介詞", "高頻"], audio: null,
  },
  {
    id: "dans", word: "dans", displayWord: "dans", partOfSpeech: "preposition",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 21, category: "questionWords",
    meanings: ["在……裡面", "（時間）……之後"],
    usageSummary: "表示在某個空間內部，也可以表示「多久之後」。",
    patterns: ["dans ＋ 地點／時間"],
    conjugation: null,
    examples: [
      { french: "Le livre est dans le sac.", chinese: "書在袋子裡。", note: "" },
      { french: "Je reviens dans dix minutes.", chinese: "我十分鐘後回來。", note: "dans 表示「之後」時，用於未來的時間。" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["chez", "sur"],
    tags: ["介詞", "高頻"], audio: null,
  },
  {
    id: "sur", word: "sur", displayWord: "sur", partOfSpeech: "preposition",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 22, category: "questionWords",
    meanings: ["在……上面", "關於"],
    usageSummary: "表示位置在某物表面之上，也可以表示「關於」某個主題。",
    patterns: ["sur ＋ 名詞"],
    conjugation: null,
    examples: [
      { french: "Le téléphone est sur la table.", chinese: "手機在桌上。", note: "" },
      { french: "Un livre sur la France.", chinese: "一本關於法國的書。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["sous"],
    tags: ["介詞", "高頻"], audio: null,
  },
  {
    id: "sous", word: "sous", displayWord: "sous", partOfSpeech: "preposition",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 23, category: "questionWords",
    meanings: ["在……下面"],
    usageSummary: "表示位置在某物下方，跟 sur 意思相反。",
    patterns: ["sous ＋ 名詞"],
    conjugation: null,
    examples: [
      { french: "Le chat est sous la table.", chinese: "貓在桌子下面。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["sur"],
    tags: ["介詞"], audio: null,
  },
  {
    id: "devant", word: "devant", displayWord: "devant", partOfSpeech: "preposition",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 24, category: "questionWords",
    meanings: ["在……前面"],
    usageSummary: "表示位置在某物或某人的前方。",
    patterns: ["devant ＋ 名詞"],
    conjugation: null,
    examples: [
      { french: "La voiture est devant la maison.", chinese: "車子在房子前面。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["derrière"],
    tags: ["介詞"], audio: null,
  },
  {
    id: "derriere", word: "derrière", displayWord: "derrière", partOfSpeech: "preposition",
    gender: null, forms: null, irregular: null, level: "A1", frequencyRank: 25, category: "questionWords",
    meanings: ["在……後面"],
    usageSummary: "表示位置在某物或某人的後方，跟 devant 意思相反。",
    patterns: ["derrière ＋ 名詞"],
    conjugation: null,
    examples: [
      { french: "Le jardin est derrière la maison.", chinese: "花園在房子後面。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["devant"],
    tags: ["介詞"], audio: null,
  },
];
