// 常用動詞：A1 階段只列現在式六人稱變化，不加入其他時態，避免頁面變成完整動詞課程。

export const VERBS_WORDS = [
  {
    id: "etre", word: "être", displayWord: "être", partOfSpeech: "verb",
    gender: null, forms: null, irregular: true, level: "A1", frequencyRank: 1, category: "verbs",
    meanings: ["是", "處於"],
    usageSummary: "être 用來說明身份、職業、國籍、狀態或特徵。",
    patterns: ["主語 ＋ être ＋ 名詞", "主語 ＋ être ＋ 形容詞"],
    conjugation: { je: "suis", tu: "es", ilElleOn: "est", nous: "sommes", vous: "êtes", ilsElles: "sont" },
    examples: [
      { french: "Je suis étudiant.", chinese: "我是學生。", note: "用 être 表示身份。" },
      { french: "Elle est française.", chinese: "她是法國人。", note: "" },
      { french: "Nous sommes fatigués.", chinese: "我們很累。", note: "" },
    ],
    usageTip: "法語不能直接說「Je étudiant」，必須加入 être，說成「Je suis étudiant」。",
    collocations: [{ french: "être content", chinese: "感到高興" }, { french: "être fatigué", chinese: "感到疲倦" }, { french: "être en retard", chinese: "遲到" }],
    commonMistakes: [{ wrong: "Je étudiant.", correct: "Je suis étudiant.", explanation: "法語句子需要 être 連接主語和身份，不能省略動詞。" }],
    relatedWords: ["avoir"],
    tags: ["高頻", "不規則", "動詞"], audio: null,
  },
  {
    id: "avoir", word: "avoir", displayWord: "avoir", partOfSpeech: "verb",
    gender: null, forms: null, irregular: true, level: "A1", frequencyRank: 2, category: "verbs",
    meanings: ["有", "擁有"],
    usageSummary: "avoir 用來表示擁有某件東西，也用來表達年齡和部分身體感覺。",
    patterns: ["主語 ＋ avoir ＋ 名詞"],
    conjugation: { je: "ai", tu: "as", ilElleOn: "a", nous: "avons", vous: "avez", ilsElles: "ont" },
    examples: [
      { french: "J'ai un livre.", chinese: "我有一本書。", note: "" },
      { french: "Tu as vingt ans.", chinese: "你二十歲。", note: "" },
      { french: "Nous avons faim.", chinese: "我們餓了。", note: "" },
    ],
    usageTip: "法語表達年齡時使用 avoir，不使用 être：正確是「J'ai vingt ans」，不是「Je suis vingt ans」。",
    collocations: [{ french: "avoir faim", chinese: "肚子餓" }, { french: "avoir soif", chinese: "口渴" }, { french: "avoir peur", chinese: "害怕" }, { french: "avoir besoin de", chinese: "需要" }, { french: "avoir envie de", chinese: "想要" }],
    commonMistakes: [{ wrong: "Je suis vingt ans.", correct: "J'ai vingt ans.", explanation: "表達年齡要用 avoir，不能用 être。" }],
    relatedWords: ["être"],
    tags: ["高頻", "不規則", "動詞"], audio: null,
  },
  {
    id: "aller", word: "aller", displayWord: "aller", partOfSpeech: "verb",
    gender: null, forms: null, irregular: true, level: "A1", frequencyRank: 3, category: "verbs",
    meanings: ["去", "前往", "（狀態）如何"],
    usageSummary: "用來表示前往某個地方，也會出現在問候語「Comment ça va ?」裡。",
    patterns: ["主語 ＋ aller ＋ 地點"],
    conjugation: { je: "vais", tu: "vas", ilElleOn: "va", nous: "allons", vous: "allez", ilsElles: "vont" },
    examples: [
      { french: "Je vais à l'école.", chinese: "我去學校。", note: "" },
      { french: "Nous allons au restaurant.", chinese: "我們去餐廳。", note: "" },
      { french: "Comment ça va ?", chinese: "你最近怎麼樣？", note: "" },
    ],
    usageTip: "地點前通常需要使用 à、au、à la、à l' 或 aux。",
    collocations: [{ french: "aller à Paris", chinese: "去巴黎" }, { french: "aller au travail", chinese: "去上班" }, { french: "aller bien/mal", chinese: "狀況好／不好" }],
    commonMistakes: [],
    relatedWords: ["venir"],
    tags: ["高頻", "不規則", "動詞"], audio: null,
  },
  {
    id: "faire", word: "faire", displayWord: "faire", partOfSpeech: "verb",
    gender: null, forms: null, irregular: true, level: "A1", frequencyRank: 4, category: "verbs",
    meanings: ["做", "製作"],
    usageSummary: "法語中用途最廣的動詞之一，也常用於天氣表達（il fait beau）。",
    patterns: ["主語 ＋ faire ＋ 名詞"],
    conjugation: { je: "fais", tu: "fais", ilElleOn: "fait", nous: "faisons", vous: "faites", ilsElles: "font" },
    examples: [
      { french: "Qu'est-ce que tu fais ?", chinese: "你在做什麼？", note: "" },
      { french: "Il fait beau aujourd'hui.", chinese: "今天天氣很好。", note: "faire 常用於天氣表達。" },
    ],
    usageTip: "很多固定用法都用 faire，例如 faire les courses（買東西）、faire du sport（運動）。",
    collocations: [{ french: "faire les courses", chinese: "買東西、採購" }, { french: "faire du sport", chinese: "做運動" }],
    commonMistakes: [],
    relatedWords: [],
    tags: ["高頻", "不規則", "動詞"], audio: null,
  },
  {
    id: "venir", word: "venir", displayWord: "venir", partOfSpeech: "verb",
    gender: null, forms: null, irregular: true, level: "A1", frequencyRank: 5, category: "verbs",
    meanings: ["來"],
    usageSummary: "表示朝說話者的方向移動，跟 aller 相反。",
    patterns: ["主語 ＋ venir ＋ de/à + 地點"],
    conjugation: { je: "viens", tu: "viens", ilElleOn: "vient", nous: "venons", vous: "venez", ilsElles: "viennent" },
    examples: [
      { french: "Je viens de Taïwan.", chinese: "我來自台灣。", note: "venir de＋地方＝「來自……」。" },
      { french: "Tu viens avec moi ?", chinese: "你要跟我一起來嗎？", note: "" },
    ],
    usageTip: "venir de 也可以表示「剛剛做過某事」，例如 je viens de manger（我剛吃過飯）。",
    collocations: [{ french: "venir de", chinese: "來自……／剛剛……" }],
    commonMistakes: [],
    relatedWords: ["aller"],
    tags: ["高頻", "不規則", "動詞"], audio: null,
  },
  {
    id: "pouvoir", word: "pouvoir", displayWord: "pouvoir", partOfSpeech: "verb",
    gender: null, forms: null, irregular: true, level: "A1", frequencyRank: 6, category: "verbs",
    meanings: ["能夠", "可以"],
    usageSummary: "表示能力或許可，後面接動詞原形。",
    patterns: ["主語 ＋ pouvoir ＋ 動詞原形"],
    conjugation: { je: "peux", tu: "peux", ilElleOn: "peut", nous: "pouvons", vous: "pouvez", ilsElles: "peuvent" },
    examples: [
      { french: "Je peux vous aider.", chinese: "我可以幫您。", note: "" },
      { french: "Est-ce que je peux entrer ?", chinese: "我可以進來嗎？", note: "禮貌詢問許可。" },
    ],
    usageTip: "pouvoir 後面直接接動詞原形，不需要加介詞。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["vouloir", "devoir"],
    tags: ["高頻", "不規則", "動詞"], audio: null,
  },
  {
    id: "vouloir", word: "vouloir", displayWord: "vouloir", partOfSpeech: "verb",
    gender: null, forms: null, irregular: true, level: "A1", frequencyRank: 7, category: "verbs",
    meanings: ["想要"],
    usageSummary: "表示願望，後面可接名詞或動詞原形。",
    patterns: ["主語 ＋ vouloir ＋ 名詞／動詞原形"],
    conjugation: { je: "veux", tu: "veux", ilElleOn: "veut", nous: "voulons", vous: "voulez", ilsElles: "veulent" },
    examples: [
      { french: "Je voudrais un café.", chinese: "我想要一杯咖啡。", note: "voudrais 是更禮貌的說法（條件式），點餐時常用。" },
      { french: "Qu'est-ce que tu veux faire ?", chinese: "你想做什麼？", note: "" },
    ],
    usageTip: "點餐或提出禮貌請求時，用 je voudrais 比 je veux 更客氣。",
    collocations: [{ french: "je voudrais", chinese: "我想要（禮貌）" }],
    commonMistakes: [],
    relatedWords: ["pouvoir", "devoir"],
    tags: ["高頻", "不規則", "動詞"], audio: null,
  },
  {
    id: "devoir", word: "devoir", displayWord: "devoir", partOfSpeech: "verb",
    gender: null, forms: null, irregular: true, level: "A1", frequencyRank: 8, category: "verbs",
    meanings: ["必須", "應該", "欠（錢）"],
    usageSummary: "表示義務或必要性，後面接動詞原形；也可以表示欠錢。",
    patterns: ["主語 ＋ devoir ＋ 動詞原形"],
    conjugation: { je: "dois", tu: "dois", ilElleOn: "doit", nous: "devons", vous: "devez", ilsElles: "doivent" },
    examples: [
      { french: "Je dois partir maintenant.", chinese: "我現在必須走了。", note: "" },
      { french: "Tu me dois dix euros.", chinese: "你欠我十歐元。", note: "devoir 也可以表示「欠」。" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["pouvoir", "vouloir"],
    tags: ["高頻", "不規則", "動詞"], audio: null,
  },
  {
    id: "savoir", word: "savoir", displayWord: "savoir", partOfSpeech: "verb",
    gender: null, forms: null, irregular: true, level: "A1", frequencyRank: 9, category: "verbs",
    meanings: ["知道", "會（技能）"],
    usageSummary: "表示知道事實或掌握某項技能，跟 connaître（認識人／地方）不同。",
    patterns: ["主語 ＋ savoir ＋ 動詞原形／que + 句子"],
    conjugation: { je: "sais", tu: "sais", ilElleOn: "sait", nous: "savons", vous: "savez", ilsElles: "savent" },
    examples: [
      { french: "Je sais nager.", chinese: "我會游泳。", note: "savoir＋動詞原形＝會做某件事。" },
      { french: "Je ne sais pas.", chinese: "我不知道。", note: "" },
    ],
    usageTip: "savoir 用於知識或技能（會做某事），connaître 用於認識人或熟悉地方，不能互換。",
    collocations: [{ french: "je ne sais pas", chinese: "我不知道" }],
    commonMistakes: [{ wrong: "Je connais nager.", correct: "Je sais nager.", explanation: "表達會不會某項技能要用 savoir，不能用 connaître。" }],
    relatedWords: ["connaître"],
    tags: ["高頻", "不規則", "動詞"], audio: null,
  },
  {
    id: "connaitre", word: "connaître", displayWord: "connaître", partOfSpeech: "verb",
    gender: null, forms: null, irregular: true, level: "A1", frequencyRank: 10, category: "verbs",
    meanings: ["認識", "熟悉"],
    usageSummary: "表示認識人、熟悉地方或事物，後面直接接名詞，不能接動詞原形。",
    patterns: ["主語 ＋ connaître ＋ 名詞"],
    conjugation: { je: "connais", tu: "connais", ilElleOn: "connaît", nous: "connaissons", vous: "connaissez", ilsElles: "connaissent" },
    examples: [
      { french: "Je connais Paris.", chinese: "我熟悉巴黎。", note: "" },
      { french: "Tu connais cette personne ?", chinese: "你認識這個人嗎？", note: "" },
    ],
    usageTip: "connaître 後面一定接名詞（人、地方、事物），不能像 savoir 一樣接動詞原形。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["savoir"],
    tags: ["不規則", "動詞"], audio: null,
  },
  {
    id: "aimer", word: "aimer", displayWord: "aimer", partOfSpeech: "verb",
    gender: null, forms: null, irregular: false, level: "A1", frequencyRank: 11, category: "verbs",
    meanings: ["喜歡", "愛"],
    usageSummary: "規則 -er 動詞，表示喜歡或愛，後面可接名詞或動詞原形。",
    patterns: ["主語 ＋ aimer ＋ 名詞／動詞原形"],
    conjugation: { je: "aime", tu: "aimes", ilElleOn: "aime", nous: "aimons", vous: "aimez", ilsElles: "aiment" },
    examples: [
      { french: "J'aime le café.", chinese: "我喜歡咖啡。", note: "" },
      { french: "Elle aime lire.", chinese: "她喜歡閱讀。", note: "" },
    ],
    usageTip: "aimer 後面接名詞時，通常要保留定冠詞（j'aime le café，不是 j'aime café）。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["préférer"],
    tags: ["高頻", "規則", "動詞"], audio: null,
  },
  {
    id: "parler", word: "parler", displayWord: "parler", partOfSpeech: "verb",
    gender: null, forms: null, irregular: false, level: "A1", frequencyRank: 12, category: "verbs",
    meanings: ["說", "說話"],
    usageSummary: "規則 -er 動詞，表示說話或使用某種語言。",
    patterns: ["主語 ＋ parler ＋ 語言"],
    conjugation: { je: "parle", tu: "parles", ilElleOn: "parle", nous: "parlons", vous: "parlez", ilsElles: "parlent" },
    examples: [
      { french: "Je parle français.", chinese: "我說法語。", note: "語言名稱前不加冠詞。" },
      { french: "Tu parles trop vite.", chinese: "你說得太快了。", note: "" },
    ],
    usageTip: "parler 後面接語言名稱時不加冠詞：je parle français，不是 je parle le français。",
    collocations: [],
    commonMistakes: [{ wrong: "Je parle le français.", correct: "Je parle français.", explanation: "parler＋語言名稱時通常不加定冠詞。" }],
    relatedWords: ["dire"],
    tags: ["高頻", "規則", "動詞"], audio: null,
  },
  {
    id: "habiter", word: "habiter", displayWord: "habiter", partOfSpeech: "verb",
    gender: null, forms: null, irregular: false, level: "A1", frequencyRank: 13, category: "verbs",
    meanings: ["居住"],
    usageSummary: "規則 -er 動詞，表示住在某個地方。母音開頭，je 要縮寫成 j'。",
    patterns: ["主語 ＋ habiter ＋ à/en + 地點"],
    conjugation: { je: "habite", tu: "habites", ilElleOn: "habite", nous: "habitons", vous: "habitez", ilsElles: "habitent" },
    examples: [
      { french: "J'habite à Paris.", chinese: "我住在巴黎。", note: "habite 母音開頭，je 縮寫成 j'。" },
      { french: "Nous habitons en France.", chinese: "我們住在法國。", note: "" },
    ],
    usageTip: "城市前用 à，陰性國家名前用 en。",
    collocations: [],
    commonMistakes: [],
    relatedWords: [],
    tags: ["高頻", "規則", "動詞"], audio: null,
  },
  {
    id: "travailler", word: "travailler", displayWord: "travailler", partOfSpeech: "verb",
    gender: null, forms: null, irregular: false, level: "A1", frequencyRank: 14, category: "verbs",
    meanings: ["工作"],
    usageSummary: "規則 -er 動詞，表示工作。",
    patterns: ["主語 ＋ travailler"],
    conjugation: { je: "travaille", tu: "travailles", ilElleOn: "travaille", nous: "travaillons", vous: "travaillez", ilsElles: "travaillent" },
    examples: [
      { french: "Je travaille dans un magasin.", chinese: "我在一間商店工作。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["travail"],
    tags: ["高頻", "規則", "動詞"], audio: null,
  },
  {
    id: "etudier", word: "étudier", displayWord: "étudier", partOfSpeech: "verb",
    gender: null, forms: null, irregular: false, level: "A1", frequencyRank: 15, category: "verbs",
    meanings: ["學習", "研讀"],
    usageSummary: "規則 -er 動詞，表示學習或研讀某個科目。",
    patterns: ["主語 ＋ étudier ＋ 名詞"],
    conjugation: { je: "étudie", tu: "étudies", ilElleOn: "étudie", nous: "étudions", vous: "étudiez", ilsElles: "étudient" },
    examples: [
      { french: "J'étudie le français.", chinese: "我在學法語。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["école"],
    tags: ["規則", "動詞"], audio: null,
  },
  {
    id: "manger", word: "manger", displayWord: "manger", partOfSpeech: "verb",
    gender: null, forms: null, irregular: false, level: "A1", frequencyRank: 16, category: "verbs",
    meanings: ["吃"],
    usageSummary: "規則 -er 動詞，nous 的變化拼寫加 e（mangeons）以保持軟音。",
    patterns: ["主語 ＋ manger ＋ 名詞"],
    conjugation: { je: "mange", tu: "manges", ilElleOn: "mange", nous: "mangeons", vous: "mangez", ilsElles: "mangent" },
    examples: [
      { french: "Je mange du pain.", chinese: "我吃麵包。", note: "" },
      { french: "Nous mangeons ensemble.", chinese: "我們一起吃飯。", note: "nous mangeons 多了一個 e。" },
    ],
    usageTip: "nous 的變化要寫成 mangeons（多一個 e），保持 g 的軟音，不是 mangons。",
    collocations: [],
    commonMistakes: [{ wrong: "nous mangons", correct: "nous mangeons", explanation: "-ger 結尾的動詞在 nous 形式要加 e 保持軟音。" }],
    relatedWords: ["boire"],
    tags: ["高頻", "規則", "動詞"], audio: null,
  },
  {
    id: "boire", word: "boire", displayWord: "boire", partOfSpeech: "verb",
    gender: null, forms: null, irregular: true, level: "A1", frequencyRank: 17, category: "verbs",
    meanings: ["喝"],
    usageSummary: "不規則動詞，表示喝東西。",
    patterns: ["主語 ＋ boire ＋ 名詞"],
    conjugation: { je: "bois", tu: "bois", ilElleOn: "boit", nous: "buvons", vous: "buvez", ilsElles: "boivent" },
    examples: [
      { french: "Je bois de l'eau.", chinese: "我喝水。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["manger"],
    tags: ["不規則", "動詞"], audio: null,
  },
  {
    id: "acheter", word: "acheter", displayWord: "acheter", partOfSpeech: "verb",
    gender: null, forms: null, irregular: false, level: "A1", frequencyRank: 18, category: "verbs",
    meanings: ["買"],
    usageSummary: "規則 -er 動詞，但除了 nous/vous 之外都要在 e 上加重音（è）。",
    patterns: ["主語 ＋ acheter ＋ 名詞"],
    conjugation: { je: "achète", tu: "achètes", ilElleOn: "achète", nous: "achetons", vous: "achetez", ilsElles: "achètent" },
    examples: [
      { french: "J'achète un livre.", chinese: "我買一本書。", note: "" },
    ],
    usageTip: "除了 nous 和 vous，其他人稱要把 e 改成 è（achète 而不是 achete）。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["argent"],
    tags: ["規則", "動詞"], audio: null,
  },
  {
    id: "prendre", word: "prendre", displayWord: "prendre", partOfSpeech: "verb",
    gender: null, forms: null, irregular: true, level: "A1", frequencyRank: 19, category: "verbs",
    meanings: ["拿", "搭乘", "點（餐）"],
    usageSummary: "不規則動詞，用途廣泛：拿東西、搭乘交通工具、點餐都可以用。",
    patterns: ["主語 ＋ prendre ＋ 名詞"],
    conjugation: { je: "prends", tu: "prends", ilElleOn: "prend", nous: "prenons", vous: "prenez", ilsElles: "prennent" },
    examples: [
      { french: "Je prends le bus.", chinese: "我搭公車。", note: "" },
      { french: "Je prends un café.", chinese: "我要點一杯咖啡。", note: "在餐廳點餐常用 prendre。" },
    ],
    usageTip: "",
    collocations: [{ french: "prendre le bus/train", chinese: "搭公車／火車" }],
    commonMistakes: [],
    relatedWords: ["comprendre"],
    tags: ["高頻", "不規則", "動詞"], audio: null,
  },
  {
    id: "donner", word: "donner", displayWord: "donner", partOfSpeech: "verb",
    gender: null, forms: null, irregular: false, level: "A1", frequencyRank: 20, category: "verbs",
    meanings: ["給"],
    usageSummary: "規則 -er 動詞，表示給予。",
    patterns: ["主語 ＋ donner ＋ 名詞 ＋ à + 人"],
    conjugation: { je: "donne", tu: "donnes", ilElleOn: "donne", nous: "donnons", vous: "donnez", ilsElles: "donnent" },
    examples: [
      { french: "Je donne un livre à mon ami.", chinese: "我給我朋友一本書。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["demander"],
    tags: ["規則", "動詞"], audio: null,
  },
  {
    id: "demander", word: "demander", displayWord: "demander", partOfSpeech: "verb",
    gender: null, forms: null, irregular: false, level: "A1", frequencyRank: 21, category: "verbs",
    meanings: ["問", "要求"],
    usageSummary: "規則 -er 動詞，表示提出問題或要求，不要跟英文 demand 搞混語氣強度。",
    patterns: ["主語 ＋ demander ＋ 名詞"],
    conjugation: { je: "demande", tu: "demandes", ilElleOn: "demande", nous: "demandons", vous: "demandez", ilsElles: "demandent" },
    examples: [
      { french: "Je demande l'heure.", chinese: "我問時間。", note: "" },
    ],
    usageTip: "demander 語氣比英文 demand 溫和，通常只是「詢問」，不是強硬「要求」。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["donner"],
    tags: ["規則", "動詞"], audio: null,
  },
  {
    id: "regarder", word: "regarder", displayWord: "regarder", partOfSpeech: "verb",
    gender: null, forms: null, irregular: false, level: "A1", frequencyRank: 22, category: "verbs",
    meanings: ["看"],
    usageSummary: "規則 -er 動詞，表示看某件事物（電視、電影等），直接接受詞不需介詞。",
    patterns: ["主語 ＋ regarder ＋ 名詞"],
    conjugation: { je: "regarde", tu: "regardes", ilElleOn: "regarde", nous: "regardons", vous: "regardez", ilsElles: "regardent" },
    examples: [
      { french: "Je regarde la télévision.", chinese: "我在看電視。", note: "" },
    ],
    usageTip: "regarder 直接接受詞，不需要介詞（regarder la télé，不是 regarder à la télé）。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["écouter"],
    tags: ["規則", "動詞"], audio: null,
  },
  {
    id: "ecouter", word: "écouter", displayWord: "écouter", partOfSpeech: "verb",
    gender: null, forms: null, irregular: false, level: "A1", frequencyRank: 23, category: "verbs",
    meanings: ["聽"],
    usageSummary: "規則 -er 動詞，表示聽（音樂、別人說話等），直接接受詞不需介詞。",
    patterns: ["主語 ＋ écouter ＋ 名詞"],
    conjugation: { je: "écoute", tu: "écoutes", ilElleOn: "écoute", nous: "écoutons", vous: "écoutez", ilsElles: "écoutent" },
    examples: [
      { french: "J'écoute de la musique.", chinese: "我在聽音樂。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["regarder"],
    tags: ["規則", "動詞"], audio: null,
  },
  {
    id: "lire", word: "lire", displayWord: "lire", partOfSpeech: "verb",
    gender: null, forms: null, irregular: true, level: "A1", frequencyRank: 24, category: "verbs",
    meanings: ["讀", "閱讀"],
    usageSummary: "不規則動詞，表示閱讀。",
    patterns: ["主語 ＋ lire ＋ 名詞"],
    conjugation: { je: "lis", tu: "lis", ilElleOn: "lit", nous: "lisons", vous: "lisez", ilsElles: "lisent" },
    examples: [
      { french: "Je lis un livre.", chinese: "我在讀一本書。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["écrire"],
    tags: ["不規則", "動詞"], audio: null,
  },
  {
    id: "ecrire", word: "écrire", displayWord: "écrire", partOfSpeech: "verb",
    gender: null, forms: null, irregular: true, level: "A1", frequencyRank: 25, category: "verbs",
    meanings: ["寫"],
    usageSummary: "不規則動詞，表示書寫。",
    patterns: ["主語 ＋ écrire ＋ 名詞"],
    conjugation: { je: "écris", tu: "écris", ilElleOn: "écrit", nous: "écrivons", vous: "écrivez", ilsElles: "écrivent" },
    examples: [
      { french: "J'écris une lettre.", chinese: "我在寫一封信。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["lire"],
    tags: ["不規則", "動詞"], audio: null,
  },
  {
    id: "comprendre", word: "comprendre", displayWord: "comprendre", partOfSpeech: "verb",
    gender: null, forms: null, irregular: true, level: "A1", frequencyRank: 26, category: "verbs",
    meanings: ["理解", "懂"],
    usageSummary: "不規則動詞，變化方式跟 prendre 相同。",
    patterns: ["主語 ＋ comprendre ＋ 名詞"],
    conjugation: { je: "comprends", tu: "comprends", ilElleOn: "comprend", nous: "comprenons", vous: "comprenez", ilsElles: "comprennent" },
    examples: [
      { french: "Je ne comprends pas.", chinese: "我不明白。", note: "非常常用的句子。" },
    ],
    usageTip: "",
    collocations: [{ french: "je ne comprends pas", chinese: "我不明白" }],
    commonMistakes: [],
    relatedWords: ["prendre"],
    tags: ["高頻", "不規則", "動詞"], audio: null,
  },
  {
    id: "chercher", word: "chercher", displayWord: "chercher", partOfSpeech: "verb",
    gender: null, forms: null, irregular: false, level: "A1", frequencyRank: 27, category: "verbs",
    meanings: ["尋找"],
    usageSummary: "規則 -er 動詞，直接接受詞，不需要介詞 pour。",
    patterns: ["主語 ＋ chercher ＋ 名詞"],
    conjugation: { je: "cherche", tu: "cherches", ilElleOn: "cherche", nous: "cherchons", vous: "cherchez", ilsElles: "cherchent" },
    examples: [
      { french: "Je cherche la gare.", chinese: "我在找火車站。", note: "" },
    ],
    usageTip: "chercher 直接接受詞：je cherche mes clés，不是 je cherche pour mes clés。",
    collocations: [],
    commonMistakes: [{ wrong: "chercher pour quelque chose", correct: "chercher quelque chose", explanation: "chercher 後面直接接受詞，不需要介詞 pour。" }],
    relatedWords: ["trouver"],
    tags: ["規則", "動詞"], audio: null,
  },
  {
    id: "trouver", word: "trouver", displayWord: "trouver", partOfSpeech: "verb",
    gender: null, forms: null, irregular: false, level: "A1", frequencyRank: 28, category: "verbs",
    meanings: ["找到", "覺得"],
    usageSummary: "規則 -er 動詞，表示找到某物，也可以表示對某事的看法。",
    patterns: ["主語 ＋ trouver ＋ 名詞"],
    conjugation: { je: "trouve", tu: "trouves", ilElleOn: "trouve", nous: "trouvons", vous: "trouvez", ilsElles: "trouvent" },
    examples: [
      { french: "J'ai trouvé mes clés.", chinese: "我找到我的鑰匙了。", note: "" },
      { french: "Je trouve ce film intéressant.", chinese: "我覺得這部電影很有趣。", note: "trouver 也可以表示「覺得」。" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["chercher"],
    tags: ["規則", "動詞"], audio: null,
  },
  {
    id: "arriver", word: "arriver", displayWord: "arriver", partOfSpeech: "verb",
    gender: null, forms: null, irregular: false, level: "A1", frequencyRank: 29, category: "verbs",
    meanings: ["到達"],
    usageSummary: "規則 -er 動詞，表示抵達某地。",
    patterns: ["主語 ＋ arriver ＋ à + 地點"],
    conjugation: { je: "arrive", tu: "arrives", ilElleOn: "arrive", nous: "arrivons", vous: "arrivez", ilsElles: "arrivent" },
    examples: [
      { french: "Le train arrive à midi.", chinese: "火車中午到達。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["partir"],
    tags: ["規則", "動詞"], audio: null,
  },
  {
    id: "partir", word: "partir", displayWord: "partir", partOfSpeech: "verb",
    gender: null, forms: null, irregular: true, level: "A1", frequencyRank: 30, category: "verbs",
    meanings: ["離開", "出發"],
    usageSummary: "不規則 -ir 動詞，表示離開或出發，跟 arriver 相反。",
    patterns: ["主語 ＋ partir ＋ à/pour + 地點"],
    conjugation: { je: "pars", tu: "pars", ilElleOn: "part", nous: "partons", vous: "partez", ilsElles: "partent" },
    examples: [
      { french: "Je pars demain.", chinese: "我明天出發。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["arriver", "sortir"],
    tags: ["不規則", "動詞"], audio: null,
  },
  {
    id: "entrer", word: "entrer", displayWord: "entrer", partOfSpeech: "verb",
    gender: null, forms: null, irregular: false, level: "A1", frequencyRank: 31, category: "verbs",
    meanings: ["進入"],
    usageSummary: "規則 -er 動詞，表示進入某個地方。",
    patterns: ["主語 ＋ entrer ＋ dans + 地點"],
    conjugation: { je: "entre", tu: "entres", ilElleOn: "entre", nous: "entrons", vous: "entrez", ilsElles: "entrent" },
    examples: [
      { french: "Il entre dans la maison.", chinese: "他走進房子。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["sortir"],
    tags: ["規則", "動詞"], audio: null,
  },
  {
    id: "sortir", word: "sortir", displayWord: "sortir", partOfSpeech: "verb",
    gender: null, forms: null, irregular: true, level: "A1", frequencyRank: 32, category: "verbs",
    meanings: ["出去", "外出"],
    usageSummary: "不規則 -ir 動詞，變化方式跟 partir 相同，表示離開某個空間或外出。",
    patterns: ["主語 ＋ sortir ＋ de + 地點"],
    conjugation: { je: "sors", tu: "sors", ilElleOn: "sort", nous: "sortons", vous: "sortez", ilsElles: "sortent" },
    examples: [
      { french: "Je sors ce soir.", chinese: "我今晚要外出。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["entrer", "partir"],
    tags: ["不規則", "動詞"], audio: null,
  },
  {
    id: "ouvrir", word: "ouvrir", displayWord: "ouvrir", partOfSpeech: "verb",
    gender: null, forms: null, irregular: true, level: "A1", frequencyRank: 33, category: "verbs",
    meanings: ["打開"],
    usageSummary: "不規則動詞，但現在式變化跟規則 -er 動詞相同（容易搞混，因為原形是 -ir）。",
    patterns: ["主語 ＋ ouvrir ＋ 名詞"],
    conjugation: { je: "ouvre", tu: "ouvres", ilElleOn: "ouvre", nous: "ouvrons", vous: "ouvrez", ilsElles: "ouvrent" },
    examples: [
      { french: "J'ouvre la porte.", chinese: "我打開門。", note: "" },
    ],
    usageTip: "ouvrir 雖然原形是 -ir，但現在式變化用的是 -er 動詞的字尾（ouvre, ouvres, ouvre...）。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["fermer"],
    tags: ["不規則", "動詞"], audio: null,
  },
  {
    id: "fermer", word: "fermer", displayWord: "fermer", partOfSpeech: "verb",
    gender: null, forms: null, irregular: false, level: "A1", frequencyRank: 34, category: "verbs",
    meanings: ["關閉"],
    usageSummary: "規則 -er 動詞，表示關閉，跟 ouvrir 相反。",
    patterns: ["主語 ＋ fermer ＋ 名詞"],
    conjugation: { je: "ferme", tu: "fermes", ilElleOn: "ferme", nous: "fermons", vous: "fermez", ilsElles: "ferment" },
    examples: [
      { french: "Fermez la porte, s'il vous plaît.", chinese: "請關門。", note: "" },
    ],
    usageTip: "",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["ouvrir"],
    tags: ["規則", "動詞"], audio: null,
  },
  {
    id: "commencer", word: "commencer", displayWord: "commencer", partOfSpeech: "verb",
    gender: null, forms: null, irregular: false, level: "A1", frequencyRank: 35, category: "verbs",
    meanings: ["開始"],
    usageSummary: "規則 -er 動詞，nous 的變化要把 c 改成 ç（commençons）以保持軟音。",
    patterns: ["主語 ＋ commencer ＋ à + 動詞原形"],
    conjugation: { je: "commence", tu: "commences", ilElleOn: "commence", nous: "commençons", vous: "commencez", ilsElles: "commencent" },
    examples: [
      { french: "Le cours commence à neuf heures.", chinese: "課程九點開始。", note: "" },
    ],
    usageTip: "nous 的變化要寫成 commençons（c 改成 ç），保持軟音，不是 commencons。",
    collocations: [],
    commonMistakes: [{ wrong: "nous commencons", correct: "nous commençons", explanation: "-cer 結尾的動詞在 nous 形式要把 c 改成 ç 保持軟音。" }],
    relatedWords: ["finir"],
    tags: ["規則", "動詞"], audio: null,
  },
  {
    id: "finir", word: "finir", displayWord: "finir", partOfSpeech: "verb",
    gender: null, forms: null, irregular: false, level: "A1", frequencyRank: 36, category: "verbs",
    meanings: ["結束", "完成"],
    usageSummary: "規則 -ir 動詞（第二組動詞），nous/vous 形式會插入 -iss-。",
    patterns: ["主語 ＋ finir ＋ 名詞"],
    conjugation: { je: "finis", tu: "finis", ilElleOn: "finit", nous: "finissons", vous: "finissez", ilsElles: "finissent" },
    examples: [
      { french: "Je finis à cinq heures.", chinese: "我五點結束（下班／下課）。", note: "" },
    ],
    usageTip: "finir 屬於規則第二組動詞，複數形式會多出 -iss-（finissons, finissez, finissent）。",
    collocations: [],
    commonMistakes: [],
    relatedWords: ["commencer"],
    tags: ["規則", "動詞"], audio: null,
  },
  {
    id: "preferer", word: "préférer", displayWord: "préférer", partOfSpeech: "verb",
    gender: null, forms: null, irregular: false, level: "A1", frequencyRank: 37, category: "verbs",
    meanings: ["比較喜歡", "偏好"],
    usageSummary: "規則 -er 動詞，但除了 nous/vous 之外，第二個 é 要改成 è。",
    patterns: ["主語 ＋ préférer ＋ 名詞"],
    conjugation: { je: "préfère", tu: "préfères", ilElleOn: "préfère", nous: "préférons", vous: "préférez", ilsElles: "préfèrent" },
    examples: [
      { french: "Je préfère le thé au café.", chinese: "比起咖啡我更喜歡茶。", note: "préférer A à B＝「比起B更喜歡A」。" },
    ],
    usageTip: "除了 nous 和 vous，其他人稱字尾第二個 é 要改成 è（préfère 而不是 préfere）。",
    collocations: [{ french: "préférer A à B", chinese: "比起B更喜歡A" }],
    commonMistakes: [],
    relatedWords: ["aimer"],
    tags: ["規則", "動詞"], audio: null,
  },
  {
    id: "appeler", word: "appeler", displayWord: "appeler", partOfSpeech: "verb",
    gender: null, forms: null, irregular: false, level: "A1", frequencyRank: 38, category: "verbs",
    meanings: ["叫", "打電話給"],
    usageSummary: "規則 -er 動詞，除了 nous/vous 之外 l 要疊寫成 ll；反身形式 s'appeler 表示「名叫」。",
    patterns: ["主語 ＋ appeler ＋ 人", "主語 ＋ s'appeler"],
    conjugation: { je: "appelle", tu: "appelles", ilElleOn: "appelle", nous: "appelons", vous: "appelez", ilsElles: "appellent" },
    examples: [
      { french: "Je t'appelle ce soir.", chinese: "我今晚打電話給你。", note: "" },
      { french: "Je m'appelle Julie.", chinese: "我叫茱莉。", note: "s'appeler 是反身動詞，表示「名叫」。" },
    ],
    usageTip: "除了 nous 和 vous，其他人稱 l 要疊寫成 ll（appelle 而不是 apele）。",
    collocations: [{ french: "s'appeler", chinese: "名叫" }],
    commonMistakes: [],
    relatedWords: [],
    tags: ["高頻", "規則", "動詞"], audio: null,
  },
  {
    id: "attendre", word: "attendre", displayWord: "attendre", partOfSpeech: "verb",
    gender: null, forms: null, irregular: false, level: "A1", frequencyRank: 39, category: "verbs",
    meanings: ["等待"],
    usageSummary: "規則 -re 動詞（第三組動詞），直接接受詞，不需要介詞 pour。",
    patterns: ["主語 ＋ attendre ＋ 名詞"],
    conjugation: { je: "attends", tu: "attends", ilElleOn: "attend", nous: "attendons", vous: "attendez", ilsElles: "attendent" },
    examples: [
      { french: "J'attends le bus.", chinese: "我在等公車。", note: "" },
    ],
    usageTip: "attendre 直接接受詞：j'attends mon ami，不是 j'attends pour mon ami。",
    collocations: [],
    commonMistakes: [{ wrong: "attendre pour quelqu'un", correct: "attendre quelqu'un", explanation: "attendre 後面直接接受詞，不需要介詞 pour。" }],
    relatedWords: [],
    tags: ["規則", "動詞"], audio: null,
  },
];
