import { resolveVerb } from "../verbEngine";

function fullForms(table) {
  return {
    yo: table.yo.fullForm,
    tu: table.tu.fullForm,
    elEllaUsted: table.elEllaUsted.fullForm,
    nosotros: table.nosotros.fullForm,
    vosotros: table.vosotros.fullForm,
    ellosEllasUstedes: table.ellosEllasUstedes.fullForm,
  };
}

describe("reflexive verb conjugation — presente", () => {
  test("llamarse", () => {
    const { conjugation, isReflexive } = resolveVerb("llamarse");
    expect(isReflexive).toBe(true);
    expect(fullForms(conjugation.presente)).toEqual({
      yo: "me llamo",
      tu: "te llamas",
      elEllaUsted: "se llama",
      nosotros: "nos llamamos",
      vosotros: "os llamáis",
      ellosEllasUstedes: "se llaman",
    });
  });

  test("despertarse", () => {
    const { conjugation } = resolveVerb("despertarse");
    expect(fullForms(conjugation.presente)).toEqual({
      yo: "me despierto",
      tu: "te despiertas",
      elEllaUsted: "se despierta",
      nosotros: "nos despertamos",
      vosotros: "os despertáis",
      ellosEllasUstedes: "se despiertan",
    });
  });

  test("acostarse", () => {
    const { conjugation } = resolveVerb("acostarse");
    expect(fullForms(conjugation.presente)).toEqual({
      yo: "me acuesto",
      tu: "te acuestas",
      elEllaUsted: "se acuesta",
      nosotros: "nos acostamos",
      vosotros: "os acostáis",
      ellosEllasUstedes: "se acuestan",
    });
  });

  test("nosotros/vosotros never receive the e→ie / o→ue stem change", () => {
    const despertarse = resolveVerb("despertarse").conjugation;
    expect(despertarse.presente.nosotros.verbForm).toBe("despertamos");
    expect(despertarse.presente.vosotros.verbForm).toBe("despertáis");

    const acostarse = resolveVerb("acostarse").conjugation;
    expect(acostarse.presente.nosotros.verbForm).toBe("acostamos");
    expect(acostarse.presente.vosotros.verbForm).toBe("acostáis");
  });

  test("reflexive pronoun and verb form are separate fields, not merged into one string", () => {
    const { conjugation } = resolveVerb("llamarse");
    expect(conjugation.presente.yo.reflexivePronoun).toBe("me");
    expect(conjugation.presente.yo.verbForm).toBe("llamo");
    expect(conjugation.presente.yo.fullForm).toBe("me llamo");
  });

  test("accent marks are preserved in reflexive forms (vosotros)", () => {
    expect(resolveVerb("llamarse").conjugation.presente.vosotros.verbForm).toBe("llamáis");
  });

  test("gerundio attaches the reflexive pronoun with the correct written accent", () => {
    expect(resolveVerb("llamarse").conjugation.gerundio).toBe("llamándose");
    expect(resolveVerb("despertarse").conjugation.gerundio).toBe("despertándose");
    expect(resolveVerb("vestirse").conjugation.gerundio).toBe("vistiéndose");
  });

  test("infinitivo shows the original reflexive form, not the base verb", () => {
    expect(resolveVerb("llamarse").conjugation.infinitivo).toBe("llamarse");
    expect(resolveVerb("despertarse").conjugation.infinitivo).toBe("despertarse");
  });

  test("reflexive verbs inherit the base verb's irregular/stem-change data (not lost by stripping se)", () => {
    // despertarse must use despertar's e→ie pattern, not a generic regular -ar conjugation.
    const { entry } = resolveVerb("despertarse");
    expect(entry.reflexiveBaseInfinitive).toBe("despertar");
    expect(resolveVerb("despertarse").conjugation.presente.yo.verbForm).toBe("despierto");
  });

  test("sentirse and dormirse reuse the already-indexed sentir/dormir stem changes", () => {
    expect(resolveVerb("sentirse").conjugation.presente.yo.verbForm).toBe("siento");
    expect(resolveVerb("dormirse").conjugation.presente.yo.verbForm).toBe("duermo");
  });

  test("imperativo is explicitly marked incomplete for reflexive verbs, not silently wrong", () => {
    const { conjugation } = resolveVerb("llamarse");
    expect(conjugation.imperativoAfirmativo.tu).toContain("稍後加入");
    expect(conjugation.imperativoNegativo.tu).toContain("稍後加入");
  });

  test("non-reflexive verbs are completely unaffected (existing behavior preserved)", () => {
    const { conjugation, isReflexive } = resolveVerb("tener");
    expect(isReflexive).toBe(false);
    expect(conjugation.presente.yo).toBe("tengo");
    expect(conjugation.presente.ellosEllasUstedes).toBe("tienen");
    expect(typeof conjugation.presente.yo).toBe("string");
  });

  test("a reflexive verb whose base isn't in VERB_INDEX still auto-generates a regular conjugation", () => {
    // "aburrir" (to bore) isn't indexed; aburrirse must still conjugate as a regular -ir verb.
    const { conjugation, autoGenerated, isReflexive } = resolveVerb("aburrirse");
    expect(isReflexive).toBe(true);
    expect(autoGenerated).toBe(true);
    expect(conjugation.presente.yo.fullForm).toBe("me aburro");
  });
});
