// Browser-safe adaptations of the supplied AI Office methods, not its runtime
// capabilities. Keep source locations and execution/approval claims out of UI data.
const EVIDENCE_BOUNDARY = "共同要求：只使用我提供的資料，分開事實、假設與缺口，保留來源列識別、公式、單位、幣別、期間與捨入規則。數值須有實際精確計算與可重現的驗證紀錄；金額使用十進位或縮放整數，不用浮點累加。缺資料或工具時，先提供可用的規格與待確認清單，將相關結果標為「待驗證」，不得心算後宣稱已驗證。不得冒稱已查詢資料庫、更新外部系統或產生檔案。涉及稅務、對外財務承諾、佣金或合約，列明覆核項目、原因及所需專業人員，未覆核不得標為正式完成。";

function prompt(method, inputs) {
  return `${method}\n\n${EVIDENCE_BOUNDARY}\n\n${inputs}：\n`;
}

export const DATA_FINANCE_SALES_SKILLS = [
  {
    id: "budget-modeling-controls",
    title: "預算模型控制",
    category: "財務控制",
    icon: "finance",
    professional: true,
    description: "核對預算分配、收支平衡與實際差異",
    keywords: "budget 預算 收支 allocation reconciliation",
    prompt: prompt("請建立可覆核的預算工作底稿。以「期間＋幣別＋科目」為一致鍵，不直接合併不同期間或幣別；換算需要有來源及基準日的匯率。列出輸入、分配明細、收支表、對帳及缺口。核對「期初＋流入－流出＝期末」與「可用預算－已分配＝剩餘」；不平衡時列出 reconciliation_gap，不得宣稱完成。差異使用 actual − budget，清楚說明費用正差異是超支、收入正差異是超收。僅有估計而無實際數字時，只做計畫，不製造差異分析。合計必須來自未捨入的明細，呈現時才取位；對外數字及稅務項目待財務／稅務人員覆核。", "期間、幣別、科目、預算、實際收支與分配限制"),
  },
  {
    id: "capacity-modeling",
    title: "產能模型",
    category: "資料與模型",
    icon: "data",
    professional: true,
    description: "統一人力工時，分析需求、產能與缺口",
    keywords: "capacity 產能 人力 工時 資源 planning scenario",
    prompt: prompt("請建立產能情境模型。先盤點件數、工時、人力及利用率；沒有真實輸入時只列所需資料，不捏造模型。將人天、人週、人月統一為人時，寫明換算率及使用者提供／預設的來源。需求＝Σ（件數×單件工時），產能＝Σ（人數×可用工時×利用率），缺口＝需求－產能，列出中間值；負缺口表示剩餘產能，保留負號。保守、基準、樂觀情境使用同一公式，只改有明示依據的假設。分母為零時寫「無基準，無法計算比率」；缺任一必要輸入的情境標為「無法計算」，不得借用其他情境數字。輸出假設表、情境比較、瓶頸與待補資料；成本預算另列，不混用工時與金額。", "工作量、人力、可用工時、利用率與情境假設"),
  },
  {
    id: "commission-rule-formalization",
    title: "佣金規則正式化",
    category: "財務控制",
    icon: "finance",
    professional: true,
    description: "釐清抽成級距、規則優先順序與驗算案例",
    keywords: "commission 佣金 抽成 薪酬 級距 compensation",
    prompt: prompt("請將佣金政策整理成可覆核規格，先不要代替薪酬負責人決定模糊條款。每條規則用「條件→計算基礎→比率→調整→生效時點」表示，標示覆蓋、先後或互斥關係。分清超額累進、達標後全額追溯、僅門檻判斷、達標固定率四種級距。存在兩種合理解釋時，保留 A／B 方案及金額影響，請人確認，不自行選定。列出零值、負值、剛好門檻、跨級距、多人分拆及缺值測試。期望值只接受政策範例、使用者確認實例、不同方法的獨立推導（保留步驟並精確覆核）或獨立工具結果；同一公式跑兩次不是獨立驗證。測試保留 expected／actual／tolerance／結果及依據，不得放寬誤差迎合結果。仍有重大歧義時標為部分完成，佣金支付前需 HR／薪酬負責人覆核。", "佣金政策、級距、生效期間、交易資料與已確認範例"),
  },
  {
    id: "data-query-methodology",
    title: "資料查詢方法",
    category: "資料與模型",
    icon: "data",
    professional: true,
    description: "先確認欄位與資料粒度，再設計可驗證查詢",
    keywords: "data query 資料 查詢 SQL DuckDB join schema",
    prompt: prompt("請根據我提供的資料結構設計查詢計畫，不直接產生或執行 raw SQL。先檢查欄位名稱、型別、列數、非空值數及每列代表的粒度；區分 count(field) 與 count(*)，SUM 忽略空值、AVG 以非空值為分母，保留空值群組。說明重複列全部計入或按主鍵去重的規則。Join 前檢查鍵唯一性、型別、匹配率、連接前後列數及扇出；字串「001」不得默認等於數值 1。不同單位、幣別不可直接加總。輸出結構化查詢計畫（來源、篩選、分組、連接、聚合、排序、限制）與驗證清單：前後合計、抽樣、零結果、極值及截斷影響。只有接上經驗證的計畫驗證器、參數化查詢編譯器與資料庫執行器後才可執行；本次未實際查詢時，結果標為待執行，不虛構資料列或驗證通過。", "分析問題、欄位結構、資料樣本、主鍵與篩選條件"),
  },
  {
    id: "financial-variance-method",
    title: "財務差異分析",
    category: "財務控制",
    icon: "finance",
    professional: true,
    description: "比較實際與基準，分開已證實原因和假設",
    keywords: "financial variance 財務 差異 actual budget 同比",
    prompt: prompt("請比較實際值與預算、前期或目標，建立可重算的財務差異底稿。先確認期間、幣別、千元／萬元等單位與基準可比性，不自行挑選匯率。採實際－基準並說明費用與收入正負差異的不同意義，每個結果保留來源列、公式及分母。基準為 0 時明寫「基準為 0，無法計算變動率；絕對差異為 X」，不可輸出 0%、100% 或無限大。中間值保留精度，小計與總計由未取位數值計算，僅呈現時捨入一次。把有證據的原因與未驗證假設分開；假設轉為調查問題而不是結論。輸出差異表、原因證據、待調查清單及計算驗證狀態。這是供人覆核的分析，不等同入帳、財報或正式對帳完成。", "期間、幣別、實際值、比較基準、科目與原因證據"),
  },
  {
    id: "formula-specification-verification",
    title: "公式規格驗證",
    category: "資料與模型",
    icon: "data",
    professional: true,
    description: "檢查變數、單位、公式依賴與獨立驗算",
    keywords: "formula 公式 量綱 單位 calculator DAG oracle",
    prompt: prompt("請把計算需求整理為公式規格與驗證計畫。每個變數定義 name／type／unit／domain，建立 input→intermediate→output 依賴圖，查找未定義輸入與循環依賴。逐運算子檢查量綱，例如金額＋時間非法、數量×單價合法。明列捨入、分母為零及非法輸入的處理，至少五個正常／邊界案例並涵蓋零、負、缺值、極值及精度。Golden test 保留 inputs、expected、actual、tolerance、結果與驗證狀態；期望值只能來自政策範例、使用者確認實例、獨立工具或不同方法的獨立推導。獨立推導須保留步驟並精確覆核，不可讓同一算式同時作公式與驗證依據。缺工具時只交付規格與待驗算表，不宣稱 calculator 已測試。動態匯率／稅率沒有當期來源時，公式可保留，當期結果不可判為完成。", "計算目的、變數、單位、合法範圍、公式與已知範例"),
  },
  {
    id: "invoice-draft-validation",
    title: "發票草稿驗證",
    category: "財務控制",
    icon: "finance",
    professional: true,
    description: "確認收費依據、稅基與草稿／開立狀態",
    keywords: "invoice 發票 請款 收費 billing tax",
    prompt: prompt("請協助檢查請款／發票草稿。每一行列出收費項目、數量或里程碑、可查證來源依據（已交付数量、已驗收里程碑或使用者授權收費）；無依據項目移到待確認清單，不得列入應收草稿。建立小計、折扣、費用、稅額及總額的計算底稿並對帳。課稅基礎組成、稅費先後順序及來源（管轄規則／政策／使用者提供）須明示；未知時標 tax-base-undetermined，不假設費用應課稅或硬編先稅後費。狀態只用 draft、ready-for-human-review、issued-external-evidence；後者必須有外部實際開立證據。没有開票系統整合／證據時最高只能是 ready-for-human-review，PDF 存在不代表已開票。輸出收費依據表、計算對帳、狀態紀錄與會計／稅務人員待覆核項目。", "請款對象、交付／驗收依據、收費明細、幣別與稅務參數"),
  },
  {
    id: "pipeline-coverage-analysis",
    title: "銷售管線覆蓋分析",
    category: "銷售規劃",
    icon: "sales",
    professional: true,
    description: "檢查商機涵蓋率、停滯原因與下一步",
    keywords: "sales pipeline 銷售 管線 涵蓋率 coverage CRM",
    prompt: prompt("請檢查我提供的商機管線。缺階段、金額、預計成交日的商機一律列入 Data Quality Issues，說明對合計的影響，不靜默排除或填值。停滯門檻優先用使用者定義；未指定時僅在有歷史平均週期資料下使用「同階段平均週期兩倍」，明示為預設，沒有歷史資料就列待確認。涵蓋率＝管道總額÷目標，目標為零時不輸出倍數。加權金額使用明確來源的階段機率，不發明業界常見值。每筆下一步必須含具體動作與時點，不只寫「持續追蹤」；無法提出時列缺少資訊。輸出管線摘要、停滯商機、下一步及資料品質清單，數值待精確計算驗證。這是檢討建議，不代表 CRM 已更新或同步；未來區間預測另用預測情境方法。", "商機清單、目標、階段機率、活動日期與歷史階段週期"),
  },
  {
    id: "reconciliation-control-method",
    title: "對帳控制方法",
    category: "財務控制",
    icon: "finance",
    professional: true,
    description: "保留雙方來源列，用明確規則配對差異",
    keywords: "reconciliation 對帳 差額 核對 matching ledger",
    prompt: prompt("請制定並套用可重現的對帳規則，保留双方原始列 ID。先明示鍵值相等、金額容差、日期容許範圍及優先順序，不憑相近金額配對。區分一對一、一對多、多對一；群組配對列出所有來源列與合計。重複鍵造成歧義時不要任選一筆，列候選與待人工判定原因。金額相近但鍵不同、跨期日期、不同幣別都列人工覆核；沒有來源匯率與基準日，不自行换算。輸出配對規則、已配對清單、未配對／歧義清單及差異登記，每項差異追溯兩側輸入並核對總額。只登記差異，不自動沖銷、調整分錄或補平；缺少可追溯證據與驗算時不得宣稱正式對帳完成。", "兩份資料、來源列 ID、配對鍵、金額容差與日期範圍"),
  },
  {
    id: "sales-call-strategy",
    title: "銷售通話策略",
    category: "銷售規劃",
    icon: "sales",
    professional: true,
    description: "安排會議節奏、探索問題與異議回應",
    keywords: "sales call 銷售 通話 discovery 會議 objection",
    prompt: prompt("請根據客戶資料規劃銷售通話，而不是捏造已發生的會議紀錄。分段議程需包含開場、探索、方案討論、下一步及收尾，分鐘總和必須等於實際會議長度；缺時長先詢問。把有來源的背景事實與假設分開；無來源的客戶需求、預算、決策權轉為 discovery questions，不當作已知。針對可能的異議，提供回應方向、追問與需要內部確認的事項，不擅自承諾折扣、交期、尚不存在的功能或合約條件。輸出時間議程、優先問題清單、異議處理指南、成功判準及會後跟進草稿；尚未通話的結論保持待確認，不宣稱已聯絡客戶或發出郵件。", "會議目標、時長、客戶背景、參與者、產品能力與承諾限制"),
  },
  {
    id: "sales-forecast-scenario-modeling",
    title: "銷售預測情境模型",
    category: "銷售規劃",
    icon: "sales",
    professional: true,
    description: "建立有來源的預測區間與敏感度比較",
    keywords: "sales forecast 銷售 預測 情境 sensitivity CRM",
    prompt: prompt("請建立銷售預測情境模型。先列假設名稱、數值、來源（使用者提供／使用者指定／缺少）及適用情境；成交率、轉換率、平均客單價與商機數缺少來源時先詢問，不自行補「業界常見值」。保守、基準、樂觀三種情境使用同一公式，逐項列出假設改動、原值、新值與依據。輸出基準及最小－最大區間，不把單一預測寫成保證收入。選 2–3 個主要假設做 ±10% 敏感度分析，保持其他值不變、遵守合法範圍（機率 0–1）並列明邊界，按影響排序。保留數值計算與驗證紀錄；資料不足時交付模型結構與待補清單，不虛構結果。缺少有來源機率或預測區間時不得宣稱完成；不表示 CRM 已更新。", "預測期間、商機／銷量、單價、轉換率及三種情境假設來源"),
  },
  {
    id: "sales-quote-pricing-control",
    title: "報價與定價控制",
    category: "銷售規劃",
    icon: "sales",
    professional: true,
    description: "追蹤價格來源、有效期、範圍與核准狀態",
    keywords: "quote pricing 報價 定價 折扣 approval",
    prompt: prompt("請整理可覆核報價草稿。逐項標示價格來源：user-authorized、current-catalog-verified、contract-specific-verified 或 assumption-pending-approval，附可查依據與日期，不虛構現價或客戶合約價。只有確有原始資料驗證時才標 verified；使用者提供與假設分開。狀態依 draft→pricing-reviewed→commercially-approved→ready-to-send 推進，每一步都要有核准證據，產出檔案不等於通過核准或已寄出。明列報價基準日、有效起迄、價格假設、供貨與交期假設。included／excluded／assumptions 交叉檢查，不把矛盾藏在備註。核對明細、折扣、稅費與合計；課稅組成及先後依有來源的參數，不自行判定。缺即時價格或核准時保留待確認，不越級；輸出價格來源表、計算底稿、範圍差異與待核准事項。可發送報價不等同發票、合約或對外財務承諾已生效。", "客戶、品項、數量、價目／合約依據、有效期、範圍與核准紀錄"),
  },
];
