export const frenchA1ExamScope = {
  skills: [
    {
      id: "listening",
      icon: "🎧",
      title: "聽力",
      color: "#3b82f6",
      desc: "聽懂日常簡短對話與資訊",
      items: [
        "聽懂短對話的主題和要點",
        "聽留言或語音訊息，找出關鍵資訊",
        "聽出時間（幾點、幾號、幾月）",
        "聽出地點（在哪裡、往哪去）",
        "聽出價錢與數量",
        "聽出電話號碼、地址",
      ],
    },
    {
      id: "reading",
      icon: "📖",
      title: "閱讀",
      color: "#10b981",
      desc: "看懂生活中常見的文字材料",
      items: [
        "看懂告示、通知、標示",
        "看懂短訊和留言",
        "看懂簡單表格（時刻表、菜單、清單）",
        "看懂簡短電郵或信件",
        "看懂廣告和海報的主要資訊",
        "看懂簡單個人資料表",
      ],
    },
    {
      id: "writing",
      icon: "✍️",
      title: "寫作",
      color: "#f59e0b",
      desc: "寫出簡短的日常文字",
      items: [
        "填寫個人資料表（姓名、年齡、國籍等）",
        "寫簡短自我介紹（3–5 句）",
        "寫明信片或短留言",
        "寫簡單電郵或訊息回覆",
        "寫購物清單或待辦事項",
      ],
    },
    {
      id: "speaking",
      icon: "🗣️",
      title: "口說",
      color: "#ec4899",
      desc: "能在簡單日常場景開口表達",
      items: [
        "自我介紹（姓名、年齡、國籍、職業）",
        "回答考官的問題",
        "從圖卡中提問或回應",
        "模擬日常對話（買東西、問路、點餐、訂位）",
        "描述圖片中的人物或場景",
      ],
    },
  ],

  themes: [
    { emoji: "👤", name: "自我介紹", detail: "姓名、年齡、職業、國籍、語言" },
    { emoji: "👨‍👩‍👧", name: "家庭與朋友", detail: "父母、兄弟姐妹、朋友關係、描述外貌" },
    { emoji: "🌍", name: "國家、城市、語言", detail: "法國、台灣、我來自…、我說…語" },
    { emoji: "🌅", name: "日常生活", detail: "起床、上學、工作、吃飯、睡覺" },
    { emoji: "🕐", name: "時間與日期", detail: "幾點、星期幾、幾月幾號、今天、明天" },
    { emoji: "🍽️", name: "食物與餐廳", detail: "點餐、菜單、食物名稱、我要一杯…" },
    { emoji: "🛍️", name: "購物", detail: "多少錢、買東西、衣服尺碼、顏色" },
    { emoji: "🗺️", name: "方向與交通", detail: "往左/右、地鐵、公車、走路幾分鐘" },
    { emoji: "🏠", name: "住房與地方", detail: "我住在…、房間、城市、附近有…" },
    { emoji: "❤️", name: "興趣與喜好", detail: "我喜歡…、我不喜歡…、運動、音樂" },
  ],

  grammar: [
    { item: "主語代詞", detail: "je, tu, il, elle, nous, vous, ils, elles", level: "核心" },
    { item: "être（是）", detail: "je suis, tu es, il est, nous sommes, vous êtes, ils sont", level: "核心" },
    { item: "avoir（有）", detail: "j'ai, tu as, il a, nous avons, vous avez, ils ont", level: "核心" },
    { item: "第一組 -er 動詞", detail: "parler, aimer, habiter, travailler 等規則變位", level: "核心" },
    { item: "否定句 ne...pas", detail: "Je ne parle pas anglais. / Il n'aime pas ça.", level: "核心" },
    { item: "疑問句", detail: "語調上揚、Est-ce que...、倒裝式（正式）", level: "核心" },
    { item: "不定冠詞", detail: "un（陽性）、une（陰性）、des（複數）", level: "核心" },
    { item: "定冠詞", detail: "le（陽性）、la（陰性）、les（複數）、l'（母音前）", level: "核心" },
    { item: "形容詞性數配合", detail: "grand / grande / grands / grandes；陰性加 e，複數加 s", level: "重要" },
    { item: "常用介詞", detail: "à（在/去）、de（從/的）、en（在/用）、au / aux、chez、dans、sur", level: "重要" },
    { item: "近未來 aller + 原形", detail: "Je vais manger. / Tu vas partir.", level: "重要" },
    { item: "命令句", detail: "Parle ! / Parlez ! / Allons-y !", level: "補充" },
    { item: "數字 0–100", detail: "0–20 背誦；21–99 組合規律（vingt et un、soixante-dix）", level: "核心" },
    { item: "所有格形容詞", detail: "mon/ma/mes、ton/ta/tes、son/sa/ses、notre/votre/leur", level: "重要" },
    { item: "部分冠詞", detail: "du（陽）、de la（陰）、de l'（母音）——用於不可數名詞", level: "重要" },
  ],

  sentencePatterns: [
    { fr: "Je m'appelle ...", zh: "我叫⋯（自我介紹）", example: "Je m'appelle Marie." },
    { fr: "J'ai ... ans.", zh: "我 ... 歲", example: "J'ai vingt ans." },
    { fr: "Je suis ...", zh: "我是⋯（職業 / 身份）", example: "Je suis étudiant." },
    { fr: "J'habite à ...", zh: "我住在⋯", example: "J'habite à Paris." },
    { fr: "Je parle ...", zh: "我說⋯語", example: "Je parle français et anglais." },
    { fr: "J'aime ...", zh: "我喜歡⋯", example: "J'aime le sport." },
    { fr: "Je n'aime pas ...", zh: "我不喜歡⋯", example: "Je n'aime pas la pluie." },
    { fr: "Je voudrais ...", zh: "我想要⋯（客氣請求）", example: "Je voudrais un café, s'il vous plaît." },
    { fr: "C'est combien ?", zh: "這多少錢？", example: "C'est combien, la baguette ?" },
    { fr: "Où est ... ?", zh: "⋯在哪裡？", example: "Où est la gare ?" },
    { fr: "Il y a ...", zh: "有⋯（存在）", example: "Il y a une boulangerie ici." },
    { fr: "Il n'y a pas de ...", zh: "沒有⋯", example: "Il n'y a pas de parking." },
    { fr: "Est-ce que vous avez ... ?", zh: "你們有⋯嗎？", example: "Est-ce que vous avez une chambre ?" },
    { fr: "Je vais ... (+ 原形)", zh: "我要去做⋯（近未來）", example: "Je vais manger maintenant." },
  ],

  vocabularyCategories: [
    { emoji: "👤", name: "個人資料", words: "nom, prénom, âge, adresse, nationalité, profession, téléphone, email" },
    { emoji: "👨‍👩‍👧", name: "家庭", words: "père, mère, frère, sœur, fils, fille, mari, femme, grand-père, grand-mère, oncle, tante" },
    { emoji: "🌍", name: "國家與語言", words: "France, Chine, Japon, anglais, chinois, japonais, français, espagnol" },
    { emoji: "🍽️", name: "食物飲品", words: "pain, eau, café, thé, vin, lait, fromage, viande, poisson, légume, fruit" },
    { emoji: "🕐", name: "日期時間", words: "heure, minute, jour, semaine, mois, an, lundi–dimanche, janvier–décembre" },
    { emoji: "🏙️", name: "地方", words: "maison, appartement, école, gare, hôpital, banque, marché, restaurant, hôtel, rue, ville" },
    { emoji: "🚇", name: "交通", words: "bus, métro, train, avion, voiture, vélo, pied, à gauche, à droite, tout droit" },
    { emoji: "👗", name: "衣服與購物", words: "robe, pantalon, chemise, chaussures, taille, couleur, cher, bon marché, caisse, soldes" },
    { emoji: "💪", name: "日常動作", words: "manger, boire, aller, venir, prendre, faire, parler, écouter, lire, écrire, dormir" },
    { emoji: "🔢", name: "數字", words: "0–100 及 ordinal：premier, deuxième, troisième..." },
  ],

  examTasks: {
    listening: [
      { task: "聽短對話選答案", desc: "聽 2–3 句對話，選出符合的圖片或文字答案" },
      { task: "聽留言找資訊", desc: "聽電話留言，填寫時間、姓名、電話等" },
      { task: "聽時間 / 地點 / 價錢", desc: "聽對話後回答：幾點？在哪裡？多少錢？" },
    ],
    reading: [
      { task: "看告示", desc: "看公告、路標、禁止標誌，判斷「可以 / 不可以做什麼」" },
      { task: "看短訊", desc: "讀 WhatsApp / SMS，找出邀約時間地點或說明事項" },
      { task: "看表格", desc: "讀班次表、菜單、課表，回答具體問題" },
      { task: "看簡單電郵", desc: "讀 5–8 句電郵，判斷目的、時間、人物關係" },
      { task: "看廣告或時間表", desc: "讀海報或時刻表，找出開放時間、票價等資訊" },
    ],
    writing: [
      { task: "填個人資料表", desc: "填寫姓名、年齡、地址、電話、職業等欄位" },
      { task: "寫簡短自我介紹", desc: "寫 40–60 字，介紹自己（我叫、我是、我住、我喜歡）" },
      { task: "寫明信片", desc: "給朋友寫度假明信片，說說在哪裡、做什麼、天氣如何" },
      { task: "寫簡單電郵或留言", desc: "回覆邀請、確認時間、請求某事，字數 40–60 字" },
    ],
    speaking: [
      { task: "自我介紹", desc: "考官請你介紹自己：名字、年齡、國籍、職業、語言" },
      { task: "回答考官問題", desc: "回答日常問題：你住哪？你喜歡什麼？你的家庭？" },
      { task: "抽卡問問題", desc: "抽到一張卡，根據卡上提示問考官問題" },
      { task: "模擬日常對話", desc: "買東西、問路、訂位、訂房等場景的角色扮演" },
    ],
  },

  studyOrder: [
    { step: 1, emoji: "👤", title: "個人資料", desc: "先學會說自己是誰：名字、年齡、國籍、職業、語言" },
    { step: 2, emoji: "🔤", title: "être / avoir", desc: "法語兩大基礎動詞，幾乎所有句子都用得到" },
    { step: 3, emoji: "🔢", title: "數字、時間、日期", desc: "0–100 的數字、一週七天、一年十二個月" },
    { step: 4, emoji: "📚", title: "日常主題詞彙", desc: "按主題背單字：家庭、食物、地方、交通、購物" },
    { step: 5, emoji: "💬", title: "基本句型", desc: "練習 A1 核心句型，能開口說出完整句子" },
    { step: 6, emoji: "📝", title: "四大考試題型", desc: "針對聽力、閱讀、寫作、口說分別練習題型格式" },
  ],
};
