// 法語發音資料：完整音位清單（母音／鼻母音／半母音／子音）＋特殊主題（拼寫規則／連音／重音）。
// 每筆資料對應 components/pronunciation/PronunciationSoundCard.js 的統一欄位設計。

export const FRENCH_CATEGORIES = ["全部", "母音", "鼻母音", "半母音", "子音", "特殊組合", "重音與連音"];

function mkAudio() {
  return {
    phonemeNormalUrl: null,
    phonemeSlowUrl: null,
    wordNormalUrl: null,
    wordSlowUrl: null,
    teacherAudioUrl: null,
    repeatAudioUrl: null,
    provider: "static-mp3",
    fallbackLang: "fr-FR",
  };
}

function combo(ipaConsonant, vowels = ["a", "i", "u", "e", "o", "y"]) {
  return vowels.map(v => ({ combo: `${ipaConsonant}${v}`, audioUrl: null }));
}

const DEFAULT_STEPS = symbol => [
  `先擺好嘴形：對照上面「嘴巴和舌頭怎樣放」的描述，把嘴唇、舌頭定位到位`,
  `調整舌頭位置：確認舌頭前後、高低是否正確`,
  `慢慢呼氣：先不出聲，感受氣流方向（口腔或鼻腔）`,
  `發出目標音：加上聲帶震動（如果是濁音），發出 ${symbol}`,
  `與示範聲音比較：點擊「聽音標」或例字播放鈕，比對自己的發音`,
];

export const FRENCH_SOUNDS = [
  // ══════════════════════════ 口腔母音 ══════════════════════════
  {
    id: "i", category: "母音", ipa: "/i/", exampleWord: "midi", exampleIpa: "/midi/", meaningZh: "中午",
    shortDescription: "嘴角用力向兩側拉開，聲音短促清晰，像中文「衣」但更緊",
    mouthPosition: "嘴巴幾乎閉合，嘴角盡量向兩側拉開成扁平狀",
    tonguePosition: "舌面盡量抬高，舌尖抵住下齒背，舌頭前部靠近硬顎",
    airflow: "氣流從口腔中央持續流出，不中斷",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: [
      "先把嘴角用力向兩側拉開，像微笑一樣",
      "舌面抬高靠近硬顎，但不要碰到",
      "牙齒幾乎閉合，只留一條窄縫",
      "穩定吐氣，發出短而緊的「伊」",
      "跟示範音比較，確認聲音沒有往下滑成「ei」",
    ],
    commonSpellings: [
      { spelling: "i", examples: [{ word: "midi", ipa: "/midi/", meaningZh: "中午" }] },
      { spelling: "î", examples: [{ word: "île", ipa: "/il/", meaningZh: "島" }] },
      { spelling: "y", examples: [{ word: "stylo", ipa: "/stilo/", meaningZh: "筆" }] },
    ],
    wordExamples: [
      { word: "midi", ipa: "/midi/", meaningZh: "中午", highlight: "i" },
      { word: "ville", ipa: "/vil/", meaningZh: "城市", highlight: "i" },
      { word: "stylo", ipa: "/stilo/", meaningZh: "筆", highlight: "y" },
    ],
    practiceWords: ["midi", "ville", "stylo"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "e", category: "母音", ipa: "/e/", exampleWord: "été", exampleIpa: "/ete/", meaningZh: "夏天",
    shortDescription: "嘴巴半開，嘴角向兩側拉緊，聲音乾淨不下滑",
    mouthPosition: "嘴巴半開，比 /i/ 略開，嘴角仍向兩側拉緊",
    tonguePosition: "舌面抬高但比 /i/ 略低，舌尖抵下齒",
    airflow: "氣流平穩持續，不中斷、不滑動",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/e/"),
    commonSpellings: [
      { spelling: "é", examples: [{ word: "été", ipa: "/ete/", meaningZh: "夏天" }] },
      { spelling: "er（動詞字尾）", examples: [{ word: "parler", ipa: "/paʁle/", meaningZh: "說話" }] },
      { spelling: "ez", examples: [{ word: "chantez", ipa: "/ʃɑ̃te/", meaningZh: "你們唱歌" }] },
      { spelling: "es（單音節詞）", examples: [{ word: "les", ipa: "/le/", meaningZh: "（複數冠詞）" }] },
    ],
    wordExamples: [
      { word: "été", ipa: "/ete/", meaningZh: "夏天", highlight: "é" },
      { word: "parler", ipa: "/paʁle/", meaningZh: "說話", highlight: "er" },
      { word: "les", ipa: "/le/", meaningZh: "（複數冠詞）", highlight: "es" },
    ],
    comparisons: [{
      otherIpa: "/ɛ/",
      mouthDiff: "/e/ 嘴巴半開、嘴角略向兩側拉緊；/ɛ/ 嘴巴張得比 /e/ 更開，嘴角放鬆",
      tongueDiff: "/e/ 舌位較高、較前；/ɛ/ 舌位略低",
      vocalDiff: "兩者皆為濁音（聲帶持續震動），差異在開口度與舌位高低，不在聲帶",
      wordA: { word: "été", ipa: "/ete/", meaningZh: "夏天" },
      wordB: { word: "père", ipa: "/pɛʁ/", meaningZh: "父親" },
    }],
    practiceWords: ["été", "parler", "les"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "ɛ", category: "母音", ipa: "/ɛ/", exampleWord: "père", exampleIpa: "/pɛʁ/", meaningZh: "父親",
    shortDescription: "嘴巴張得比 /e/ 更開，嘴角放鬆，聲音較低較鬆",
    mouthPosition: "嘴巴張開程度中等偏大，比 /e/ 明顯更開",
    tonguePosition: "舌面抬高程度比 /e/ 低，舌頭較放鬆",
    airflow: "氣流平穩持續",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/ɛ/"),
    commonSpellings: [
      { spelling: "è", examples: [{ word: "père", ipa: "/pɛʁ/", meaningZh: "父親" }] },
      { spelling: "ê", examples: [{ word: "tête", ipa: "/tɛt/", meaningZh: "頭" }] },
      { spelling: "ai", examples: [{ word: "lait", ipa: "/lɛ/", meaningZh: "牛奶" }] },
      { spelling: "ei", examples: [{ word: "neige", ipa: "/nɛʒ/", meaningZh: "雪" }] },
      { spelling: "e + 雙子音", examples: [{ word: "belle", ipa: "/bɛl/", meaningZh: "美麗的（陰性）" }] },
    ],
    wordExamples: [
      { word: "père", ipa: "/pɛʁ/", meaningZh: "父親", highlight: "è" },
      { word: "tête", ipa: "/tɛt/", meaningZh: "頭", highlight: "ê" },
      { word: "lait", ipa: "/lɛ/", meaningZh: "牛奶", highlight: "ai" },
    ],
    comparisons: [{
      otherIpa: "/e/",
      mouthDiff: "/ɛ/ 嘴巴張得比 /e/ 更開，嘴角放鬆；/e/ 嘴角向兩側拉緊、開口較小",
      tongueDiff: "/ɛ/ 舌位較低；/e/ 舌位較高、較前",
      vocalDiff: "兩者皆為濁音，差異在開口度與舌位高低，不在聲帶",
      wordA: { word: "père", ipa: "/pɛʁ/", meaningZh: "父親" },
      wordB: { word: "été", ipa: "/ete/", meaningZh: "夏天" },
    }],
    practiceWords: ["père", "tête", "lait"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "a", category: "母音", ipa: "/a/", exampleWord: "chat", exampleIpa: "/ʃa/", meaningZh: "貓", approxZh: "啊",
    shortDescription: "嘴巴自然張開，舌頭放鬆，發音短而清楚",
    mouthPosition: "嘴巴自然張開，比 /ɛ/ 更開",
    tonguePosition: "舌頭平放在口腔中央，不前不後",
    airflow: "氣流從口腔中央穩定流出",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/a/"),
    commonSpellings: [
      { spelling: "a", examples: [{ word: "chat", ipa: "/ʃa/", meaningZh: "貓" }] },
      { spelling: "à", examples: [{ word: "voilà", ipa: "/vwala/", meaningZh: "這就是／看" }] },
    ],
    wordExamples: [
      { word: "chat", ipa: "/ʃa/", meaningZh: "貓", highlight: "a" },
      { word: "ami", ipa: "/ami/", meaningZh: "朋友", highlight: "a" },
      { word: "salade", ipa: "/salad/", meaningZh: "沙拉", highlight: "a" },
    ],
    practiceWords: ["chat", "ami", "salade"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "ɑ", category: "母音", ipa: "/ɑ/", exampleWord: "pâte", exampleIpa: "/pɑt/", meaningZh: "麵團／麵糊",
    shortDescription: "嘴巴張得比 /a/ 更大更後，聲音更深沉（現代法語中部分地區已與 /a/ 合併，仍建議認識這個音）",
    mouthPosition: "嘴巴張大，開口比 /a/ 更大",
    tonguePosition: "舌頭位置比 /a/ 更後、更低",
    airflow: "氣流從口腔後方穩定流出",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/ɑ/"),
    commonSpellings: [
      { spelling: "â", examples: [{ word: "pâte", ipa: "/pɑt/", meaningZh: "麵團" }] },
      { spelling: "as（少數字）", examples: [{ word: "pas", ipa: "/pɑ/", meaningZh: "不／步伐" }] },
    ],
    wordExamples: [
      { word: "pâte", ipa: "/pɑt/", meaningZh: "麵團", highlight: "â" },
      { word: "pâle", ipa: "/pɑl/", meaningZh: "蒼白的", highlight: "â" },
      { word: "âge", ipa: "/ɑʒ/", meaningZh: "年齡", highlight: "â" },
    ],
    practiceWords: ["pâte", "pâle", "âge"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "y", category: "母音", ipa: "/y/", exampleWord: "tu", exampleIpa: "/ty/", meaningZh: "你",
    shortDescription: "嘴唇收得又圓又小向前突出，舌位卻像 /i/ 一樣抬高靠前",
    mouthPosition: "嘴唇用力收圓向前突出，像要吹口哨",
    tonguePosition: "舌面抬高靠前，位置接近 /i/，但嘴唇是圓的",
    airflow: "氣流穩定流出，不中斷",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/y/"),
    commonSpellings: [
      { spelling: "u", examples: [{ word: "tu", ipa: "/ty/", meaningZh: "你" }] },
      { spelling: "û", examples: [{ word: "sûr", ipa: "/syʁ/", meaningZh: "確定的" }] },
    ],
    wordExamples: [
      { word: "tu", ipa: "/ty/", meaningZh: "你", highlight: "u" },
      { word: "rue", ipa: "/ʁy/", meaningZh: "街道", highlight: "u" },
      { word: "musique", ipa: "/myzik/", meaningZh: "音樂", highlight: "u" },
    ],
    comparisons: [{
      otherIpa: "/u/",
      mouthDiff: "/y/ 嘴唇要收得更圓更小，幾乎像吹口哨；/u/ 嘴唇更向前突出、開口稍大",
      tongueDiff: "/y/ 舌頭前移到接近 /i/ 的位置；/u/ 舌頭在後方偏高",
      vocalDiff: "兩者皆為濁音，差異在嘴唇與舌位，不在聲帶",
      wordA: { word: "tu", ipa: "/ty/", meaningZh: "你" },
      wordB: { word: "tout", ipa: "/tu/", meaningZh: "全部" },
    }],
    practiceWords: ["tu", "rue", "musique"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "ø", category: "母音", ipa: "/ø/", exampleWord: "peu", exampleIpa: "/pø/", meaningZh: "一點點／少",
    shortDescription: "嘴唇圓起像 /o/，但舌位前移像 /e/，聲音介於兩者之間",
    mouthPosition: "嘴唇收圓，開口中等",
    tonguePosition: "舌面抬高偏前，接近 /e/ 的舌位",
    airflow: "氣流平穩持續",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/ø/"),
    commonSpellings: [
      { spelling: "eu", examples: [{ word: "peu", ipa: "/pø/", meaningZh: "一點點" }] },
      { spelling: "œu（字尾）", examples: [{ word: "vœu", ipa: "/vø/", meaningZh: "願望" }] },
    ],
    wordExamples: [
      { word: "peu", ipa: "/pø/", meaningZh: "一點點", highlight: "eu" },
      { word: "deux", ipa: "/dø/", meaningZh: "二", highlight: "eu" },
      { word: "jeudi", ipa: "/ʒødi/", meaningZh: "星期四", highlight: "eu" },
    ],
    practiceWords: ["peu", "deux", "jeudi"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "œ", category: "母音", ipa: "/œ/", exampleWord: "sœur", exampleIpa: "/sœʁ/", meaningZh: "姊妹",
    shortDescription: "嘴唇圓起像 /ɔ/，舌位前移像 /ɛ/，開口比 /ø/ 更大",
    mouthPosition: "嘴唇收圓但比 /ø/ 開口更大",
    tonguePosition: "舌面抬高偏前，但比 /ø/ 略低，接近 /ɛ/",
    airflow: "氣流平穩持續",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/œ/"),
    commonSpellings: [
      { spelling: "eu（+ 發音子音）", examples: [{ word: "peur", ipa: "/pœʁ/", meaningZh: "害怕" }] },
      { spelling: "œu（+ 發音子音）", examples: [{ word: "sœur", ipa: "/sœʁ/", meaningZh: "姊妹" }] },
    ],
    wordExamples: [
      { word: "sœur", ipa: "/sœʁ/", meaningZh: "姊妹", highlight: "œu" },
      { word: "peur", ipa: "/pœʁ/", meaningZh: "害怕", highlight: "eu" },
      { word: "heure", ipa: "/œʁ/", meaningZh: "小時／點鐘", highlight: "eu" },
    ],
    practiceWords: ["sœur", "peur", "heure"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "u", category: "母音", ipa: "/u/", exampleWord: "vous", exampleIpa: "/vu/", meaningZh: "你們／您",
    shortDescription: "嘴唇最圓最小，向前突出，聲音低沉厚實",
    mouthPosition: "嘴唇圓形向前突出，開口很小",
    tonguePosition: "舌頭盡量後縮、抬高",
    airflow: "氣流穩定持續流出",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/u/"),
    commonSpellings: [
      { spelling: "ou", examples: [{ word: "vous", ipa: "/vu/", meaningZh: "你們／您" }] },
      { spelling: "où", examples: [{ word: "où", ipa: "/u/", meaningZh: "哪裡" }] },
      { spelling: "oû", examples: [{ word: "goût", ipa: "/gu/", meaningZh: "味道" }] },
    ],
    wordExamples: [
      { word: "vous", ipa: "/vu/", meaningZh: "你們／您", highlight: "ou" },
      { word: "tout", ipa: "/tu/", meaningZh: "全部", highlight: "ou" },
      { word: "amour", ipa: "/amuʁ/", meaningZh: "愛", highlight: "ou" },
    ],
    comparisons: [{
      otherIpa: "/y/",
      mouthDiff: "/u/ 嘴唇更向前突出、開口稍大；/y/ 嘴唇要收得更圓更小，幾乎像吹口哨",
      tongueDiff: "/u/ 舌頭在後方偏高；/y/ 舌頭前移到接近 /i/ 的位置",
      vocalDiff: "兩者皆為濁音，差異在嘴唇與舌位，不在聲帶",
      wordA: { word: "tout", ipa: "/tu/", meaningZh: "全部" },
      wordB: { word: "tu", ipa: "/ty/", meaningZh: "你" },
    }],
    practiceWords: ["vous", "tout", "amour"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "o", category: "母音", ipa: "/o/", exampleWord: "mot", exampleIpa: "/mo/", meaningZh: "詞語",
    shortDescription: "嘴唇圓形，比 /ɔ/ 更緊更突出，聲音乾淨不下滑",
    mouthPosition: "嘴唇收圓，開口較小",
    tonguePosition: "舌頭偏後、抬高，比 /ɔ/ 更高",
    airflow: "氣流穩定持續",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/o/"),
    commonSpellings: [
      { spelling: "o（字尾／開音節）", examples: [{ word: "mot", ipa: "/mo/", meaningZh: "詞語" }] },
      { spelling: "ô", examples: [{ word: "hôtel", ipa: "/otɛl/", meaningZh: "旅館" }] },
      { spelling: "au", examples: [{ word: "chaud", ipa: "/ʃo/", meaningZh: "熱的" }] },
      { spelling: "eau", examples: [{ word: "eau", ipa: "/o/", meaningZh: "水" }] },
    ],
    wordExamples: [
      { word: "mot", ipa: "/mo/", meaningZh: "詞語", highlight: "o" },
      { word: "eau", ipa: "/o/", meaningZh: "水", highlight: "eau" },
      { word: "chaud", ipa: "/ʃo/", meaningZh: "熱的", highlight: "au" },
    ],
    comparisons: [{
      otherIpa: "/ɔ/",
      mouthDiff: "/o/ 嘴唇更圓、更緊、更突出，開口較小；/ɔ/ 嘴唇圓但開口更大",
      tongueDiff: "/o/ 舌位較高偏後；/ɔ/ 舌位略低",
      vocalDiff: "兩者皆為濁音，差異在開口度，不在聲帶",
      wordA: { word: "mot", ipa: "/mo/", meaningZh: "詞語" },
      wordB: { word: "porte", ipa: "/pɔʁt/", meaningZh: "門" },
    }],
    practiceWords: ["mot", "eau", "chaud"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "ɔ", category: "母音", ipa: "/ɔ/", exampleWord: "porte", exampleIpa: "/pɔʁt/", meaningZh: "門",
    shortDescription: "嘴唇圓但開口比 /o/ 更大，聲音較短較鬆",
    mouthPosition: "嘴唇收圓，開口比 /o/ 明顯更大",
    tonguePosition: "舌頭偏後，但比 /o/ 略低",
    airflow: "氣流平穩持續",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/ɔ/"),
    commonSpellings: [
      { spelling: "o（+ 發音子音，閉音節）", examples: [{ word: "porte", ipa: "/pɔʁt/", meaningZh: "門" }] },
    ],
    wordExamples: [
      { word: "porte", ipa: "/pɔʁt/", meaningZh: "門", highlight: "o" },
      { word: "robe", ipa: "/ʁɔb/", meaningZh: "洋裝", highlight: "o" },
      { word: "école", ipa: "/ekɔl/", meaningZh: "學校", highlight: "o" },
    ],
    comparisons: [{
      otherIpa: "/o/",
      mouthDiff: "/ɔ/ 嘴唇圓但開口更大；/o/ 嘴唇更圓、更緊、更突出，開口較小",
      tongueDiff: "/ɔ/ 舌位略低；/o/ 舌位較高偏後",
      vocalDiff: "兩者皆為濁音，差異在開口度，不在聲帶",
      wordA: { word: "porte", ipa: "/pɔʁt/", meaningZh: "門" },
      wordB: { word: "mot", ipa: "/mo/", meaningZh: "詞語" },
    }],
    practiceWords: ["porte", "robe", "école"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "ə", category: "母音", ipa: "/ə/", exampleWord: "le", exampleIpa: "/lə/", meaningZh: "（陽性冠詞）",
    shortDescription: "輕短模糊的音，嘴唇微圓，常在說話時被省略",
    mouthPosition: "嘴巴微開，嘴唇略微收圓但不明顯",
    tonguePosition: "舌頭放鬆置於口腔中央，不刻意抬高或前後移動",
    airflow: "氣流輕短，音量比其他母音弱",
    vocalCord: "聲帶持續震動（濁音），但很輕",
    pronunciationSteps: DEFAULT_STEPS("/ə/"),
    commonSpellings: [
      { spelling: "e（非重讀音節）", examples: [{ word: "le", ipa: "/lə/", meaningZh: "（陽性冠詞）" }] },
    ],
    wordExamples: [
      { word: "le", ipa: "/lə/", meaningZh: "（陽性冠詞）", highlight: "e" },
      { word: "petit", ipa: "/pəti/", meaningZh: "小的", highlight: "e" },
      { word: "regarder", ipa: "/ʁəgaʁde/", meaningZh: "看", highlight: "e" },
    ],
    practiceWords: ["le", "petit", "regarder"], showPracticeSteps: true,
    audio: mkAudio(),
  },

  // ══════════════════════════ 鼻母音 ══════════════════════════
  {
    id: "ɑ̃", category: "鼻母音", ipa: "/ɑ̃/", exampleWord: "dans", exampleIpa: "/dɑ̃/", meaningZh: "在……裡面",
    shortDescription: "嘴巴張大像 /a/，但氣流同時從鼻腔和口腔出來",
    mouthPosition: "嘴巴張開程度接近 /a/",
    tonguePosition: "舌頭放低放後",
    airflow: "軟顎下垂，氣流同時從口腔和鼻腔流出（鼻化）",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/ɑ̃/"),
    commonSpellings: [
      { spelling: "an", examples: [{ word: "dans", ipa: "/dɑ̃/", meaningZh: "在……裡面" }] },
      { spelling: "en", examples: [{ word: "enfant", ipa: "/ɑ̃fɑ̃/", meaningZh: "小孩" }] },
      { spelling: "am", examples: [{ word: "chambre", ipa: "/ʃɑ̃bʁ/", meaningZh: "房間" }] },
      { spelling: "em", examples: [{ word: "septembre", ipa: "/sɛptɑ̃bʁ/", meaningZh: "九月" }] },
    ],
    wordExamples: [
      { word: "dans", ipa: "/dɑ̃/", meaningZh: "在……裡面", highlight: "an" },
      { word: "enfant", ipa: "/ɑ̃fɑ̃/", meaningZh: "小孩", highlight: "en" },
      { word: "chambre", ipa: "/ʃɑ̃bʁ/", meaningZh: "房間", highlight: "am" },
    ],
    comparisons: [{
      otherIpa: "/ɔ̃/",
      mouthDiff: "/ɑ̃/ 嘴巴張得較大，接近 /a/ 的開口；/ɔ̃/ 嘴唇要圓起，接近 /o/ 的嘴型",
      tongueDiff: "/ɑ̃/ 舌頭放低放後；/ɔ̃/ 舌頭略高，同時軟顎下垂讓氣流進入鼻腔",
      vocalDiff: "兩者皆為濁音且部分氣流從鼻腔通過，差異在嘴唇圓展和開口度，不在聲帶",
      wordA: { word: "dans", ipa: "/dɑ̃/", meaningZh: "在……裡面" },
      wordB: { word: "bon", ipa: "/bɔ̃/", meaningZh: "好的" },
    }],
    practiceWords: ["dans", "enfant", "chambre"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "ɛ̃", category: "鼻母音", ipa: "/ɛ̃/", exampleWord: "pain", exampleIpa: "/pɛ̃/", meaningZh: "麵包",
    shortDescription: "嘴巴半開像 /ɛ/，氣流同時從鼻腔和口腔出來",
    mouthPosition: "嘴巴半開，接近 /ɛ/ 的開口",
    tonguePosition: "舌面前部略抬高",
    airflow: "軟顎下垂，氣流同時從口腔和鼻腔流出（鼻化）",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/ɛ̃/"),
    commonSpellings: [
      { spelling: "in", examples: [{ word: "jardin", ipa: "/ʒaʁdɛ̃/", meaningZh: "花園" }] },
      { spelling: "ain", examples: [{ word: "pain", ipa: "/pɛ̃/", meaningZh: "麵包" }] },
      { spelling: "ein", examples: [{ word: "peintre", ipa: "/pɛ̃tʁ/", meaningZh: "畫家" }] },
      { spelling: "im", examples: [{ word: "important", ipa: "/ɛ̃pɔʁtɑ̃/", meaningZh: "重要的" }] },
    ],
    wordExamples: [
      { word: "pain", ipa: "/pɛ̃/", meaningZh: "麵包", highlight: "ain" },
      { word: "jardin", ipa: "/ʒaʁdɛ̃/", meaningZh: "花園", highlight: "in" },
      { word: "important", ipa: "/ɛ̃pɔʁtɑ̃/", meaningZh: "重要的", highlight: "im" },
    ],
    practiceWords: ["pain", "jardin", "important"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "ɔ̃", category: "鼻母音", ipa: "/ɔ̃/", exampleWord: "bon", exampleIpa: "/bɔ̃/", meaningZh: "好的",
    shortDescription: "嘴唇圓起像 /o/，氣流同時從鼻腔和口腔出來",
    mouthPosition: "嘴唇收圓，接近 /o/ 的嘴型",
    tonguePosition: "舌頭偏後、略抬高",
    airflow: "軟顎下垂，氣流同時從口腔和鼻腔流出（鼻化）",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/ɔ̃/"),
    commonSpellings: [
      { spelling: "on", examples: [{ word: "bon", ipa: "/bɔ̃/", meaningZh: "好的" }] },
      { spelling: "om", examples: [{ word: "nombre", ipa: "/nɔ̃bʁ/", meaningZh: "數字" }] },
    ],
    wordExamples: [
      { word: "bon", ipa: "/bɔ̃/", meaningZh: "好的", highlight: "on" },
      { word: "maison", ipa: "/mɛzɔ̃/", meaningZh: "房子", highlight: "on" },
      { word: "nombre", ipa: "/nɔ̃bʁ/", meaningZh: "數字", highlight: "om" },
    ],
    comparisons: [{
      otherIpa: "/ɑ̃/",
      mouthDiff: "/ɔ̃/ 嘴唇要圓起，接近 /o/ 的嘴型；/ɑ̃/ 嘴巴張得較大，接近 /a/ 的開口",
      tongueDiff: "/ɔ̃/ 舌頭略高；/ɑ̃/ 舌頭放低放後",
      vocalDiff: "兩者皆為濁音且部分氣流從鼻腔通過，差異在嘴唇圓展和開口度，不在聲帶",
      wordA: { word: "bon", ipa: "/bɔ̃/", meaningZh: "好的" },
      wordB: { word: "dans", ipa: "/dɑ̃/", meaningZh: "在……裡面" },
    }],
    practiceWords: ["bon", "maison", "nombre"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "œ̃", category: "鼻母音", ipa: "/œ̃/", exampleWord: "un", exampleIpa: "/œ̃/", meaningZh: "一（陽性）",
    shortDescription: "嘴唇圓起像 /œ/，氣流同時從鼻腔和口腔出來（現代法語中很多地區已與 /ɛ̃/ 合併，仍建議認識這個音）",
    mouthPosition: "嘴唇微圓，開口中等，接近 /œ/",
    tonguePosition: "舌面前部中等高度",
    airflow: "軟顎下垂，氣流同時從口腔和鼻腔流出（鼻化）",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/œ̃/"),
    commonSpellings: [
      { spelling: "un", examples: [{ word: "un", ipa: "/œ̃/", meaningZh: "一（陽性）" }] },
      { spelling: "um", examples: [{ word: "parfum", ipa: "/paʁfœ̃/", meaningZh: "香水" }] },
    ],
    wordExamples: [
      { word: "un", ipa: "/œ̃/", meaningZh: "一（陽性）", highlight: "un" },
      { word: "lundi", ipa: "/lœ̃di/", meaningZh: "星期一", highlight: "un" },
      { word: "parfum", ipa: "/paʁfœ̃/", meaningZh: "香水", highlight: "um" },
    ],
    practiceWords: ["un", "lundi", "parfum"], showPracticeSteps: true,
    audio: mkAudio(),
  },

  // ══════════════════════════ 半母音 ══════════════════════════
  {
    id: "j", category: "半母音", ipa: "/j/", exampleWord: "fille", exampleIpa: "/fij/", meaningZh: "女孩",
    shortDescription: "像很短促的「一」快速滑向下一個母音，舌位高但不成獨立音節",
    mouthPosition: "嘴角向兩側拉開，接近 /i/ 的嘴型但時間極短",
    tonguePosition: "舌面抬高靠前，很快滑向下一個母音的位置",
    airflow: "氣流連續不中斷，滑動快速",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/j/"),
    commonSpellings: [
      { spelling: "i + 母音", examples: [{ word: "piano", ipa: "/pjano/", meaningZh: "鋼琴" }] },
      { spelling: "il（字尾）", examples: [{ word: "soleil", ipa: "/sɔlɛj/", meaningZh: "太陽" }] },
      { spelling: "ill", examples: [{ word: "fille", ipa: "/fij/", meaningZh: "女孩" }] },
      { spelling: "y + 母音", examples: [{ word: "yeux", ipa: "/jø/", meaningZh: "眼睛" }] },
    ],
    wordExamples: [
      { word: "fille", ipa: "/fij/", meaningZh: "女孩", highlight: "ill" },
      { word: "soleil", ipa: "/sɔlɛj/", meaningZh: "太陽", highlight: "eil" },
      { word: "piano", ipa: "/pjano/", meaningZh: "鋼琴", highlight: "i" },
    ],
    practiceWords: ["fille", "soleil", "piano"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "ɥ", category: "半母音", ipa: "/ɥ/", exampleWord: "huit", exampleIpa: "/ɥit/", meaningZh: "八",
    shortDescription: "嘴唇先圓起像 /y/，立刻快速滑向下一個母音",
    mouthPosition: "嘴唇先收圓突出（像 /y/），隨即快速放開滑向下一個母音",
    tonguePosition: "舌面先抬高靠前，隨即快速移動",
    airflow: "氣流連續不中斷，滑動極快",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/ɥ/"),
    commonSpellings: [
      { spelling: "u + 母音", examples: [{ word: "huit", ipa: "/ɥit/", meaningZh: "八" }] },
    ],
    wordExamples: [
      { word: "huit", ipa: "/ɥit/", meaningZh: "八", highlight: "ui" },
      { word: "nuit", ipa: "/nɥi/", meaningZh: "夜晚", highlight: "ui" },
      { word: "suis", ipa: "/sɥi/", meaningZh: "（我）是", highlight: "ui" },
    ],
    practiceWords: ["huit", "nuit", "suis"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "w", category: "半母音", ipa: "/w/", exampleWord: "oui", exampleIpa: "/wi/", meaningZh: "是（的）",
    shortDescription: "嘴唇先圓起像 /u/，立刻快速滑向下一個母音",
    mouthPosition: "嘴唇先收圓突出（像 /u/），隨即快速放開滑向下一個母音",
    tonguePosition: "舌頭先後縮抬高，隨即快速移動",
    airflow: "氣流連續不中斷，滑動極快",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/w/"),
    commonSpellings: [
      { spelling: "ou + 母音", examples: [{ word: "oui", ipa: "/wi/", meaningZh: "是的" }] },
      { spelling: "w（外來詞）", examples: [{ word: "week-end", ipa: "/wikɛnd/", meaningZh: "週末" }] },
    ],
    wordExamples: [
      { word: "oui", ipa: "/wi/", meaningZh: "是的", highlight: "oui" },
      { word: "moi", ipa: "/mwa/", meaningZh: "我", highlight: "oi" },
      { word: "trois", ipa: "/tʁwa/", meaningZh: "三", highlight: "oi" },
    ],
    practiceWords: ["oui", "moi", "trois"], showPracticeSteps: true,
    audio: mkAudio(),
  },

  // ══════════════════════════ 子音 ══════════════════════════
  {
    id: "p", category: "子音", ipa: "/p/", exampleWord: "pain", exampleIpa: "/pɛ̃/", meaningZh: "麵包",
    shortDescription: "雙唇緊閉後突然放開，氣流爆破而出",
    mouthPosition: "雙唇完全閉合，然後突然張開",
    tonguePosition: "舌頭放鬆，不參與阻塞",
    airflow: "氣流先完全阻塞在雙唇後，然後爆破釋放",
    vocalCord: "聲帶不震動（清音）",
    pronunciationSteps: DEFAULT_STEPS("/p/"),
    commonSpellings: [{ spelling: "p", examples: [{ word: "pain", ipa: "/pɛ̃/", meaningZh: "麵包" }] }],
    wordExamples: [
      { word: "pain", ipa: "/pɛ̃/", meaningZh: "麵包", highlight: "p" },
      { word: "parler", ipa: "/paʁle/", meaningZh: "說話", highlight: "p" },
      { word: "soupe", ipa: "/sup/", meaningZh: "湯", highlight: "p" },
    ],
    combinations: combo("p"),
    practiceWords: ["pain", "parler", "soupe"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "b", category: "子音", ipa: "/b/", exampleWord: "bon", exampleIpa: "/bɔ̃/", meaningZh: "好的",
    shortDescription: "雙唇緊閉後放開，跟 /p/ 動作相同但聲帶要震動",
    mouthPosition: "雙唇完全閉合，然後張開",
    tonguePosition: "舌頭放鬆",
    airflow: "氣流先阻塞在雙唇後，然後爆破釋放",
    vocalCord: "聲帶持續震動（濁音），閉唇時也能感覺喉嚨震動",
    pronunciationSteps: DEFAULT_STEPS("/b/"),
    commonSpellings: [{ spelling: "b", examples: [{ word: "bon", ipa: "/bɔ̃/", meaningZh: "好的" }] }],
    wordExamples: [
      { word: "bon", ipa: "/bɔ̃/", meaningZh: "好的", highlight: "b" },
      { word: "bébé", ipa: "/bebe/", meaningZh: "嬰兒", highlight: "b" },
      { word: "robe", ipa: "/ʁɔb/", meaningZh: "洋裝", highlight: "b" },
    ],
    combinations: combo("b"),
    practiceWords: ["bon", "bébé", "robe"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "t", category: "子音", ipa: "/t/", exampleWord: "tu", exampleIpa: "/ty/", meaningZh: "你",
    shortDescription: "舌尖抵住上齒齦後方，形成阻塞後突然放開",
    mouthPosition: "雙唇微開，嘴巴自然",
    tonguePosition: "舌尖抵住上齒齦後方，形成阻塞後放開",
    airflow: "氣流先阻塞在舌尖後，然後爆破釋放",
    vocalCord: "聲帶不震動（清音）",
    pronunciationSteps: DEFAULT_STEPS("/t/"),
    commonSpellings: [{ spelling: "t", examples: [{ word: "tu", ipa: "/ty/", meaningZh: "你" }] }],
    wordExamples: [
      { word: "tu", ipa: "/ty/", meaningZh: "你", highlight: "t" },
      { word: "table", ipa: "/tabl/", meaningZh: "桌子", highlight: "t" },
      { word: "petit", ipa: "/pəti/", meaningZh: "小的", highlight: "t" },
    ],
    combinations: combo("t"),
    practiceWords: ["tu", "table", "petit"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "d", category: "子音", ipa: "/d/", exampleWord: "dans", exampleIpa: "/dɑ̃/", meaningZh: "在……裡面",
    shortDescription: "舌尖抵住上齒齦後方，跟 /t/ 相同位置但聲帶要震動",
    mouthPosition: "雙唇微開，嘴巴自然",
    tonguePosition: "舌尖抵住上齒齦後方，跟 /t/ 相同位置",
    airflow: "氣流先阻塞在舌尖後，然後爆破釋放",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/d/"),
    commonSpellings: [{ spelling: "d", examples: [{ word: "dans", ipa: "/dɑ̃/", meaningZh: "在……裡面" }] }],
    wordExamples: [
      { word: "dans", ipa: "/dɑ̃/", meaningZh: "在……裡面", highlight: "d" },
      { word: "madame", ipa: "/madam/", meaningZh: "女士", highlight: "d" },
      { word: "regarder", ipa: "/ʁəgaʁde/", meaningZh: "看", highlight: "d" },
    ],
    combinations: combo("d"),
    practiceWords: ["dans", "madame", "regarder"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "k", category: "子音", ipa: "/k/", exampleWord: "quatre", exampleIpa: "/katʁ/", meaningZh: "四",
    shortDescription: "舌根頂住軟顎，形成阻塞後突然放開",
    mouthPosition: "嘴巴自然微開",
    tonguePosition: "舌根頂住軟顎，形成阻塞後放開",
    airflow: "氣流先阻塞在舌根後，然後爆破釋放",
    vocalCord: "聲帶不震動（清音）",
    pronunciationSteps: DEFAULT_STEPS("/k/"),
    commonSpellings: [
      { spelling: "c（+a,o,u）", examples: [{ word: "café", ipa: "/kafe/", meaningZh: "咖啡" }] },
      { spelling: "qu", examples: [{ word: "quatre", ipa: "/katʁ/", meaningZh: "四" }] },
      { spelling: "k", examples: [{ word: "kilo", ipa: "/kilo/", meaningZh: "公斤" }] },
    ],
    wordExamples: [
      { word: "quatre", ipa: "/katʁ/", meaningZh: "四", highlight: "qu" },
      { word: "café", ipa: "/kafe/", meaningZh: "咖啡", highlight: "c" },
      { word: "kilo", ipa: "/kilo/", meaningZh: "公斤", highlight: "k" },
    ],
    combinations: combo("k"),
    practiceWords: ["quatre", "café", "kilo"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "ɡ", category: "子音", ipa: "/ɡ/", exampleWord: "gare", exampleIpa: "/ɡaʁ/", meaningZh: "火車站",
    shortDescription: "舌根頂住軟顎，跟 /k/ 相同位置但聲帶要震動",
    mouthPosition: "嘴巴自然微開",
    tonguePosition: "舌根頂住軟顎，跟 /k/ 相同位置",
    airflow: "氣流先阻塞在舌根後，然後爆破釋放",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/ɡ/"),
    commonSpellings: [
      { spelling: "g（+a,o,u）", examples: [{ word: "gare", ipa: "/ɡaʁ/", meaningZh: "火車站" }] },
      { spelling: "gu（+e,i）", examples: [{ word: "guerre", ipa: "/ɡɛʁ/", meaningZh: "戰爭" }] },
    ],
    wordExamples: [
      { word: "gare", ipa: "/ɡaʁ/", meaningZh: "火車站", highlight: "g" },
      { word: "guitare", ipa: "/ɡitaʁ/", meaningZh: "吉他", highlight: "gu" },
      { word: "légume", ipa: "/leɡym/", meaningZh: "蔬菜", highlight: "g" },
    ],
    combinations: combo("ɡ"),
    practiceWords: ["gare", "guitare", "légume"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "f", category: "子音", ipa: "/f/", exampleWord: "fille", exampleIpa: "/fij/", meaningZh: "女孩",
    shortDescription: "上齒輕觸下唇，氣流持續摩擦而出",
    mouthPosition: "上齒輕觸下唇",
    tonguePosition: "舌頭放鬆，不參與阻塞",
    airflow: "氣流持續從上齒與下唇的縫隙摩擦而出",
    vocalCord: "聲帶不震動（清音）",
    pronunciationSteps: DEFAULT_STEPS("/f/"),
    commonSpellings: [
      { spelling: "f", examples: [{ word: "fille", ipa: "/fij/", meaningZh: "女孩" }] },
      { spelling: "ph", examples: [{ word: "photo", ipa: "/foto/", meaningZh: "照片" }] },
    ],
    wordExamples: [
      { word: "fille", ipa: "/fij/", meaningZh: "女孩", highlight: "f" },
      { word: "café", ipa: "/kafe/", meaningZh: "咖啡", highlight: "f" },
      { word: "photo", ipa: "/foto/", meaningZh: "照片", highlight: "ph" },
    ],
    combinations: combo("f"),
    practiceWords: ["fille", "café", "photo"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "v", category: "子音", ipa: "/v/", exampleWord: "vous", exampleIpa: "/vu/", meaningZh: "你們／您",
    shortDescription: "上齒輕觸下唇，跟 /f/ 相同但聲帶要震動",
    mouthPosition: "上齒輕觸下唇",
    tonguePosition: "舌頭放鬆",
    airflow: "氣流持續從上齒與下唇的縫隙摩擦而出",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/v/"),
    commonSpellings: [{ spelling: "v", examples: [{ word: "vous", ipa: "/vu/", meaningZh: "你們／您" }] }],
    wordExamples: [
      { word: "vous", ipa: "/vu/", meaningZh: "你們／您", highlight: "v" },
      { word: "ville", ipa: "/vil/", meaningZh: "城市", highlight: "v" },
      { word: "cave", ipa: "/kav/", meaningZh: "地窖", highlight: "v" },
    ],
    combinations: combo("v"),
    practiceWords: ["vous", "ville", "cave"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "s", category: "子音", ipa: "/s/", exampleWord: "sac", exampleIpa: "/sak/", meaningZh: "包包",
    shortDescription: "舌尖靠近上齒齦留一條窄縫，氣流摩擦而出",
    mouthPosition: "嘴唇微開，嘴角略拉",
    tonguePosition: "舌尖靠近上齒齦，留一條窄縫",
    airflow: "氣流持續從舌尖窄縫摩擦而出",
    vocalCord: "聲帶不震動（清音）",
    pronunciationSteps: DEFAULT_STEPS("/s/"),
    commonSpellings: [
      { spelling: "s（字首／子音旁）", examples: [{ word: "sac", ipa: "/sak/", meaningZh: "包包" }] },
      { spelling: "ss（母音之間）", examples: [{ word: "poisson", ipa: "/pwasɔ̃/", meaningZh: "魚" }] },
      { spelling: "c（+e,i）", examples: [{ word: "cinéma", ipa: "/sinema/", meaningZh: "電影院" }] },
      { spelling: "ç", examples: [{ word: "garçon", ipa: "/ɡaʁsɔ̃/", meaningZh: "男孩" }] },
    ],
    wordExamples: [
      { word: "sac", ipa: "/sak/", meaningZh: "包包", highlight: "s" },
      { word: "poisson", ipa: "/pwasɔ̃/", meaningZh: "魚", highlight: "ss" },
      { word: "garçon", ipa: "/ɡaʁsɔ̃/", meaningZh: "男孩", highlight: "ç" },
    ],
    combinations: combo("s"),
    comparisons: [{
      otherIpa: "/z/",
      mouthDiff: "嘴型幾乎相同，嘴唇微開，不是差異重點",
      tongueDiff: "舌尖都靠近上齒齦、留一條窄縫讓氣流摩擦而出，舌位相同",
      vocalDiff: "關鍵差異在聲帶：/s/ 聲帶不震動（清音）；/z/ 聲帶持續震動（濁音），可以用手摸喉嚨感覺震動與否",
      wordA: { word: "poisson", ipa: "/pwasɔ̃/", meaningZh: "魚" },
      wordB: { word: "poison", ipa: "/pwazɔ̃/", meaningZh: "毒藥" },
    }],
    practiceWords: ["sac", "poisson", "garçon"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "z", category: "子音", ipa: "/z/", exampleWord: "zéro", exampleIpa: "/zeʁo/", meaningZh: "零",
    shortDescription: "舌尖靠近上齒齦留一條窄縫，跟 /s/ 相同但聲帶要震動",
    mouthPosition: "嘴唇微開，跟 /s/ 相同",
    tonguePosition: "舌尖靠近上齒齦，留一條窄縫，跟 /s/ 相同位置",
    airflow: "氣流持續從舌尖窄縫摩擦而出",
    vocalCord: "聲帶持續震動（濁音），這是跟 /s/ 唯一的差別",
    pronunciationSteps: DEFAULT_STEPS("/z/"),
    commonSpellings: [
      { spelling: "z", examples: [{ word: "zéro", ipa: "/zeʁo/", meaningZh: "零" }] },
      { spelling: "s（母音之間）", examples: [{ word: "maison", ipa: "/mɛzɔ̃/", meaningZh: "房子" }] },
    ],
    wordExamples: [
      { word: "zéro", ipa: "/zeʁo/", meaningZh: "零", highlight: "z" },
      { word: "maison", ipa: "/mɛzɔ̃/", meaningZh: "房子", highlight: "s" },
      { word: "zoo", ipa: "/zo/", meaningZh: "動物園", highlight: "z" },
    ],
    combinations: combo("z"),
    comparisons: [{
      otherIpa: "/s/",
      mouthDiff: "嘴型幾乎相同，嘴唇微開，不是差異重點",
      tongueDiff: "舌尖都靠近上齒齦、留一條窄縫讓氣流摩擦而出，舌位相同",
      vocalDiff: "關鍵差異在聲帶：/z/ 聲帶持續震動（濁音）；/s/ 聲帶不震動（清音），可以用手摸喉嚨感覺震動與否",
      wordA: { word: "poison", ipa: "/pwazɔ̃/", meaningZh: "毒藥" },
      wordB: { word: "poisson", ipa: "/pwasɔ̃/", meaningZh: "魚" },
    }],
    practiceWords: ["zéro", "maison", "zoo"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "ʃ", category: "子音", ipa: "/ʃ/", exampleWord: "chat", exampleIpa: "/ʃa/", meaningZh: "貓",
    shortDescription: "嘴唇向前突出收圓，舌面靠近硬顎摩擦而出",
    mouthPosition: "嘴唇向前突出收圓",
    tonguePosition: "舌面抬高靠近硬顎前部，留一條縫",
    airflow: "氣流持續從舌面與硬顎的縫隙摩擦而出",
    vocalCord: "聲帶不震動（清音）",
    pronunciationSteps: DEFAULT_STEPS("/ʃ/"),
    commonSpellings: [{ spelling: "ch", examples: [{ word: "chat", ipa: "/ʃa/", meaningZh: "貓" }] }],
    wordExamples: [
      { word: "chat", ipa: "/ʃa/", meaningZh: "貓", highlight: "ch" },
      { word: "chien", ipa: "/ʃjɛ̃/", meaningZh: "狗", highlight: "ch" },
      { word: "chocolat", ipa: "/ʃɔkɔla/", meaningZh: "巧克力", highlight: "ch" },
    ],
    combinations: combo("ʃ"),
    comparisons: [{
      otherIpa: "/ʒ/",
      mouthDiff: "嘴型相同，嘴唇略向前突出成圓形",
      tongueDiff: "舌面都抬高靠近硬顎前部，留縫隙讓氣流摩擦，舌位相同",
      vocalDiff: "關鍵差異在聲帶：/ʃ/ 聲帶不震動（清音）；/ʒ/ 聲帶持續震動（濁音）",
      wordA: { word: "chou", ipa: "/ʃu/", meaningZh: "包心菜" },
      wordB: { word: "joue", ipa: "/ʒu/", meaningZh: "臉頰" },
    }],
    practiceWords: ["chat", "chien", "chocolat"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "ʒ", category: "子音", ipa: "/ʒ/", exampleWord: "je", exampleIpa: "/ʒə/", meaningZh: "我",
    shortDescription: "嘴唇向前突出收圓，跟 /ʃ/ 相同但聲帶要震動",
    mouthPosition: "嘴唇向前突出收圓，跟 /ʃ/ 相同",
    tonguePosition: "舌面抬高靠近硬顎前部，跟 /ʃ/ 相同位置",
    airflow: "氣流持續從舌面與硬顎的縫隙摩擦而出",
    vocalCord: "聲帶持續震動（濁音），這是跟 /ʃ/ 唯一的差別",
    pronunciationSteps: DEFAULT_STEPS("/ʒ/"),
    commonSpellings: [
      { spelling: "j", examples: [{ word: "je", ipa: "/ʒə/", meaningZh: "我" }] },
      { spelling: "g（+e,i）", examples: [{ word: "rouge", ipa: "/ʁuʒ/", meaningZh: "紅色" }] },
    ],
    wordExamples: [
      { word: "je", ipa: "/ʒə/", meaningZh: "我", highlight: "j" },
      { word: "rouge", ipa: "/ʁuʒ/", meaningZh: "紅色", highlight: "g" },
      { word: "jour", ipa: "/ʒuʁ/", meaningZh: "日子", highlight: "j" },
    ],
    combinations: combo("ʒ"),
    comparisons: [{
      otherIpa: "/ʃ/",
      mouthDiff: "嘴型相同，嘴唇略向前突出成圓形",
      tongueDiff: "舌面都抬高靠近硬顎前部，留縫隙讓氣流摩擦，舌位相同",
      vocalDiff: "關鍵差異在聲帶：/ʒ/ 聲帶持續震動（濁音）；/ʃ/ 聲帶不震動（清音）",
      wordA: { word: "joue", ipa: "/ʒu/", meaningZh: "臉頰" },
      wordB: { word: "chou", ipa: "/ʃu/", meaningZh: "包心菜" },
    }],
    practiceWords: ["je", "rouge", "jour"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "m", category: "子音", ipa: "/m/", exampleWord: "maman", exampleIpa: "/mamɑ̃/", meaningZh: "媽媽",
    shortDescription: "雙唇閉合，氣流從鼻腔流出",
    mouthPosition: "雙唇閉合",
    tonguePosition: "舌頭放鬆，不參與阻塞",
    airflow: "氣流從鼻腔持續流出，口腔完全阻塞",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/m/"),
    commonSpellings: [{ spelling: "m", examples: [{ word: "maman", ipa: "/mamɑ̃/", meaningZh: "媽媽" }] }],
    wordExamples: [
      { word: "maman", ipa: "/mamɑ̃/", meaningZh: "媽媽", highlight: "m" },
      { word: "ami", ipa: "/ami/", meaningZh: "朋友", highlight: "m" },
      { word: "pomme", ipa: "/pɔm/", meaningZh: "蘋果", highlight: "m" },
    ],
    combinations: combo("m"),
    practiceWords: ["maman", "ami", "pomme"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "n", category: "子音", ipa: "/n/", exampleWord: "non", exampleIpa: "/nɔ̃/", meaningZh: "不",
    shortDescription: "舌尖抵住上齒齦，氣流從鼻腔流出",
    mouthPosition: "嘴巴微開",
    tonguePosition: "舌尖抵住上齒齦，形成阻塞",
    airflow: "氣流從鼻腔持續流出，口腔被舌尖阻塞",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/n/"),
    commonSpellings: [{ spelling: "n", examples: [{ word: "non", ipa: "/nɔ̃/", meaningZh: "不" }] }],
    wordExamples: [
      { word: "non", ipa: "/nɔ̃/", meaningZh: "不", highlight: "n" },
      { word: "nous", ipa: "/nu/", meaningZh: "我們", highlight: "n" },
      { word: "bonne", ipa: "/bɔn/", meaningZh: "好的（陰性）", highlight: "nn" },
    ],
    combinations: combo("n"),
    practiceWords: ["non", "nous", "bonne"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "ɲ", category: "子音", ipa: "/ɲ/", exampleWord: "montagne", exampleIpa: "/mɔ̃taɲ/", meaningZh: "山",
    shortDescription: "舌面（不是舌尖）貼住硬顎，氣流從鼻腔流出",
    mouthPosition: "嘴巴微開",
    tonguePosition: "舌面（不是舌尖）貼住硬顎",
    airflow: "氣流從鼻腔持續流出，口腔被舌面阻塞",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/ɲ/"),
    commonSpellings: [{ spelling: "gn", examples: [{ word: "montagne", ipa: "/mɔ̃taɲ/", meaningZh: "山" }] }],
    wordExamples: [
      { word: "montagne", ipa: "/mɔ̃taɲ/", meaningZh: "山", highlight: "gn" },
      { word: "agneau", ipa: "/aɲo/", meaningZh: "小羊", highlight: "gn" },
      { word: "espagnol", ipa: "/ɛspaɲɔl/", meaningZh: "西班牙語", highlight: "gn" },
    ],
    combinations: combo("ɲ"),
    practiceWords: ["montagne", "agneau", "espagnol"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "ŋ", category: "子音", ipa: "/ŋ/", exampleWord: "parking", exampleIpa: "/paʁkiŋ/", meaningZh: "停車場",
    shortDescription: "外來詞尾常見音，法語本身很少見，多出現在英語借詞",
    mouthPosition: "嘴巴微開",
    tonguePosition: "舌根頂住軟顎，形成阻塞",
    airflow: "氣流從鼻腔持續流出，口腔被舌根阻塞",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/ŋ/"),
    commonSpellings: [{ spelling: "ng（外來詞字尾）", examples: [{ word: "parking", ipa: "/paʁkiŋ/", meaningZh: "停車場" }] }],
    wordExamples: [
      { word: "parking", ipa: "/paʁkiŋ/", meaningZh: "停車場", highlight: "ng" },
      { word: "camping", ipa: "/kɑ̃piŋ/", meaningZh: "露營", highlight: "ng" },
      { word: "jogging", ipa: "/dʒɔɡiŋ/", meaningZh: "慢跑", highlight: "ng" },
    ],
    combinations: combo("ŋ"),
    practiceWords: ["parking", "camping", "jogging"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "l", category: "子音", ipa: "/l/", exampleWord: "lait", exampleIpa: "/lɛ/", meaningZh: "牛奶",
    shortDescription: "舌尖抵住上齒齦，氣流從舌頭兩側繞過",
    mouthPosition: "嘴巴微開",
    tonguePosition: "舌尖抵住上齒齦，氣流從舌頭兩側繞過",
    airflow: "氣流持續從舌頭兩側流出，口腔中央被阻塞",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/l/"),
    commonSpellings: [{ spelling: "l", examples: [{ word: "lait", ipa: "/lɛ/", meaningZh: "牛奶" }] }],
    wordExamples: [
      { word: "lait", ipa: "/lɛ/", meaningZh: "牛奶", highlight: "l" },
      { word: "ville", ipa: "/vil/", meaningZh: "城市", highlight: "ll" },
      { word: "animal", ipa: "/animal/", meaningZh: "動物", highlight: "l" },
    ],
    combinations: combo("l"),
    practiceWords: ["lait", "ville", "animal"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "ʁ", category: "子音", ipa: "/ʁ/", exampleWord: "rouge", exampleIpa: "/ʁuʒ/", meaningZh: "紅色",
    shortDescription: "舌根靠近小舌，氣流摩擦而出，帶有輕微振動感",
    mouthPosition: "嘴巴微開",
    tonguePosition: "舌根靠近軟顎／小舌，留一條窄縫",
    airflow: "氣流持續從舌根與小舌之間的縫隙摩擦而出，帶有輕微振動感",
    vocalCord: "聲帶持續震動（濁音）",
    pronunciationSteps: DEFAULT_STEPS("/ʁ/"),
    commonSpellings: [
      { spelling: "r", examples: [{ word: "rouge", ipa: "/ʁuʒ/", meaningZh: "紅色" }] },
      { spelling: "rr", examples: [{ word: "terre", ipa: "/tɛʁ/", meaningZh: "土地" }] },
    ],
    wordExamples: [
      { word: "rouge", ipa: "/ʁuʒ/", meaningZh: "紅色", highlight: "r" },
      { word: "Paris", ipa: "/paʁi/", meaningZh: "巴黎", highlight: "r" },
      { word: "bonjour", ipa: "/bɔ̃ʒuʁ/", meaningZh: "你好", highlight: "r" },
    ],
    combinations: combo("ʁ"),
    practiceWords: ["rouge", "Paris", "bonjour"], showPracticeSteps: true,
    audio: mkAudio(),
  },

  // ══════════════════════════ 特殊組合 ══════════════════════════
  {
    id: "silent-letters", category: "特殊組合", ipa: "（不發音）", exampleWord: "beaucoup", exampleIpa: "/boku/", meaningZh: "很多",
    shortDescription: "字尾的 e、s、t、d、x、p 等子音字母經常完全不發音",
    pronunciationSteps: [
      "先看清楚單字最後一個字母是什麼",
      "確認是否屬於常見不發音字母（e/s/t/d/x/p 等）",
      "把該字母直接跳過、不出聲",
      "只發前面確實會發音的部分",
      "跟示範音比較，確認結尾沒有多餘的聲音",
    ],
    commonSpellings: [
      { spelling: "字尾 s（複數）", examples: [{ word: "chats", ipa: "/ʃa/", meaningZh: "貓（複數）" }] },
      { spelling: "字尾 t", examples: [{ word: "petit", ipa: "/pəti/", meaningZh: "小的（陽性，字尾 t 不發音）" }] },
      { spelling: "字尾 e", examples: [{ word: "table", ipa: "/tabl/", meaningZh: "桌子" }] },
      { spelling: "字尾 x", examples: [{ word: "deux", ipa: "/dø/", meaningZh: "二" }] },
    ],
    wordExamples: [
      { word: "beaucoup", ipa: "/boku/", meaningZh: "很多", highlight: "p" },
      { word: "petit", ipa: "/pəti/", meaningZh: "小的", highlight: "t" },
      { word: "chats", ipa: "/ʃa/", meaningZh: "貓（複數）", highlight: "s" },
    ],
    practiceWords: ["beaucoup", "petit", "chats"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "final-consonants", category: "特殊組合", ipa: "（詞尾子音）", exampleWord: "sac", exampleIpa: "/sak/", meaningZh: "包包",
    shortDescription: "雖然大部分字尾子音不發音，但 c、r、f、l（口訣「CaReFuL」）通常要發音",
    pronunciationSteps: [
      "看單字最後一個字母",
      "確認是否是 c、r、f、l 其中之一",
      "如果是，就要清楚發出這個子音",
      "如果不是（如 s、t、d、x、e），通常跳過不發音",
      "用「CaReFuL」這個口訣快速判斷",
    ],
    commonSpellings: [
      { spelling: "字尾 c", examples: [{ word: "sac", ipa: "/sak/", meaningZh: "包包" }] },
      { spelling: "字尾 r", examples: [{ word: "pour", ipa: "/puʁ/", meaningZh: "為了" }] },
      { spelling: "字尾 f", examples: [{ word: "neuf", ipa: "/nœf/", meaningZh: "九" }] },
      { spelling: "字尾 l", examples: [{ word: "animal", ipa: "/animal/", meaningZh: "動物" }] },
    ],
    wordExamples: [
      { word: "sac", ipa: "/sak/", meaningZh: "包包", highlight: "c" },
      { word: "neuf", ipa: "/nœf/", meaningZh: "九", highlight: "f" },
      { word: "animal", ipa: "/animal/", meaningZh: "動物", highlight: "l" },
    ],
    practiceWords: ["sac", "neuf", "animal"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "h-muet", category: "特殊組合", ipa: "（h muet）", exampleWord: "habiter", exampleIpa: "/abite/", meaningZh: "居住",
    shortDescription: "h muet（啞音 h）完全不發音，前面的字可以縮寫、連音當作 h 不存在",
    pronunciationSteps: [
      "看到字首的 h，先確認它是啞音還是噓音",
      "啞音 h：直接當作這個字是母音開頭",
      "允許前面的冠詞縮寫，例如 le+habite → l'habite",
      "允許連音穿過 h，例如 les habits 要連音成 /le-z‿abi/",
      "整段唸起來要像 h 完全不存在一樣",
    ],
    commonSpellings: [
      { spelling: "h + 母音（啞音）", examples: [{ word: "habiter", ipa: "/abite/", meaningZh: "居住" }] },
    ],
    wordExamples: [
      { word: "habiter", ipa: "/abite/", meaningZh: "居住", highlight: "h" },
      { word: "heure", ipa: "/œʁ/", meaningZh: "小時", highlight: "h" },
      { word: "homme", ipa: "/ɔm/", meaningZh: "男人", highlight: "h" },
    ],
    practiceWords: ["habiter", "heure", "homme"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "h-aspire", category: "特殊組合", ipa: "（h aspiré）", exampleWord: "haricot", exampleIpa: "/aʁiko/", meaningZh: "四季豆",
    shortDescription: "h aspiré（噓音 h）本身也不發音，但會阻止前面的縮寫和連音",
    pronunciationSteps: [
      "看到字首的 h，先確認它是噓音 h（通常需要查字典標記）",
      "h 本身仍然不發出聲音",
      "但前面的冠詞不能縮寫，例如 le haricot 不能變成 l'haricot",
      "前後兩個字之間也不能連音，中間要有一個小停頓",
      "把 h aspiré 當成一道看不見的牆，阻止前後音連在一起",
    ],
    commonSpellings: [
      { spelling: "h + 母音（噓音）", examples: [{ word: "haricot", ipa: "/aʁiko/", meaningZh: "四季豆" }] },
    ],
    wordExamples: [
      { word: "haricot", ipa: "/aʁiko/", meaningZh: "四季豆", highlight: "h" },
      { word: "héros", ipa: "/eʁo/", meaningZh: "英雄", highlight: "h" },
      { word: "hibou", ipa: "/ibu/", meaningZh: "貓頭鷹", highlight: "h" },
    ],
    practiceWords: ["haricot", "héros", "hibou"], showPracticeSteps: true,
    audio: mkAudio(),
  },

  // ══════════════════════════ 重音與連音 ══════════════════════════
  {
    id: "liaison", category: "重音與連音", ipa: "（liaison）", exampleWord: "les amis", exampleIpa: "/le-z‿ami/", meaningZh: "朋友們",
    shortDescription: "前一個字尾本來不發音的子音，在下一個字是母音開頭時要連起來發音",
    pronunciationSteps: [
      "檢查前一個字字尾是不是平常不發音的子音（s、t、x、n 等）",
      "檢查下一個字是不是母音或啞音 h 開頭",
      "如果兩個條件都符合，就把字尾子音跟下一個字的母音連著唸",
      "s 在連音時通常唸成 /z/",
      "整句唸起來兩個字之間不留停頓，像變成一個字",
    ],
    commonSpellings: [
      { spelling: "s + 母音 → /z/", examples: [{ word: "les amis", ipa: "/le-z‿ami/", meaningZh: "朋友們" }] },
      { spelling: "t + 母音", examples: [{ word: "c'est important", ipa: "/sɛ-t‿ɛ̃pɔʁtɑ̃/", meaningZh: "這很重要" }] },
      { spelling: "n + 母音", examples: [{ word: "un ami", ipa: "/œ̃-n‿ami/", meaningZh: "一個朋友" }] },
    ],
    wordExamples: [
      { word: "les amis", ipa: "/le-z‿ami/", meaningZh: "朋友們", highlight: "s" },
      { word: "un ami", ipa: "/œ̃-n‿ami/", meaningZh: "一個朋友", highlight: "n" },
      { word: "c'est important", ipa: "/sɛ-t‿ɛ̃pɔʁtɑ̃/", meaningZh: "這很重要", highlight: "t" },
    ],
    practiceWords: ["les amis", "un ami"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "enchainement", category: "重音與連音", ipa: "（enchaînement）", exampleWord: "elle arrive", exampleIpa: "/ɛ.la.ʁiv/", meaningZh: "她到了",
    shortDescription: "前一個字尾本來就會發音的子音，自然滑向下一個母音開頭的字，中間不停頓",
    pronunciationSteps: [
      "找出前一個字字尾原本就會發音的子音",
      "確認下一個字是母音開頭",
      "把這個子音直接當作下一個字的開頭來唸",
      "兩個字之間不留任何停頓",
      "整句聽起來音節會重新分配，像連成一串",
    ],
    commonSpellings: [
      { spelling: "發音子音 + 母音", examples: [{ word: "elle arrive", ipa: "/ɛ.la.ʁiv/", meaningZh: "她到了" }] },
      { spelling: "發音子音 + 母音", examples: [{ word: "il habite", ipa: "/i.la.bit/", meaningZh: "他住" }] },
    ],
    wordExamples: [
      { word: "elle arrive", ipa: "/ɛ.la.ʁiv/", meaningZh: "她到了", highlight: "ll" },
      { word: "il habite", ipa: "/i.la.bit/", meaningZh: "他住", highlight: "l" },
      { word: "avec elle", ipa: "/a.vɛ.kɛl/", meaningZh: "跟她一起", highlight: "c" },
    ],
    practiceWords: ["elle arrive", "il habite"], showPracticeSteps: true,
    audio: mkAudio(),
  },
  {
    id: "stress-rhythm", category: "重音與連音", ipa: "（重音與節奏）", exampleWord: "je m'appelle Marie", exampleIpa: "/ʒə.ma.pɛl.ma.ʁi/", meaningZh: "我叫瑪麗",
    shortDescription: "法語重音不在單字上，而落在每個節奏群的最後一個音節，且每個音節長度接近",
    pronunciationSteps: [
      "先把整句話依照意義切成幾個小節奏群",
      "找出每個節奏群的最後一個音節",
      "只把最後一個音節唸得稍微長一點、重一點",
      "群內其他音節保持平均、不特別加重",
      "整句聽起來像一串長度平均、結尾略揚的音節",
    ],
    commonSpellings: [
      { spelling: "節奏群結尾音節加重", examples: [{ word: "je m'appelle Marie", ipa: "/ʒə.ma.pɛl.ma.ʁi/", meaningZh: "我叫瑪麗" }] },
    ],
    wordExamples: [
      { word: "je m'appelle Marie", ipa: "/ʒə.ma.pɛl.ma.ʁi/", meaningZh: "我叫瑪麗", highlight: "ri" },
      { word: "comment ça va", ipa: "/kɔ.mɑ̃.sa.va/", meaningZh: "你好嗎", highlight: "va" },
      { word: "au revoir", ipa: "/o.ʁə.vwaʁ/", meaningZh: "再見", highlight: "voir" },
    ],
    practiceWords: ["je m'appelle Marie", "comment ça va", "au revoir"], showPracticeSteps: true,
    audio: mkAudio(),
  },
];
