// ─────────────────────────────────────────────
//  IELTS Band 4.0 Data
// ─────────────────────────────────────────────

// ── Vocabulary ───────────────────────────────

export const VOCAB_TOPICS = [
  {
    id: "intro",
    title: "自我介紹",
    emoji: "👤",
    color: "#6366f1",
    words: [
      { id: "v-i01", word: "name", meaningZh: "名字", pos: "noun", example: "My name is Tom.", exampleZh: "我的名字是湯姆。", usage: "Part 1 第一題必考" },
      { id: "v-i02", word: "age", meaningZh: "年齡", pos: "noun", example: "I am twenty years old.", exampleZh: "我二十歲。", usage: "Part 1 個人資料" },
      { id: "v-i03", word: "nationality", meaningZh: "國籍", pos: "noun", example: "My nationality is Chinese.", exampleZh: "我的國籍是中國人。", usage: "Part 1 個人背景" },
      { id: "v-i04", word: "live", meaningZh: "居住", pos: "verb", example: "I live in Hong Kong.", exampleZh: "我住在香港。", usage: "Part 1 居住地點" },
      { id: "v-i05", word: "speak", meaningZh: "說（語言）", pos: "verb", example: "I speak English and Chinese.", exampleZh: "我說英文和中文。", usage: "Part 1 語言能力" },
      { id: "v-i06", word: "interested in", meaningZh: "對…感興趣", pos: "phrase", example: "I am interested in music.", exampleZh: "我對音樂感興趣。", usage: "Part 1 興趣愛好" },
      { id: "v-i07", word: "married", meaningZh: "已婚", pos: "adjective", example: "I am not married.", exampleZh: "我未婚。", usage: "Part 1 個人狀況" },
      { id: "v-i08", word: "originally", meaningZh: "原本、原來是", pos: "adverb", example: "I am originally from Guangzhou.", exampleZh: "我原本來自廣州。", usage: "Part 1 家鄉介紹" },
      { id: "v-i09", word: "describe", meaningZh: "描述", pos: "verb", example: "Can you describe yourself?", exampleZh: "你可以描述一下自己嗎？", usage: "考官常用指令" },
      { id: "v-i10", word: "hometown", meaningZh: "家鄉", pos: "noun", example: "My hometown is Beijing.", exampleZh: "我的家鄉是北京。", usage: "Part 1 高頻話題" },
    ],
  },
  {
    id: "family",
    title: "家庭與朋友",
    emoji: "👨‍👩‍👧",
    color: "#ec4899",
    words: [
      { id: "v-f01", word: "family", meaningZh: "家庭", pos: "noun", example: "I live with my family.", exampleZh: "我和家人一起住。", usage: "Part 1 高頻話題" },
      { id: "v-f02", word: "parents", meaningZh: "父母", pos: "noun", example: "My parents live in Guangzhou.", exampleZh: "我的父母住在廣州。", usage: "Part 1 家庭介紹" },
      { id: "v-f03", word: "sibling", meaningZh: "兄弟姐妹", pos: "noun", example: "I have one sibling, a sister.", exampleZh: "我有一個兄弟姐妹，是姐姐。", usage: "Part 1 家庭成員" },
      { id: "v-f04", word: "close", meaningZh: "親近的", pos: "adjective", example: "I am close to my mother.", exampleZh: "我和我媽媽很親近。", usage: "描述家庭關係" },
      { id: "v-f05", word: "support", meaningZh: "支持", pos: "verb", example: "My family supports me.", exampleZh: "我的家人支持我。", usage: "描述家庭關係" },
      { id: "v-f06", word: "spend time", meaningZh: "花時間", pos: "phrase", example: "I like to spend time with friends.", exampleZh: "我喜歡和朋友花時間。", usage: "Part 1 日常活動" },
      { id: "v-f07", word: "best friend", meaningZh: "最好的朋友", pos: "phrase", example: "My best friend is very kind.", exampleZh: "我最好的朋友非常友善。", usage: "Part 1 朋友話題" },
      { id: "v-f08", word: "trust", meaningZh: "信任", pos: "verb", example: "I trust my friends.", exampleZh: "我信任我的朋友。", usage: "描述友誼" },
      { id: "v-f09", word: "grow up", meaningZh: "成長", pos: "phrase", example: "I grew up in a small town.", exampleZh: "我在一個小鎮長大。", usage: "Part 1 童年話題" },
      { id: "v-f10", word: "together", meaningZh: "一起", pos: "adverb", example: "We eat together every evening.", exampleZh: "我們每天晚上一起吃飯。", usage: "描述日常習慣" },
    ],
  },
  {
    id: "study-work",
    title: "學校與工作",
    emoji: "🎓",
    color: "#0891b2",
    words: [
      { id: "v-s01", word: "student", meaningZh: "學生", pos: "noun", example: "I am a student at university.", exampleZh: "我是大學生。", usage: "Part 1 第一題" },
      { id: "v-s02", word: "study", meaningZh: "學習、讀書", pos: "verb", example: "I study English every day.", exampleZh: "我每天學英文。", usage: "Part 1 學習話題" },
      { id: "v-s03", word: "subject", meaningZh: "科目", pos: "noun", example: "My favourite subject is maths.", exampleZh: "我最喜歡的科目是數學。", usage: "Part 1 學校話題" },
      { id: "v-s04", word: "job", meaningZh: "工作", pos: "noun", example: "I have a part-time job.", exampleZh: "我有一份兼職工作。", usage: "Part 1 工作話題" },
      { id: "v-s05", word: "office", meaningZh: "辦公室", pos: "noun", example: "I work in an office.", exampleZh: "我在辦公室工作。", usage: "描述工作地點" },
      { id: "v-s06", word: "colleague", meaningZh: "同事", pos: "noun", example: "My colleagues are very friendly.", exampleZh: "我的同事非常友善。", usage: "Part 1 工作話題" },
      { id: "v-s07", word: "graduate", meaningZh: "畢業", pos: "verb", example: "I graduated last year.", exampleZh: "我去年畢業。", usage: "描述學歷" },
      { id: "v-s08", word: "major", meaningZh: "主修", pos: "noun", example: "My major is business.", exampleZh: "我主修商業。", usage: "Part 1 學習話題" },
      { id: "v-s09", word: "experience", meaningZh: "經驗", pos: "noun", example: "I have some work experience.", exampleZh: "我有一些工作經驗。", usage: "描述個人背景" },
      { id: "v-s10", word: "plan", meaningZh: "計劃", pos: "noun/verb", example: "I plan to find a job next year.", exampleZh: "我計劃明年找工作。", usage: "Part 1 未來計劃" },
    ],
  },
  {
    id: "daily",
    title: "日常生活",
    emoji: "🏠",
    color: "#059669",
    words: [
      { id: "v-d01", word: "routine", meaningZh: "日常習慣", pos: "noun", example: "My daily routine starts at 7 a.m.", exampleZh: "我的日常習慣從早上七點開始。", usage: "Part 1 日常話題" },
      { id: "v-d02", word: "wake up", meaningZh: "起床", pos: "phrase", example: "I wake up at 7 every morning.", exampleZh: "我每天早上七點起床。", usage: "描述日常習慣" },
      { id: "v-d03", word: "breakfast", meaningZh: "早餐", pos: "noun", example: "I have breakfast before work.", exampleZh: "我上班前吃早餐。", usage: "Part 1 飲食習慣" },
      { id: "v-d04", word: "usually", meaningZh: "通常", pos: "adverb", example: "I usually go to bed at 11 p.m.", exampleZh: "我通常晚上十一點睡覺。", usage: "描述習慣頻率" },
      { id: "v-d05", word: "sometimes", meaningZh: "有時候", pos: "adverb", example: "I sometimes cook at home.", exampleZh: "我有時候在家煮飯。", usage: "描述習慣頻率" },
      { id: "v-d06", word: "exercise", meaningZh: "運動", pos: "noun/verb", example: "I exercise three times a week.", exampleZh: "我每週運動三次。", usage: "Part 1 健康話題" },
      { id: "v-d07", word: "busy", meaningZh: "忙碌", pos: "adjective", example: "My weekdays are very busy.", exampleZh: "我的平日非常忙碌。", usage: "描述生活節奏" },
      { id: "v-d08", word: "relax", meaningZh: "放鬆", pos: "verb", example: "I relax by watching TV.", exampleZh: "我透過看電視放鬆。", usage: "Part 1 休閒話題" },
      { id: "v-d09", word: "shopping", meaningZh: "購物", pos: "noun", example: "I go shopping on weekends.", exampleZh: "我週末去購物。", usage: "Part 1 休閒話題" },
      { id: "v-d10", word: "free time", meaningZh: "空閒時間", pos: "phrase", example: "In my free time, I read books.", exampleZh: "在空閒時間，我讀書。", usage: "Part 1 興趣話題" },
    ],
  },
  {
    id: "food",
    title: "食物與餐廳",
    emoji: "🍜",
    color: "#d97706",
    words: [
      { id: "v-fo01", word: "meal", meaningZh: "餐、一頓飯", pos: "noun", example: "I have three meals a day.", exampleZh: "我每天吃三頓飯。", usage: "Part 1 飲食話題" },
      { id: "v-fo02", word: "delicious", meaningZh: "美味", pos: "adjective", example: "The food here is delicious.", exampleZh: "這裡的食物很美味。", usage: "描述食物" },
      { id: "v-fo03", word: "favourite", meaningZh: "最喜歡的", pos: "adjective", example: "My favourite food is noodles.", exampleZh: "我最喜歡的食物是麵條。", usage: "Part 1 飲食話題" },
      { id: "v-fo04", word: "restaurant", meaningZh: "餐廳", pos: "noun", example: "I often eat at a restaurant.", exampleZh: "我經常在餐廳吃飯。", usage: "Part 1 飲食話題" },
      { id: "v-fo05", word: "cook", meaningZh: "煮、烹飪", pos: "verb", example: "I cook dinner for my family.", exampleZh: "我為家人煮晚飯。", usage: "Part 1 日常習慣" },
      { id: "v-fo06", word: "healthy", meaningZh: "健康的", pos: "adjective", example: "I try to eat healthy food.", exampleZh: "我嘗試吃健康食物。", usage: "Part 1 健康話題" },
      { id: "v-fo07", word: "vegetable", meaningZh: "蔬菜", pos: "noun", example: "I eat vegetables every day.", exampleZh: "我每天吃蔬菜。", usage: "描述飲食習慣" },
      { id: "v-fo08", word: "order", meaningZh: "點菜、訂購", pos: "verb", example: "I ordered a bowl of rice.", exampleZh: "我點了一碗飯。", usage: "餐廳場景" },
      { id: "v-fo09", word: "spicy", meaningZh: "辣的", pos: "adjective", example: "I do not like spicy food.", exampleZh: "我不喜歡辣的食物。", usage: "描述口味偏好" },
      { id: "v-fo10", word: "taste", meaningZh: "味道、口感", pos: "noun/verb", example: "This soup tastes very good.", exampleZh: "這個湯味道很好。", usage: "描述食物" },
    ],
  },
  {
    id: "transport",
    title: "交通與地點",
    emoji: "🚌",
    color: "#7c3aed",
    words: [
      { id: "v-t01", word: "bus", meaningZh: "巴士", pos: "noun", example: "I take the bus to school.", exampleZh: "我坐巴士上學。", usage: "描述交通方式" },
      { id: "v-t02", word: "station", meaningZh: "車站", pos: "noun", example: "The train station is nearby.", exampleZh: "火車站在附近。", usage: "聽力 Section 2" },
      { id: "v-t03", word: "near", meaningZh: "附近", pos: "preposition", example: "The school is near my home.", exampleZh: "學校在我家附近。", usage: "描述地點" },
      { id: "v-t04", word: "far", meaningZh: "遠的", pos: "adjective", example: "My office is not far from home.", exampleZh: "我的辦公室離家不遠。", usage: "描述距離" },
      { id: "v-t05", word: "on foot", meaningZh: "步行", pos: "phrase", example: "I go to school on foot.", exampleZh: "我步行上學。", usage: "描述交通方式" },
      { id: "v-t06", word: "map", meaningZh: "地圖", pos: "noun", example: "I use a map on my phone.", exampleZh: "我用手機上的地圖。", usage: "日常科技" },
      { id: "v-t07", word: "direction", meaningZh: "方向", pos: "noun", example: "Can you give me directions?", exampleZh: "你可以給我指路嗎？", usage: "聽力 Section 2" },
      { id: "v-t08", word: "left / right", meaningZh: "左 / 右", pos: "noun", example: "Turn left at the traffic light.", exampleZh: "在紅綠燈左轉。", usage: "聽力地圖題" },
      { id: "v-t09", word: "arrive", meaningZh: "到達", pos: "verb", example: "I arrive at school at 8 a.m.", exampleZh: "我早上八點到學校。", usage: "描述日常習慣" },
      { id: "v-t10", word: "traffic", meaningZh: "交通（情況）", pos: "noun", example: "The traffic is very busy at 8 a.m.", exampleZh: "早上八點交通非常繁忙。", usage: "Part 1 城市話題" },
    ],
  },
  {
    id: "weather",
    title: "天氣與季節",
    emoji: "☀️",
    color: "#f59e0b",
    words: [
      { id: "v-w01", word: "weather", meaningZh: "天氣", pos: "noun", example: "The weather today is very hot.", exampleZh: "今天天氣很熱。", usage: "Part 1 高頻話題" },
      { id: "v-w02", word: "sunny", meaningZh: "晴天的", pos: "adjective", example: "I like sunny days.", exampleZh: "我喜歡晴天。", usage: "描述天氣" },
      { id: "v-w03", word: "rainy", meaningZh: "下雨的", pos: "adjective", example: "It is rainy in spring here.", exampleZh: "這裡春天多雨。", usage: "描述氣候" },
      { id: "v-w04", word: "cold", meaningZh: "冷的", pos: "adjective", example: "Winter is very cold in my city.", exampleZh: "我的城市冬天很冷。", usage: "描述氣候" },
      { id: "v-w05", word: "hot", meaningZh: "熱的", pos: "adjective", example: "Summer is very hot here.", exampleZh: "這裡夏天很熱。", usage: "描述氣候" },
      { id: "v-w06", word: "season", meaningZh: "季節", pos: "noun", example: "My favourite season is autumn.", exampleZh: "我最喜歡的季節是秋天。", usage: "Part 1 天氣話題" },
      { id: "v-w07", word: "temperature", meaningZh: "溫度", pos: "noun", example: "The temperature is about 30 degrees.", exampleZh: "氣溫大約三十度。", usage: "描述天氣" },
      { id: "v-w08", word: "outdoor", meaningZh: "戶外的", pos: "adjective", example: "I like outdoor activities.", exampleZh: "我喜歡戶外活動。", usage: "Part 1 興趣話題" },
      { id: "v-w09", word: "climate", meaningZh: "氣候", pos: "noun", example: "The climate here is warm.", exampleZh: "這裡的氣候溫暖。", usage: "描述居住環境" },
      { id: "v-w10", word: "prefer", meaningZh: "比較喜歡", pos: "verb", example: "I prefer cold weather.", exampleZh: "我比較喜歡冷天。", usage: "Part 1 個人偏好" },
    ],
  },
  {
    id: "hobbies",
    title: "興趣與空閒",
    emoji: "🎮",
    color: "#10b981",
    words: [
      { id: "v-h01", word: "hobby", meaningZh: "興趣愛好", pos: "noun", example: "My hobby is reading books.", exampleZh: "我的興趣是讀書。", usage: "Part 1 高頻話題" },
      { id: "v-h02", word: "enjoy", meaningZh: "享受、喜歡做", pos: "verb", example: "I enjoy watching movies.", exampleZh: "我喜歡看電影。", usage: "Part 1 興趣話題" },
      { id: "v-h03", word: "music", meaningZh: "音樂", pos: "noun", example: "I listen to music every day.", exampleZh: "我每天聽音樂。", usage: "Part 1 高頻話題" },
      { id: "v-h04", word: "sport", meaningZh: "運動", pos: "noun", example: "My favourite sport is swimming.", exampleZh: "我最喜歡的運動是游泳。", usage: "Part 1 高頻話題" },
      { id: "v-h05", word: "travel", meaningZh: "旅遊", pos: "verb/noun", example: "I love to travel to new places.", exampleZh: "我喜歡到新地方旅遊。", usage: "Part 1 旅遊話題" },
      { id: "v-h06", word: "draw", meaningZh: "畫畫", pos: "verb", example: "I draw pictures in my free time.", exampleZh: "我在空閒時畫畫。", usage: "Part 1 藝術話題" },
      { id: "v-h07", word: "online", meaningZh: "網上的", pos: "adjective", example: "I play online games with friends.", exampleZh: "我和朋友玩網絡遊戲。", usage: "Part 1 科技話題" },
      { id: "v-h08", word: "calm", meaningZh: "平靜的", pos: "adjective", example: "Reading makes me feel calm.", exampleZh: "閱讀讓我感到平靜。", usage: "描述興趣原因" },
      { id: "v-h09", word: "creative", meaningZh: "有創意的", pos: "adjective", example: "I like creative activities.", exampleZh: "我喜歡有創意的活動。", usage: "描述個人特質" },
      { id: "v-h10", word: "weekends", meaningZh: "週末", pos: "noun", example: "I go hiking on weekends.", exampleZh: "我週末去遠足。", usage: "Part 1 日常話題" },
    ],
  },
];

// ── Listening ─────────────────────────────────

export const LISTENING_STAGES = [
  {
    id: "numbers",
    title: "數字與電話號碼",
    emoji: "📞",
    color: "#6366f1",
    tip: "聽電話號碼時，每個數字要分開聽，0 通常念 'oh' 或 'zero'。",
    keywords: ["number", "phone", "zero", "double"],
    items: [
      {
        id: "ls-n01",
        scenario: "電話號碼",
        transcript: "My phone number is 9 2 3 double 4 6 7.",
        transcriptZh: "我的電話號碼是 9 2 3 double 4 6 7。",
        question: "What is the phone number?",
        questionZh: "電話號碼是什麼？",
        options: ["923-4467", "923-4447", "923-4674", "932-4467"],
        answer: 1,
        explanationZh: "double 4 表示「兩個 4」，所以是 44。完整號碼是 923-4467。",
      },
      {
        id: "ls-n02",
        scenario: "房間號碼",
        transcript: "Please go to room three hundred and fifteen.",
        transcriptZh: "請到三百一十五號房間。",
        question: "What is the room number?",
        questionZh: "房間號碼是幾號？",
        options: ["215", "315", "350", "515"],
        answer: 1,
        explanationZh: "three hundred and fifteen = 315。hundred 是百，fifteen 是十五。",
      },
      {
        id: "ls-n03",
        scenario: "價格",
        transcript: "The total cost is forty-five dollars and fifty cents.",
        transcriptZh: "總費用是四十五元五角。",
        question: "How much does it cost?",
        questionZh: "費用是多少？",
        options: ["$45.15", "$45.50", "$54.50", "$40.55"],
        answer: 1,
        explanationZh: "forty-five = 45，fifty cents = 50 分，所以是 $45.50。",
      },
    ],
  },
  {
    id: "time",
    title: "時間與日期",
    emoji: "🕐",
    color: "#ec4899",
    tip: "am = 上午，pm = 下午。half past = 三十分，quarter past = 十五分，quarter to = 差十五分。",
    keywords: ["o'clock", "half past", "quarter", "morning", "afternoon"],
    items: [
      {
        id: "ls-t01",
        scenario: "預約時間",
        transcript: "Your appointment is at half past nine in the morning.",
        transcriptZh: "你的預約是早上九點半。",
        question: "What time is the appointment?",
        questionZh: "預約是幾點？",
        options: ["9:00 am", "9:15 am", "9:30 am", "9:45 am"],
        answer: 2,
        explanationZh: "half past nine = 九點三十分 = 9:30。half past 表示「⋯點半」。",
      },
      {
        id: "ls-t02",
        scenario: "開放時間",
        transcript: "The library opens at quarter past eight and closes at nine o'clock.",
        transcriptZh: "圖書館八點一刻開放，九點關閉。",
        question: "When does the library open?",
        questionZh: "圖書館幾點開放？",
        options: ["8:00", "8:15", "8:30", "8:45"],
        answer: 1,
        explanationZh: "quarter past eight = 八點一刻 = 8:15。quarter past 表示「⋯點十五分」。",
      },
      {
        id: "ls-t03",
        scenario: "會議日期",
        transcript: "The meeting is on the fifteenth of March.",
        transcriptZh: "會議在三月十五日。",
        question: "When is the meeting?",
        questionZh: "會議是哪天？",
        options: ["March 5", "March 13", "March 15", "March 50"],
        answer: 2,
        explanationZh: "fifteenth = 第十五，March = 三月，所以是 March 15（3月15日）。",
      },
    ],
  },
  {
    id: "location",
    title: "地點與方向",
    emoji: "🗺️",
    color: "#0891b2",
    tip: "聽方向時，注意 turn left / turn right / go straight / opposite / next to 等關鍵詞。",
    keywords: ["turn left", "turn right", "straight", "opposite", "next to", "near"],
    items: [
      {
        id: "ls-l01",
        scenario: "問路",
        transcript: "Go straight and then turn left at the traffic light. The post office is next to the bank.",
        transcriptZh: "直行，然後在紅綠燈左轉。郵局在銀行旁邊。",
        question: "Where is the post office?",
        questionZh: "郵局在哪裡？",
        options: ["Opposite the bank", "Next to the bank", "Behind the bank", "In front of the bank"],
        answer: 1,
        explanationZh: "next to = 在旁邊。The post office is next to the bank = 郵局在銀行旁邊。",
      },
      {
        id: "ls-l02",
        scenario: "校園地圖",
        transcript: "The cafeteria is on the second floor, opposite the library.",
        transcriptZh: "餐廳在二樓，圖書館對面。",
        question: "Where is the cafeteria?",
        questionZh: "餐廳在哪裡？",
        options: ["1st floor, next to library", "2nd floor, opposite library", "3rd floor, near library", "Ground floor"],
        answer: 1,
        explanationZh: "second floor = 二樓，opposite = 對面。餐廳在二樓、圖書館對面。",
      },
      {
        id: "ls-l03",
        scenario: "找停車場",
        transcript: "The car park is behind the shopping centre, near the exit.",
        transcriptZh: "停車場在購物中心後面，出口附近。",
        question: "Where is the car park?",
        questionZh: "停車場在哪裡？",
        options: ["In front of the shopping centre", "Inside the shopping centre", "Behind the shopping centre", "Next to the exit on the left"],
        answer: 2,
        explanationZh: "behind = 後面。The car park is behind the shopping centre = 停車場在購物中心後面。",
      },
    ],
  },
  {
    id: "objects",
    title: "日常物品",
    emoji: "🧳",
    color: "#059669",
    tip: "IELTS 聽力常考物品顏色、尺寸、數量。聽到描述時，先圈出關鍵特徵。",
    keywords: ["colour", "size", "large", "small", "number"],
    items: [
      {
        id: "ls-o01",
        scenario: "遺失物品",
        transcript: "I lost a bag. It is large and black with a red zip.",
        transcriptZh: "我遺失了一個袋。它是大的、黑色、有紅色拉鏈。",
        question: "What does the bag look like?",
        questionZh: "袋是什麼樣子的？",
        options: ["Small and red", "Large and blue with a zip", "Large and black with a red zip", "Small and black"],
        answer: 2,
        explanationZh: "large = 大的，black = 黑色，red zip = 紅色拉鏈。三個特徵全部吻合選項 C。",
      },
      {
        id: "ls-o02",
        scenario: "書店購物",
        transcript: "I would like to buy two notebooks and a blue pen, please.",
        transcriptZh: "我想買兩本筆記本和一支藍色筆。",
        question: "What does the customer want to buy?",
        questionZh: "顧客想買什麼？",
        options: ["One notebook and a red pen", "Two notebooks and a blue pen", "Three notebooks and a pen", "Two pens and a notebook"],
        answer: 1,
        explanationZh: "two notebooks = 兩本筆記本，a blue pen = 一支藍色筆。",
      },
      {
        id: "ls-o03",
        scenario: "行李重量",
        transcript: "Your bag is twenty-three kilograms. The limit is twenty.",
        transcriptZh: "你的袋是二十三公斤。上限是二十公斤。",
        question: "How much does the bag weigh?",
        questionZh: "袋重多少？",
        options: ["20 kg", "22 kg", "23 kg", "30 kg"],
        answer: 2,
        explanationZh: "twenty-three kilograms = 23 公斤。limit 是上限，袋超出了 3 公斤。",
      },
    ],
  },
  {
    id: "personal-info",
    title: "簡單人物資料",
    emoji: "📋",
    color: "#d97706",
    tip: "IELTS Section 1 常考填寫表格，注意拼寫姓名、地址、電話號碼。",
    keywords: ["surname", "first name", "address", "postcode", "nationality"],
    items: [
      {
        id: "ls-p01",
        scenario: "圖書館登記",
        transcript: "My surname is Chen, C-H-E-N. My first name is Lisa.",
        transcriptZh: "我的姓是 Chen，C-H-E-N。我的名是 Lisa。",
        question: "What is the person's full name?",
        questionZh: "這個人的全名是什麼？",
        options: ["Lisa Wang", "Lisa Chen", "Chen Lisa Wang", "Chris Chen"],
        answer: 1,
        explanationZh: "surname = 姓，first name = 名。C-H-E-N = Chen，所以是 Lisa Chen。",
      },
      {
        id: "ls-p02",
        scenario: "課程報名",
        transcript: "I am twenty-two years old and I am from Vietnam.",
        transcriptZh: "我二十二歲，來自越南。",
        question: "Where is this person from?",
        questionZh: "這個人來自哪裡？",
        options: ["China", "Korea", "Vietnam", "Thailand"],
        answer: 2,
        explanationZh: "from Vietnam = 來自越南。twenty-two = 22 歲（這是年齡，不是地點）。",
      },
      {
        id: "ls-p03",
        scenario: "酒店入住",
        transcript: "I booked a single room for three nights, from the 5th to the 8th.",
        transcriptZh: "我預訂了單人房三晚，從五號到八號。",
        question: "How many nights is the booking?",
        questionZh: "預訂了多少晚？",
        options: ["2", "3", "4", "5"],
        answer: 1,
        explanationZh: "three nights = 三晚。5th to 8th = 5、6、7 號共三晚（8號退房）。",
      },
    ],
  },
  {
    id: "dialogue",
    title: "簡短日常對話",
    emoji: "💬",
    color: "#7c3aed",
    tip: "聽對話時，先看問題和選項，知道要聽什麼，再聽音頻。",
    keywords: ["would like", "could you", "I think", "actually", "sorry"],
    items: [
      {
        id: "ls-d01",
        scenario: "餐廳訂位",
        transcript: "Hello, I would like to book a table for two people at 7 p.m.",
        transcriptZh: "你好，我想預訂一張兩位的桌子，晚上七點。",
        question: "How many people is the reservation for?",
        questionZh: "預訂幾人位？",
        options: ["One", "Two", "Three", "Four"],
        answer: 1,
        explanationZh: "for two people = 兩個人。a table for two = 兩人桌。",
      },
      {
        id: "ls-d02",
        scenario: "問候對話",
        transcript: "A: How are you today? B: I'm fine, thanks. A bit tired actually.",
        transcriptZh: "A：你今天好嗎？B：我很好，謝謝。其實有點累。",
        question: "How does Person B feel?",
        questionZh: "B 感覺如何？",
        options: ["Very happy", "Sick", "Fine but a bit tired", "Angry"],
        answer: 2,
        explanationZh: "fine = 好，a bit tired = 有點累。actually 表示「其實」，表明補充資訊。",
      },
      {
        id: "ls-d03",
        scenario: "問路對話",
        transcript: "A: Excuse me, is there a supermarket near here? B: Yes, there is one on Green Street, about five minutes' walk.",
        transcriptZh: "A：不好意思，附近有超市嗎？B：有，Green Street 有一間，走路大約五分鐘。",
        question: "How far is the supermarket?",
        questionZh: "超市有多遠？",
        options: ["2 minutes' walk", "5 minutes' walk", "10 minutes' walk", "By bus"],
        answer: 1,
        explanationZh: "five minutes' walk = 步行五分鐘。about = 大約，表示不是精確數字。",
      },
    ],
  },
];

// ── Speaking ──────────────────────────────────

export const SPEAKING_TOPICS = [
  {
    id: "sp-name",
    topic: "Name",
    emoji: "👤",
    color: "#6366f1",
    question: "What is your name? / Can you tell me your name?",
    questionZh: "你的名字是什麼？",
    band4Answer: "My name is Tom. People call me Tom.",
    betterAnswer: "My name is Tom, and most people just call me Tom. It is a common name in my family.",
    breakdownZh: [
      { en: "My name is Tom.", zh: "我的名字是湯姆。" },
      { en: "People call me Tom.", zh: "人們叫我湯姆。" },
      { en: "It is a common name.", zh: "這是一個常見的名字。" },
    ],
    template: "My name is _____. People / My friends call me _____.",
    practiceTask: "用你自己的名字回答：My name is _____ . People call me _____ .",
    teacherTipZh: "IELTS 口說第一題幾乎必問名字。回答要清楚，不需要太長。說完名字後，可以加一句補充，例如說別人怎麼稱呼你，自然加長答案。",
  },
  {
    id: "sp-hometown",
    topic: "Hometown",
    emoji: "🏙️",
    color: "#ec4899",
    question: "Where are you from? / Tell me about your hometown.",
    questionZh: "你來自哪裡？請告訴我你的家鄉。",
    band4Answer: "I am from Hong Kong. It is a big city.",
    betterAnswer: "I am from Hong Kong, which is a big and busy city in southern China. It is famous for its food and shopping.",
    breakdownZh: [
      { en: "I am from Hong Kong.", zh: "我來自香港。" },
      { en: "which is a big city", zh: "那是一個大城市" },
      { en: "It is famous for...", zh: "它以⋯出名。" },
    ],
    template: "I am from _____. It is a _____ city / town. It is famous for _____.",
    practiceTask: "介紹你的家鄉：I am from _____ . It is a _____ place. It is famous for _____ .",
    teacherTipZh: "介紹家鄉時，先說地點，再加一個形容詞（大城市、安靜小鎮），最後說它著名的東西（食物、景點）。三個步驟就夠了。",
  },
  {
    id: "sp-work-study",
    topic: "Work or Study",
    emoji: "🎓",
    color: "#0891b2",
    question: "Do you work or study? / What do you do?",
    questionZh: "你是上班還是讀書？",
    band4Answer: "I am a student. I study English at university.",
    betterAnswer: "I am a student at university, and I am studying Business. I chose this subject because I am interested in management.",
    breakdownZh: [
      { en: "I am a student.", zh: "我是學生。" },
      { en: "I study / I am studying...", zh: "我讀的是⋯" },
      { en: "I chose this because...", zh: "我選擇這個因為⋯" },
    ],
    template: "I am a _____. I study / work at _____. I chose this because _____.",
    practiceTask: "用你自己的情況回答：I am a _____ . I study / work at _____ . I chose this because _____ .",
    teacherTipZh: "這是 Part 1 必考問題。先說你是學生還是上班族，再說讀什麼 / 做什麼，最後加一個理由。理由用 because 連接，容易獲得更高分。",
  },
  {
    id: "sp-family",
    topic: "Family",
    emoji: "👨‍👩‍👧",
    color: "#d97706",
    question: "Tell me about your family. / Do you have a big family?",
    questionZh: "告訴我你的家庭。你家人多嗎？",
    band4Answer: "I have a small family. There are four people in my family.",
    betterAnswer: "I have a small family of four — my parents, my sister, and me. We are very close and we usually eat dinner together.",
    breakdownZh: [
      { en: "There are _____ people in my family.", zh: "我家有＿人。" },
      { en: "We are very close.", zh: "我們非常親近。" },
      { en: "We usually...", zh: "我們通常⋯" },
    ],
    template: "I have a _____ family. There are _____ people — _____. We usually _____.",
    practiceTask: "描述你的家庭：There are _____ people in my family. We usually _____ together.",
    teacherTipZh: "介紹家庭時，先說家庭大小（big/small），再列家庭成員，最後說一個一起做的事情。close 是很自然的形容詞，表示關係親密。",
  },
  {
    id: "sp-routine",
    topic: "Daily Routine",
    emoji: "⏰",
    color: "#059669",
    question: "What do you usually do in the morning? / Describe your daily routine.",
    questionZh: "你早上通常做什麼？描述你的日常習慣。",
    band4Answer: "I wake up at 7. I have breakfast. Then I go to school.",
    betterAnswer: "I usually wake up at 7 o'clock and have a simple breakfast. After that, I take the bus to school. In the evening, I study or watch videos to relax.",
    breakdownZh: [
      { en: "I usually wake up at...", zh: "我通常⋯點起床。" },
      { en: "After that,", zh: "之後，" },
      { en: "In the evening, I...", zh: "晚上我⋯" },
    ],
    template: "I usually wake up at _____. After that, I _____. In the evening, I _____.",
    practiceTask: "描述你的一天：I wake up at _____ . Then I _____ . In the evening, I _____ .",
    teacherTipZh: "描述日常習慣，最重要的連接詞是 after that（之後）、then（然後）、in the evening（晚上）。把幾件事用這些詞串連起來，答案就自然而完整。",
  },
  {
    id: "sp-hobbies",
    topic: "Hobbies",
    emoji: "🎮",
    color: "#7c3aed",
    question: "What do you like to do in your free time? / Do you have any hobbies?",
    questionZh: "你空閒時間喜歡做什麼？你有什麼興趣？",
    band4Answer: "I like watching movies. I also play games.",
    betterAnswer: "In my free time, I enjoy watching movies, especially action films. I also like playing online games because it helps me relax after a busy day.",
    breakdownZh: [
      { en: "In my free time, I enjoy...", zh: "在空閒時間，我喜歡⋯" },
      { en: "I also like...", zh: "我也喜歡⋯" },
      { en: "because it helps me relax", zh: "因為它幫助我放鬆" },
    ],
    template: "In my free time, I enjoy _____. I also like _____ because _____.",
    practiceTask: "說說你的興趣：In my free time, I enjoy _____ . I also like _____ because _____ .",
    teacherTipZh: "興趣話題一定要加 because 解釋原因，這是 Band 4 和 Band 5 的差別。最常用的原因：because it helps me relax / because it is interesting / because it is fun。",
  },
  {
    id: "sp-food",
    topic: "Food",
    emoji: "🍜",
    color: "#f59e0b",
    question: "What is your favourite food? / Do you like cooking?",
    questionZh: "你最喜歡的食物是什麼？你喜歡煮飯嗎？",
    band4Answer: "My favourite food is rice. I eat rice every day.",
    betterAnswer: "My favourite food is rice noodles. I love them because they are delicious and easy to prepare. I usually have them for lunch.",
    breakdownZh: [
      { en: "My favourite food is...", zh: "我最喜歡的食物是⋯" },
      { en: "I love them because...", zh: "我喜歡它因為⋯" },
      { en: "I usually have them for...", zh: "我通常在⋯吃它。" },
    ],
    template: "My favourite food is _____. I love it / them because _____. I usually eat it for _____.",
    practiceTask: "介紹你的最愛食物：My favourite food is _____ . I love it because _____ . I usually eat it for _____ .",
    teacherTipZh: "食物話題很容易發揮。先說食物名稱，再說為什麼喜歡（口味、方便、健康），最後說什麼時候吃。記住 delicious 是最常用的形容詞。",
  },
  {
    id: "sp-weather",
    topic: "Weather",
    emoji: "☀️",
    color: "#10b981",
    question: "What is the weather like in your country? / What is your favourite season?",
    questionZh: "你的國家天氣怎樣？你最喜歡什麼季節？",
    band4Answer: "The weather is hot in summer. I like autumn best.",
    betterAnswer: "In my city, summer is very hot and humid, but autumn is cool and comfortable. I prefer autumn because I can go outdoors more easily.",
    breakdownZh: [
      { en: "Summer is very hot.", zh: "夏天非常熱。" },
      { en: "I prefer... because...", zh: "我比較喜歡⋯因為⋯" },
      { en: "I can go outdoors more easily.", zh: "我可以更容易地去戶外。" },
    ],
    template: "In my city, summer is _____ but _____ is _____. I prefer _____ because _____.",
    practiceTask: "描述你的城市天氣和你最愛的季節：In my city, _____ is _____ . I prefer _____ because _____ .",
    teacherTipZh: "天氣話題用 prefer 比 like 更自然，because 之後說可以做的活動。humid = 潮濕，comfortable = 舒適，這兩個詞在天氣話題很好用。",
  },
];

// ── Speaking Templates ────────────────────────

export const SPEAKING_TEMPLATES = [
  {
    id: "t-who",
    category: "我是誰",
    emoji: "👤",
    color: "#6366f1",
    templates: [
      { en: "I am a student.", zh: "我是學生。" },
      { en: "I am a worker / office worker.", zh: "我是上班族。" },
      { en: "I am from Hong Kong.", zh: "我來自香港。" },
      { en: "I am twenty-two years old.", zh: "我二十二歲。" },
    ],
  },
  {
    id: "t-like",
    category: "我喜歡什麼",
    emoji: "❤️",
    color: "#ec4899",
    templates: [
      { en: "I like music.", zh: "我喜歡音樂。" },
      { en: "I like watching movies.", zh: "我喜歡看電影。" },
      { en: "I enjoy learning English.", zh: "我喜歡學英文。" },
      { en: "My favourite food is noodles.", zh: "我最喜歡的食物是麵條。" },
    ],
  },
  {
    id: "t-usually",
    category: "我經常做什麼",
    emoji: "🔄",
    color: "#059669",
    templates: [
      { en: "I usually study at home.", zh: "我通常在家學習。" },
      { en: "I often watch videos online.", zh: "我經常在網上看影片。" },
      { en: "I sometimes go shopping.", zh: "我有時候去購物。" },
      { en: "I rarely eat fast food.", zh: "我很少吃快餐。" },
    ],
  },
  {
    id: "t-because",
    category: "給原因",
    emoji: "💡",
    color: "#d97706",
    templates: [
      { en: "...because it is interesting.", zh: "⋯因為它很有趣。" },
      { en: "...because it is useful.", zh: "⋯因為它很有用。" },
      { en: "...because it helps me relax.", zh: "⋯因為它幫助我放鬆。" },
      { en: "...because I enjoy it a lot.", zh: "⋯因為我非常喜歡它。" },
    ],
  },
  {
    id: "t-extend",
    category: "簡單延伸",
    emoji: "📎",
    color: "#7c3aed",
    templates: [
      { en: "For example, I usually watch English videos.", zh: "例如，我通常看英文影片。" },
      { en: "Also, I like learning new words.", zh: "另外，我喜歡學新單字。" },
      { en: "In addition, I practice every day.", zh: "此外，我每天練習。" },
      { en: "However, I do not have much time.", zh: "但是，我沒有很多時間。" },
    ],
  },
];
