// Spanish A1 Listening Practice Data — 10 topics × 10 exercises = 100 exercises
// Question types: multiple-choice | fill-blank | true-false | sort

export const listeningTopics = [
  { id: "greetings",  title: "打招呼與自我介紹", emoji: "👋", color: "#6366f1" },
  { id: "identity",   title: "國籍、職業、年齡",  emoji: "🌍", color: "#8b5cf6" },
  { id: "family",     title: "家庭與人物描述",    emoji: "👨‍👩‍👧", color: "#ec4899" },
  { id: "time",       title: "數字、時間、日期",  emoji: "🕐", color: "#f59e0b" },
  { id: "daily",      title: "日常生活",          emoji: "☀️", color: "#10b981" },
  { id: "food",       title: "食物與餐廳",        emoji: "☕", color: "#ef4444" },
  { id: "shopping",   title: "購物與價格",        emoji: "🛍️", color: "#06b6d4" },
  { id: "directions", title: "方向與交通",        emoji: "🗺️", color: "#84cc16" },
  { id: "leisure",    title: "旅行與週末",        emoji: "⚽", color: "#f97316" },
  { id: "health",     title: "身體與健康",        emoji: "💊", color: "#14b8a6" },
];

export const listeningExercises = [

  // ══════════════════════════════════════════
  // TOPIC 1: 打招呼與自我介紹
  // ══════════════════════════════════════════
  {
    id: "lg-001", topicId: "greetings", title: "第一次見面", level: "A1-1",
    scene: "Ana 在學校第一次遇到 Carlos，互相打招呼。",
    audioText: "Hola, me llamo Ana. ¿Cómo te llamas?",
    transcript: "Hola, me llamo Ana. ¿Cómo te llamas?",
    zh: "你好，我叫 Ana。你叫什麼名字？",
    questions: [
      { id: "q1", type: "multiple-choice", question: "她叫什麼名字？", options: ["Ana", "Carlos", "María"], answer: "Ana" },
      { id: "q2", type: "fill-blank", sentence: "Hola, me ____ Ana.", answer: "llamo" },
      { id: "q3", type: "true-false", statement: "她問對方叫什麼名字。", answer: true },
    ],
    relatedWords: ["hola", "llamo", "llamas"],
  },
  {
    id: "lg-002", topicId: "greetings", title: "早安問候", level: "A1-1",
    scene: "Carlos 早上在公司大廳自我介紹。",
    audioText: "Buenos días. Yo me llamo Carlos. Mucho gusto.",
    transcript: "Buenos días. Yo me llamo Carlos. Mucho gusto.",
    zh: "早安。我叫 Carlos。很高興認識你。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "這是什麼時候的問候？", options: ["早上", "下午", "晚上"], answer: "早上" },
      { id: "q2", type: "true-false", statement: "他叫 Carlos。", answer: true },
      { id: "q3", type: "fill-blank", sentence: "Buenos ____.", answer: "días" },
    ],
    relatedWords: ["buenos", "días", "mucho", "gusto"],
  },
  {
    id: "lg-003", topicId: "greetings", title: "下午問候", level: "A1-1",
    scene: "María 下午在街上遇到鄰居打招呼。",
    audioText: "Buenas tardes. Me llamo María. ¿Y tú, cómo te llamas?",
    transcript: "Buenas tardes. Me llamo María. ¿Y tú, cómo te llamas?",
    zh: "下午好。我叫 María。你呢，你叫什麼名字？",
    questions: [
      { id: "q1", type: "multiple-choice", question: "她叫什麼名字？", options: ["María", "Ana", "Sofía"], answer: "María" },
      { id: "q2", type: "true-false", statement: "這是早上的問候語。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Buenas ____.", answer: "tardes" },
    ],
    relatedWords: ["buenas", "tardes", "llamas"],
  },
  {
    id: "lg-004", topicId: "greetings", title: "問候與回應", level: "A1-1",
    scene: "兩個朋友在路上偶遇互問近況。",
    audioText: "¡Hola! ¿Qué tal? Bien, gracias. ¿Y tú?",
    transcript: "¡Hola! ¿Qué tal? Bien, gracias. ¿Y tú?",
    zh: "你好！近來怎樣？很好，謝謝。你呢？",
    questions: [
      { id: "q1", type: "multiple-choice", question: "回答者感覺怎樣？", options: ["很好", "不好", "還可以"], answer: "很好" },
      { id: "q2", type: "true-false", statement: "對方沒有問回去。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "¿Qué ____?", answer: "tal" },
    ],
    relatedWords: ["hola", "tal", "bien", "gracias"],
  },
  {
    id: "lg-005", topicId: "greetings", title: "自我介紹", level: "A1-1",
    scene: "Pedro 在新班級自我介紹。",
    audioText: "Mucho gusto. Me llamo Pedro. Soy estudiante.",
    transcript: "Mucho gusto. Me llamo Pedro. Soy estudiante.",
    zh: "很高興認識你。我叫 Pedro。我是學生。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "Pedro 的身份是？", options: ["學生", "老師", "醫生"], answer: "學生" },
      { id: "q2", type: "true-false", statement: "Pedro 叫 Juan。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Mucho ____.", answer: "gusto" },
    ],
    relatedWords: ["mucho", "gusto", "llamo", "estudiante"],
  },
  {
    id: "lg-006", topicId: "greetings", title: "道別語", level: "A1-2",
    scene: "下班後同事互相道別。",
    audioText: "Adiós. Hasta luego. Hasta mañana.",
    transcript: "Adiós. Hasta luego. Hasta mañana.",
    zh: "再見。待會見。明天見。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "這些是什麼類型的用語？", options: ["道別語", "問候語", "感謝語"], answer: "道別語" },
      { id: "q2", type: "true-false", statement: "Hasta mañana 的意思是明天見。", answer: true },
      { id: "q3", type: "fill-blank", sentence: "Hasta ____.", answer: "luego" },
    ],
    relatedWords: ["adiós", "hasta", "luego", "mañana"],
  },
  {
    id: "lg-007", topicId: "greetings", title: "初次見面", level: "A1-2",
    scene: "Sofía 在派對上認識新朋友。",
    audioText: "Hola, ¿cómo te llamas? Me llamo Sofía. ¡Encantada!",
    transcript: "Hola, ¿cómo te llamas? Me llamo Sofía. ¡Encantada!",
    zh: "你好，你叫什麼名字？我叫 Sofía。很高興認識你！",
    questions: [
      { id: "q1", type: "multiple-choice", question: "她叫什麼名字？", options: ["Sofía", "Lucía", "Elena"], answer: "Sofía" },
      { id: "q2", type: "true-false", statement: "Encantada 表示很高興認識對方。", answer: true },
      { id: "q3", type: "sort", instruction: "把句子排成正確順序", words: ["llamo", "Me", "Sofía."], answer: ["Me", "llamo", "Sofía."] },
    ],
    relatedWords: ["encantada", "llamas", "llamo"],
  },
  {
    id: "lg-008", topicId: "greetings", title: "正式問候", level: "A1-2",
    scene: "學生向老師正式問好。",
    audioText: "Buenos días, señor. ¿Cómo está usted? Muy bien, gracias.",
    transcript: "Buenos días, señor. ¿Cómo está usted? Muy bien, gracias.",
    zh: "先生，早安。您好嗎？很好，謝謝。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "這是對誰說話？", options: ["長輩或陌生人", "好朋友", "小孩"], answer: "長輩或陌生人" },
      { id: "q2", type: "true-false", statement: "他回答「很好」。", answer: true },
      { id: "q3", type: "fill-blank", sentence: "¿Cómo ____ usted?", answer: "está" },
    ],
    relatedWords: ["señor", "usted", "está", "muy"],
  },
  {
    id: "lg-009", topicId: "greetings", title: "介紹來自哪裡", level: "A1-2",
    scene: "Juan 在語言交換活動介紹自己。",
    audioText: "Hola, yo soy Juan. Soy de España. ¿Y tú?",
    transcript: "Hola, yo soy Juan. Soy de España. ¿Y tú?",
    zh: "你好，我是 Juan。我來自西班牙。你呢？",
    questions: [
      { id: "q1", type: "multiple-choice", question: "Juan 來自哪裡？", options: ["西班牙", "墨西哥", "阿根廷"], answer: "西班牙" },
      { id: "q2", type: "true-false", statement: "Juan 問對方從哪裡來。", answer: true },
      { id: "q3", type: "fill-blank", sentence: "Soy de ____.", answer: "España" },
    ],
    relatedWords: ["soy", "España", "de"],
  },
  {
    id: "lg-010", topicId: "greetings", title: "晚安道別", level: "A1-3",
    scene: "晚上朋友聚餐結束後道別。",
    audioText: "Buenas noches. Hasta mañana. Que descanses.",
    transcript: "Buenas noches. Hasta mañana. Que descanses.",
    zh: "晚安。明天見。好好休息。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "這是什麼時候說的話？", options: ["晚上", "早上", "中午"], answer: "晚上" },
      { id: "q2", type: "true-false", statement: "Que descanses 意思是好好休息。", answer: true },
      { id: "q3", type: "fill-blank", sentence: "Buenas ____.", answer: "noches" },
    ],
    relatedWords: ["noches", "descanses", "hasta"],
  },

  // ══════════════════════════════════════════
  // TOPIC 2: 國籍、職業、年齡
  // ══════════════════════════════════════════
  {
    id: "li-001", topicId: "identity", title: "我是西班牙人", level: "A1-1",
    scene: "男子向外國朋友介紹自己的國籍。",
    audioText: "Soy español. Soy de Madrid, la capital de España.",
    transcript: "Soy español. Soy de Madrid, la capital de España.",
    zh: "我是西班牙人。我來自西班牙首都馬德里。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他來自哪個城市？", options: ["馬德里", "巴塞隆納", "塞維亞"], answer: "馬德里" },
      { id: "q2", type: "true-false", statement: "馬德里是西班牙的首都。", answer: true },
      { id: "q3", type: "fill-blank", sentence: "Soy de ____, la capital de España.", answer: "Madrid" },
    ],
    relatedWords: ["español", "Madrid", "capital", "España"],
  },
  {
    id: "li-002", topicId: "identity", title: "她是醫生", level: "A1-1",
    scene: "介紹同事的職業。",
    audioText: "Ella es médica. Trabaja en un hospital grande.",
    transcript: "Ella es médica. Trabaja en un hospital grande.",
    zh: "她是醫生。她在一家大醫院工作。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "她的職業是什麼？", options: ["醫生", "護士", "老師"], answer: "醫生" },
      { id: "q2", type: "true-false", statement: "她在小醫院工作。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Ella es ____.", answer: "médica" },
    ],
    relatedWords: ["médica", "trabaja", "hospital"],
  },
  {
    id: "li-003", topicId: "identity", title: "你幾歲？", level: "A1-1",
    scene: "兩個年輕人互問年齡。",
    audioText: "Tengo veinte años. ¿Cuántos años tienes tú?",
    transcript: "Tengo veinte años. ¿Cuántos años tienes tú?",
    zh: "我二十歲。你幾歲？",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他幾歲？", options: ["20歲", "18歲", "25歲"], answer: "20歲" },
      { id: "q2", type: "true-false", statement: "他問對方幾歲。", answer: true },
      { id: "q3", type: "fill-blank", sentence: "Tengo ____ años.", answer: "veinte" },
    ],
    relatedWords: ["tengo", "veinte", "años", "cuántos"],
  },
  {
    id: "li-004", topicId: "identity", title: "來自中國", level: "A1-1",
    scene: "中國學生在西班牙自我介紹。",
    audioText: "Soy chino. Soy de Pekín. Estudio español aquí.",
    transcript: "Soy chino. Soy de Pekín. Estudio español aquí.",
    zh: "我是中國人。我來自北京。我在這裡學西班牙語。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他在學什麼？", options: ["西班牙語", "英語", "法語"], answer: "西班牙語" },
      { id: "q2", type: "true-false", statement: "他來自上海。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Soy de ____.", answer: "Pekín" },
    ],
    relatedWords: ["chino", "Pekín", "estudio", "español"],
  },
  {
    id: "li-005", topicId: "identity", title: "來自墨西哥", level: "A1-1",
    scene: "墨西哥人介紹自己的國籍。",
    audioText: "¿De dónde eres? Soy de México. Soy mexicano.",
    transcript: "¿De dónde eres? Soy de México. Soy mexicano.",
    zh: "你從哪裡來？我來自墨西哥。我是墨西哥人。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他來自哪裡？", options: ["墨西哥", "西班牙", "哥倫比亞"], answer: "墨西哥" },
      { id: "q2", type: "true-false", statement: "他是西班牙人。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Soy de ____.", answer: "México" },
    ],
    relatedWords: ["México", "mexicano", "dónde", "eres"],
  },
  {
    id: "li-006", topicId: "identity", title: "年輕的學生", level: "A1-2",
    scene: "介紹班上一位同學。",
    audioText: "Ella es estudiante. Tiene dieciocho años. Estudia inglés.",
    transcript: "Ella es estudiante. Tiene dieciocho años. Estudia inglés.",
    zh: "她是學生。她十八歲。她學英語。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "她幾歲？", options: ["18歲", "17歲", "20歲"], answer: "18歲" },
      { id: "q2", type: "true-false", statement: "她是老師。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Tiene ____ años.", answer: "dieciocho" },
    ],
    relatedWords: ["estudiante", "dieciocho", "inglés"],
  },
  {
    id: "li-007", topicId: "identity", title: "護士職業", level: "A1-2",
    scene: "護士介紹自己的工作。",
    audioText: "Soy enfermera. Trabajo en un hospital. Me gusta mi trabajo.",
    transcript: "Soy enfermera. Trabajo en un hospital. Me gusta mi trabajo.",
    zh: "我是護士。我在醫院工作。我喜歡我的工作。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "她的職業是什麼？", options: ["護士", "醫生", "藥劑師"], answer: "護士" },
      { id: "q2", type: "true-false", statement: "她不喜歡她的工作。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Trabajo en un ____.", answer: "hospital" },
    ],
    relatedWords: ["enfermera", "trabaja", "hospital", "gusta"],
  },
  {
    id: "li-008", topicId: "identity", title: "廚師", level: "A1-2",
    scene: "介紹在餐廳工作的朋友。",
    audioText: "Él es cocinero. Trabaja en un restaurante italiano.",
    transcript: "Él es cocinero. Trabaja en un restaurante italiano.",
    zh: "他是廚師。他在一家義大利餐廳工作。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他在哪種餐廳工作？", options: ["義大利", "西班牙", "法國"], answer: "義大利" },
      { id: "q2", type: "true-false", statement: "他是服務員。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Él es ____.", answer: "cocinero" },
    ],
    relatedWords: ["cocinero", "restaurante", "italiano"],
  },
  {
    id: "li-009", topicId: "identity", title: "老師幾歲", level: "A1-3",
    scene: "學生詢問老師的年齡。",
    audioText: "¿Cuántos años tiene ella? Tiene treinta años. Es profesora.",
    transcript: "¿Cuántos años tiene ella? Tiene treinta años. Es profesora.",
    zh: "她幾歲？她三十歲。她是老師。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "她幾歲？", options: ["30歲", "25歲", "35歲"], answer: "30歲" },
      { id: "q2", type: "true-false", statement: "她是學生。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Tiene ____ años.", answer: "treinta" },
    ],
    relatedWords: ["treinta", "años", "profesora"],
  },
  {
    id: "li-010", topicId: "identity", title: "建築師", level: "A1-3",
    scene: "在職業介紹會上自我介紹。",
    audioText: "Soy arquitecto. Soy de Buenos Aires, Argentina.",
    transcript: "Soy arquitecto. Soy de Buenos Aires, Argentina.",
    zh: "我是建築師。我來自阿根廷的布宜諾斯艾利斯。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他的職業是什麼？", options: ["建築師", "工程師", "律師"], answer: "建築師" },
      { id: "q2", type: "multiple-choice", question: "他來自哪個國家？", options: ["阿根廷", "智利", "烏拉圭"], answer: "阿根廷" },
      { id: "q3", type: "fill-blank", sentence: "Soy de Buenos Aires, ____.", answer: "Argentina" },
    ],
    relatedWords: ["arquitecto", "Argentina", "Buenos Aires"],
  },

  // ══════════════════════════════════════════
  // TOPIC 3: 家庭與人物描述
  // ══════════════════════════════════════════
  {
    id: "lf-001", topicId: "family", title: "兄弟姐妹", level: "A1-1",
    scene: "介紹自己的家庭成員。",
    audioText: "Tengo una hermana y un hermano. Mi hermana se llama Lucía.",
    transcript: "Tengo una hermana y un hermano. Mi hermana se llama Lucía.",
    zh: "我有一個姐妹和一個兄弟。我的姐妹叫 Lucía。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他的姐妹叫什麼名字？", options: ["Lucía", "Ana", "Carmen"], answer: "Lucía" },
      { id: "q2", type: "true-false", statement: "他只有兄弟，沒有姐妹。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Tengo una hermana y un ____.", answer: "hermano" },
    ],
    relatedWords: ["hermana", "hermano", "llama"],
  },
  {
    id: "lf-002", topicId: "family", title: "描述媽媽", level: "A1-1",
    scene: "描述媽媽的外表。",
    audioText: "Mi madre es alta y tiene el pelo largo y rubio.",
    transcript: "Mi madre es alta y tiene el pelo largo y rubio.",
    zh: "我媽媽個子高，有一頭長長的金髮。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "媽媽的頭髮是什麼顏色？", options: ["金色", "黑色", "棕色"], answer: "金色" },
      { id: "q2", type: "true-false", statement: "媽媽個子矮。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Mi madre es ____.", answer: "alta" },
    ],
    relatedWords: ["madre", "alta", "pelo", "rubio"],
  },
  {
    id: "lf-003", topicId: "family", title: "爸爸上班", level: "A1-1",
    scene: "介紹爸爸的工作。",
    audioText: "Mi padre trabaja en una oficina. Llega a casa a las seis.",
    transcript: "Mi padre trabaja en una oficina. Llega a casa a las seis.",
    zh: "我爸爸在辦公室工作。他六點到家。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "爸爸幾點到家？", options: ["六點", "七點", "五點"], answer: "六點" },
      { id: "q2", type: "true-false", statement: "爸爸在家工作。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Mi padre trabaja en una ____.", answer: "oficina" },
    ],
    relatedWords: ["padre", "trabaja", "oficina", "llega"],
  },
  {
    id: "lf-004", topicId: "family", title: "有兩個孩子", level: "A1-1",
    scene: "媽媽介紹自己的孩子。",
    audioText: "Tengo dos hijos: un niño y una niña. El niño tiene cinco años.",
    transcript: "Tengo dos hijos: un niño y una niña. El niño tiene cinco años.",
    zh: "我有兩個孩子：一個男孩和一個女孩。男孩五歲。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "男孩幾歲？", options: ["5歲", "4歲", "6歲"], answer: "5歲" },
      { id: "q2", type: "true-false", statement: "她有兩個兒子。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Tengo dos ____.", answer: "hijos" },
    ],
    relatedWords: ["hijos", "niño", "niña", "cinco"],
  },
  {
    id: "lf-005", topicId: "family", title: "奶奶七十歲", level: "A1-2",
    scene: "描述祖母的年齡和個性。",
    audioText: "Mi abuela tiene setenta años. Es muy simpática y cariñosa.",
    transcript: "Mi abuela tiene setenta años. Es muy simpática y cariñosa.",
    zh: "我的祖母七十歲。她非常友善和充滿愛心。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "祖母幾歲？", options: ["70歲", "60歲", "80歲"], answer: "70歲" },
      { id: "q2", type: "true-false", statement: "祖母個性不好。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Mi abuela tiene ____ años.", answer: "setenta" },
    ],
    relatedWords: ["abuela", "setenta", "simpática", "cariñosa"],
  },
  {
    id: "lf-006", topicId: "family", title: "有沒有兄弟", level: "A1-2",
    scene: "朋友之間互問家庭情況。",
    audioText: "¿Tienes hermanos? Sí, tengo una hermana mayor.",
    transcript: "¿Tienes hermanos? Sí, tengo una hermana mayor.",
    zh: "你有兄弟姐妹嗎？有，我有一個姐姐。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "她有什麼兄弟姐妹？", options: ["一個姐姐", "一個哥哥", "一個妹妹"], answer: "一個姐姐" },
      { id: "q2", type: "true-false", statement: "她沒有兄弟姐妹。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Tengo una hermana ____.", answer: "mayor" },
    ],
    relatedWords: ["hermanos", "hermana", "mayor"],
  },
  {
    id: "lf-007", topicId: "family", title: "描述丈夫", level: "A1-2",
    scene: "描述丈夫的外表和個性。",
    audioText: "Mi marido es moreno, bajo y muy simpático.",
    transcript: "Mi marido es moreno, bajo y muy simpático.",
    zh: "我丈夫皮膚黝黑，身材矮小，非常友善。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "丈夫的身材如何？", options: ["矮小", "高大", "中等"], answer: "矮小" },
      { id: "q2", type: "true-false", statement: "丈夫很友善。", answer: true },
      { id: "q3", type: "fill-blank", sentence: "Mi marido es moreno y ____.", answer: "bajo" },
    ],
    relatedWords: ["marido", "moreno", "bajo", "simpático"],
  },
  {
    id: "lf-008", topicId: "family", title: "表妹喜歡足球", level: "A1-2",
    scene: "介紹表妹的年齡和愛好。",
    audioText: "Ella es mi prima. Tiene quince años y le gusta el fútbol.",
    transcript: "Ella es mi prima. Tiene quince años y le gusta el fútbol.",
    zh: "她是我的表妹。她十五歲，喜歡足球。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "她幾歲？", options: ["15歲", "16歲", "14歲"], answer: "15歲" },
      { id: "q2", type: "true-false", statement: "她喜歡籃球。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Ella es mi ____.", answer: "prima" },
    ],
    relatedWords: ["prima", "quince", "fútbol"],
  },
  {
    id: "lf-009", topicId: "family", title: "五口之家", level: "A1-3",
    scene: "介紹自己的家庭成員。",
    audioText: "Mi familia tiene cinco personas: mis padres, mis dos hermanos y yo.",
    transcript: "Mi familia tiene cinco personas: mis padres, mis dos hermanos y yo.",
    zh: "我家有五個人：我的父母、我的兩個兄弟和我。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "家裡有幾個人？", options: ["5人", "4人", "6人"], answer: "5人" },
      { id: "q2", type: "true-false", statement: "他有兩個兄弟。", answer: true },
      { id: "q3", type: "fill-blank", sentence: "Mi familia tiene ____ personas.", answer: "cinco" },
    ],
    relatedWords: ["familia", "padres", "hermanos"],
  },
  {
    id: "lf-010", topicId: "family", title: "我的狗", level: "A1-3",
    scene: "介紹家裡的寵物。",
    audioText: "Mi perro se llama Max. Es grande y negro. Me gusta mucho.",
    transcript: "Mi perro se llama Max. Es grande y negro. Me gusta mucho.",
    zh: "我的狗叫 Max。牠又大又黑。我非常喜歡牠。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "狗叫什麼名字？", options: ["Max", "Rex", "Toby"], answer: "Max" },
      { id: "q2", type: "true-false", statement: "這隻狗是白色的。", answer: false },
      { id: "q3", type: "sort", instruction: "把句子排成正確順序", words: ["llama", "Mi", "Max.", "perro", "se"], answer: ["Mi", "perro", "se", "llama", "Max."] },
    ],
    relatedWords: ["perro", "grande", "negro", "llama"],
  },

  // ══════════════════════════════════════════
  // TOPIC 4: 數字、時間、日期
  // ══════════════════════════════════════════
  {
    id: "lt-001", topicId: "time", title: "下午三點", level: "A1-1",
    scene: "同學問現在幾點。",
    audioText: "Son las tres de la tarde. Tengo clase ahora.",
    transcript: "Son las tres de la tarde. Tengo clase ahora.",
    zh: "現在是下午三點。我現在有課。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "現在幾點？", options: ["下午三點", "上午三點", "下午兩點"], answer: "下午三點" },
      { id: "q2", type: "true-false", statement: "他現在沒有課。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Son las ____ de la tarde.", answer: "tres" },
    ],
    relatedWords: ["son", "las", "tarde", "clase"],
  },
  {
    id: "lt-002", topicId: "time", title: "今天星期一", level: "A1-1",
    scene: "早上確認日期。",
    audioText: "Hoy es lunes, cinco de enero. Hace frío.",
    transcript: "Hoy es lunes, cinco de enero. Hace frío.",
    zh: "今天是一月五日，星期一。天氣很冷。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "今天是星期幾？", options: ["星期一", "星期二", "星期三"], answer: "星期一" },
      { id: "q2", type: "true-false", statement: "今天是二月五日。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Hoy es ____, cinco de enero.", answer: "lunes" },
    ],
    relatedWords: ["lunes", "enero", "frío"],
  },
  {
    id: "lt-003", topicId: "time", title: "Ana 的生日", level: "A1-1",
    scene: "朋友討論 Ana 的生日。",
    audioText: "El cumpleaños de Ana es el tres de marzo.",
    transcript: "El cumpleaños de Ana es el tres de marzo.",
    zh: "Ana 的生日是三月三日。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "Ana 的生日是幾月？", options: ["三月", "二月", "四月"], answer: "三月" },
      { id: "q2", type: "true-false", statement: "Ana 的生日是三月三日。", answer: true },
      { id: "q3", type: "fill-blank", sentence: "El cumpleaños de Ana es en ____.", answer: "marzo" },
    ],
    relatedWords: ["cumpleaños", "marzo", "tres"],
  },
  {
    id: "lt-004", topicId: "time", title: "八點半", level: "A1-1",
    scene: "媽媽問孩子幾點了。",
    audioText: "¿Qué hora es? Son las ocho y media de la mañana.",
    transcript: "¿Qué hora es? Son las ocho y media de la mañana.",
    zh: "現在幾點？早上八點半。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "現在幾點？", options: ["八點半", "九點半", "七點半"], answer: "八點半" },
      { id: "q2", type: "true-false", statement: "現在是下午。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Son las ocho y ____.", answer: "media" },
    ],
    relatedWords: ["hora", "ocho", "media", "mañana"],
  },
  {
    id: "lt-005", topicId: "time", title: "明天有課", level: "A1-2",
    scene: "學生確認明天的課表。",
    audioText: "Mañana es martes. Tengo clase de español a las nueve.",
    transcript: "Mañana es martes. Tengo clase de español a las nueve.",
    zh: "明天是星期二。我九點有西班牙語課。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "西班牙語課幾點開始？", options: ["九點", "十點", "八點"], answer: "九點" },
      { id: "q2", type: "true-false", statement: "明天是星期三。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Tengo clase a las ____.", answer: "nueve" },
    ],
    relatedWords: ["martes", "clase", "nueve"],
  },
  {
    id: "lt-006", topicId: "time", title: "夏天開始", level: "A1-2",
    scene: "朋友聊天說到夏天的計劃。",
    audioText: "El verano empieza en junio. Me gusta mucho el verano.",
    transcript: "El verano empieza en junio. Me gusta mucho el verano.",
    zh: "夏天從六月開始。我非常喜歡夏天。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "夏天哪個月開始？", options: ["六月", "七月", "五月"], answer: "六月" },
      { id: "q2", type: "true-false", statement: "他不喜歡夏天。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "El verano empieza en ____.", answer: "junio" },
    ],
    relatedWords: ["verano", "junio", "empieza"],
  },
  {
    id: "lt-007", topicId: "time", title: "午餐時間", level: "A1-2",
    scene: "同事提醒午餐時間到了。",
    audioText: "Son las doce y cuarto. Es la hora de comer.",
    transcript: "Son las doce y cuarto. Es la hora de comer.",
    zh: "現在十二點一刻。是吃午飯的時間了。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "現在幾點？", options: ["十二點一刻", "十二點", "十二點半"], answer: "十二點一刻" },
      { id: "q2", type: "true-false", statement: "現在是吃晚飯的時間。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Son las doce y ____.", answer: "cuarto" },
    ],
    relatedWords: ["doce", "cuarto", "hora", "comer"],
  },
  {
    id: "lt-008", topicId: "time", title: "今天星期五", level: "A1-2",
    scene: "週末快來了，大家很開心。",
    audioText: "Hoy es viernes. El fin de semana empieza mañana.",
    transcript: "Hoy es viernes. El fin de semana empieza mañana.",
    zh: "今天是星期五。週末從明天開始。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "今天是星期幾？", options: ["星期五", "星期六", "星期四"], answer: "星期五" },
      { id: "q2", type: "true-false", statement: "週末已經開始了。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Hoy es ____.", answer: "viernes" },
    ],
    relatedWords: ["viernes", "fin", "semana"],
  },
  {
    id: "lt-009", topicId: "time", title: "我的生日", level: "A1-3",
    scene: "聊天說到自己的生日。",
    audioText: "Mi cumpleaños es el quince de agosto. Cumplo veinticinco años.",
    transcript: "Mi cumpleaños es el quince de agosto. Cumplo veinticinco años.",
    zh: "我的生日是八月十五日。我要滿二十五歲了。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他生日是幾月？", options: ["八月", "七月", "九月"], answer: "八月" },
      { id: "q2", type: "true-false", statement: "他要滿三十歲。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Mi cumpleaños es el quince de ____.", answer: "agosto" },
    ],
    relatedWords: ["cumpleaños", "agosto", "veinticinco"],
  },
  {
    id: "lt-010", topicId: "time", title: "六點四十五", level: "A1-3",
    scene: "早上鬧鐘響起確認時間。",
    audioText: "Son las siete menos cuarto de la mañana. Me levanto ahora.",
    transcript: "Son las siete menos cuarto de la mañana. Me levanto ahora.",
    zh: "現在是早上六點四十五分。我現在起床。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "現在幾點？", options: ["六點四十五分", "七點一刻", "六點三十分"], answer: "六點四十五分" },
      { id: "q2", type: "true-false", statement: "他要去睡覺了。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Son las siete menos ____.", answer: "cuarto" },
    ],
    relatedWords: ["siete", "menos", "cuarto", "levanto"],
  },

  // ══════════════════════════════════════════
  // TOPIC 5: 日常生活
  // ══════════════════════════════════════════
  {
    id: "ld-001", topicId: "daily", title: "早上的例行公事", level: "A1-1",
    scene: "描述早上起床後的活動。",
    audioText: "Me despierto a las siete. Me ducho y luego desayuno.",
    transcript: "Me despierto a las siete. Me ducho y luego desayuno.",
    zh: "我七點起床。我洗澡然後吃早餐。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他幾點起床？", options: ["七點", "六點", "八點"], answer: "七點" },
      { id: "q2", type: "true-false", statement: "他先吃早餐再洗澡。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Me despierto a las ____.", answer: "siete" },
    ],
    relatedWords: ["despierto", "siete", "ducho", "desayuno"],
  },
  {
    id: "ld-002", topicId: "daily", title: "坐公車上班", level: "A1-1",
    scene: "描述通勤方式。",
    audioText: "Por la tarde, voy al trabajo en autobús. Tardo veinte minutos.",
    transcript: "Por la tarde, voy al trabajo en autobús. Tardo veinte minutos.",
    zh: "下午，我搭公車去上班。要花二十分鐘。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他怎麼去上班？", options: ["搭公車", "開車", "步行"], answer: "搭公車" },
      { id: "q2", type: "true-false", statement: "他花一小時到公司。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Voy al trabajo en ____.", answer: "autobús" },
    ],
    relatedWords: ["trabajo", "autobús", "tarde", "minutos"],
  },
  {
    id: "ld-003", topicId: "daily", title: "晚餐時光", level: "A1-1",
    scene: "描述晚上和家人共進晚餐。",
    audioText: "Por la noche, ceno con mi familia. Cenamos a las ocho.",
    transcript: "Por la noche, ceno con mi familia. Cenamos a las ocho.",
    zh: "晚上，我和家人一起吃晚餐。我們八點吃晚餐。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他們幾點吃晚餐？", options: ["八點", "七點", "九點"], answer: "八點" },
      { id: "q2", type: "true-false", statement: "他一個人吃晚餐。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Cenamos a las ____.", answer: "ocho" },
    ],
    relatedWords: ["noche", "ceno", "familia", "ocho"],
  },
  {
    id: "ld-004", topicId: "daily", title: "星期一有課", level: "A1-1",
    scene: "說明每週固定的課程。",
    audioText: "Los lunes tengo clase de español. La clase dura dos horas.",
    transcript: "Los lunes tengo clase de español. La clase dura dos horas.",
    zh: "每週一我有西班牙語課。課程持續兩小時。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "西班牙語課幾個小時？", options: ["兩小時", "一小時", "三小時"], answer: "兩小時" },
      { id: "q2", type: "true-false", statement: "他星期二有西班牙語課。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Los ____ tengo clase de español.", answer: "lunes" },
    ],
    relatedWords: ["lunes", "clase", "español", "dura"],
  },
  {
    id: "ld-005", topicId: "daily", title: "早上喝咖啡", level: "A1-2",
    scene: "描述早晨的習慣。",
    audioText: "Me gusta leer por la mañana. Leo el periódico y tomo café.",
    transcript: "Me gusta leer por la mañana. Leo el periódico y tomo café.",
    zh: "我喜歡早上看書。我看報紙和喝咖啡。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他早上喝什麼？", options: ["咖啡", "茶", "果汁"], answer: "咖啡" },
      { id: "q2", type: "true-false", statement: "他早上看電視。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Me gusta ____ por la mañana.", answer: "leer" },
    ],
    relatedWords: ["leer", "mañana", "periódico", "café"],
  },
  {
    id: "ld-006", topicId: "daily", title: "幾點起床", level: "A1-2",
    scene: "朋友互問早上幾點起床。",
    audioText: "¿A qué hora te levantas? Me levanto a las seis y media.",
    transcript: "¿A qué hora te levantas? Me levanto a las seis y media.",
    zh: "你幾點起床？我六點半起床。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他幾點起床？", options: ["六點半", "七點半", "六點"], answer: "六點半" },
      { id: "q2", type: "true-false", statement: "他很晚起床。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Me levanto a las seis y ____.", answer: "media" },
    ],
    relatedWords: ["levantas", "levanto", "seis", "media"],
  },
  {
    id: "ld-007", topicId: "daily", title: "下班後運動", level: "A1-2",
    scene: "描述下班後的活動。",
    audioText: "Después del trabajo, hago ejercicio en el gimnasio.",
    transcript: "Después del trabajo, hago ejercicio en el gimnasio.",
    zh: "下班後，我在健身房運動。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他在哪裡運動？", options: ["健身房", "公園", "家裡"], answer: "健身房" },
      { id: "q2", type: "true-false", statement: "他下班後直接回家。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Hago ejercicio en el ____.", answer: "gimnasio" },
    ],
    relatedWords: ["trabajo", "ejercicio", "gimnasio"],
  },
  {
    id: "ld-008", topicId: "daily", title: "週日在家", level: "A1-2",
    scene: "描述週日的休息活動。",
    audioText: "Los domingos descanso en casa. A veces veo películas.",
    transcript: "Los domingos descanso en casa. A veces veo películas.",
    zh: "週日我在家休息。有時候看電影。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他週日做什麼？", options: ["在家休息", "去上班", "去運動"], answer: "在家休息" },
      { id: "q2", type: "true-false", statement: "他從不看電影。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Los domingos ____ en casa.", answer: "descanso" },
    ],
    relatedWords: ["domingos", "descanso", "películas"],
  },
  {
    id: "ld-009", topicId: "daily", title: "週六去超市", level: "A1-3",
    scene: "描述週末購物習慣。",
    audioText: "Voy al supermercado los sábados. Compro fruta y verdura.",
    transcript: "Voy al supermercado los sábados. Compro fruta y verdura.",
    zh: "我每週六去超市。我買水果和蔬菜。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他每週幾去超市？", options: ["週六", "週日", "週五"], answer: "週六" },
      { id: "q2", type: "true-false", statement: "他在超市買肉。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Voy al ____ los sábados.", answer: "supermercado" },
    ],
    relatedWords: ["supermercado", "sábados", "fruta", "verdura"],
  },
  {
    id: "ld-010", topicId: "daily", title: "睡前閱讀", level: "A1-3",
    scene: "描述睡前習慣。",
    audioText: "Me acuesto a las once de la noche. Leo un poco antes de dormir.",
    transcript: "Me acuesto a las once de la noche. Leo un poco antes de dormir.",
    zh: "我晚上十一點上床睡覺。睡前我看一會兒書。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他幾點睡覺？", options: ["十一點", "十點", "十二點"], answer: "十一點" },
      { id: "q2", type: "true-false", statement: "他睡前看電視。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Me acuesto a las ____ de la noche.", answer: "once" },
    ],
    relatedWords: ["acuesto", "once", "dormir", "noche"],
  },

  // ══════════════════════════════════════════
  // TOPIC 6: 食物與餐廳
  // ══════════════════════════════════════════
  {
    id: "lfo-001", topicId: "food", title: "點餐", level: "A1-1",
    scene: "在餐廳點披薩。",
    audioText: "Quiero una pizza, por favor. Y también una Coca-Cola.",
    transcript: "Quiero una pizza, por favor. Y también una Coca-Cola.",
    zh: "請給我一個披薩。還有一杯可口可樂。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他點了什麼飲料？", options: ["可口可樂", "水", "果汁"], answer: "可口可樂" },
      { id: "q2", type: "true-false", statement: "他只點了飲料。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Quiero una ____, por favor.", answer: "pizza" },
    ],
    relatedWords: ["quiero", "pizza", "también"],
  },
  {
    id: "lfo-002", topicId: "food", title: "早餐點餐", level: "A1-1",
    scene: "在咖啡廳點早餐。",
    audioText: "¿Qué desea? Quiero un café con leche y un croissant.",
    transcript: "¿Qué desea? Quiero un café con leche y un croissant.",
    zh: "您要什麼？我要一杯牛奶咖啡和一個可頌。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他點了什麼早餐？", options: ["咖啡和可頌", "茶和吐司", "果汁和蛋糕"], answer: "咖啡和可頌" },
      { id: "q2", type: "true-false", statement: "他要了純黑咖啡。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Quiero un café con ____.", answer: "leche" },
    ],
    relatedWords: ["desea", "café", "leche", "croissant"],
  },
  {
    id: "lfo-003", topicId: "food", title: "最愛的菜", level: "A1-1",
    scene: "介紹自己最喜歡的食物。",
    audioText: "Me gusta el arroz con pollo. Es mi plato favorito.",
    transcript: "Me gusta el arroz con pollo. Es mi plato favorito.",
    zh: "我喜歡雞肉燉飯。這是我最喜歡的菜。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他最喜歡什麼菜？", options: ["雞肉燉飯", "海鮮飯", "牛肉燉飯"], answer: "雞肉燉飯" },
      { id: "q2", type: "true-false", statement: "他不喜歡雞肉燉飯。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Me gusta el arroz con ____.", answer: "pollo" },
    ],
    relatedWords: ["arroz", "pollo", "plato", "favorito"],
  },
  {
    id: "lfo-004", topicId: "food", title: "結帳", level: "A1-1",
    scene: "在餐廳用完餐後要求結帳。",
    audioText: "La cuenta, por favor. ¿Puedo pagar con tarjeta?",
    transcript: "La cuenta, por favor. ¿Puedo pagar con tarjeta?",
    zh: "請結帳。我可以用信用卡付款嗎？",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他想做什麼？", options: ["結帳", "點餐", "要菜單"], answer: "結帳" },
      { id: "q2", type: "true-false", statement: "他要用現金付款。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "La ____, por favor.", answer: "cuenta" },
    ],
    relatedWords: ["cuenta", "pagar", "tarjeta"],
  },
  {
    id: "lfo-005", topicId: "food", title: "訂桌", level: "A1-2",
    scene: "兩人進餐廳詢問有沒有空位。",
    audioText: "¿Tienen mesa para dos? Sí, por aquí, por favor.",
    transcript: "¿Tienen mesa para dos? Sí, por aquí, por favor.",
    zh: "你們有兩人桌嗎？有，請這邊走。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他們要幾人桌？", options: ["兩人", "三人", "四人"], answer: "兩人" },
      { id: "q2", type: "true-false", statement: "餐廳沒有空桌。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "¿Tienen mesa para ____?", answer: "dos" },
    ],
    relatedWords: ["mesa", "dos", "aquí"],
  },
  {
    id: "lfo-006", topicId: "food", title: "不吃魚", level: "A1-2",
    scene: "在餐廳表達飲食偏好。",
    audioText: "No me gusta el pescado. Prefiero la carne de ternera.",
    transcript: "No me gusta el pescado. Prefiero la carne de ternera.",
    zh: "我不喜歡魚。我比較喜歡小牛肉。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他不喜歡什麼？", options: ["魚", "肉", "蔬菜"], answer: "魚" },
      { id: "q2", type: "true-false", statement: "他喜歡吃魚。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "No me gusta el ____.", answer: "pescado" },
    ],
    relatedWords: ["gusta", "pescado", "prefiero", "carne"],
  },
  {
    id: "lfo-007", topicId: "food", title: "今日套餐", level: "A1-2",
    scene: "詢問餐廳今日套餐內容。",
    audioText: "¿Qué hay de menú hoy? Hay sopa de verduras, pollo y ensalada.",
    transcript: "¿Qué hay de menú hoy? Hay sopa de verduras, pollo y ensalada.",
    zh: "今天的套餐有什麼？有蔬菜湯、雞肉和沙拉。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "套餐中沒有什麼？", options: ["牛排", "雞肉", "沙拉"], answer: "牛排" },
      { id: "q2", type: "true-false", statement: "套餐裡有蔬菜湯。", answer: true },
      { id: "q3", type: "fill-blank", sentence: "¿Qué hay de ____?", answer: "menú" },
    ],
    relatedWords: ["menú", "sopa", "verduras", "ensalada"],
  },
  {
    id: "lfo-008", topicId: "food", title: "點飲料", level: "A1-2",
    scene: "點飲料。",
    audioText: "Quiero agua sin gas, por favor. Y un vaso de zumo de naranja.",
    transcript: "Quiero agua sin gas, por favor. Y un vaso de zumo de naranja.",
    zh: "請給我一杯無氣泡水。和一杯柳橙汁。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他要什麼水？", options: ["無氣泡水", "氣泡水", "礦泉水"], answer: "無氣泡水" },
      { id: "q2", type: "true-false", statement: "他只要水，不要其他飲料。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Quiero agua sin ____.", answer: "gas" },
    ],
    relatedWords: ["agua", "gas", "vaso", "naranja"],
  },
  {
    id: "lfo-009", topicId: "food", title: "海鮮飯很好吃", level: "A1-3",
    scene: "在餐廳稱讚菜肴並想再要一份。",
    audioText: "Esta paella está muy rica. ¿Puedo repetir?",
    transcript: "Esta paella está muy rica. ¿Puedo repetir?",
    zh: "這道海鮮飯非常好吃。我可以再要一份嗎？",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他覺得海鮮飯怎樣？", options: ["很好吃", "一般", "不好吃"], answer: "很好吃" },
      { id: "q2", type: "true-false", statement: "他不想再吃了。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Esta paella está muy ____.", answer: "rica" },
    ],
    relatedWords: ["paella", "rica", "repetir"],
  },
  {
    id: "lfo-010", topicId: "food", title: "早餐含不含", level: "A1-3",
    scene: "在飯店辦理入住時詢問早餐。",
    audioText: "¿El desayuno está incluido en el precio? Sí, señor. Empieza a las siete.",
    transcript: "¿El desayuno está incluido en el precio? Sí, señor. Empieza a las siete.",
    zh: "早餐包含在房價內嗎？是的，先生。從七點開始。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "早餐幾點開始？", options: ["七點", "八點", "六點"], answer: "七點" },
      { id: "q2", type: "true-false", statement: "早餐不含在房價內。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "El desayuno está ____ en el precio.", answer: "incluido" },
    ],
    relatedWords: ["desayuno", "incluido", "precio", "señor"],
  },

  // ══════════════════════════════════════════
  // TOPIC 7: 購物與價格
  // ══════════════════════════════════════════
  {
    id: "lsh-001", topicId: "shopping", title: "這件多少錢", level: "A1-1",
    scene: "在服裝店詢問價格。",
    audioText: "¿Cuánto cuesta esta camisa? Cuesta veinte euros.",
    transcript: "¿Cuánto cuesta esta camisa? Cuesta veinte euros.",
    zh: "這件襯衫多少錢？二十歐元。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "這件襯衫多少錢？", options: ["20歐元", "25歐元", "15歐元"], answer: "20歐元" },
      { id: "q2", type: "true-false", statement: "這件襯衫是免費的。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "¿Cuánto ____ esta camisa?", answer: "cuesta" },
    ],
    relatedWords: ["cuánto", "cuesta", "camisa", "euros"],
  },
  {
    id: "lsh-002", topicId: "shopping", title: "有大一號嗎", level: "A1-1",
    scene: "在服裝店詢問尺碼。",
    audioText: "¿Tiene una talla más grande? Sí, aquí tiene la talla L.",
    transcript: "¿Tiene una talla más grande? Sí, aquí tiene la talla L.",
    zh: "你們有大一號的嗎？有，這裡是 L 號。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他要什麼尺碼？", options: ["L號", "M號", "XL號"], answer: "L號" },
      { id: "q2", type: "true-false", statement: "沒有他要的尺碼。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "¿Tiene una talla más ____?", answer: "grande" },
    ],
    relatedWords: ["talla", "grande", "aquí"],
  },
  {
    id: "lsh-003", topicId: "shopping", title: "買黑鞋", level: "A1-1",
    scene: "在鞋店詢問有沒有特定商品。",
    audioText: "Quiero comprar unos zapatos negros. ¿Tienen el número cuarenta?",
    transcript: "Quiero comprar unos zapatos negros. ¿Tienen el número cuarenta?",
    zh: "我想買黑色的鞋子。你們有四十號嗎？",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他要買什麼顏色的鞋？", options: ["黑色", "棕色", "白色"], answer: "黑色" },
      { id: "q2", type: "true-false", statement: "他要四十二號的鞋。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Quiero comprar unos ____ negros.", answer: "zapatos" },
    ],
    relatedWords: ["zapatos", "negros", "número", "cuarenta"],
  },
  {
    id: "lsh-004", topicId: "shopping", title: "可以刷卡嗎", level: "A1-2",
    scene: "在收銀台詢問付款方式。",
    audioText: "¿Puedo pagar con tarjeta de crédito? Sí, claro. También aceptamos efectivo.",
    transcript: "¿Puedo pagar con tarjeta de crédito? Sí, claro. También aceptamos efectivo.",
    zh: "我可以用信用卡付款嗎？當然可以。我們也接受現金。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "這家店接受哪些付款方式？", options: ["信用卡和現金", "只接受現金", "只接受信用卡"], answer: "信用卡和現金" },
      { id: "q2", type: "true-false", statement: "這家店不接受信用卡。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "¿Puedo pagar con ____?", answer: "tarjeta" },
    ],
    relatedWords: ["pagar", "tarjeta", "efectivo", "aceptamos"],
  },
  {
    id: "lsh-005", topicId: "shopping", title: "特價商品", level: "A1-2",
    scene: "看到特價裙子的廣告。",
    audioText: "Esta falda está en oferta. Normalmente cuesta treinta euros, pero hoy quince.",
    transcript: "Esta falda está en oferta. Normalmente cuesta treinta euros, pero hoy quince.",
    zh: "這條裙子在特賣。通常三十歐元，但今天十五歐元。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "特賣價是多少？", options: ["15歐元", "20歐元", "25歐元"], answer: "15歐元" },
      { id: "q2", type: "true-false", statement: "原價是四十歐元。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Esta falda está en ____.", answer: "oferta" },
    ],
    relatedWords: ["falda", "oferta", "normalmente", "euros"],
  },
  {
    id: "lsh-006", topicId: "shopping", title: "要收據", level: "A1-2",
    scene: "購物後要求收據。",
    audioText: "¿Me puede dar un recibo? Sí, un momento. Aquí tiene.",
    transcript: "¿Me puede dar un recibo? Sí, un momento. Aquí tiene.",
    zh: "你可以給我收據嗎？好的，稍等一下。這裡。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他要什麼？", options: ["收據", "袋子", "找零"], answer: "收據" },
      { id: "q2", type: "true-false", statement: "收銀員立刻給了收據。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "¿Me puede dar un ____?", answer: "recibo" },
    ],
    relatedWords: ["recibo", "momento", "aquí"],
  },
  {
    id: "lsh-007", topicId: "shopping", title: "換顏色", level: "A1-2",
    scene: "詢問有沒有不同顏色的商品。",
    audioText: "No me gusta este color azul. ¿Lo tiene en rojo o en verde?",
    transcript: "No me gusta este color azul. ¿Lo tiene en rojo o en verde?",
    zh: "我不喜歡這個藍色。你們有紅色或綠色的嗎？",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他不喜歡什麼顏色？", options: ["藍色", "紅色", "綠色"], answer: "藍色" },
      { id: "q2", type: "true-false", statement: "他想要紅色或綠色的。", answer: true },
      { id: "q3", type: "fill-blank", sentence: "No me gusta este color ____.", answer: "azul" },
    ],
    relatedWords: ["color", "azul", "rojo", "verde"],
  },
  {
    id: "lsh-008", topicId: "shopping", title: "總共多少", level: "A1-3",
    scene: "在收銀台聽取總金額。",
    audioText: "El total son treinta y cinco euros. ¿Cómo desea pagar?",
    transcript: "El total son treinta y cinco euros. ¿Cómo desea pagar?",
    zh: "總共是三十五歐元。您想怎麼付款？",
    questions: [
      { id: "q1", type: "multiple-choice", question: "總共多少錢？", options: ["35歐元", "25歐元", "45歐元"], answer: "35歐元" },
      { id: "q2", type: "true-false", statement: "收銀員問付款方式。", answer: true },
      { id: "q3", type: "fill-blank", sentence: "El total son treinta y ____ euros.", answer: "cinco" },
    ],
    relatedWords: ["total", "treinta", "cinco", "pagar"],
  },
  {
    id: "lsh-009", topicId: "shopping", title: "收銀台在哪", level: "A1-3",
    scene: "在店裡詢問收銀台位置。",
    audioText: "¿Dónde está la caja? Está al fondo, a la derecha.",
    transcript: "¿Dónde está la caja? Está al fondo, a la derecha.",
    zh: "收銀台在哪裡？在最後面，右邊。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "收銀台在哪裡？", options: ["最後面右邊", "入口左邊", "中間"], answer: "最後面右邊" },
      { id: "q2", type: "true-false", statement: "收銀台在左邊。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "¿Dónde está la ____?", answer: "caja" },
    ],
    relatedWords: ["caja", "fondo", "derecha"],
  },
  {
    id: "lsh-010", topicId: "shopping", title: "退貨", level: "A1-3",
    scene: "到店裡退回不合適的衣服。",
    audioText: "Quiero devolver este jersey. No me queda bien.",
    transcript: "Quiero devolver este jersey. No me queda bien.",
    zh: "我想退回這件毛衣。它不合適我。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他要做什麼？", options: ["退貨", "換貨", "修改"], answer: "退貨" },
      { id: "q2", type: "true-false", statement: "這件毛衣很合他的身。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Quiero ____ este jersey.", answer: "devolver" },
    ],
    relatedWords: ["devolver", "jersey", "queda"],
  },

  // ══════════════════════════════════════════
  // TOPIC 8: 方向與交通
  // ══════════════════════════════════════════
  {
    id: "ldir-001", topicId: "directions", title: "銀行在哪", level: "A1-1",
    scene: "在街上詢問銀行的位置。",
    audioText: "Perdone, ¿dónde está el banco? Está a la derecha, al lado de la farmacia.",
    transcript: "Perdone, ¿dónde está el banco? Está a la derecha, al lado de la farmacia.",
    zh: "打擾一下，銀行在哪裡？在右邊，藥局旁邊。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "銀行在哪個方向？", options: ["右邊", "左邊", "前方"], answer: "右邊" },
      { id: "q2", type: "true-false", statement: "銀行在超市旁邊。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Está a la ____.", answer: "derecha" },
    ],
    relatedWords: ["banco", "derecha", "farmacia", "lado"],
  },
  {
    id: "ldir-002", topicId: "directions", title: "左轉直走", level: "A1-1",
    scene: "路人給出簡單的方向指示。",
    audioText: "Gire a la izquierda y luego siga recto por cien metros.",
    transcript: "Gire a la izquierda y luego siga recto por cien metros.",
    zh: "往左轉，然後直走一百公尺。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "先往哪個方向？", options: ["左轉", "右轉", "直走"], answer: "左轉" },
      { id: "q2", type: "true-false", statement: "直走五百公尺。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Gire a la ____.", answer: "izquierda" },
    ],
    relatedWords: ["gire", "izquierda", "siga", "recto"],
  },
  {
    id: "ldir-003", topicId: "directions", title: "怎麼到地鐵", level: "A1-1",
    scene: "詢問如何到達地鐵站。",
    audioText: "¿Cómo llego al metro? Tome el autobús número cinco y baje en la tercera parada.",
    transcript: "¿Cómo llego al metro? Tome el autobús número cinco y baje en la tercera parada.",
    zh: "怎麼到地鐵站？搭五號公車，在第三站下車。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "搭幾號公車？", options: ["5號", "3號", "15號"], answer: "5號" },
      { id: "q2", type: "true-false", statement: "在第五站下車。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Tome el autobús número ____.", answer: "cinco" },
    ],
    relatedWords: ["metro", "autobús", "parada", "baje"],
  },
  {
    id: "ldir-004", topicId: "directions", title: "醫院在公園對面", level: "A1-2",
    scene: "描述醫院的位置。",
    audioText: "El hospital está enfrente del parque, cerca de la estación de tren.",
    transcript: "El hospital está enfrente del parque, cerca de la estación de tren.",
    zh: "醫院在公園對面，靠近火車站。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "醫院在哪裡？", options: ["公園對面", "公園旁邊", "車站後面"], answer: "公園對面" },
      { id: "q2", type: "true-false", statement: "醫院遠離車站。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "El hospital está ____ del parque.", answer: "enfrente" },
    ],
    relatedWords: ["hospital", "enfrente", "parque", "estación"],
  },
  {
    id: "ldir-005", topicId: "directions", title: "步行五分鐘", level: "A1-2",
    scene: "詢問目的地有多遠。",
    audioText: "¿Está lejos? No, está a cinco minutos a pie.",
    transcript: "¿Está lejos? No, está a cinco minutos a pie.",
    zh: "遠嗎？不，步行五分鐘。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "需要走多久？", options: ["五分鐘", "十分鐘", "十五分鐘"], answer: "五分鐘" },
      { id: "q2", type: "true-false", statement: "需要搭車才能到達。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Está a cinco minutos a ____.", answer: "pie" },
    ],
    relatedWords: ["lejos", "cinco", "minutos", "pie"],
  },
  {
    id: "ldir-006", topicId: "directions", title: "第一條街右轉", level: "A1-2",
    scene: "給出更詳細的路線指引。",
    audioText: "Tome la primera calle a la derecha. El hotel está allí.",
    transcript: "Tome la primera calle a la derecha. El hotel está allí.",
    zh: "走第一條街道右轉。飯店就在那裡。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "飯店在哪裡？", options: ["第一條街右轉後", "直走", "左轉後"], answer: "第一條街右轉後" },
      { id: "q2", type: "true-false", statement: "飯店在左邊。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Tome la primera calle a la ____.", answer: "derecha" },
    ],
    relatedWords: ["primera", "calle", "derecha", "hotel"],
  },
  {
    id: "ldir-007", topicId: "directions", title: "超市在飯店後面", level: "A1-2",
    scene: "詢問附近是否有超市。",
    audioText: "¿Hay un supermercado cerca? Sí, está detrás del hotel, en la calle Mayor.",
    transcript: "¿Hay un supermercado cerca? Sí, está detrás del hotel, en la calle Mayor.",
    zh: "附近有超市嗎？有，在飯店後面，Mayor 街上。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "超市在哪裡？", options: ["飯店後面", "飯店前面", "飯店旁邊"], answer: "飯店後面" },
      { id: "q2", type: "true-false", statement: "超市在 Mayor 街上。", answer: true },
      { id: "q3", type: "fill-blank", sentence: "Está ____ del hotel.", answer: "detrás" },
    ],
    relatedWords: ["supermercado", "detrás", "hotel", "calle"],
  },
  {
    id: "ldir-008", topicId: "directions", title: "直走過橋", level: "A1-3",
    scene: "指引去車站的路線。",
    audioText: "Para ir a la estación, siga todo recto y cruce el puente.",
    transcript: "Para ir a la estación, siga todo recto y cruce el puente.",
    zh: "去車站的話，一直直走然後穿過橋梁。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "去車站需要怎麼走？", options: ["直走過橋", "左轉", "右轉再直走"], answer: "直走過橋" },
      { id: "q2", type: "true-false", statement: "車站在橋的前面。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Siga todo ____ y cruce el puente.", answer: "recto" },
    ],
    relatedWords: ["estación", "recto", "cruce", "puente"],
  },
  {
    id: "ldir-009", topicId: "directions", title: "博物館在中間", level: "A1-3",
    scene: "描述博物館的精確位置。",
    audioText: "El museo está entre la iglesia y el ayuntamiento.",
    transcript: "El museo está entre la iglesia y el ayuntamiento.",
    zh: "博物館在教堂和市政廳之間。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "博物館在什麼之間？", options: ["教堂和市政廳", "銀行和藥局", "公園和學校"], answer: "教堂和市政廳" },
      { id: "q2", type: "true-false", statement: "博物館只在教堂旁邊。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "El museo está ____ la iglesia y el ayuntamiento.", answer: "entre" },
    ],
    relatedWords: ["museo", "entre", "iglesia", "ayuntamiento"],
  },
  {
    id: "ldir-010", topicId: "directions", title: "公車多久一班", level: "A1-3",
    scene: "在公車站詢問公車需要多久。",
    audioText: "¿Cuánto tiempo tarda el autobús? Unos veinte minutos desde aquí.",
    transcript: "¿Cuánto tiempo tarda el autobús? Unos veinte minutos desde aquí.",
    zh: "公車要多久？從這裡大約二十分鐘。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "公車需要多久？", options: ["約20分鐘", "約10分鐘", "約30分鐘"], answer: "約20分鐘" },
      { id: "q2", type: "true-false", statement: "公車只要五分鐘。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "¿Cuánto tiempo ____ el autobús?", answer: "tarda" },
    ],
    relatedWords: ["tiempo", "tarda", "autobús", "minutos"],
  },

  // ══════════════════════════════════════════
  // TOPIC 9: 旅行與週末
  // ══════════════════════════════════════════
  {
    id: "ll-001", topicId: "leisure", title: "訂飯店房間", level: "A1-1",
    scene: "在飯店前台訂房。",
    audioText: "Quiero una habitación doble para dos noches, por favor.",
    transcript: "Quiero una habitación doble para dos noches, por favor.",
    zh: "請給我一間雙人房，住兩晚。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他要住幾晚？", options: ["兩晚", "一晚", "三晚"], answer: "兩晚" },
      { id: "q2", type: "true-false", statement: "他要單人房。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Quiero una habitación ____ para dos noches.", answer: "doble" },
    ],
    relatedWords: ["habitación", "doble", "noches"],
  },
  {
    id: "ll-002", topicId: "leisure", title: "火車幾點出發", level: "A1-1",
    scene: "在火車站詢問發車時間。",
    audioText: "¿A qué hora sale el tren para Barcelona? Sale a las diez y cuarto.",
    transcript: "¿A qué hora sale el tren para Barcelona? Sale a las diez y cuarto.",
    zh: "去巴塞隆納的火車幾點出發？十點一刻出發。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "火車幾點出發？", options: ["十點一刻", "十點", "十點半"], answer: "十點一刻" },
      { id: "q2", type: "true-false", statement: "這是去馬德里的火車。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "¿A qué hora ____ el tren?", answer: "sale" },
    ],
    relatedWords: ["tren", "Barcelona", "sale", "cuarto"],
  },
  {
    id: "ll-003", topicId: "leisure", title: "週末看電影", level: "A1-1",
    scene: "描述喜歡的週末活動。",
    audioText: "Me gustan los fines de semana. Los sábados voy al cine con amigos.",
    transcript: "Me gustan los fines de semana. Los sábados voy al cine con amigos.",
    zh: "我喜歡週末。週六我和朋友去看電影。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他週六做什麼？", options: ["看電影", "去購物", "運動"], answer: "看電影" },
      { id: "q2", type: "true-false", statement: "他一個人去看電影。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Los sábados voy al ____.", answer: "cine" },
    ],
    relatedWords: ["fines", "semana", "sábados", "cine"],
  },
  {
    id: "ll-004", topicId: "leisure", title: "來回票", level: "A1-2",
    scene: "在售票處購買車票。",
    audioText: "Quiero un billete de ida y vuelta para Valencia. ¿Cuánto cuesta?",
    transcript: "Quiero un billete de ida y vuelta para Valencia. ¿Cuánto cuesta?",
    zh: "我要一張去瓦倫西亞的來回票。多少錢？",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他要去哪裡？", options: ["瓦倫西亞", "巴塞隆納", "馬德里"], answer: "瓦倫西亞" },
      { id: "q2", type: "true-false", statement: "他只要單程票。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Quiero un billete de ida y ____.", answer: "vuelta" },
    ],
    relatedWords: ["billete", "ida", "vuelta", "Valencia"],
  },
  {
    id: "ll-005", topicId: "leisure", title: "飯店設施", level: "A1-2",
    scene: "介紹飯店的設施。",
    audioText: "El hotel tiene piscina, restaurante y gimnasio. Todo está incluido.",
    transcript: "El hotel tiene piscina, restaurante y gimnasio. Todo está incluido.",
    zh: "這家飯店有游泳池、餐廳和健身房。全部包含在內。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "飯店沒有什麼設施？", options: ["SPA", "游泳池", "健身房"], answer: "SPA" },
      { id: "q2", type: "true-false", statement: "設施費用另計。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "El hotel tiene piscina, restaurante y ____.", answer: "gimnasio" },
    ],
    relatedWords: ["hotel", "piscina", "restaurante", "gimnasio"],
  },
  {
    id: "ll-006", topicId: "leisure", title: "有空房嗎", level: "A1-2",
    scene: "在飯店詢問有無空房。",
    audioText: "¿Tiene habitaciones libres para este fin de semana? Sí, tenemos una doble.",
    transcript: "¿Tiene habitaciones libres para este fin de semana? Sí, tenemos una doble.",
    zh: "這個週末你們有空房嗎？有，我們有一間雙人房。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "飯店有什麼空房？", options: ["雙人房", "單人房", "套房"], answer: "雙人房" },
      { id: "q2", type: "true-false", statement: "這個週末沒有空房。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "¿Tiene habitaciones ____?", answer: "libres" },
    ],
    relatedWords: ["habitaciones", "libres", "fin", "semana"],
  },
  {
    id: "ll-007", topicId: "leisure", title: "週日健行", level: "A1-2",
    scene: "描述週日的戶外活動。",
    audioText: "Me gusta hacer senderismo en las montañas los domingos.",
    transcript: "Me gusta hacer senderismo en las montañas los domingos.",
    zh: "我喜歡週日在山裡健行。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他週日喜歡做什麼？", options: ["健行", "游泳", "騎車"], answer: "健行" },
      { id: "q2", type: "true-false", statement: "他在海邊健行。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Me gusta hacer ____ en las montañas.", answer: "senderismo" },
    ],
    relatedWords: ["senderismo", "montañas", "domingos"],
  },
  {
    id: "ll-008", topicId: "leisure", title: "航班時間", level: "A1-3",
    scene: "確認航班起飛時間。",
    audioText: "El vuelo sale a las ocho de la mañana. Hay que estar en el aeropuerto a las seis.",
    transcript: "El vuelo sale a las ocho de la mañana. Hay que estar en el aeropuerto a las seis.",
    zh: "航班早上八點起飛。六點要到機場。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "航班幾點起飛？", options: ["早上八點", "早上九點", "早上七點"], answer: "早上八點" },
      { id: "q2", type: "true-false", statement: "五點要到機場。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "El vuelo sale a las ____ de la mañana.", answer: "ocho" },
    ],
    relatedWords: ["vuelo", "aeropuerto", "ocho", "mañana"],
  },
  {
    id: "ll-009", topicId: "leisure", title: "踢足球", level: "A1-3",
    scene: "描述週日的運動活動。",
    audioText: "Los domingos juego al fútbol con mis amigos en el parque.",
    transcript: "Los domingos juego al fútbol con mis amigos en el parque.",
    zh: "週日我和朋友在公園踢足球。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他在哪裡踢足球？", options: ["公園", "體育館", "海灘"], answer: "公園" },
      { id: "q2", type: "true-false", statement: "他一個人踢足球。", answer: false },
      { id: "q3", type: "sort", instruction: "把句子排成正確順序", words: ["fútbol.", "juego", "Los", "al", "domingos"], answer: ["Los", "domingos", "juego", "al", "fútbol."] },
    ],
    relatedWords: ["fútbol", "domingos", "parque", "amigos"],
  },
  {
    id: "ll-010", topicId: "leisure", title: "空閒時間", level: "A1-3",
    scene: "朋友互問空閒時間做什麼。",
    audioText: "¿Qué haces en tus ratos libres? Leo libros y escucho música.",
    transcript: "¿Qué haces en tus ratos libres? Leo libros y escucho música.",
    zh: "你空閒時做什麼？我看書和聽音樂。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他空閒時做什麼？", options: ["看書和聽音樂", "看電影和運動", "購物和旅行"], answer: "看書和聽音樂" },
      { id: "q2", type: "true-false", statement: "他空閒時玩電動遊戲。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Leo libros y escucho ____.", answer: "música" },
    ],
    relatedWords: ["ratos", "libres", "leo", "música"],
  },

  // ══════════════════════════════════════════
  // TOPIC 10: 身體與健康
  // ══════════════════════════════════════════
  {
    id: "lh-001", topicId: "health", title: "頭痛發燒", level: "A1-1",
    scene: "告訴家人自己不舒服。",
    audioText: "Me duele la cabeza y tengo fiebre. Necesito descansar.",
    transcript: "Me duele la cabeza y tengo fiebre. Necesito descansar.",
    zh: "我頭痛而且發燒。我需要休息。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他有什麼症狀？", options: ["頭痛和發燒", "肚子痛和咳嗽", "喉嚨痛和流鼻涕"], answer: "頭痛和發燒" },
      { id: "q2", type: "true-false", statement: "他想去上班。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Me duele la ____.", answer: "cabeza" },
    ],
    relatedWords: ["duele", "cabeza", "fiebre", "descansar"],
  },
  {
    id: "lh-002", topicId: "health", title: "胃痛", level: "A1-1",
    scene: "在診所描述症狀。",
    audioText: "¿Qué le pasa? Me duele el estómago desde esta mañana.",
    transcript: "¿Qué le pasa? Me duele el estómago desde esta mañana.",
    zh: "您哪裡不舒服？我從今天早上開始胃痛。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他哪裡不舒服？", options: ["胃痛", "頭痛", "背痛"], answer: "胃痛" },
      { id: "q2", type: "true-false", statement: "他昨天開始胃痛。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Me duele el ____.", answer: "estómago" },
    ],
    relatedWords: ["duele", "estómago", "mañana", "pasa"],
  },
  {
    id: "lh-003", topicId: "health", title: "需要看醫生", level: "A1-1",
    scene: "詢問附近有沒有醫療機構。",
    audioText: "Necesito ver al médico. ¿Hay una farmacia o una clínica cerca?",
    transcript: "Necesito ver al médico. ¿Hay una farmacia o una clínica cerca?",
    zh: "我需要看醫生。附近有藥局或診所嗎？",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他需要什麼？", options: ["看醫生", "買食物", "休息"], answer: "看醫生" },
      { id: "q2", type: "true-false", statement: "他在找超市。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Necesito ver al ____.", answer: "médico" },
    ],
    relatedWords: ["necesito", "médico", "farmacia", "clínica"],
  },
  {
    id: "lh-004", topicId: "health", title: "吃藥說明", level: "A1-2",
    scene: "醫生說明如何服藥。",
    audioText: "Tome estas pastillas dos veces al día, después de comer.",
    transcript: "Tome estas pastillas dos veces al día, después de comer.",
    zh: "一天服用這些藥片兩次，飯後服用。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "一天服用幾次？", options: ["兩次", "三次", "一次"], answer: "兩次" },
      { id: "q2", type: "true-false", statement: "要在飯前服用藥片。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Tome estas pastillas ____ veces al día.", answer: "dos" },
    ],
    relatedWords: ["pastillas", "veces", "día", "comer"],
  },
  {
    id: "lh-005", topicId: "health", title: "手臂骨折", level: "A1-2",
    scene: "描述意外受傷的情況。",
    audioText: "Me he roto el brazo. El médico dice que necesito una radiografía.",
    transcript: "Me he roto el brazo. El médico dice que necesito una radiografía.",
    zh: "我手臂骨折了。醫生說我需要照X光。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他受了什麼傷？", options: ["手臂骨折", "腿部受傷", "頭部受傷"], answer: "手臂骨折" },
      { id: "q2", type: "true-false", statement: "他不需要照X光。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Me he roto el ____.", answer: "brazo" },
    ],
    relatedWords: ["roto", "brazo", "médico", "radiografía"],
  },
  {
    id: "lh-006", topicId: "health", title: "咳嗽喉嚨痛", level: "A1-2",
    scene: "告訴朋友感冒症狀。",
    audioText: "Tengo tos y me duele la garganta. Creo que tengo un resfriado.",
    transcript: "Tengo tos y me duele la garganta. Creo que tengo un resfriado.",
    zh: "我咳嗽而且喉嚨痛。我想我感冒了。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他認為他怎麼了？", options: ["感冒", "發燒", "過敏"], answer: "感冒" },
      { id: "q2", type: "true-false", statement: "他只有咳嗽，沒有喉嚨痛。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Me duele la ____.", answer: "garganta" },
    ],
    relatedWords: ["tos", "garganta", "resfriado", "creo"],
  },
  {
    id: "lh-007", topicId: "health", title: "藥物過敏", level: "A1-2",
    scene: "醫生詢問病人是否有藥物過敏。",
    audioText: "¿Es usted alérgico a algún medicamento? No, no soy alérgico a nada.",
    transcript: "¿Es usted alérgico a algún medicamento? No, no soy alérgico a nada.",
    zh: "您對任何藥物過敏嗎？不，我對任何東西都不過敏。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "他對什麼過敏？", options: ["什麼都不過敏", "花生", "盤尼西林"], answer: "什麼都不過敏" },
      { id: "q2", type: "true-false", statement: "他對某些藥物過敏。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "No soy alérgico a ____.", answer: "nada" },
    ],
    relatedWords: ["alérgico", "medicamento", "nada"],
  },
  {
    id: "lh-008", topicId: "health", title: "醫生的建議", level: "A1-3",
    scene: "醫生給出治療建議。",
    audioText: "El médico dice que debo descansar y beber mucha agua.",
    transcript: "El médico dice que debo descansar y beber mucha agua.",
    zh: "醫生說我應該休息並多喝水。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "醫生的建議是什麼？", options: ["休息多喝水", "吃藥打針", "去醫院住院"], answer: "休息多喝水" },
      { id: "q2", type: "true-false", statement: "醫生說不用休息。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Debo descansar y beber mucha ____.", answer: "agua" },
    ],
    relatedWords: ["médico", "descansar", "beber", "agua"],
  },
  {
    id: "lh-009", topicId: "health", title: "什麼時候痛", level: "A1-3",
    scene: "醫生詢問疼痛的時間規律。",
    audioText: "¿Cuándo le duele más? Me duele principalmente por la mañana.",
    transcript: "¿Cuándo le duele más? Me duele principalmente por la mañana.",
    zh: "什麼時候最痛？主要是早上的時候。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "什麼時候最痛？", options: ["早上", "晚上", "下午"], answer: "早上" },
      { id: "q2", type: "true-false", statement: "他整天都很痛。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Me duele principalmente por la ____.", answer: "mañana" },
    ],
    relatedWords: ["duele", "principalmente", "mañana"],
  },
  {
    id: "lh-010", topicId: "health", title: "預約看診", level: "A1-3",
    scene: "提到下午的看診預約。",
    audioText: "Tengo una cita con el médico a las cuatro de la tarde.",
    transcript: "Tengo una cita con el médico a las cuatro de la tarde.",
    zh: "我下午四點有醫生預約。",
    questions: [
      { id: "q1", type: "multiple-choice", question: "預約時間是幾點？", options: ["下午四點", "下午三點", "下午五點"], answer: "下午四點" },
      { id: "q2", type: "true-false", statement: "這是上午的預約。", answer: false },
      { id: "q3", type: "fill-blank", sentence: "Tengo una cita con el médico a las ____ de la tarde.", answer: "cuatro" },
    ],
    relatedWords: ["cita", "médico", "cuatro", "tarde"],
  },
];

export default { listeningTopics, listeningExercises };
