// Spanish A1 Writing Practice Data
// 10 topics × 20 exercises = 200 exercises
// Types: cn-to-es | es-to-cn | fill-blank | sort-sentence | error-correct | free-write

export const topics = [
  { id: "greetings",    title: "打招呼與自我介紹", emoji: "👋", color: "#6366f1" },
  { id: "identity",     title: "國籍、職業、年齡",  emoji: "🌍", color: "#8b5cf6" },
  { id: "family",       title: "家庭與人物描述",    emoji: "👨‍👩‍👧", color: "#ec4899" },
  { id: "time",         title: "數字、時間、日期",  emoji: "🕐", color: "#f59e0b" },
  { id: "daily",        title: "日常生活",          emoji: "☀️", color: "#10b981" },
  { id: "food",         title: "食物與餐廳",        emoji: "☕", color: "#ef4444" },
  { id: "shopping",     title: "購物與價格",        emoji: "🛍️", color: "#06b6d4" },
  { id: "directions",   title: "方向與交通",        emoji: "🗺️", color: "#84cc16" },
  { id: "leisure",      title: "旅行與週末",        emoji: "⚽", color: "#f97316" },
  { id: "health",       title: "身體與健康",        emoji: "💊", color: "#14b8a6" },
];

export const exercises = [

  // ══════════════════════════════════════════════════════════
  // TOPIC 1: 打招呼與自我介紹
  // ══════════════════════════════════════════════════════════
  {
    id: "g-01", topicId: "greetings", type: "cn-to-es", level: "A1-1",
    prompt: "你好。",
    answer: "Hola.",
    alternates: ["¡Hola!"],
    explanation: "Hola 是西語最常用的打招呼，相當於中文的「你好」，非常口語化。",
    relatedWords: ["hola"],
  },
  {
    id: "g-02", topicId: "greetings", type: "cn-to-es", level: "A1-1",
    prompt: "我叫 Ana。",
    answer: "Me llamo Ana.",
    alternates: ["Soy Ana."],
    explanation: "'Me llamo' 字面意思是「我叫自己」，是介紹名字最常見的說法。也可以說 'Soy Ana'。",
    relatedWords: ["llamarse", "soy"],
  },
  {
    id: "g-03", topicId: "greetings", type: "es-to-cn", level: "A1-1",
    prompt: "¿Cómo te llamas?",
    answer: "你叫什麼名字？",
    explanation: "¿Cómo te llamas? 字面是「你叫自己什麼？」，是問名字的標準問法。",
    relatedWords: ["llamarse", "cómo"],
  },
  {
    id: "g-04", topicId: "greetings", type: "fill-blank", level: "A1-1",
    blank: "Me ____ Juan.",
    options: ["llamo", "llamas", "llama", "llamar"],
    answer: "llamo",
    explanation: "'Me llamo' 中 llamo 是 llamarse 的第一人稱：yo me llamo（我叫）。",
    relatedWords: ["llamarse"],
  },
  {
    id: "g-05", topicId: "greetings", type: "sort-sentence", level: "A1-1",
    words: ["Ana.", "soy", "Hola,"],
    answer: ["Hola,", "soy", "Ana."],
    explanation: "基本語序：感嘆詞 + 動詞 + 名字。Hola 之後加逗號，表示打招呼後說話。",
    relatedWords: ["hola", "soy"],
  },
  {
    id: "g-06", topicId: "greetings", type: "error-correct", level: "A1-2",
    prompt: "Yo llamo Ana.",
    answer: "Me llamo Ana.",
    explanation: "llamarse 是反身動詞，必須用反身代詞 'me'，不能省略。'Yo llamo' 意思是「我叫（別人）」，完全不同。",
    relatedWords: ["llamarse"],
  },
  {
    id: "g-07", topicId: "greetings", type: "cn-to-es", level: "A1-1",
    prompt: "很高興認識你。",
    answer: "Mucho gusto.",
    alternates: ["Encantado.", "Encantada."],
    explanation: "Mucho gusto 是見面時說的客套話，男女都可用。男生也可以說 Encantado，女生說 Encantada。",
    relatedWords: ["mucho gusto", "encantado"],
  },
  {
    id: "g-08", topicId: "greetings", type: "es-to-cn", level: "A1-1",
    prompt: "Buenos días.",
    answer: "早上好。",
    explanation: "Buenos días 用於早上打招呼。類似的還有 Buenas tardes（下午好）和 Buenas noches（晚上好）。",
    relatedWords: ["buenos", "día"],
  },
  {
    id: "g-09", topicId: "greetings", type: "fill-blank", level: "A1-1",
    blank: "Hola, _____ Ana.",
    options: ["soy", "sé", "tengo", "llama"],
    answer: "soy",
    explanation: "介紹自己的身份用 soy（我是），來自動詞 ser。",
    relatedWords: ["soy", "ser"],
  },
  {
    id: "g-10", topicId: "greetings", type: "cn-to-es", level: "A1-1",
    prompt: "明天見。",
    answer: "Hasta mañana.",
    explanation: "Hasta mañana 字面意思是「直到明天」，用於道別。類似的有 Hasta luego（之後見）。",
    relatedWords: ["hasta", "mañana"],
  },
  {
    id: "g-11", topicId: "greetings", type: "es-to-cn", level: "A1-1",
    prompt: "Encantado.",
    answer: "很榮幸認識你。（男性說）",
    explanation: "Encantado（男）/ Encantada（女）是比 Mucho gusto 更正式的見面客套語，意思是「我感到榮幸」。",
    relatedWords: ["encantado", "encantada"],
  },
  {
    id: "g-12", topicId: "greetings", type: "sort-sentence", level: "A1-2",
    words: ["gusto.", "Mucho", "¡Hola!", "llamo", "Me", "Ana."],
    answer: ["¡Hola!", "Me", "llamo", "Ana.", "Mucho", "gusto."],
    explanation: "自我介紹的完整流程：打招呼 → 報名字 → 表示高興。",
    relatedWords: ["hola", "llamarse", "mucho gusto"],
  },
  {
    id: "g-13", topicId: "greetings", type: "cn-to-es", level: "A1-2",
    prompt: "你好嗎？",
    answer: "¿Cómo estás?",
    alternates: ["¿Cómo está usted?"],
    explanation: "¿Cómo estás? 是非正式的問候，對朋友使用。對長輩或陌生人用 ¿Cómo está usted?（正式）。",
    relatedWords: ["cómo", "estás"],
  },
  {
    id: "g-14", topicId: "greetings", type: "error-correct", level: "A1-2",
    prompt: "Soy llamo Carlos.",
    answer: "Me llamo Carlos.",
    explanation: "不能把 soy 和 llamo 混用。介紹名字用 'Me llamo + 名字' 或 'Soy + 名字'，兩者只能選一種。",
    relatedWords: ["llamarse", "soy"],
  },
  {
    id: "g-15", topicId: "greetings", type: "fill-blank", level: "A1-2",
    blank: "Nos _____.",
    options: ["vemos", "vemos a", "ver", "ven"],
    answer: "vemos",
    explanation: "'Nos vemos' 是告別語，意思是「我們再見」，字面是「我們看見彼此」。",
    relatedWords: ["nos", "vemos"],
  },
  {
    id: "g-16", topicId: "greetings", type: "es-to-cn", level: "A1-2",
    prompt: "¡Que tengas un buen día!",
    answer: "祝你有美好的一天！",
    explanation: "que tengas 是虛擬語氣，表達祝願。整句意思是「希望你有美好的一天」。",
    relatedWords: ["buen", "día"],
  },
  {
    id: "g-17", topicId: "greetings", type: "cn-to-es", level: "A1-2",
    prompt: "你也是。（回應對方的祝福）",
    answer: "Igualmente.",
    explanation: "Igualmente 字面是「同樣地」，用於回應對方的問候或祝福，相當於「你也是」。",
    relatedWords: ["igualmente"],
  },
  {
    id: "g-18", topicId: "greetings", type: "sort-sentence", level: "A1-2",
    words: ["luego.", "hasta", "¡Adiós,"],
    answer: ["¡Adiós,", "hasta", "luego."],
    explanation: "Adiós（再見）和 hasta luego（之後見）可以合用，加強道別的語氣。",
    relatedWords: ["adiós", "hasta", "luego"],
  },
  {
    id: "g-19", topicId: "greetings", type: "fill-blank", level: "A1-3",
    blank: "¿_____ te llamas?",
    options: ["Cómo", "Qué", "Cuánto", "Dónde"],
    answer: "Cómo",
    explanation: "問名字用 ¿Cómo te llamas?（你叫什麼名字？）。注意：問「什麼」時，問名字用 cómo 而非 qué。",
    relatedWords: ["cómo", "llamarse"],
  },
  {
    id: "g-20", topicId: "greetings", type: "free-write", level: "A1-3",
    prompt: "請用西語寫一段完整的自我介紹（包括打招呼、姓名、來自哪裡）。",
    answer: "（示範）Hola, me llamo [名字]. Soy de Hong Kong. Mucho gusto.",
    explanation: "完整的自我介紹包含：1) 打招呼（Hola）2) 名字（Me llamo...）3) 來源（Soy de...）4) 客套語（Mucho gusto）。",
    relatedWords: ["hola", "llamarse", "soy", "mucho gusto"],
  },

  // ══════════════════════════════════════════════════════════
  // TOPIC 2: 國籍、職業、年齡
  // ══════════════════════════════════════════════════════════
  {
    id: "id-01", topicId: "identity", type: "cn-to-es", level: "A1-1",
    prompt: "你從哪裡來？",
    answer: "¿De dónde eres?",
    explanation: "de dónde 是「從哪裡」，eres 是 ser 的第二人稱。整句用於詢問對方的國籍或來源地。",
    relatedWords: ["dónde", "eres"],
  },
  {
    id: "id-02", topicId: "identity", type: "es-to-cn", level: "A1-1",
    prompt: "Soy de China.",
    answer: "我來自中國。",
    explanation: "Soy de + 地方 = 我來自某地。這是說明國籍最常用的句型。",
    relatedWords: ["soy", "de"],
  },
  {
    id: "id-03", topicId: "identity", type: "fill-blank", level: "A1-1",
    blank: "¿De ____ eres?",
    options: ["dónde", "qué", "cuándo", "cómo"],
    answer: "dónde",
    explanation: "問「在哪裡/從哪裡」時用 dónde。帶了疑問號需要加重音符號：dónde。",
    relatedWords: ["dónde"],
  },
  {
    id: "id-04", topicId: "identity", type: "cn-to-es", level: "A1-1",
    prompt: "我二十歲。",
    answer: "Tengo veinte años.",
    explanation: "西語說年齡不用 ser，而是用 tener（有）：Tengo veinte años.（我有二十歲 = 我二十歲）。",
    relatedWords: ["tener", "años"],
  },
  {
    id: "id-05", topicId: "identity", type: "sort-sentence", level: "A1-1",
    words: ["años?", "tienes", "¿Cuántos"],
    answer: ["¿Cuántos", "años", "tienes?"],
    explanation: "¿Cuántos años tienes? 是問年齡的標準句式。cuántos 是「多少（複數）」，años 是「歲/年」。",
    relatedWords: ["cuántos", "años", "tienes"],
  },
  {
    id: "id-06", topicId: "identity", type: "error-correct", level: "A1-2",
    prompt: "Soy veinte años.",
    answer: "Tengo veinte años.",
    explanation: "年齡必須用 tener（有），不能用 ser（是）。Tengo veinte años = 我有二十歲 = 我二十歲。",
    relatedWords: ["tener", "años"],
  },
  {
    id: "id-07", topicId: "identity", type: "cn-to-es", level: "A1-1",
    prompt: "你說英語嗎？",
    answer: "¿Hablas inglés?",
    explanation: "hablar 是「說話」，hablas 是第二人稱（你）的形式。詢問對方是否說某種語言。",
    relatedWords: ["hablar", "hablas"],
  },
  {
    id: "id-08", topicId: "identity", type: "es-to-cn", level: "A1-1",
    prompt: "Hablo inglés y chino.",
    answer: "我說英語和中文。",
    explanation: "hablo 是 hablar 的第一人稱（我），y 是「和/與」，連接兩種語言。",
    relatedWords: ["hablo", "y"],
  },
  {
    id: "id-09", topicId: "identity", type: "fill-blank", level: "A1-1",
    blank: "___ inglés y español.",
    options: ["Hablo", "Habla", "Hablas", "Hablar"],
    answer: "Hablo",
    explanation: "第一人稱（我）用 hablo，第二人稱（你）用 hablas，第三人稱（他/她）用 habla。",
    relatedWords: ["hablo"],
  },
  {
    id: "id-10", topicId: "identity", type: "cn-to-es", level: "A1-2",
    prompt: "我爸爸是工程師。",
    answer: "Mi padre es ingeniero.",
    explanation: "西語說職業時，ser 後面不加不定冠詞。說 'Soy médico'，不說 'Soy un médico'。",
    relatedWords: ["padre", "ingeniero", "es"],
  },
  {
    id: "id-11", topicId: "identity", type: "error-correct", level: "A1-2",
    prompt: "Mi madre es una enfermera.",
    answer: "Mi madre es enfermera.",
    explanation: "西語說職業不用冠詞 un/una。直接說 'es enfermera'（是護士），省略 una。",
    relatedWords: ["madre", "enfermera"],
  },
  {
    id: "id-12", topicId: "identity", type: "cn-to-es", level: "A1-1",
    prompt: "我媽媽是護士。",
    answer: "Mi madre es enfermera.",
    explanation: "描述職業用 ser：mi madre es enfermera。enfermera 是女性護士，男性護士說 enfermero。",
    relatedWords: ["madre", "enfermera"],
  },
  {
    id: "id-13", topicId: "identity", type: "es-to-cn", level: "A1-2",
    prompt: "¿A qué se dedica tu padre?",
    answer: "你爸爸是做什麼的？",
    explanation: "dedicarse a 是「從事；專注於」，¿A qué se dedica? 是問職業的正式說法。",
    relatedWords: ["padre"],
  },
  {
    id: "id-14", topicId: "identity", type: "fill-blank", level: "A1-1",
    blank: "Soy ___ Hong Kong.",
    options: ["de", "en", "a", "por"],
    answer: "de",
    explanation: "說來自哪裡用介詞 de：Soy de Hong Kong.（我來自香港）。",
    relatedWords: ["de"],
  },
  {
    id: "id-15", topicId: "identity", type: "sort-sentence", level: "A1-2",
    words: ["años.", "Tengo", "veinticinco"],
    answer: ["Tengo", "veinticinco", "años."],
    explanation: "說年齡：Tengo + 數字 + años。veinticinco 是二十五。",
    relatedWords: ["tengo", "años"],
  },
  {
    id: "id-16", topicId: "identity", type: "cn-to-es", level: "A1-2",
    prompt: "我是學生。",
    answer: "Soy estudiante.",
    explanation: "estudiante（學生）不分男女，都用同一個詞。說職業不加冠詞。",
    relatedWords: ["soy", "ser"],
  },
  {
    id: "id-17", topicId: "identity", type: "es-to-cn", level: "A1-2",
    prompt: "Soy profesora de español.",
    answer: "我是西班牙語老師。（女性說）",
    explanation: "profesora 是女性老師，profesor 是男性老師。de español 說明教什麼科目。",
    relatedWords: ["profesora"],
  },
  {
    id: "id-18", topicId: "identity", type: "fill-blank", level: "A1-2",
    blank: "¿___ médico?",
    options: ["Eres", "Soy", "Estar", "Somos"],
    answer: "Eres",
    explanation: "問「你是…嗎？」用 ¿Eres + 職業?。eres 是 ser 的第二人稱。",
    relatedWords: ["eres", "médico"],
  },
  {
    id: "id-19", topicId: "identity", type: "sort-sentence", level: "A1-3",
    words: ["de", "Soy", "y", "chino", "España", "hablo"],
    answer: ["Soy", "de", "España", "y", "hablo", "chino."],
    explanation: "兩個分句用 y（和）連接：來源地 + 語言能力。",
    relatedWords: ["soy", "de", "hablo", "y"],
  },
  {
    id: "id-20", topicId: "identity", type: "free-write", level: "A1-3",
    prompt: "請用西語說說你的國籍、職業和年齡（各一句）。",
    answer: "（示範）Soy de Hong Kong. Soy estudiante. Tengo veinte años.",
    explanation: "三個關鍵句型：1) Soy de... 2) Soy + 職業 3) Tengo + 年齡 + años",
    relatedWords: ["soy", "de", "tengo", "años"],
  },

  // ══════════════════════════════════════════════════════════
  // TOPIC 3: 家庭與人物描述
  // ══════════════════════════════════════════════════════════
  {
    id: "fam-01", topicId: "family", type: "cn-to-es", level: "A1-1",
    prompt: "這是我的家人。",
    answer: "Esta es mi familia.",
    explanation: "esta（這個，陰性）搭配 familia（家庭，陰性名詞）。mi 是「我的」（單數所有格）。",
    relatedWords: ["familia", "mi"],
  },
  {
    id: "fam-02", topicId: "family", type: "es-to-cn", level: "A1-1",
    prompt: "Tengo dos hermanos.",
    answer: "我有兩個兄弟。",
    explanation: "hermanos 可以指「兄弟們」，也可以指兄弟姐妹的混合群體（男性複數包括女性）。",
    relatedWords: ["hermano", "dos"],
  },
  {
    id: "fam-03", topicId: "family", type: "fill-blank", level: "A1-1",
    blank: "Mi ___ se llama Rosa.",
    options: ["madre", "padre", "hermano", "abuelo"],
    answer: "madre",
    explanation: "madre 是媽媽（陰性），padre 是爸爸（陽性）。根據句意「她叫 Rosa」，應填女性詞。",
    relatedWords: ["madre"],
  },
  {
    id: "fam-04", topicId: "family", type: "cn-to-es", level: "A1-1",
    prompt: "我爺爺很高。",
    answer: "Mi abuelo es muy alto.",
    explanation: "abuelo（爺爺/外公）是陽性，形容詞 alto（高）也用陽性形式，不需要改為 alta。",
    relatedWords: ["abuelo", "alto", "muy"],
  },
  {
    id: "fam-05", topicId: "family", type: "sort-sentence", level: "A1-1",
    words: ["familia.", "mi", "Esta", "es"],
    answer: ["Esta", "es", "mi", "familia."],
    explanation: "句型：esta（這個）+ es（是）+ mi（我的）+ familia（家人）。",
    relatedWords: ["familia", "mi"],
  },
  {
    id: "fam-06", topicId: "family", type: "error-correct", level: "A1-2",
    prompt: "Mi abuela es alto.",
    answer: "Mi abuela es alta.",
    explanation: "西語形容詞要和名詞性別一致。abuela（奶奶）是陰性，所以要用 alta，不是 alto。",
    relatedWords: ["abuela", "alta"],
  },
  {
    id: "fam-07", topicId: "family", type: "cn-to-es", level: "A1-1",
    prompt: "她非常慈愛。",
    answer: "Ella es muy cariñosa.",
    explanation: "cariñoso（男性）→ cariñosa（女性）。描述女性時，以 -o 結尾的形容詞要改為 -a。",
    relatedWords: ["cariñoso", "ella", "muy"],
  },
  {
    id: "fam-08", topicId: "family", type: "es-to-cn", level: "A1-1",
    prompt: "Mi tío es joven y divertido.",
    answer: "我叔叔年輕又有趣。",
    explanation: "y（和/又）連接兩個形容詞。joven（年輕的）+ divertido（有趣的）都是陽性形式。",
    relatedWords: ["tío", "joven", "divertido"],
  },
  {
    id: "fam-09", topicId: "family", type: "fill-blank", level: "A1-1",
    blank: "Somos una familia ___.",
    options: ["grande", "gran", "grandes", "grand"],
    answer: "grande",
    explanation: "grande（大的）放在名詞後面用完整形式。放在名詞前面才縮短為 gran：una gran familia。",
    relatedWords: ["grande"],
  },
  {
    id: "fam-10", topicId: "family", type: "cn-to-es", level: "A1-2",
    prompt: "我和父母同住。",
    answer: "Vivo con mis padres.",
    explanation: "mis（我的，複數）搭配複數名詞 padres（父母）。con 是「和/與」。",
    relatedWords: ["vivir", "mis", "padres"],
  },
  {
    id: "fam-11", topicId: "family", type: "es-to-cn", level: "A1-2",
    prompt: "Mi padre trabaja en una oficina.",
    answer: "我爸爸在辦公室工作。",
    explanation: "trabaja 是 trabajar（工作）的第三人稱單數。en 表示位置：en una oficina（在辦公室）。",
    relatedWords: ["padre", "trabajar"],
  },
  {
    id: "fam-12", topicId: "family", type: "fill-blank", level: "A1-2",
    blank: "Mi hermano ___ en la universidad.",
    options: ["estudia", "estudiar", "estudio", "estudias"],
    answer: "estudia",
    explanation: "estudia 是 estudiar（學習）的第三人稱單數（他/她）。hermano（兄弟）是第三人稱。",
    relatedWords: ["estudiar", "universidad"],
  },
  {
    id: "fam-13", topicId: "family", type: "cn-to-es", level: "A1-2",
    prompt: "我奶奶有白頭髮。",
    answer: "Mi abuela tiene el pelo blanco.",
    explanation: "「有頭髮」用 tener：tiene el pelo（有頭髮）。blanco（白色，陽性）搭配 pelo（頭髮，陽性）。",
    relatedWords: ["abuela", "pelo", "blanco"],
  },
  {
    id: "fam-14", topicId: "family", type: "sort-sentence", level: "A1-2",
    words: ["padres.", "con", "Vivo", "mis"],
    answer: ["Vivo", "con", "mis", "padres."],
    explanation: "句型：動詞 + con（和）+ mis（我的）+ 名詞（複數）。",
    relatedWords: ["vivir", "padres"],
  },
  {
    id: "fam-15", topicId: "family", type: "error-correct", level: "A1-2",
    prompt: "Tengo dos hermanos y una hermano.",
    answer: "Tengo dos hermanos y un hermano.",
    explanation: "hermano 是陽性名詞，不定冠詞用 un（陽性），不是 una（陰性）。",
    relatedWords: ["hermano"],
  },
  {
    id: "fam-16", topicId: "family", type: "cn-to-es", level: "A1-1",
    prompt: "我有一個姐妹。",
    answer: "Tengo una hermana.",
    explanation: "hermana 是姐妹（陰性），用陰性不定冠詞 una。注意：hermana = 姐妹，hermano = 兄弟。",
    relatedWords: ["hermana", "tener"],
  },
  {
    id: "fam-17", topicId: "family", type: "es-to-cn", level: "A1-2",
    prompt: "¿Cuántos hermanos tienes?",
    answer: "你有幾個兄弟姐妹？",
    explanation: "cuántos（多少，複數）問數量。tienes 是 tener 的第二人稱，hermanos 指兄弟姐妹。",
    relatedWords: ["cuántos", "hermano"],
  },
  {
    id: "fam-18", topicId: "family", type: "fill-blank", level: "A1-2",
    blank: "Mi madre ___ enfermera.",
    options: ["es", "está", "ser", "estoy"],
    answer: "es",
    explanation: "描述職業用 ser（永久性身份），所以用 es（他/她是），不用 está（estar，表示狀態）。",
    relatedWords: ["madre", "ser", "enfermera"],
  },
  {
    id: "fam-19", topicId: "family", type: "sort-sentence", level: "A1-3",
    words: ["muy", "simpático.", "Mi", "y", "es", "abuelo", "alto"],
    answer: ["Mi", "abuelo", "es", "alto", "y", "muy", "simpático."],
    explanation: "描述人物：mi + 稱謂 + es + 形容詞。多個形容詞用 y（和）連接，表示「又…又…」。",
    relatedWords: ["abuelo", "alto", "simpático"],
  },
  {
    id: "fam-20", topicId: "family", type: "free-write", level: "A1-3",
    prompt: "請用西語描述你的一位家人（名字、關係、外貌或個性）。",
    answer: "（示範）Mi madre se llama [名字]. Ella es simpática y cariñosa. Tiene el pelo negro.",
    explanation: "描述家人三要素：1) 名字（se llama）2) 個性（es + 形容詞）3) 外貌（tiene el pelo...）。",
    relatedWords: ["madre", "hermana", "abuelo"],
  },

  // ══════════════════════════════════════════════════════════
  // TOPIC 4: 數字、時間、日期
  // ══════════════════════════════════════════════════════════
  {
    id: "t-01", topicId: "time", type: "cn-to-es", level: "A1-1",
    prompt: "現在幾點？",
    answer: "¿Qué hora es?",
    explanation: "¿Qué hora es? 是問時間的標準句式，字面意思是「什麼小時是？」。",
    relatedWords: ["hora"],
  },
  {
    id: "t-02", topicId: "time", type: "es-to-cn", level: "A1-1",
    prompt: "Son las tres y cuarto.",
    answer: "三點一刻。",
    explanation: "son las 三（點）+ y cuarto（加一刻，15分鐘）= 三點十五分。",
    relatedWords: ["son", "cuarto"],
  },
  {
    id: "t-03", topicId: "time", type: "fill-blank", level: "A1-1",
    blank: "Son las diez ___ cinco.",
    options: ["menos", "y", "con", "de"],
    answer: "menos",
    explanation: "menos（減）表示差幾分：son las diez menos cinco = 差五分十點（= 九點五十五分）。",
    relatedWords: ["menos"],
  },
  {
    id: "t-04", topicId: "time", type: "cn-to-es", level: "A1-1",
    prompt: "三點半。",
    answer: "Son las tres y media.",
    explanation: "y media（加半）表示 30 分鐘：son las tres y media = 三點三十分。",
    relatedWords: ["media"],
  },
  {
    id: "t-05", topicId: "time", type: "sort-sentence", level: "A1-1",
    words: ["hora", "¿Qué", "es?"],
    answer: ["¿Qué", "hora", "es?"],
    explanation: "疑問句語序：¿Qué（什麼）+ hora（小時）+ es（是）?",
    relatedWords: ["hora"],
  },
  {
    id: "t-06", topicId: "time", type: "error-correct", level: "A1-2",
    prompt: "Es las tres.",
    answer: "Son las tres.",
    explanation: "說時間時，除了一點用 'Es la una'，其他時間都用複數 'Son las...'。",
    relatedWords: ["son"],
  },
  {
    id: "t-07", topicId: "time", type: "cn-to-es", level: "A1-1",
    prompt: "今天是星期一。",
    answer: "Hoy es lunes.",
    explanation: "西語的星期名稱不大寫，句型是 Hoy es + 星期名稱。",
    relatedWords: ["hoy", "lunes"],
  },
  {
    id: "t-08", topicId: "time", type: "es-to-cn", level: "A1-2",
    prompt: "Mi cumpleaños es en agosto.",
    answer: "我的生日在八月。",
    explanation: "en + 月份 = 「在某月」。月份名稱不大寫：agosto（八月）。",
    relatedWords: ["cumpleaños", "agosto"],
  },
  {
    id: "t-09", topicId: "time", type: "fill-blank", level: "A1-2",
    blank: "El viernes tengo un ___ de español.",
    options: ["examen", "exámenes", "estudio", "clase"],
    answer: "examen",
    explanation: "examen（考試）是陽性名詞，用 un。¡Buena suerte en tu examen!（考試加油！）",
    relatedWords: ["viernes"],
  },
  {
    id: "t-10", topicId: "time", type: "cn-to-es", level: "A1-2",
    prompt: "我的生日是七月十五日。",
    answer: "Mi cumpleaños es el quince de julio.",
    explanation: "說日期：el + 數字 + de + 月份。quince 是「十五」。注意月份名稱不大寫。",
    relatedWords: ["cumpleaños", "julio"],
  },
  {
    id: "t-11", topicId: "time", type: "error-correct", level: "A1-2",
    prompt: "Son la una y media.",
    answer: "Es la una y media.",
    explanation: "一點鐘特殊：用 'Es la una'（單數 es），因為 una（一）是單數。其他時間用 son。",
    relatedWords: ["media"],
  },
  {
    id: "t-12", topicId: "time", type: "fill-blank", level: "A1-1",
    blank: "¿___ día es hoy?",
    options: ["Qué", "Cuándo", "Cómo", "Dónde"],
    answer: "Qué",
    explanation: "¿Qué día es hoy? = 今天是哪一天？（問星期幾或日期）。qué 是「什麼」。",
    relatedWords: ["hoy"],
  },
  {
    id: "t-13", topicId: "time", type: "cn-to-es", level: "A1-2",
    prompt: "差十分四點。",
    answer: "Son las cuatro menos diez.",
    explanation: "menos（減）表示差幾分鐘：cuatro（四）menos（差）diez（十）= 三點五十。",
    relatedWords: ["menos"],
  },
  {
    id: "t-14", topicId: "time", type: "es-to-cn", level: "A1-2",
    prompt: "¿Quedamos a las seis en punto?",
    answer: "我們約好六點整見面嗎？",
    explanation: "quedar 是「約好見面」，a las seis（在六點），en punto 是「整點」。",
    relatedWords: ["quedar", "punto"],
  },
  {
    id: "t-15", topicId: "time", type: "sort-sentence", level: "A1-2",
    words: ["agosto.", "en", "es", "Mi", "cumpleaños"],
    answer: ["Mi", "cumpleaños", "es", "en", "agosto."],
    explanation: "句型：Mi cumpleaños（我的生日）+ es（是）+ en + 月份名稱。",
    relatedWords: ["cumpleaños", "agosto"],
  },
  {
    id: "t-16", topicId: "time", type: "cn-to-es", level: "A1-1",
    prompt: "今天是七月十日。",
    answer: "Hoy es el diez de julio.",
    explanation: "日期句型：Hoy es el + 數字 + de + 月份。記住：月份不大寫。",
    relatedWords: ["hoy", "julio"],
  },
  {
    id: "t-17", topicId: "time", type: "fill-blank", level: "A1-2",
    blank: "Hoy es ___, el quince de marzo.",
    options: ["lunes", "enero", "mañana", "tarde"],
    answer: "lunes",
    explanation: "日期的完整說法：星期 + el + 日數 + de + 月份。lunes（星期一）和 marzo（三月）都不大寫。",
    relatedWords: ["lunes"],
  },
  {
    id: "t-18", topicId: "time", type: "es-to-cn", level: "A1-3",
    prompt: "¿Cuándo es tu cumpleaños?",
    answer: "你的生日是什麼時候？",
    explanation: "cuándo 是「什麼時候」，用於詢問時間、日期或事件。",
    relatedWords: ["cumpleaños"],
  },
  {
    id: "t-19", topicId: "time", type: "sort-sentence", level: "A1-3",
    words: ["en", "Son", "y", "cuarto.", "las", "tres"],
    answer: ["Son", "las", "tres", "y", "cuarto."],
    explanation: "時間表達：Son las + 數字 + y + 分鐘。cuarto（一刻）表示 15 分鐘。",
    relatedWords: ["son", "cuarto"],
  },
  {
    id: "t-20", topicId: "time", type: "free-write", level: "A1-3",
    prompt: "請用西語說今天的日期、星期幾、以及現在幾點。",
    answer: "（示範）Hoy es lunes, el diez de julio. Son las tres y media.",
    explanation: "組合句：1) Hoy es + 星期 + el + 日期 + de + 月份。2) Son las + 時間。",
    relatedWords: ["hoy", "son"],
  },

  // ══════════════════════════════════════════════════════════
  // TOPIC 5: 日常生活
  // ══════════════════════════════════════════════════════════
  {
    id: "dl-01", topicId: "daily", type: "cn-to-es", level: "A1-1",
    prompt: "我七點起床。",
    answer: "Me levanto a las siete.",
    explanation: "levantarse 是反身動詞，要用 me：me levanto。說時間用 a las + 數字。",
    relatedWords: ["levantarse"],
  },
  {
    id: "dl-02", topicId: "daily", type: "es-to-cn", level: "A1-1",
    prompt: "Desayuno con mi familia.",
    answer: "我和家人吃早餐。",
    explanation: "desayuno 既是動詞（我吃早餐）也是名詞（早餐）。con mi familia = 和我的家人。",
    relatedWords: ["desayunar", "familia"],
  },
  {
    id: "dl-03", topicId: "daily", type: "fill-blank", level: "A1-1",
    blank: "Me ___ a las once.",
    options: ["acuesto", "levanto", "desayuno", "ducho"],
    answer: "acuesto",
    explanation: "acostarse = 睡覺（躺下），me acuesto 是第一人稱。a las once = 在十一點。",
    relatedWords: ["acostarse"],
  },
  {
    id: "dl-04", topicId: "daily", type: "cn-to-es", level: "A1-1",
    prompt: "我坐地鐵去上班。",
    answer: "Voy al trabajo en metro.",
    explanation: "voy（我去）+ al trabajo（去上班）+ en metro（坐地鐵）。al = a + el 的縮寫。",
    relatedWords: ["metro", "trabajo"],
  },
  {
    id: "dl-05", topicId: "daily", type: "sort-sentence", level: "A1-1",
    words: ["a", "las", "Me", "levanto", "siete."],
    answer: ["Me", "levanto", "a", "las", "siete."],
    explanation: "反身動詞句型：Me + 動詞 + a las + 時間。levanto 是 levantarse 的第一人稱。",
    relatedWords: ["levantarse"],
  },
  {
    id: "dl-06", topicId: "daily", type: "error-correct", level: "A1-2",
    prompt: "Me levanto en las siete.",
    answer: "Me levanto a las siete.",
    explanation: "說「在幾點」用介詞 a（不是 en）：a las siete（在七點）。a las 是固定搭配。",
    relatedWords: ["levantarse"],
  },
  {
    id: "dl-07", topicId: "daily", type: "cn-to-es", level: "A1-2",
    prompt: "我六點離開辦公室。",
    answer: "Salgo de la oficina a las seis.",
    explanation: "salgo（我離開，salir 的第一人稱）+ de la oficina（從辦公室）+ a las seis（在六點）。",
    relatedWords: ["salir"],
  },
  {
    id: "dl-08", topicId: "daily", type: "es-to-cn", level: "A1-2",
    prompt: "Siempre desayuno temprano.",
    answer: "我總是很早吃早餐。",
    explanation: "siempre（總是）是頻率副詞，放在動詞前面。temprano（早）是時間副詞。",
    relatedWords: ["siempre", "desayunar", "temprano"],
  },
  {
    id: "dl-09", topicId: "daily", type: "fill-blank", level: "A1-1",
    blank: "Me ducho ___ la mañana.",
    options: ["por", "en", "a", "de"],
    answer: "por",
    explanation: "por la mañana = 在早上（時段）。類似：por la tarde（在下午），por la noche（在晚上）。",
    relatedWords: ["ducharse"],
  },
  {
    id: "dl-10", topicId: "daily", type: "cn-to-es", level: "A1-2",
    prompt: "你幾點睡覺？",
    answer: "¿A qué hora te acuestas?",
    explanation: "問「幾點」用 ¿A qué hora?。te acuestas 是 acostarse 的第二人稱（你）。",
    relatedWords: ["acostarse"],
  },
  {
    id: "dl-11", topicId: "daily", type: "es-to-cn", level: "A1-2",
    prompt: "Salgo de casa a las ocho.",
    answer: "我八點出門。",
    explanation: "salir de casa = 離開家（出門）。a las ocho = 在八點。",
    relatedWords: ["salir"],
  },
  {
    id: "dl-12", topicId: "daily", type: "sort-sentence", level: "A1-2",
    words: ["trabajo", "en", "al", "Voy", "metro."],
    answer: ["Voy", "al", "trabajo", "en", "metro."],
    explanation: "voy（我去）+ al trabajo（去工作）+ en metro（坐地鐵）。注意 al = a + el。",
    relatedWords: ["metro"],
  },
  {
    id: "dl-13", topicId: "daily", type: "fill-blank", level: "A1-2",
    blank: "Normalmente ___ a las ocho.",
    options: ["desayuno", "desayunar", "desayunas", "desayuna"],
    answer: "desayuno",
    explanation: "第一人稱（我）用 desayuno。normalmente（通常/一般來說）是頻率副詞。",
    relatedWords: ["desayunar"],
  },
  {
    id: "dl-14", topicId: "daily", type: "cn-to-es", level: "A1-1",
    prompt: "我早上洗澡。",
    answer: "Me ducho por la mañana.",
    explanation: "ducharse 是反身動詞，me ducho = 我洗澡。por la mañana = 在早上時段。",
    relatedWords: ["ducharse"],
  },
  {
    id: "dl-15", topicId: "daily", type: "error-correct", level: "A1-2",
    prompt: "Me levanto las siete.",
    answer: "Me levanto a las siete.",
    explanation: "說「在幾點」必須有介詞 a：a las siete（在七點）。不能省略 a。",
    relatedWords: ["levantarse"],
  },
  {
    id: "dl-16", topicId: "daily", type: "es-to-cn", level: "A1-2",
    prompt: "¿A qué hora te levantas normalmente?",
    answer: "你通常幾點起床？",
    explanation: "normalmente（通常）修飾整個句子。te levantas 是 levantarse 的第二人稱（你）。",
    relatedWords: ["levantarse"],
  },
  {
    id: "dl-17", topicId: "daily", type: "cn-to-es", level: "A1-2",
    prompt: "我總是很晚睡覺。",
    answer: "Siempre me acuesto tarde.",
    explanation: "siempre（總是）放在句首或動詞前。tarde（晚）是副詞，說明時間狀態。",
    relatedWords: ["siempre", "acostarse", "tarde"],
  },
  {
    id: "dl-18", topicId: "daily", type: "fill-blank", level: "A1-1",
    blank: "Salgo de casa ___ las ocho.",
    options: ["a", "en", "de", "para"],
    answer: "a",
    explanation: "說「在幾點」用 a：a las ocho（在八點）。a + las 是表示時間的固定搭配。",
    relatedWords: ["salir"],
  },
  {
    id: "dl-19", topicId: "daily", type: "sort-sentence", level: "A1-3",
    words: ["siete,", "Me", "a", "y", "las", "levanto", "desayuno.", "luego"],
    answer: ["Me", "levanto", "a", "las", "siete,", "y", "luego", "desayuno."],
    explanation: "連接兩個動作用 y luego（然後）：先起床，然後吃早餐。",
    relatedWords: ["levantarse", "desayunar"],
  },
  {
    id: "dl-20", topicId: "daily", type: "free-write", level: "A1-3",
    prompt: "請用 3-4 句西語描述你的一天（從起床到睡覺）。",
    answer: "（示範）Me levanto a las siete. Desayuno con mi familia. Voy al trabajo en metro. Me acuesto a las once.",
    explanation: "常用詞：levantarse（起床）desayunar（早餐）trabajar（工作）acostarse（睡覺）。",
    relatedWords: ["levantarse", "desayunar", "acostarse"],
  },

  // ══════════════════════════════════════════════════════════
  // TOPIC 6: 食物與餐廳
  // ══════════════════════════════════════════════════════════
  {
    id: "food-01", topicId: "food", type: "cn-to-es", level: "A1-1",
    prompt: "我想要一杯拿鐵。",
    answer: "Quiero un café con leche.",
    explanation: "quiero（我想要）來自 querer。café con leche 字面是「加牛奶的咖啡」= 拿鐵。",
    relatedWords: ["quiero", "café", "leche"],
  },
  {
    id: "food-02", topicId: "food", type: "es-to-cn", level: "A1-1",
    prompt: "¿Qué desea?",
    answer: "您想要什麼？",
    explanation: "desea 是 desear（想要，正式）的第三人稱敬語（usted）。用於服務業對客人。",
    relatedWords: ["desear"],
  },
  {
    id: "food-03", topicId: "food", type: "fill-blank", level: "A1-1",
    blank: "_____ un café con leche, por favor.",
    options: ["Quiero", "Quieres", "Quiere", "Queremos"],
    answer: "Quiero",
    explanation: "quiero 是 querer 的第一人稱（我）：yo quiero（我想要）。點餐時加 por favor 更有禮貌。",
    relatedWords: ["quiero"],
  },
  {
    id: "food-04", topicId: "food", type: "cn-to-es", level: "A1-1",
    prompt: "結帳，麻煩你。",
    answer: "La cuenta, por favor.",
    explanation: "la cuenta 是「帳單」（陰性名詞）。por favor 放在句尾表示有禮貌的請求。",
    relatedWords: ["cuenta", "por favor"],
  },
  {
    id: "food-05", topicId: "food", type: "sort-sentence", level: "A1-1",
    words: ["favor.", "por", "café,", "con", "Quiero", "un", "leche,"],
    answer: ["Quiero", "un", "café", "con", "leche,", "por", "favor."],
    explanation: "點餐句型：Quiero + 冠詞 + 飲品 + por favor（請）。",
    relatedWords: ["quiero", "café", "leche"],
  },
  {
    id: "food-06", topicId: "food", type: "error-correct", level: "A1-2",
    prompt: "Quiero una café.",
    answer: "Quiero un café.",
    explanation: "café（咖啡）是陽性名詞，冠詞用 un（陽性），不是 una（陰性）。",
    relatedWords: ["café"],
  },
  {
    id: "food-07", topicId: "food", type: "cn-to-es", level: "A1-2",
    prompt: "我非常喜歡辣食。",
    answer: "Me encanta la comida picante.",
    explanation: "me encanta（我超喜歡）比 me gusta 更強烈。comida 是「食物」（陰性），picante 是「辣的」。",
    relatedWords: ["encanta", "comida", "picante"],
  },
  {
    id: "food-08", topicId: "food", type: "es-to-cn", level: "A1-1",
    prompt: "¿Algo más?",
    answer: "還要其他的嗎？",
    explanation: "algo（某些東西/還有）+ más（更多）= 「還要別的嗎？」服務員常說的句子。",
    relatedWords: ["algo", "más"],
  },
  {
    id: "food-09", topicId: "food", type: "fill-blank", level: "A1-1",
    blank: "Me gusta ___ el chocolate.",
    options: ["mucho", "muy", "bastante", "poco"],
    answer: "mucho",
    explanation: "me gusta mucho = 我非常喜歡。mucho 是副詞修飾 gusta，而不是形容詞修飾名詞。",
    relatedWords: ["gustar", "mucho"],
  },
  {
    id: "food-10", topicId: "food", type: "cn-to-es", level: "A1-2",
    prompt: "一共多少錢？",
    answer: "¿Cuánto es en total?",
    explanation: "cuánto（多少）用於問價格。en total 是「總計」。也可以說 ¿Cuánto es?（更簡短）。",
    relatedWords: ["cuánto", "total"],
  },
  {
    id: "food-11", topicId: "food", type: "es-to-cn", level: "A1-2",
    prompt: "Prefiero el té verde.",
    answer: "我比較喜歡綠茶。",
    explanation: "prefiero 是 preferir（偏好）的第一人稱。el té verde = 綠茶（verde = 綠色的）。",
    relatedWords: ["preferir"],
  },
  {
    id: "food-12", topicId: "food", type: "fill-blank", level: "A1-2",
    blank: "No me ___ el café amargo.",
    options: ["gusta", "gustan", "encanta", "gusto"],
    answer: "gusta",
    explanation: "café 是單數，所以用 gusta（單數）。如果是複數（las frutas），用 gustan。",
    relatedWords: ["gustar", "amargo"],
  },
  {
    id: "food-13", topicId: "food", type: "cn-to-es", level: "A1-1",
    prompt: "是的，當然。",
    answer: "Sí, por supuesto.",
    explanation: "por supuesto 是「當然」的表達方式，語氣肯定。相當於 claro（當然/清楚）。",
    relatedWords: ["sí"],
  },
  {
    id: "food-14", topicId: "food", type: "sort-sentence", level: "A1-1",
    words: ["cuenta,", "La", "favor.", "por"],
    answer: ["La", "cuenta,", "por", "favor."],
    explanation: "La cuenta（帳單）+ por favor（麻煩）= 結帳請求句。La 是定冠詞（陰性）。",
    relatedWords: ["cuenta"],
  },
  {
    id: "food-15", topicId: "food", type: "error-correct", level: "A1-2",
    prompt: "Me gustan el café.",
    answer: "Me gusta el café.",
    explanation: "café 是單數，gustar 要和主語一致：el café（單數）→ me gusta（單數形式）。",
    relatedWords: ["gustar"],
  },
  {
    id: "food-16", topicId: "food", type: "cn-to-es", level: "A1-1",
    prompt: "馬上來。",
    answer: "Enseguida.",
    explanation: "Enseguida 是「馬上/立刻」，服務員常用這個詞回應客人的點單。",
    relatedWords: ["enseguida"],
  },
  {
    id: "food-17", topicId: "food", type: "es-to-cn", level: "A1-2",
    prompt: "Son cinco euros con veinte céntimos.",
    answer: "總共是五點二歐元。",
    explanation: "說西班牙的金額用 con 代替小數點：cinco euros con veinte = 5.20 歐元。",
    relatedWords: ["son", "euros"],
  },
  {
    id: "food-18", topicId: "food", type: "fill-blank", level: "A1-2",
    blank: "¿___ tarjeta de crédito?",
    options: ["Aceptan", "Acepta", "Aceptas", "Acepto"],
    answer: "Aceptan",
    explanation: "aceptan 是 aceptar 的第三人稱複數（他們），用於詢問商家政策：¿Aceptan tarjeta?",
    relatedWords: ["aceptar", "tarjeta"],
  },
  {
    id: "food-19", topicId: "food", type: "sort-sentence", level: "A1-3",
    words: ["gusta", "Me", "picante.", "comida", "la", "encanta", "y", "me"],
    answer: ["Me", "gusta", "la", "comida", "y", "me", "encanta", "lo", "picante."],
    explanation: "gustar 接名詞（la comida）；encantar 強調程度更強。y 連接兩個喜好。",
    hint: "示範：Me gusta la comida y me encanta lo picante.",
    relatedWords: ["gustar", "encantar"],
  },
  {
    id: "food-20", topicId: "food", type: "free-write", level: "A1-3",
    prompt: "請用西語向服務員點一杯飲料和一份食物，並問價格。",
    answer: "（示範）Quiero un café con leche y un croissant, por favor. ¿Cuánto es en total?",
    explanation: "點餐流程：Quiero + 食物/飲料 + por favor → 問價格：¿Cuánto es?",
    relatedWords: ["quiero", "cuenta", "cuánto"],
  },

  // ══════════════════════════════════════════════════════════
  // TOPIC 7: 購物與價格
  // ══════════════════════════════════════════════════════════
  {
    id: "sh-01", topicId: "shopping", type: "cn-to-es", level: "A1-1",
    prompt: "我在找一件 T 恤。",
    answer: "Estoy buscando una camiseta.",
    explanation: "estoy buscando = 我正在找（estar + gerundio 現在進行式）。camiseta（T 恤）是陰性名詞。",
    relatedWords: ["buscar", "camiseta"],
  },
  {
    id: "sh-02", topicId: "shopping", type: "es-to-cn", level: "A1-1",
    prompt: "¿De qué talla?",
    answer: "什麼尺寸的？",
    explanation: "talla 是「尺碼」（陰性名詞）。¿De qué talla? 是店員詢問顧客尺寸的常用問法。",
    relatedWords: ["talla"],
  },
  {
    id: "sh-03", topicId: "shopping", type: "fill-blank", level: "A1-1",
    blank: "Estoy ____ una camiseta azul.",
    options: ["buscando", "buscar", "busco", "buscas"],
    answer: "buscando",
    explanation: "estar + -ando 表示現在進行式：estoy buscando = 我正在找。-ar 動詞 + ando。",
    relatedWords: ["buscar"],
  },
  {
    id: "sh-04", topicId: "shopping", type: "cn-to-es", level: "A1-2",
    prompt: "這個比較便宜。",
    answer: "Este es más barato.",
    explanation: "más + 形容詞 = 比較...：más barato（比較便宜）。este 指陽性單數的物品。",
    relatedWords: ["barato"],
  },
  {
    id: "sh-05", topicId: "shopping", type: "sort-sentence", level: "A1-1",
    words: ["buscando", "Estoy", "camiseta.", "una"],
    answer: ["Estoy", "buscando", "una", "camiseta."],
    explanation: "句型：estoy（我在）+ buscando（找）+ una camiseta（一件 T 恤）。",
    relatedWords: ["buscar", "camiseta"],
  },
  {
    id: "sh-06", topicId: "shopping", type: "error-correct", level: "A1-2",
    prompt: "¿Tienen algo más cheap?",
    answer: "¿Tienen algo más barato?",
    explanation: "不能在西語句子裡混用英語。「便宜的」是 barato（陽性）/ barata（陰性）。",
    relatedWords: ["barato"],
  },
  {
    id: "sh-07", topicId: "shopping", type: "cn-to-es", level: "A1-1",
    prompt: "有藍色的嗎？",
    answer: "¿Lo tienen en azul?",
    explanation: "lo（它）指前面提到的商品。tienen 是「你們有」（第三人稱複數，指店員）。en azul 是「藍色的」。",
    relatedWords: ["azul"],
  },
  {
    id: "sh-08", topicId: "shopping", type: "es-to-cn", level: "A1-1",
    prompt: "Me lo llevo.",
    answer: "我要買這個。",
    explanation: "me lo llevo 字面是「我把它帶走」，是購物時說「我要這個/我買了」的常用說法。",
    relatedWords: ["llevarse"],
  },
  {
    id: "sh-09", topicId: "shopping", type: "fill-blank", level: "A1-1",
    blank: "¿Lo ___ en azul?",
    options: ["tienen", "tenemos", "tienes", "tengo"],
    answer: "tienen",
    explanation: "tienen 是 tener 的第三人稱複數，對店員（他們）說：¿Lo tienen?（他們有嗎？）",
    relatedWords: ["azul"],
  },
  {
    id: "sh-10", topicId: "shopping", type: "cn-to-es", level: "A1-2",
    prompt: "我要用現金付。",
    answer: "Voy a pagar en efectivo.",
    explanation: "voy a + 動詞原形 = 打算做某事（近未來）。en efectivo = 用現金。",
    relatedWords: ["pagar", "efectivo"],
  },
  {
    id: "sh-11", topicId: "shopping", type: "es-to-cn", level: "A1-2",
    prompt: "¿En qué le puedo ayudar?",
    answer: "我可以怎樣幫您？",
    explanation: "le（您，敬語間接受格）puedo ayudar（我可以幫助）。這是正式的服務語。",
    relatedWords: ["ayudar"],
  },
  {
    id: "sh-12", topicId: "shopping", type: "fill-blank", level: "A1-2",
    blank: "Voy a ___ en efectivo.",
    options: ["pagar", "pago", "paga", "pagues"],
    answer: "pagar",
    explanation: "voy a + 動詞原形（infinitivo）。pagar 是動詞原形（付款），不需要變位。",
    relatedWords: ["pagar", "efectivo"],
  },
  {
    id: "sh-13", topicId: "shopping", type: "cn-to-es", level: "A1-2",
    prompt: "這個款式很受歡迎。",
    answer: "Este modelo es muy popular.",
    explanation: "modelo（款式，陽性）+ es + muy popular。popular 不需要性別變化（男女相同）。",
    relatedWords: ["modelo"],
  },
  {
    id: "sh-14", topicId: "shopping", type: "sort-sentence", level: "A1-2",
    words: ["efectivo.", "pagar", "Voy", "en", "a"],
    answer: ["Voy", "a", "pagar", "en", "efectivo."],
    explanation: "voy a + 動詞原形：表示即將要做的事。en efectivo（用現金）是付款方式。",
    relatedWords: ["pagar", "efectivo"],
  },
  {
    id: "sh-15", topicId: "shopping", type: "error-correct", level: "A1-2",
    prompt: "El talla mediana, por favor.",
    answer: "Talla mediana, por favor.",
    explanation: "talla（尺碼）是陰性名詞，但說尺碼時通常不加定冠詞。直接說 talla mediana 就可以。",
    relatedWords: ["talla"],
  },
  {
    id: "sh-16", topicId: "shopping", type: "cn-to-es", level: "A1-2",
    prompt: "有折扣嗎？",
    answer: "¿Tienen descuento?",
    explanation: "descuento（折扣，陽性名詞）。¿Tienen descuento? = 他們有折扣嗎？",
    relatedWords: ["descuento"],
  },
  {
    id: "sh-17", topicId: "shopping", type: "es-to-cn", level: "A1-2",
    prompt: "¿Puedo probármela?",
    answer: "我可以試穿嗎？",
    explanation: "puedo（我可以）+ probar（試）+ me（反身代詞）+ la（它，指衣服）。",
    relatedWords: ["probar"],
  },
  {
    id: "sh-18", topicId: "shopping", type: "fill-blank", level: "A1-2",
    blank: "El probador está al ___.",
    options: ["fondo", "lado", "frente", "centro"],
    answer: "fondo",
    explanation: "al fondo = 「在最裡面/最深處」。probador 是「試衣間」，常在店舖最裡面。",
    relatedWords: ["probador"],
  },
  {
    id: "sh-19", topicId: "shopping", type: "sort-sentence", level: "A1-3",
    words: ["cambio.", "el", "tiene", "Aquí"],
    answer: ["Aquí", "tiene", "el", "cambio."],
    explanation: "Aquí tiene（這裡給您）是服務員交東西時的說法。el cambio = 找零。",
    relatedWords: ["cambio"],
  },
  {
    id: "sh-20", topicId: "shopping", type: "free-write", level: "A1-3",
    prompt: "請用西語模擬在商店的對話（詢問是否有某顏色，問價格，並說要購買）。",
    answer: "（示範）¿Lo tienen en negro? — ¿Cuánto cuesta? — Me lo llevo.",
    explanation: "購物三部曲：1) 詢問顏色 2) 詢問價格（¿Cuánto cuesta?）3) 決定購買（Me lo llevo）",
    relatedWords: ["azul", "precio", "llevarse"],
  },

  // ══════════════════════════════════════════════════════════
  // TOPIC 8: 方向與交通
  // ══════════════════════════════════════════════════════════
  {
    id: "dir-01", topicId: "directions", type: "cn-to-es", level: "A1-1",
    prompt: "打擾一下，博物館在哪裡？",
    answer: "Perdona, ¿dónde está el museo?",
    explanation: "perdona（打擾一下）是問路的開場語。dónde está...?（...在哪裡？）詢問位置。",
    relatedWords: ["perdona", "museo"],
  },
  {
    id: "dir-02", topicId: "directions", type: "es-to-cn", level: "A1-1",
    prompt: "Siga todo recto.",
    answer: "一直走直。",
    explanation: "siga 是 seguir 的命令式（對陌生人/正式）。todo recto = 一直直走。",
    relatedWords: ["seguir", "recto"],
  },
  {
    id: "dir-03", topicId: "directions", type: "fill-blank", level: "A1-1",
    blank: "Gire a la ___.",
    options: ["derecha", "derecho", "derechos", "derechas"],
    answer: "derecha",
    explanation: "a la derecha（向右），a la izquierda（向左）。derecha 是陰性名詞，用 la。",
    relatedWords: ["derecha", "izquierda"],
  },
  {
    id: "dir-04", topicId: "directions", type: "cn-to-es", level: "A1-1",
    prompt: "向右轉。",
    answer: "Gire a la derecha.",
    explanation: "gire 是 girar 的命令式（對陌生人）。a la derecha = 向右。對朋友可說 gira。",
    relatedWords: ["girar", "derecha"],
  },
  {
    id: "dir-05", topicId: "directions", type: "sort-sentence", level: "A1-1",
    words: ["recto.", "todo", "Siga"],
    answer: ["Siga", "todo", "recto."],
    explanation: "命令式句型：動詞命令式（Siga）+ 方向說明（todo recto）。",
    relatedWords: ["seguir", "recto"],
  },
  {
    id: "dir-06", topicId: "directions", type: "error-correct", level: "A1-2",
    prompt: "Gira a la derechos.",
    answer: "Gire a la derecha.",
    explanation: "兩個問題：1) gira 是非正式，問路通常用正式 gire；2) derecha 是單數陰性，不是 derechos。",
    relatedWords: ["girar", "derecha"],
  },
  {
    id: "dir-07", topicId: "directions", type: "cn-to-es", level: "A1-2",
    prompt: "銀行在公園附近。",
    answer: "El banco está cerca del parque.",
    explanation: "cerca de（在…附近）。de + el = del（縮寫）：cerca del parque（在公園附近）。",
    relatedWords: ["banco", "parque", "cerca"],
  },
  {
    id: "dir-08", topicId: "directions", type: "es-to-cn", level: "A1-1",
    prompt: "¿Hay un supermercado por aquí?",
    answer: "這附近有超市嗎？",
    explanation: "hay（有）用於表示存在。por aquí = 在這附近。hay un + 地點 = 有一個…。",
    relatedWords: ["supermercado", "aquí"],
  },
  {
    id: "dir-09", topicId: "directions", type: "fill-blank", level: "A1-1",
    blank: "El banco está ___ del parque.",
    options: ["cerca", "lejos", "enfrente", "encima"],
    answer: "cerca",
    explanation: "cerca de（附近）最常用。cerca del = cerca de + el（縮寫）。",
    relatedWords: ["cerca", "banco", "parque"],
  },
  {
    id: "dir-10", topicId: "directions", type: "cn-to-es", level: "A1-2",
    prompt: "怎樣去市中心？",
    answer: "¿Cómo llego al centro?",
    explanation: "llego 是 llegar（到達）的第一人稱。al centro（到市中心）= a + el centro。",
    relatedWords: ["metro"],
  },
  {
    id: "dir-11", topicId: "directions", type: "es-to-cn", level: "A1-2",
    prompt: "Está a diez minutos andando.",
    answer: "步行十分鐘。",
    explanation: "a + 時間 + andando = 步行多久可到達。andando 是 andar（走路）的現在分詞。",
    relatedWords: ["andando"],
  },
  {
    id: "dir-12", topicId: "directions", type: "fill-blank", level: "A1-2",
    blank: "¿Cómo ___ al centro?",
    options: ["llego", "voy", "llega", "llegamos"],
    answer: "llego",
    explanation: "llego 是 llegar（到達）的第一人稱（我）。¿Cómo llego...? = 我怎樣到達…?",
    relatedWords: ["metro"],
  },
  {
    id: "dir-13", topicId: "directions", type: "cn-to-es", level: "A1-2",
    prompt: "在這個站搭地鐵。",
    answer: "Coge el metro en esta estación.",
    explanation: "coger（搭乘，西班牙用法）。en esta estación = 在這個站。拉丁美洲說 tomar el metro。",
    relatedWords: ["metro", "estación"],
  },
  {
    id: "dir-14", topicId: "directions", type: "sort-sentence", level: "A1-2",
    words: ["del", "está", "banco", "El", "cerca", "parque."],
    answer: ["El", "banco", "está", "cerca", "del", "parque."],
    explanation: "位置句型：主語 + está（在）+ 位置介詞片語（cerca del parque）。",
    relatedWords: ["banco", "cerca", "parque"],
  },
  {
    id: "dir-15", topicId: "directions", type: "error-correct", level: "A1-2",
    prompt: "El parada de metro está lejos.",
    answer: "La parada de metro está lejos.",
    explanation: "parada（站/站牌）是陰性名詞，冠詞用 la，不是 el。el metro vs. la parada de metro。",
    relatedWords: ["parada", "metro"],
  },
  {
    id: "dir-16", topicId: "directions", type: "cn-to-es", level: "A1-1",
    prompt: "地鐵站很遠。",
    answer: "La parada de metro está lejos.",
    explanation: "parada（站）+ de metro（地鐵的）。lejos = 遠。cerca = 近，lejos = 遠，記住對比。",
    relatedWords: ["parada", "metro", "lejos"],
  },
  {
    id: "dir-17", topicId: "directions", type: "es-to-cn", level: "A1-2",
    prompt: "¿Dónde tengo que hacer trasbordo?",
    answer: "我在哪裡轉車？",
    explanation: "tengo que + 動詞原形 = 我必須…。hacer trasbordo = 轉車/換乘。",
    relatedWords: ["trasbordo"],
  },
  {
    id: "dir-18", topicId: "directions", type: "fill-blank", level: "A1-2",
    blank: "Está ___ del ayuntamiento.",
    options: ["enfrente", "detrás", "cerca", "encima"],
    answer: "enfrente",
    explanation: "enfrente de = 在…對面。ayuntamiento = 市政廳。enfrente del = enfrente de + el。",
    relatedWords: ["enfrente"],
  },
  {
    id: "dir-19", topicId: "directions", type: "cn-to-es", level: "A1-2",
    prompt: "需要多長時間？",
    answer: "¿Cuánto tarda?",
    explanation: "tardar（花時間）。¿Cuánto tarda? = 需要多久？也可說 ¿Cuánto tiempo tarda?",
    relatedWords: ["tardar"],
  },
  {
    id: "dir-20", topicId: "directions", type: "free-write", level: "A1-3",
    prompt: "請用西語給一個陌生人指路，從地鐵站走到公園（直走、向右轉、公園在銀行附近）。",
    answer: "（示範）Siga todo recto. Luego gire a la derecha. El parque está cerca del banco.",
    explanation: "指路三步：1) Siga todo recto 2) Gire a la + 方向 3) 說明目的地位置。",
    relatedWords: ["recto", "derecha", "cerca"],
  },

  // ══════════════════════════════════════════════════════════
  // TOPIC 9: 旅行與週末
  // ══════════════════════════════════════════════════════════
  {
    id: "lei-01", topicId: "leisure", type: "cn-to-es", level: "A1-1",
    prompt: "你這個週末打算做什麼？",
    answer: "¿Qué vas a hacer este fin de semana?",
    explanation: "vas a + 動詞原形 = 你打算…（近未來）。fin de semana = 週末。",
    relatedWords: ["fin de semana"],
  },
  {
    id: "lei-02", topicId: "leisure", type: "es-to-cn", level: "A1-1",
    prompt: "Voy a quedar con unos amigos.",
    answer: "我打算和朋友見面。",
    explanation: "voy a（我打算）+ quedar（見面/約好）+ con unos amigos（和幾個朋友）。",
    relatedWords: ["quedar"],
  },
  {
    id: "lei-03", topicId: "leisure", type: "fill-blank", level: "A1-1",
    blank: "¿Qué ___ a hacer este fin de semana?",
    options: ["vas", "voy", "va", "van"],
    answer: "vas",
    explanation: "vas a（你打算）= ir a 的第二人稱（tú）形式。問對方打算做什麼。",
    relatedWords: ["fin de semana"],
  },
  {
    id: "lei-04", topicId: "leisure", type: "cn-to-es", level: "A1-1",
    prompt: "我打算去海灘。",
    answer: "Voy a ir a la playa.",
    alternates: ["Pienso ir a la playa."],
    explanation: "voy a ir（我打算去）。也可以說 pienso ir（我打算去）或 quiero ir（我想去）。",
    relatedWords: ["playa"],
  },
  {
    id: "lei-05", topicId: "leisure", type: "sort-sentence", level: "A1-1",
    words: ["a", "la", "Voy", "ir", "playa.", "a"],
    answer: ["Voy", "a", "ir", "a", "la", "playa."],
    explanation: "voy a + 動詞原形（ir）+ a + 地點（la playa）。",
    relatedWords: ["playa"],
  },
  {
    id: "lei-06", topicId: "leisure", type: "error-correct", level: "A1-2",
    prompt: "Pienso ir la playa.",
    answer: "Pienso ir a la playa.",
    explanation: "去某地要加介詞 a：ir a la playa（去海灘）。不能省略 a。",
    relatedWords: ["playa"],
  },
  {
    id: "lei-07", topicId: "leisure", type: "cn-to-es", level: "A1-2",
    prompt: "你想跟我們一起來嗎？",
    answer: "¿Quieres venir con nosotros?",
    explanation: "quieres venir（你想來嗎）+ con nosotros（和我們）。nosotros = 我們。",
    relatedWords: ["nosotros"],
  },
  {
    id: "lei-08", topicId: "leisure", type: "es-to-cn", level: "A1-2",
    prompt: "¿Tienes planes para el sábado?",
    answer: "你星期六有計劃嗎？",
    explanation: "planes（計劃，複數）。para el sábado = 為了/對於星期六。",
    relatedWords: ["planes", "sábado"],
  },
  {
    id: "lei-09", topicId: "leisure", type: "fill-blank", level: "A1-1",
    blank: "¿___ venir con nosotros?",
    options: ["Quieres", "Quiero", "Queremos", "Quiere"],
    answer: "Quieres",
    explanation: "quieres 是 querer 的第二人稱（你）。問對方「你想要嗎？」",
    relatedWords: ["nosotros"],
  },
  {
    id: "lei-10", topicId: "leisure", type: "cn-to-es", level: "A1-1",
    prompt: "我喜歡踢足球。",
    answer: "Me gusta jugar al fútbol.",
    explanation: "jugar a + 球類運動（加 al = a + el）：jugar al fútbol（踢足球）、jugar al tenis（打網球）。",
    relatedWords: ["jugar", "fútbol"],
  },
  {
    id: "lei-11", topicId: "leisure", type: "es-to-cn", level: "A1-2",
    prompt: "Practico natación tres veces a la semana.",
    answer: "我每週游泳三次。",
    explanation: "tres veces a la semana = 每週三次。veces（次），a la semana（每週）。",
    relatedWords: ["natación", "practicar"],
  },
  {
    id: "lei-12", topicId: "leisure", type: "fill-blank", level: "A1-2",
    blank: "Me gusta jugar ___ fútbol.",
    options: ["al", "a", "el", "del"],
    answer: "al",
    explanation: "jugar a + 球類運動。a + el = al（縮寫）：jugar al fútbol。不能省略 a 或分開寫。",
    relatedWords: ["jugar", "fútbol"],
  },
  {
    id: "lei-13", topicId: "leisure", type: "cn-to-es", level: "A1-2",
    prompt: "我比較喜歡看書或聽音樂。",
    answer: "Prefiero leer o escuchar música.",
    explanation: "preferir（偏好）+ 動詞原形。o（或）連接兩個選擇：leer（看書）o escuchar música（聽音樂）。",
    relatedWords: ["preferir", "escuchar", "música"],
  },
  {
    id: "lei-14", topicId: "leisure", type: "sort-sentence", level: "A1-2",
    words: ["fútbol.", "al", "jugar", "gusta", "Me"],
    answer: ["Me", "gusta", "jugar", "al", "fútbol."],
    explanation: "me gusta + 動詞原形（jugar）+ al + 運動（fútbol）。",
    relatedWords: ["jugar", "fútbol"],
  },
  {
    id: "lei-15", topicId: "leisure", type: "error-correct", level: "A1-2",
    prompt: "Practico el natación.",
    answer: "Practico natación.",
    explanation: "practicar（練習）後的運動名詞通常不加冠詞：practico natación（不是 la natación）。",
    relatedWords: ["natación", "practicar"],
  },
  {
    id: "lei-16", topicId: "leisure", type: "cn-to-es", level: "A1-2",
    prompt: "你那邊天氣怎樣？",
    answer: "¿Qué tiempo hace ahí?",
    explanation: "¿Qué tiempo hace? = 天氣怎樣？hacer 用於天氣表達。ahí = 那邊（那裡）。",
    relatedWords: ["tiempo"],
  },
  {
    id: "lei-17", topicId: "leisure", type: "es-to-cn", level: "A1-2",
    prompt: "Hace mucho sol y calor.",
    answer: "陽光很好，很熱。",
    explanation: "hace sol（有陽光），hace calor（天氣熱）。mucho（很多/很強）修飾 sol 和 calor。",
    relatedWords: ["sol", "calor"],
  },
  {
    id: "lei-18", topicId: "leisure", type: "fill-blank", level: "A1-1",
    blank: "¿Qué ___ hace?",
    options: ["tiempo", "hora", "día", "clima"],
    answer: "tiempo",
    explanation: "¿Qué tiempo hace? 是問天氣的固定句式。tiempo 在這裡是「天氣」的意思。",
    relatedWords: ["tiempo"],
  },
  {
    id: "lei-19", topicId: "leisure", type: "sort-sentence", level: "A1-3",
    words: ["la", "planes", "¿Tienes", "semana?", "para", "esta"],
    answer: ["¿Tienes", "planes", "para", "esta", "semana?"],
    explanation: "¿Tienes planes para...? = 你有…的計劃嗎？esta semana = 這週。",
    hint: "示範：¿Tienes planes para esta semana?",
    relatedWords: ["planes"],
  },
  {
    id: "lei-20", topicId: "leisure", type: "free-write", level: "A1-3",
    prompt: "請用西語說說你這個週末的計劃（做什麼運動、天氣怎樣、和誰一起）。",
    answer: "（示範）Este fin de semana voy a jugar al fútbol con mis amigos. Hace sol y calor.",
    explanation: "週末計劃句：fin de semana + voy a + 活動 + con + 人物 + 天氣描述。",
    relatedWords: ["fin de semana", "jugar", "tiempo"],
  },

  // ══════════════════════════════════════════════════════════
  // TOPIC 10: 身體與健康
  // ══════════════════════════════════════════════════════════
  {
    id: "h-01", topicId: "health", type: "cn-to-es", level: "A1-1",
    prompt: "我頭痛。",
    answer: "Me duele la cabeza.",
    explanation: "doler 用法同 gustar，主語是身體部位：me duele la cabeza = 頭讓我痛。",
    relatedWords: ["doler", "cabeza"],
  },
  {
    id: "h-02", topicId: "health", type: "es-to-cn", level: "A1-1",
    prompt: "Tengo fiebre y tos.",
    answer: "我發燒和咳嗽。",
    explanation: "tengo（我有，tener 第一人稱）。fiebre（發燒）和 tos（咳嗽）都是常見病症。",
    relatedWords: ["fiebre", "tos"],
  },
  {
    id: "h-03", topicId: "health", type: "fill-blank", level: "A1-1",
    blank: "Me ___ la cabeza.",
    options: ["duele", "duelen", "dolor", "duelo"],
    answer: "duele",
    explanation: "cabeza（頭）是單數，所以用 duele（單數）。如果是複數（los pies），用 duelen。",
    relatedWords: ["doler", "cabeza"],
  },
  {
    id: "h-04", topicId: "health", type: "cn-to-es", level: "A1-1",
    prompt: "我感覺不舒服。",
    answer: "No me encuentro bien.",
    alternates: ["Me siento mal."],
    explanation: "encontrarse 表示身體狀況：no me encuentro bien = 我感覺不好。bien = 好，mal = 不好。",
    relatedWords: ["encontrarse"],
  },
  {
    id: "h-05", topicId: "health", type: "sort-sentence", level: "A1-1",
    words: ["la", "Me", "cabeza.", "duele"],
    answer: ["Me", "duele", "la", "cabeza."],
    explanation: "doler 句型：me + duele（單數）+ la + 身體部位。",
    relatedWords: ["doler", "cabeza"],
  },
  {
    id: "h-06", topicId: "health", type: "error-correct", level: "A1-2",
    prompt: "Me duele los pies.",
    answer: "Me duelen los pies.",
    explanation: "pies（腳）是複數，所以 doler 也要用複數：duelen。這和 gustar/gustan 的規則一樣。",
    relatedWords: ["doler"],
  },
  {
    id: "h-07", topicId: "health", type: "cn-to-es", level: "A1-2",
    prompt: "我覺得我得了流感。",
    answer: "Creo que tengo gripe.",
    explanation: "creo que（我覺得/認為）+ 完整句子。gripe 是流感（陰性名詞），前面不用冠詞。",
    relatedWords: ["creer", "gripe"],
  },
  {
    id: "h-08", topicId: "health", type: "es-to-cn", level: "A1-2",
    prompt: "¿Desde cuándo se encuentra mal?",
    answer: "您從什麼時候開始不舒服？",
    explanation: "desde cuándo = 從什麼時候。se encuentra mal = 感覺不舒服（第三人稱，醫生問患者）。",
    relatedWords: ["encontrarse"],
  },
  {
    id: "h-09", topicId: "health", type: "fill-blank", level: "A1-1",
    blank: "Tengo ___ y tos.",
    options: ["fiebre", "dolor", "resfriado", "gripe"],
    answer: "fiebre",
    explanation: "fiebre（發燒）和 tos（咳嗽）是常見症狀的組合，也是常見感冒/流感的症狀。",
    relatedWords: ["fiebre", "tos"],
  },
  {
    id: "h-10", topicId: "health", type: "cn-to-es", level: "A1-2",
    prompt: "您必須多休息。",
    answer: "Tiene que descansar mucho.",
    explanation: "tener que + 動詞原形 = 必須。tiene que（他/她/您必須）是醫生對病人說的。",
    relatedWords: ["descansar"],
  },
  {
    id: "h-11", topicId: "health", type: "es-to-cn", level: "A1-2",
    prompt: "Voy a pedir cita con el médico.",
    answer: "我要預約看醫生。",
    explanation: "pedir cita = 預約（字面：索取約會）。con el médico = 和醫生。",
    relatedWords: ["médico", "cita"],
  },
  {
    id: "h-12", topicId: "health", type: "fill-blank", level: "A1-2",
    blank: "¿___ alérgico a algún medicamento?",
    options: ["Es", "Eres", "Soy", "Estar"],
    answer: "Es",
    explanation: "醫生用 usted（正式）詢問：¿Es usted alérgico? 。alérgico（過敏的，形容詞）。",
    relatedWords: ["alérgico"],
  },
  {
    id: "h-13", topicId: "health", type: "cn-to-es", level: "A1-2",
    prompt: "每天服三次藥片。",
    answer: "Tome las pastillas tres veces al día.",
    explanation: "tome 是 tomar 的命令式（醫生對病人說）。tres veces al día = 每天三次。",
    relatedWords: ["pastilla", "tomar"],
  },
  {
    id: "h-14", topicId: "health", type: "sort-sentence", level: "A1-1",
    words: ["bien.", "encuentro", "No", "me"],
    answer: ["No", "me", "encuentro", "bien."],
    explanation: "否定句：No + 反身代詞（me）+ 動詞（encuentro）+ 修飾語（bien）。",
    relatedWords: ["encontrarse"],
  },
  {
    id: "h-15", topicId: "health", type: "error-correct", level: "A1-2",
    prompt: "Creo tengo gripe.",
    answer: "Creo que tengo gripe.",
    explanation: "creo que（我覺得）必須加 que 才能連接後面的句子。省略 que 是常見錯誤。",
    relatedWords: ["creer"],
  },
  {
    id: "h-16", topicId: "health", type: "cn-to-es", level: "A1-2",
    prompt: "我扭傷了腳踝。",
    answer: "Me he torcido el tobillo.",
    explanation: "me he torcido 是完成時，表示剛發生的事。tobillo = 腳踝（陽性名詞）。",
    relatedWords: ["tobillo"],
  },
  {
    id: "h-17", topicId: "health", type: "es-to-cn", level: "A1-2",
    prompt: "¿Dónde le duele?",
    answer: "您哪裡痛？",
    explanation: "le（您，正式間接受格）duele（痛）。醫生詢問病人哪個部位疼痛的說法。",
    relatedWords: ["doler"],
  },
  {
    id: "h-18", topicId: "health", type: "fill-blank", level: "A1-2",
    blank: "Voy a pedir ___ con el médico.",
    options: ["cita", "cuento", "ayuda", "permiso"],
    answer: "cita",
    explanation: "pedir cita = 預約（掛號）。cita（預約/約會，陰性名詞）。",
    relatedWords: ["cita", "médico"],
  },
  {
    id: "h-19", topicId: "health", type: "sort-sentence", level: "A1-3",
    words: ["pastillas", "Tome", "veces", "las", "al", "tres", "día."],
    answer: ["Tome", "las", "pastillas", "tres", "veces", "al", "día."],
    explanation: "醫生命令：tome（服用）+ las pastillas（藥片）+ tres veces al día（每天三次）。",
    relatedWords: ["pastilla", "tomar"],
  },
  {
    id: "h-20", topicId: "health", type: "free-write", level: "A1-3",
    prompt: "請用西語向醫生說明你的症狀（至少三句：哪裡不舒服、有什麼症狀、從什麼時候開始）。",
    answer: "（示範）No me encuentro bien. Tengo fiebre y tos. Me duele la cabeza desde ayer.",
    explanation: "看醫生三要素：1) 整體狀態 2) 具體症狀 3) 從什麼時候開始（desde + 時間）。",
    relatedWords: ["fiebre", "tos", "cabeza", "doler"],
  },
];

export default { topics, exercises };
