const spanishCourseData = {
  chapters: [
    {
      id: 1,
      title: "你好！認識新朋友",
      emoji: "👋",
      color: "#6366f1",
      description: "學習最基礎的打招呼和自我介紹",
    },
    {
      id: 2,
      title: "我的家人",
      emoji: "👨‍👩‍👧",
      color: "#ec4899",
      description: "介紹家庭成員，描述家人",
    },
    {
      id: 3,
      title: "在咖啡廳",
      emoji: "☕",
      color: "#f59e0b",
      description: "點餐、問價格、表達喜好",
    },
    {
      id: 4,
      title: "去市場購物",
      emoji: "🛍️",
      color: "#10b981",
      description: "在商店買東西、討論顏色和尺寸",
    },
    {
      id: 5,
      title: "問路找地方",
      emoji: "🗺️",
      color: "#06b6d4",
      description: "問路、認識城市地點、搭交通工具",
    },
    {
      id: 6,
      title: "我的一天",
      emoji: "⏰",
      color: "#8b5cf6",
      description: "描述日常作息、說時間、星期和月份",
    },
    {
      id: 7,
      title: "週末和愛好",
      emoji: "⚽",
      color: "#ef4444",
      description: "計劃週末、討論運動和娛樂、說天氣",
    },
    {
      id: 8,
      title: "身體和健康",
      emoji: "💊",
      color: "#84cc16",
      description: "認識身體部位、說身體不舒服、去看醫生",
    },
  ],

  lessons: [
    // ── CHAPTER 1 ──────────────────────────────────────────
    {
      id: "ch1-l1",
      chapter: 1,
      lessonNum: 1,
      title: "自我介紹",
      emoji: "😊",
      context: "你在語言學校第一天，遇到了一個新同學 Carlos。你們互相打招呼、介紹自己。",
      sentences: [
        { es: "Hola, soy Ana.", cn: "你好，我是 Ana。" },
        { es: "¿Cómo te llamas?", cn: "你叫什麼名字？" },
        { es: "Me llamo Carlos.", cn: "我叫 Carlos。" },
        { es: "Mucho gusto.", cn: "很高興認識你。" },
        { es: "Soy de Hong Kong.", cn: "我來自香港。" },
      ],
      vocab: [
        { word: "hola", phonetic: "/ˈo.la/", pos: "interj.", gender: null, cn: "你好" },
        { word: "soy", phonetic: "/soj/", pos: "v.", gender: null, cn: "我是（ser 第一人稱）" },
        { word: "llamarse", phonetic: "/ʎa.ˈmar.se/", pos: "v.", gender: null, cn: "叫做（名字）" },
        { word: "mucho gusto", phonetic: "/ˈmu.tʃo ˈɡus.to/", pos: "phrase", gender: null, cn: "很高興認識你" },
        { word: "de", phonetic: "/de/", pos: "prep.", gender: null, cn: "來自；的" },
        { word: "¿cómo?", phonetic: "/ˈko.mo/", pos: "adv.", gender: null, cn: "怎麼；如何" },
        { word: "encantado", phonetic: "/en.kan.ˈta.ðo/", pos: "adj.", gender: null, cn: "很榮幸認識你（男）" },
        { word: "encantada", phonetic: "/en.kan.ˈta.ða/", pos: "adj.", gender: null, cn: "很榮幸認識你（女）" },
      ],
      grammarTip: {
        title: "用 'soy' 介紹自己",
        content: "Soy 是動詞 ser（是）的第一人稱單數。介紹自己說 'Soy + 名字' 或 'Me llamo + 名字'，兩種都常用。",
      },
      listening: {
        script: "Hola, soy Carlos. ¿Cómo te llamas? — Me llamo Ana. Mucho gusto. — Encantado.",
        question: "Ana 介紹自己時說了什麼？",
        options: ["Me llamo Ana.", "Soy Carlos.", "Mucho gusto.", "Encantado."],
        answer: 0,
      },
      sentenceOrder: {
        words: ["gusto.", "Mucho", "soy", "Hola,", "Ana."],
        answer: ["Hola,", "soy", "Ana.", "Mucho", "gusto."],
      },
    },
    {
      id: "ch1-l2",
      chapter: 1,
      lessonNum: 2,
      title: "你從哪裡來？",
      emoji: "🌍",
      context: "在語言班裡，同學們互相問對方的國籍和語言。你用西語介紹自己的背景。",
      sentences: [
        { es: "¿De dónde eres?", cn: "你從哪裡來？" },
        { es: "Soy de China.", cn: "我來自中國。" },
        { es: "¿Hablas inglés?", cn: "你說英語嗎？" },
        { es: "Sí, hablo inglés y chino.", cn: "是的，我說英語和中文。" },
        { es: "¿Cuántos años tienes?", cn: "你幾歲？" },
      ],
      vocab: [
        { word: "dónde", phonetic: "/ˈdon.de/", pos: "adv.", gender: null, cn: "哪裡" },
        { word: "eres", phonetic: "/ˈe.res/", pos: "v.", gender: null, cn: "你是（ser 第二人稱）" },
        { word: "hablar", phonetic: "/a.ˈβlar/", pos: "v.", gender: null, cn: "說話；講" },
        { word: "sí", phonetic: "/si/", pos: "adv.", gender: null, cn: "是；對" },
        { word: "y", phonetic: "/i/", pos: "conj.", gender: null, cn: "和；與" },
        { word: "años", phonetic: "/ˈa.ɲos/", pos: "n.", gender: "m", cn: "歲；年" },
        { word: "tener", phonetic: "/te.ˈner/", pos: "v.", gender: null, cn: "有；擁有" },
        { word: "cuántos", phonetic: "/ˈkwan.tos/", pos: "adj.", gender: null, cn: "多少（複數）" },
      ],
      grammarTip: {
        title: "年齡用 'tener'",
        content: "西語說年齡不用 ser，而是用 tener（有）。例如：Tengo veinte años.（我有二十歲 = 我二十歲）。這和中文不同，要特別記住！",
      },
      listening: {
        script: "¿De dónde eres? — Soy de Hong Kong. ¿Y tú? — Soy de España. ¿Hablas chino? — Sí, hablo chino e inglés.",
        question: "對方說他來自哪裡？",
        options: ["Hong Kong", "España", "China", "México"],
        answer: 1,
      },
      sentenceOrder: {
        words: ["¿De", "eres?", "dónde"],
        answer: ["¿De", "dónde", "eres?"],
      },
    },
    {
      id: "ch1-l3",
      chapter: 1,
      lessonNum: 3,
      title: "再見！",
      emoji: "👋",
      context: "下課了，你和新認識的朋友道別，並約好明天再見。",
      sentences: [
        { es: "Hasta luego.", cn: "再見（之後見）。" },
        { es: "Hasta mañana.", cn: "明天見。" },
        { es: "Nos vemos.", cn: "我們再見。" },
        { es: "¡Que tengas un buen día!", cn: "祝你有美好的一天！" },
        { es: "Igualmente.", cn: "你也是。" },
      ],
      vocab: [
        { word: "hasta", phonetic: "/ˈas.ta/", pos: "prep.", gender: null, cn: "直到；再見（告別用）" },
        { word: "luego", phonetic: "/ˈlwe.ɣo/", pos: "adv.", gender: null, cn: "之後；稍後" },
        { word: "mañana", phonetic: "/ma.ˈɲa.na/", pos: "adv./n.f.", gender: null, cn: "明天；早上" },
        { word: "nos", phonetic: "/nos/", pos: "pron.", gender: null, cn: "我們（受格）" },
        { word: "ver", phonetic: "/ber/", pos: "v.", gender: null, cn: "看見；見面" },
        { word: "buen", phonetic: "/bwen/", pos: "adj.", gender: null, cn: "好的（buen 是 bueno 省略形）" },
        { word: "día", phonetic: "/ˈdi.a/", pos: "n.", gender: "m", cn: "天；日子" },
        { word: "igualmente", phonetic: "/i.ɣwal.ˈmen.te/", pos: "adv.", gender: null, cn: "同樣地；你也是" },
      ],
      grammarTip: {
        title: "多種道別方式",
        content: "西語有很多道別說法：Adiós（再見）、Hasta luego（之後見）、Hasta mañana（明天見）、Hasta pronto（快見）。選擇取決於你打算多久後再見。",
      },
      listening: {
        script: "Bueno, hasta luego Ana. — ¡Hasta mañana Carlos! ¡Que tengas un buen día! — Igualmente.",
        question: "Ana 說了什麼祝福語？",
        options: ["Hasta luego", "Que tengas un buen día", "Igualmente", "Hasta pronto"],
        answer: 1,
      },
      sentenceOrder: {
        words: ["luego.", "Hasta", "¡", "!"],
        answer: ["¡", "Hasta", "luego", "!"],
      },
    },

    // ── CHAPTER 2 ──────────────────────────────────────────
    {
      id: "ch2-l1",
      chapter: 2,
      lessonNum: 1,
      title: "介紹家人",
      emoji: "👨‍👩‍👧",
      context: "你在展示手機裡的家庭照片，向朋友介紹你的家人。",
      sentences: [
        { es: "Esta es mi familia.", cn: "這是我的家人。" },
        { es: "Tengo dos hermanos.", cn: "我有兩個兄弟。" },
        { es: "Mi madre se llama Rosa.", cn: "我媽媽叫做 Rosa。" },
        { es: "Mi padre trabaja en una oficina.", cn: "我爸爸在辦公室工作。" },
        { es: "Vivo con mis padres.", cn: "我和父母同住。" },
      ],
      vocab: [
        { word: "familia", phonetic: "/fa.ˈmi.lja/", pos: "n.", gender: "f", cn: "家庭" },
        { word: "madre", phonetic: "/ˈma.ðre/", pos: "n.", gender: "f", cn: "媽媽；母親" },
        { word: "padre", phonetic: "/ˈpa.ðre/", pos: "n.", gender: "m", cn: "爸爸；父親" },
        { word: "hermano", phonetic: "/er.ˈma.no/", pos: "n.", gender: "m", cn: "兄弟" },
        { word: "hermana", phonetic: "/er.ˈma.na/", pos: "n.", gender: "f", cn: "姐妹" },
        { word: "padres", phonetic: "/ˈpa.ðres/", pos: "n.", gender: "m", cn: "父母" },
        { word: "vivir", phonetic: "/bi.ˈβir/", pos: "v.", gender: null, cn: "居住；生活" },
        { word: "trabajar", phonetic: "/tra.βa.ˈxar/", pos: "v.", gender: null, cn: "工作" },
      ],
      grammarTip: {
        title: "所有格：mi / mis",
        content: "mi 是「我的」（單數），mis 是「我的」（複數）。例如：mi madre（我媽媽）、mis padres（我父母）。注意西語的所有格要和名詞的數目一致。",
      },
      listening: {
        script: "Esta es mi familia. Tengo una hermana y dos hermanos. Mi madre se llama Rosa y mi padre trabaja en una tienda.",
        question: "他/她有幾個兄弟？",
        options: ["一個", "兩個", "三個", "沒有"],
        answer: 1,
      },
      sentenceOrder: {
        words: ["familia.", "mi", "Esta", "es"],
        answer: ["Esta", "es", "mi", "familia."],
      },
    },
    {
      id: "ch2-l2",
      chapter: 2,
      lessonNum: 2,
      title: "描述家人",
      emoji: "👴👵",
      context: "你在形容爺爺奶奶和他們的樣子，朋友很好奇你的大家庭。",
      sentences: [
        { es: "Mi abuelo es alto y simpático.", cn: "我爺爺又高又友善。" },
        { es: "Mi abuela tiene el pelo blanco.", cn: "我奶奶有白頭髮。" },
        { es: "Ella es muy cariñosa.", cn: "她非常慈愛。" },
        { es: "Mi tío es joven y divertido.", cn: "我叔叔年輕又有趣。" },
        { es: "Somos una familia grande.", cn: "我們是一個大家庭。" },
      ],
      vocab: [
        { word: "abuelo", phonetic: "/a.ˈβwe.lo/", pos: "n.", gender: "m", cn: "爺爺；外公" },
        { word: "abuela", phonetic: "/a.ˈβwe.la/", pos: "n.", gender: "f", cn: "奶奶；外婆" },
        { word: "alto", phonetic: "/ˈal.to/", pos: "adj.", gender: null, cn: "高的" },
        { word: "simpático", phonetic: "/sim.ˈpa.ti.ko/", pos: "adj.", gender: null, cn: "友善的；可親的" },
        { word: "pelo", phonetic: "/ˈpe.lo/", pos: "n.", gender: "m", cn: "頭髮" },
        { word: "cariñoso", phonetic: "/ka.ri.ˈɲo.so/", pos: "adj.", gender: null, cn: "慈愛的；親切的" },
        { word: "joven", phonetic: "/ˈxo.βen/", pos: "adj.", gender: null, cn: "年輕的" },
        { word: "divertido", phonetic: "/di.βer.ˈti.ðo/", pos: "adj.", gender: null, cn: "有趣的；好玩的" },
      ],
      grammarTip: {
        title: "形容詞要配合性別",
        content: "西語形容詞要和名詞性別一致：alto（男）→ alta（女），simpático → simpática。描述女性時記得把 -o 換成 -a！",
      },
      listening: {
        script: "Mi abuelo es muy alto y simpático. Mi abuela es baja pero muy cariñosa. Ella tiene el pelo blanco.",
        question: "奶奶的頭髮是什麼顏色？",
        options: ["黑色", "棕色", "白色", "金色"],
        answer: 2,
      },
      sentenceOrder: {
        words: ["simpático.", "alto", "Mi", "y", "abuelo", "es"],
        answer: ["Mi", "abuelo", "es", "alto", "y", "simpático."],
      },
    },
    {
      id: "ch2-l3",
      chapter: 2,
      lessonNum: 3,
      title: "家人的工作",
      emoji: "💼",
      context: "朋友問你家人做什麼工作，你一一介紹他們的職業。",
      sentences: [
        { es: "Mi madre es enfermera.", cn: "我媽媽是護士。" },
        { es: "Mi padre es ingeniero.", cn: "我爸爸是工程師。" },
        { es: "¿A qué se dedica tu madre?", cn: "你媽媽是做什麼的？" },
        { es: "Ella trabaja en un hospital.", cn: "她在醫院工作。" },
        { es: "Mi hermano estudia en la universidad.", cn: "我哥哥在大學讀書。" },
      ],
      vocab: [
        { word: "enfermera", phonetic: "/en.fer.ˈme.ra/", pos: "n.", gender: "f", cn: "護士（女）" },
        { word: "médico", phonetic: "/ˈme.ði.ko/", pos: "n.", gender: "m", cn: "醫生" },
        { word: "ingeniero", phonetic: "/in.xe.ˈnje.ro/", pos: "n.", gender: "m", cn: "工程師" },
        { word: "profesor", phonetic: "/pro.fe.ˈsor/", pos: "n.", gender: "m", cn: "老師" },
        { word: "estudiar", phonetic: "/es.tu.ˈðjar/", pos: "v.", gender: null, cn: "學習；讀書" },
        { word: "universidad", phonetic: "/u.ni.βer.si.ˈðað/", pos: "n.", gender: "f", cn: "大學" },
        { word: "dedicarse", phonetic: "/de.ði.ˈkar.se/", pos: "v.", gender: null, cn: "從事；專注於" },
        { word: "hospital", phonetic: "/os.pi.ˈtal/", pos: "n.", gender: "m", cn: "醫院" },
      ],
      grammarTip: {
        title: "職業不加冠詞",
        content: "西語說職業時，ser 後面不用加不定冠詞 un/una。說 'Soy médico'，不說 'Soy un médico'（這是初學者常見的錯誤）。",
      },
      listening: {
        script: "¿A qué se dedica tu padre? — Mi padre es ingeniero. Trabaja en una empresa grande. ¿Y tu madre? — Ella es profesora.",
        question: "爸爸是什麼職業？",
        options: ["醫生", "工程師", "老師", "護士"],
        answer: 1,
      },
      sentenceOrder: {
        words: ["enfermera.", "Mi", "es", "madre"],
        answer: ["Mi", "madre", "es", "enfermera."],
      },
    },

    // ── CHAPTER 3 ──────────────────────────────────────────
    {
      id: "ch3-l1",
      chapter: 3,
      lessonNum: 1,
      title: "我想要點餐",
      emoji: "🥐",
      context: "你走進一家西班牙咖啡廳，服務員過來招呼。你要點一杯咖啡和一個可頌。",
      sentences: [
        { es: "Buenos días. ¿Qué desea?", cn: "早上好。您想要什麼？" },
        { es: "Quiero un café con leche, por favor.", cn: "我想要一杯拿鐵，謝謝。" },
        { es: "¿Y algo más?", cn: "還要其他的嗎？" },
        { es: "Un croissant también, gracias.", cn: "也要一個可頌，謝謝。" },
        { es: "Enseguida.", cn: "馬上來。" },
      ],
      vocab: [
        { word: "querer", phonetic: "/ke.ˈrer/", pos: "v.", gender: null, cn: "想要" },
        { word: "café", phonetic: "/ka.ˈfe/", pos: "n.", gender: "m", cn: "咖啡" },
        { word: "leche", phonetic: "/ˈle.tʃe/", pos: "n.", gender: "f", cn: "牛奶" },
        { word: "por favor", phonetic: "/por fa.ˈβor/", pos: "phrase", gender: null, cn: "請；麻煩你" },
        { word: "algo", phonetic: "/ˈal.ɣo/", pos: "pron.", gender: null, cn: "某些東西；還有" },
        { word: "más", phonetic: "/mas/", pos: "adv.", gender: null, cn: "更多；還有" },
        { word: "también", phonetic: "/tam.ˈbjen/", pos: "adv.", gender: null, cn: "也；同樣" },
        { word: "enseguida", phonetic: "/en.se.ˈɣi.ða/", pos: "adv.", gender: null, cn: "馬上；立刻" },
      ],
      grammarTip: {
        title: "點餐用 'quiero'",
        content: "Quiero（我想要）來自 querer，是點餐最常用的說法。比 'Quería'（較有禮貌）直接，但在咖啡廳用 quiero 是完全正常的。記住加 por favor 會更有禮貌！",
      },
      listening: {
        script: "Buenos días. ¿Qué desea? — Quiero un café solo y un croissant. ¿Cuánto es? — Son tres euros con cincuenta.",
        question: "客人點了什麼咖啡？",
        options: ["café con leche", "café solo", "café americano", "té"],
        answer: 1,
      },
      sentenceOrder: {
        words: ["favor.", "con", "café", "un", "por", "Quiero", "leche,"],
        answer: ["Quiero", "un", "café", "con", "leche,", "por", "favor."],
      },
    },
    {
      id: "ch3-l2",
      chapter: 3,
      lessonNum: 2,
      title: "多少錢？",
      emoji: "💶",
      context: "喝完咖啡，你準備結帳。你問服務員多少錢，然後付款。",
      sentences: [
        { es: "La cuenta, por favor.", cn: "結帳，麻煩你。" },
        { es: "¿Cuánto es en total?", cn: "一共多少錢？" },
        { es: "Son cinco euros con veinte.", cn: "總共是五點二歐元。" },
        { es: "¿Aceptan tarjeta?", cx: "你們接受信用卡嗎？" },
        { es: "Sí, por supuesto.", cn: "是的，當然。" },
      ],
      vocab: [
        { word: "cuenta", phonetic: "/ˈkwen.ta/", pos: "n.", gender: "f", cn: "帳單；賬" },
        { word: "cuánto", phonetic: "/ˈkwan.to/", pos: "adj.", gender: null, cn: "多少（錢）" },
        { word: "total", phonetic: "/to.ˈtal/", pos: "n.", gender: "m", cn: "總計；合計" },
        { word: "euro", phonetic: "/ˈeu.ro/", pos: "n.", gender: "m", cn: "歐元" },
        { word: "aceptar", phonetic: "/a.θep.ˈtar/", pos: "v.", gender: null, cn: "接受" },
        { word: "tarjeta", phonetic: "/tar.ˈxe.ta/", pos: "n.", gender: "f", cn: "信用卡；卡片" },
        { word: "supuesto", phonetic: "/su.ˈpwes.to/", pos: "adj.", gender: null, cn: "假設的（por supuesto = 當然）" },
        { word: "cambio", phonetic: "/ˈkam.bjo/", pos: "n.", gender: "m", cn: "找零；零錢" },
      ],
      grammarTip: {
        title: "說金額用 'son'",
        content: "說價格時用 son（是）：'Son cinco euros'（是五歐元）。注意說小數點，西班牙用「con」：cinco euros con veinte = 5.20 歐元。",
      },
      listening: {
        script: "La cuenta, por favor. ¿Cuánto es? — Son cuatro euros con cincuenta. — Aquí tiene cinco euros. — El cambio son cincuenta céntimos.",
        question: "找回多少零錢？",
        options: ["五十分", "一歐元", "兩歐元", "零錢"],
        answer: 0,
      },
      sentenceOrder: {
        words: ["favor.", "cuenta,", "La", "por"],
        answer: ["La", "cuenta,", "por", "favor."],
      },
    },
    {
      id: "ch3-l3",
      chapter: 3,
      lessonNum: 3,
      title: "我喜歡什麼",
      emoji: "❤️",
      context: "你和朋友在咖啡廳聊天，討論喜歡的食物和飲料。",
      sentences: [
        { es: "Me gusta mucho el chocolate.", cn: "我非常喜歡巧克力。" },
        { es: "No me gusta el café amargo.", cn: "我不喜歡苦咖啡。" },
        { es: "¿Te gusta el té verde?", cn: "你喜歡綠茶嗎？" },
        { es: "Me encanta la comida picante.", cn: "我超喜歡辣食。" },
        { es: "Prefiero el agua con gas.", cn: "我比較喜歡氣泡水。" },
      ],
      vocab: [
        { word: "gustar", phonetic: "/ɡus.ˈtar/", pos: "v.", gender: null, cn: "喜歡（間接動詞）" },
        { word: "encantar", phonetic: "/en.kan.ˈtar/", pos: "v.", gender: null, cn: "非常喜歡；超愛" },
        { word: "preferir", phonetic: "/pre.fe.ˈrir/", pos: "v.", gender: null, cn: "比較喜歡；偏好" },
        { word: "amargo", phonetic: "/a.ˈmar.ɣo/", pos: "adj.", gender: null, cn: "苦的" },
        { word: "picante", phonetic: "/pi.ˈkan.te/", pos: "adj.", gender: null, cn: "辣的" },
        { word: "dulce", phonetic: "/ˈdul.θe/", pos: "adj.", gender: null, cn: "甜的" },
        { word: "gas", phonetic: "/ɡas/", pos: "n.", gender: "m", cn: "氣體（con gas = 有氣）" },
        { word: "comida", phonetic: "/ko.ˈmi.ða/", pos: "n.", gender: "f", cn: "食物；飯" },
      ],
      grammarTip: {
        title: "gustar 的特殊用法",
        content: "gustar（喜歡）在西語中是反過來用的：Me gusta = 字面是「它讓我高興」。喜歡單數事物用 gusta，喜歡複數事物用 gustan：'Me gustan las manzanas'（我喜歡蘋果）。",
      },
      listening: {
        script: "¿Te gusta el café? — No mucho. Prefiero el té. ¿Y a ti? — A mí me encanta el café. Tomo tres al día.",
        question: "對方每天喝幾杯咖啡？",
        options: ["一杯", "兩杯", "三杯", "不喝咖啡"],
        answer: 2,
      },
      sentenceOrder: {
        words: ["gusta", "mucho", "el", "Me", "chocolate."],
        answer: ["Me", "gusta", "mucho", "el", "chocolate."],
      },
    },

    // ── CHAPTER 4 ──────────────────────────────────────────
    {
      id: "ch4-l1",
      chapter: 4,
      lessonNum: 1,
      title: "在商店裡",
      emoji: "🏪",
      context: "你走進一家服裝店，店員過來幫忙。你在找一件 T 恤。",
      sentences: [
        { es: "¿En qué le puedo ayudar?", cn: "我可以怎樣幫您？" },
        { es: "Estoy buscando una camiseta.", cn: "我在找一件 T 恤。" },
        { es: "¿De qué talla?", cn: "什麼尺寸的？" },
        { es: "Talla mediana, por favor.", cn: "中碼，謝謝。" },
        { es: "¿Puedo probármela?", cn: "我可以試穿嗎？" },
      ],
      vocab: [
        { word: "buscar", phonetic: "/bus.ˈkar/", pos: "v.", gender: null, cn: "尋找；找" },
        { word: "camiseta", phonetic: "/ka.mi.ˈse.ta/", pos: "n.", gender: "f", cn: "T 恤" },
        { word: "talla", phonetic: "/ˈta.ʎa/", pos: "n.", gender: "f", cn: "尺碼；尺寸" },
        { word: "mediana", phonetic: "/me.ˈðja.na/", pos: "adj.", gender: null, cn: "中等的；中碼" },
        { word: "probar", phonetic: "/pro.ˈβar/", pos: "v.", gender: null, cn: "試；嘗試" },
        { word: "ayudar", phonetic: "/a.ʝu.ˈðar/", pos: "v.", gender: null, cn: "幫助；幫忙" },
        { word: "tienda", phonetic: "/ˈtjen.da/", pos: "n.", gender: "f", cn: "商店；店舖" },
        { word: "probador", phonetic: "/pro.βa.ˈðor/", pos: "n.", gender: "m", cn: "試衣間" },
      ],
      grammarTip: {
        title: "現在進行式：estar + -ando/-iendo",
        content: "Estoy buscando = 我正在找（estar + gerundio）。-ar 動詞加 -ando，-er/-ir 動詞加 -iendo。例：comer → comiendo（正在吃），buscar → buscando（正在找）。",
      },
      listening: {
        script: "¿En qué le puedo ayudar? — Estoy buscando unos pantalones negros. — ¿De qué talla? — Talla grande. — El probador está al fondo.",
        question: "客人在找什麼？",
        options: ["T 恤", "裙子", "黑色長褲", "外套"],
        answer: 2,
      },
      sentenceOrder: {
        words: ["buscando", "Estoy", "camiseta.", "una"],
        answer: ["Estoy", "buscando", "una", "camiseta."],
      },
    },
    {
      id: "ch4-l2",
      chapter: 4,
      lessonNum: 2,
      title: "顏色和款式",
      emoji: "🎨",
      context: "你在選擇衣服的顏色和款式，和店員討論哪件更好看。",
      sentences: [
        { es: "¿Lo tienen en azul?", cn: "有藍色的嗎？" },
        { es: "Me gusta más el rojo.", cn: "我比較喜歡紅色。" },
        { es: "¿Tienen algo más barato?", cn: "有比較便宜的嗎？" },
        { es: "Este modelo es muy popular.", cn: "這個款式很受歡迎。" },
        { es: "Me lo llevo.", cn: "我要買這個。" },
      ],
      vocab: [
        { word: "azul", phonetic: "/a.ˈθul/", pos: "adj.", gender: null, cn: "藍色的" },
        { word: "rojo", phonetic: "/ˈro.xo/", pos: "adj.", gender: null, cn: "紅色的" },
        { word: "verde", phonetic: "/ˈber.ðe/", pos: "adj.", gender: null, cn: "綠色的" },
        { word: "negro", phonetic: "/ˈne.ɣro/", pos: "adj.", gender: null, cn: "黑色的" },
        { word: "barato", phonetic: "/ba.ˈra.to/", pos: "adj.", gender: null, cn: "便宜的" },
        { word: "caro", phonetic: "/ˈka.ro/", pos: "adj.", gender: null, cn: "貴的" },
        { word: "modelo", phonetic: "/mo.ˈðe.lo/", pos: "n.", gender: "m", cn: "款式；型號" },
        { word: "llevarse", phonetic: "/ʎe.ˈβar.se/", pos: "v.", gender: null, cn: "帶走；購買（me lo llevo = 我買了）" },
      ],
      grammarTip: {
        title: "比較級：más + 形容詞",
        content: "más...que = 比...更...。例：Este es más barato que aquel.（這個比那個便宜）。如果不比較，只說 más 也可以：Me gusta más el rojo.（我更喜歡紅色）。",
      },
      listening: {
        script: "¿Lo tienen en verde? — Sí, aquí tiene. También lo tenemos en negro. — Me gusta más el verde. ¿Cuánto cuesta? — Veinticinco euros.",
        question: "客人最後選了什麼顏色？",
        options: ["黑色", "藍色", "綠色", "紅色"],
        answer: 2,
      },
      sentenceOrder: {
        words: ["azul?", "en", "¿Lo", "tienen"],
        answer: ["¿Lo", "tienen", "en", "azul?"],
      },
    },
    {
      id: "ch4-l3",
      chapter: 4,
      lessonNum: 3,
      title: "付款和找零",
      emoji: "💳",
      context: "你選好了衣服，走到收銀台付款。你想用現金付。",
      sentences: [
        { es: "¿Cómo va a pagar?", cn: "您打算怎樣付款？" },
        { es: "Voy a pagar en efectivo.", cn: "我要用現金付。" },
        { es: "Son treinta y dos euros.", cn: "一共是三十二歐元。" },
        { es: "Aquí tiene el cambio.", cn: "這是您的找零。" },
        { es: "¿Tiene bolsa?", cn: "有袋子嗎？" },
      ],
      vocab: [
        { word: "pagar", phonetic: "/pa.ˈɣar/", pos: "v.", gender: null, cn: "付款；付錢" },
        { word: "efectivo", phonetic: "/e.fek.ˈti.βo/", pos: "n.", gender: "m", cn: "現金" },
        { word: "cambio", phonetic: "/ˈkam.bjo/", pos: "n.", gender: "m", cn: "找零；零錢" },
        { word: "bolsa", phonetic: "/ˈbol.sa/", pos: "n.", gender: "f", cn: "袋子；手袋" },
        { word: "recibo", phonetic: "/re.ˈθi.βo/", pos: "n.", gender: "m", cn: "收據" },
        { word: "descuento", phonetic: "/des.ˈkwen.to/", pos: "n.", gender: "m", cn: "折扣；優惠" },
        { word: "oferta", phonetic: "/o.ˈfer.ta/", pos: "n.", gender: "f", cn: "特價；促銷" },
        { word: "precio", phonetic: "/ˈpre.θjo/", pos: "n.", gender: "m", cn: "價格" },
      ],
      grammarTip: {
        title: "近未來：voy a + 動詞原形",
        content: "voy a + infinitivo 表示打算做某事。例：Voy a pagar.（我要付款）、Voy a comprar.（我要買）。這是說計劃最自然的方式。",
      },
      listening: {
        script: "¿Cómo va a pagar? — Con tarjeta, por favor. — Lo siento, solo aceptamos efectivo. — Ah, está bien. Aquí tiene cuarenta euros. — El cambio son ocho euros.",
        question: "店員接受什麼付款方式？",
        options: ["信用卡", "手機支付", "現金", "支票"],
        answer: 2,
      },
      sentenceOrder: {
        words: ["efectivo.", "en", "pagar", "Voy", "a"],
        answer: ["Voy", "a", "pagar", "en", "efectivo."],
      },
    },

    // ── CHAPTER 5 ──────────────────────────────────────────
    {
      id: "ch5-l1",
      chapter: 5,
      lessonNum: 1,
      title: "請問怎麼走？",
      emoji: "🗺️",
      context: "你在城市裡迷路了，向路人問博物館怎麼走。",
      sentences: [
        { es: "Perdona, ¿sabes dónde está el museo?", cn: "對不起，你知道博物館在哪裡嗎？" },
        { es: "Siga todo recto.", cn: "一直走直。" },
        { es: "Gire a la derecha.", cn: "向右轉。" },
        { es: "Está a dos calles de aquí.", cn: "就在這裡兩條街外。" },
        { es: "Muchas gracias, muy amable.", cn: "非常感謝，你真好。" },
      ],
      vocab: [
        { word: "perdona", phonetic: "/per.ˈðo.na/", pos: "v.", gender: null, cn: "對不起；打擾一下" },
        { word: "museo", phonetic: "/mu.ˈse.o/", pos: "n.", gender: "m", cn: "博物館" },
        { word: "seguir", phonetic: "/se.ˈɣir/", pos: "v.", gender: null, cn: "繼續；跟隨" },
        { word: "recto", phonetic: "/ˈrek.to/", pos: "adv.", gender: null, cn: "直；筆直" },
        { word: "girar", phonetic: "/xi.ˈrar/", pos: "v.", gender: null, cn: "轉彎；旋轉" },
        { word: "derecha", phonetic: "/de.ˈre.tʃa/", pos: "n.", gender: "f", cn: "右邊" },
        { word: "izquierda", phonetic: "/is.ˈkjer.da/", pos: "n.", gender: "f", cn: "左邊" },
        { word: "calle", phonetic: "/ˈka.ʎe/", pos: "n.", gender: "f", cn: "街道" },
      ],
      grammarTip: {
        title: "命令式問路",
        content: "問路時常用命令式：Siga（繼續走）、Gire（轉彎）、Cruce（穿過）。這些是對陌生人用 usted 的命令式。和朋友說話可以用 sigue、gira 等 tú 命令式。",
      },
      listening: {
        script: "Perdona, ¿dónde está la farmacia? — Siga todo recto y gire a la izquierda en el semáforo. La farmacia está justo ahí. — Muchas gracias.",
        question: "藥房在哪個方向轉？",
        options: ["向右", "向左", "直走", "向後"],
        answer: 1,
      },
      sentenceOrder: {
        words: ["recto.", "todo", "Siga"],
        answer: ["Siga", "todo", "recto."],
      },
    },
    {
      id: "ch5-l2",
      chapter: 5,
      lessonNum: 2,
      title: "城市地點",
      emoji: "🏛️",
      context: "你在地圖上標出今天想去的地方，和朋友討論行程。",
      sentences: [
        { es: "El banco está cerca del parque.", cn: "銀行在公園附近。" },
        { es: "La parada de metro está lejos.", cn: "地鐵站很遠。" },
        { es: "¿Hay un supermercado por aquí?", cn: "這附近有超市嗎？" },
        { es: "Está enfrente del ayuntamiento.", cn: "在市政廳對面。" },
        { es: "Está a diez minutos andando.", cn: "步行十分鐘。" },
      ],
      vocab: [
        { word: "banco", phonetic: "/ˈban.ko/", pos: "n.", gender: "m", cn: "銀行" },
        { word: "parque", phonetic: "/ˈpar.ke/", pos: "n.", gender: "m", cn: "公園" },
        { word: "cerca", phonetic: "/ˈθer.ka/", pos: "adv.", gender: null, cn: "近；附近" },
        { word: "lejos", phonetic: "/ˈle.xos/", pos: "adv.", gender: null, cn: "遠" },
        { word: "parada", phonetic: "/pa.ˈra.ða/", pos: "n.", gender: "f", cn: "站；停靠站" },
        { word: "enfrente", phonetic: "/en.ˈfren.te/", pos: "adv.", gender: null, cn: "對面；正前方" },
        { word: "supermercado", phonetic: "/su.per.mer.ˈka.ðo/", pos: "n.", gender: "m", cn: "超市" },
        { word: "andando", phonetic: "/an.ˈdan.do/", pos: "gerund", gender: null, cn: "步行（andar 的現在分詞）" },
      ],
      grammarTip: {
        title: "位置介詞",
        content: "常用位置介詞：cerca de（附近）、lejos de（遠離）、enfrente de（對面）、al lado de（旁邊）、entre（之間）。de + el = del（縮寫）：al lado del banco。",
      },
      listening: {
        script: "¿Hay una farmacia por aquí? — Sí, hay una cerca del banco. Está a cinco minutos andando. — ¿Y hay un cajero automático? — Sí, justo enfrente.",
        question: "藥房距離多遠？",
        options: ["兩分鐘", "五分鐘", "十分鐘", "很遠"],
        answer: 1,
      },
      sentenceOrder: {
        words: ["del", "banco.", "cerca", "está", "El", "parque"],
        answer: ["El", "banco", "está", "cerca", "del", "parque."],
      },
    },
    {
      id: "ch5-l3",
      chapter: 5,
      lessonNum: 3,
      title: "搭交通工具",
      emoji: "🚇",
      context: "你要去市中心，需要搭地鐵。你在地鐵站問怎麼買票和轉線。",
      sentences: [
        { es: "¿Cómo llego al centro?", cn: "怎樣去市中心？" },
        { es: "Coge el metro en esta estación.", cn: "在這個站搭地鐵。" },
        { es: "¿Dónde tengo que hacer trasbordo?", cn: "我在哪裡轉車？" },
        { es: "En la estación Sol, cambia a la línea dos.", cn: "在 Sol 站換二號線。" },
        { es: "¿Cuánto tarda?", cn: "需要多長時間？" },
      ],
      vocab: [
        { word: "metro", phonetic: "/ˈme.tro/", pos: "n.", gender: "m", cn: "地鐵" },
        { word: "estación", phonetic: "/es.ta.ˈθjon/", pos: "n.", gender: "f", cn: "站；車站" },
        { word: "línea", phonetic: "/ˈli.ne.a/", pos: "n.", gender: "f", cn: "線；路線" },
        { word: "trasbordo", phonetic: "/tras.ˈbor.ðo/", pos: "n.", gender: "m", cn: "轉乘；換乘" },
        { word: "tardar", phonetic: "/tar.ˈðar/", pos: "v.", gender: null, cn: "花時間；延遲" },
        { word: "cambiar", phonetic: "/kam.ˈbjar/", pos: "v.", gender: null, cn: "換；改變" },
        { word: "autobús", phonetic: "/au.to.ˈβus/", pos: "n.", gender: "m", cn: "巴士" },
        { word: "taxi", phonetic: "/ˈtak.si/", pos: "n.", gender: "m", cn: "計程車" },
      ],
      grammarTip: {
        title: "coger vs. tomar",
        content: "在西班牙說「搭乘交通工具」用 coger：coger el metro/bus/taxi。在拉丁美洲則用 tomar：tomar el metro。兩種都正確，取決於你要學哪個地方的西班牙語。",
      },
      listening: {
        script: "¿Cómo llego al aeropuerto? — Puedes coger el metro. Línea ocho hasta el final. Tarda unos veinte minutos. — ¿Hay que hacer trasbordo? — No, es directo.",
        question: "去機場要坐幾號線？",
        options: ["二號線", "五號線", "八號線", "十號線"],
        answer: 2,
      },
      sentenceOrder: {
        words: ["al", "¿Cómo", "llego", "centro?"],
        answer: ["¿Cómo", "llego", "al", "centro?"],
      },
    },

    // ── CHAPTER 6 ──────────────────────────────────────────
    {
      id: "ch6-l1",
      chapter: 6,
      lessonNum: 1,
      title: "我的日常作息",
      emoji: "☀️",
      context: "你向朋友描述你每天的作息時間，從起床到睡覺。",
      sentences: [
        { es: "Me levanto a las siete.", cn: "我七點起床。" },
        { es: "Desayuno con mi familia.", cn: "我和家人吃早餐。" },
        { es: "Voy al trabajo en metro.", cn: "我坐地鐵去上班。" },
        { es: "Salgo de la oficina a las seis.", cn: "我六點離開辦公室。" },
        { es: "Me acuesto a las once.", cn: "我十一點睡覺。" },
      ],
      vocab: [
        { word: "levantarse", phonetic: "/le.βan.ˈtar.se/", pos: "v.", gender: null, cn: "起床" },
        { word: "desayunar", phonetic: "/de.sa.ʝu.ˈnar/", pos: "v.", gender: null, cn: "吃早餐" },
        { word: "almorzar", phonetic: "/al.mor.ˈθar/", pos: "v.", gender: null, cn: "吃午餐" },
        { word: "cenar", phonetic: "/θe.ˈnar/", pos: "v.", gender: null, cn: "吃晚餐" },
        { word: "salir", phonetic: "/sa.ˈlir/", pos: "v.", gender: null, cn: "出去；離開" },
        { word: "acostarse", phonetic: "/a.kos.ˈtar.se/", pos: "v.", gender: null, cn: "睡覺；躺下" },
        { word: "ducharse", phonetic: "/du.ˈtʃar.se/", pos: "v.", gender: null, cn: "洗澡" },
        { word: "siempre", phonetic: "/ˈsjem.pre/", pos: "adv.", gender: null, cn: "總是；永遠" },
      ],
      grammarTip: {
        title: "反身動詞表示自身動作",
        content: "levantarse、acostarse、ducharse 都是反身動詞（帶 -se）。使用時要配合代詞：yo me levanto、tú te levantas、él se levanta。Me 指「自己」。",
      },
      listening: {
        script: "¿A qué hora te levantas normalmente? — Me levanto a las seis y media. Desayuno rápido y salgo a las siete. ¿Y tú? — Yo me levanto a las ocho.",
        question: "對方幾點起床？",
        options: ["六點", "六點半", "七點", "八點"],
        answer: 1,
      },
      sentenceOrder: {
        words: ["siete.", "las", "a", "levanto", "Me"],
        answer: ["Me", "levanto", "a", "las", "siete."],
      },
    },
    {
      id: "ch6-l2",
      chapter: 6,
      lessonNum: 2,
      title: "現在幾點？",
      emoji: "🕐",
      context: "你要和朋友約好見面時間，討論幾點合適。",
      sentences: [
        { es: "¿Qué hora es?", cn: "現在幾點？" },
        { es: "Son las tres y cuarto.", cn: "三點一刻。" },
        { es: "Es la una y media.", cn: "一點半。" },
        { es: "Son las diez menos cinco.", cn: "九點五十五（差五分十點）。" },
        { es: "Quedamos a las siete en punto.", cn: "我們約好七點整。" },
      ],
      vocab: [
        { word: "hora", phonetic: "/ˈo.ra/", pos: "n.", gender: "f", cn: "小時；時間" },
        { word: "cuarto", phonetic: "/ˈkwar.to/", pos: "n.", gender: "m", cn: "一刻鐘（15 分鐘）" },
        { word: "media", phonetic: "/ˈme.ðja/", pos: "adj.", gender: null, cn: "一半；半" },
        { word: "menos", phonetic: "/ˈme.nos/", pos: "adv.", gender: null, cn: "差；減" },
        { word: "punto", phonetic: "/ˈpun.to/", pos: "n.", gender: "m", cn: "點；整（時間）" },
        { word: "quedar", phonetic: "/ke.ˈðar/", pos: "v.", gender: null, cn: "約好見面；安排" },
        { word: "tarde", phonetic: "/ˈtar.ðe/", pos: "adv./n.f.", gender: null, cn: "晚；下午" },
        { word: "temprano", phonetic: "/tem.ˈpra.no/", pos: "adv.", gender: null, cn: "早；提早" },
      ],
      grammarTip: {
        title: "說時間：es / son",
        content: "只有一點用 'es la una'，其餘都用 'son las...'。加 y（加）說多的分鐘：son las tres y veinte（三點二十）。用 menos（減）說快到的：son las cuatro menos diez（差十分四點）。",
      },
      listening: {
        script: "¿Qué hora es? — Son las cuatro y media. — ¿Quedamos a las seis en punto? — Mejor a las seis y cuarto. — De acuerdo.",
        question: "他們最後約好幾點？",
        options: ["六點整", "六點一刻", "六點半", "五點半"],
        answer: 1,
      },
      sentenceOrder: {
        words: ["cuarto.", "las", "tres", "Son", "y"],
        answer: ["Son", "las", "tres", "y", "cuarto."],
      },
    },
    {
      id: "ch6-l3",
      chapter: 6,
      lessonNum: 3,
      title: "星期和月份",
      emoji: "📅",
      context: "你在計劃下個月的旅行，需要用西語說日期和星期。",
      sentences: [
        { es: "Hoy es lunes, ¿verdad?", cn: "今天是星期一，對嗎？" },
        { es: "El viernes tengo un examen.", cn: "我星期五有考試。" },
        { es: "Mi cumpleaños es en agosto.", cn: "我的生日在八月。" },
        { es: "¿Qué día es hoy?", cn: "今天是幾號？" },
        { es: "Es el quince de julio.", cn: "是七月十五日。" },
      ],
      vocab: [
        { word: "lunes", phonetic: "/ˈlu.nes/", pos: "n.", gender: "m", cn: "星期一" },
        { word: "viernes", phonetic: "/ˈbjer.nes/", pos: "n.", gender: "m", cn: "星期五" },
        { word: "sábado", phonetic: "/ˈsa.βa.ðo/", pos: "n.", gender: "m", cn: "星期六" },
        { word: "domingo", phonetic: "/do.ˈmin.ɣo/", pos: "n.", gender: "m", cn: "星期日" },
        { word: "agosto", phonetic: "/a.ˈɣos.to/", pos: "n.", gender: "m", cn: "八月" },
        { word: "julio", phonetic: "/ˈxu.ljo/", pos: "n.", gender: "m", cn: "七月" },
        { word: "cumpleaños", phonetic: "/kum.ple.ˈa.ɲos/", pos: "n.", gender: "m", cn: "生日" },
        { word: "verdad", phonetic: "/ber.ˈðað/", pos: "n.", gender: "f", cn: "真相；真的（¿verdad? = 對嗎?）" },
      ],
      grammarTip: {
        title: "星期幾不需冠詞，說日期用定冠詞",
        content: "說「在星期幾」不用 en：El lunes tengo clase.（星期一我有課）。說日期用 el：El quince de julio（七月十五日）。月份和星期名稱在西語都不大寫。",
      },
      listening: {
        script: "¿Cuándo es tu cumpleaños? — Es el tres de marzo. ¿Y el tuyo? — El mío es en septiembre, el día veinte.",
        question: "他的生日是幾月？",
        options: ["三月", "七月", "八月", "九月"],
        answer: 3,
      },
      sentenceOrder: {
        words: ["agosto.", "en", "cumpleaños", "Mi", "es"],
        answer: ["Mi", "cumpleaños", "es", "en", "agosto."],
      },
    },

    // ── CHAPTER 7 ──────────────────────────────────────────
    {
      id: "ch7-l1",
      chapter: 7,
      lessonNum: 1,
      title: "週末計劃",
      emoji: "🗓️",
      context: "星期四，你和同事討論這個週末的計劃。",
      sentences: [
        { es: "¿Qué vas a hacer este fin de semana?", cn: "你這個週末打算做什麼？" },
        { es: "Voy a quedar con unos amigos.", cn: "我打算和朋友見面。" },
        { es: "Pensamos ir a la playa.", cn: "我們打算去海灘。" },
        { es: "¿Quieres venir con nosotros?", cn: "你想跟我們一起來嗎？" },
        { es: "¡Me encantaría!", cn: "我非常想去！" },
      ],
      vocab: [
        { word: "fin de semana", phonetic: "/fin de se.ˈma.na/", pos: "n.", gender: "m", cn: "週末" },
        { word: "quedar", phonetic: "/ke.ˈðar/", pos: "v.", gender: null, cn: "約好；見面" },
        { word: "pensar", phonetic: "/pen.ˈsar/", pos: "v.", gender: null, cn: "打算；思考" },
        { word: "playa", phonetic: "/ˈpla.ʝa/", pos: "n.", gender: "f", cn: "海灘；海邊" },
        { word: "nosotros", phonetic: "/no.ˈso.tros/", pos: "pron.", gender: null, cn: "我們" },
        { word: "encantar", phonetic: "/en.kan.ˈtar/", pos: "v.", gender: null, cn: "非常喜歡（me encantaría = 我會很樂意）" },
        { word: "invitar", phonetic: "/im.bi.ˈtar/", pos: "v.", gender: null, cn: "邀請" },
        { word: "plan", phonetic: "/plan/", pos: "n.", gender: "m", cn: "計劃；安排" },
      ],
      grammarTip: {
        title: "pensar + infinitivo = 打算",
        content: "pensar（思考）+ 動詞原形表示計劃：Pienso ir al cine.（我打算去看電影）。類似的還有 querer（想要）和 ir a（要去）。這三種都是說計劃的常用方式。",
      },
      listening: {
        script: "¿Tienes planes para el sábado? — Sí, pienso ir al cine con mi hermana. ¿Y tú? — Voy a quedar con unos amigos para cenar.",
        question: "說話者打算星期六做什麼？",
        options: ["去海灘", "看電影", "吃晚飯", "待在家"],
        answer: 1,
      },
      sentenceOrder: {
        words: ["con", "Voy", "amigos.", "a", "unos", "quedar"],
        answer: ["Voy", "a", "quedar", "con", "unos", "amigos."],
      },
    },
    {
      id: "ch7-l2",
      chapter: 7,
      lessonNum: 2,
      title: "運動和娛樂",
      emoji: "⚽",
      context: "你們在聊各自的愛好，討論最喜歡的運動和娛樂活動。",
      sentences: [
        { es: "Me gusta jugar al fútbol.", cn: "我喜歡踢足球。" },
        { es: "Practico natación tres veces a la semana.", cn: "我每週游泳三次。" },
        { es: "Prefiero los deportes de equipo.", cn: "我比較喜歡團隊運動。" },
        { es: "¿Ves mucho la televisión?", cn: "你常看電視嗎？" },
        { es: "Prefiero leer o escuchar música.", cn: "我比較喜歡看書或聽音樂。" },
      ],
      vocab: [
        { word: "jugar", phonetic: "/xu.ˈɣar/", pos: "v.", gender: null, cn: "玩；運動（球類用 jugar a）" },
        { word: "fútbol", phonetic: "/ˈfut.βol/", pos: "n.", gender: "m", cn: "足球" },
        { word: "natación", phonetic: "/na.ta.ˈθjon/", pos: "n.", gender: "f", cn: "游泳" },
        { word: "practicar", phonetic: "/prak.ti.ˈkar/", pos: "v.", gender: null, cn: "練習；從事（運動）" },
        { word: "equipo", phonetic: "/e.ˈki.po/", pos: "n.", gender: "m", cn: "團隊；隊伍" },
        { word: "televisión", phonetic: "/te.le.βi.ˈsjon/", pos: "n.", gender: "f", cn: "電視" },
        { word: "escuchar", phonetic: "/es.ku.ˈtʃar/", pos: "v.", gender: null, cn: "聽；聆聽" },
        { word: "música", phonetic: "/ˈmu.si.ka/", pos: "n.", gender: "f", cn: "音樂" },
      ],
      grammarTip: {
        title: "jugar a vs. practicar",
        content: "球類運動用 jugar a：jugar al fútbol（踢足球）、jugar al tenis（打網球）。其他運動用 practicar：practicar natación（游泳）、practicar yoga（練瑜伽）。",
      },
      listening: {
        script: "¿Qué deporte te gusta más? — Me encanta el tenis. Juego dos veces a la semana. ¿Y tú? — Yo practico natación. Es muy relajante.",
        question: "第一個人每週打幾次網球？",
        options: ["一次", "兩次", "三次", "四次"],
        answer: 1,
      },
      sentenceOrder: {
        words: ["fútbol.", "al", "Me", "jugar", "gusta"],
        answer: ["Me", "gusta", "jugar", "al", "fútbol."],
      },
    },
    {
      id: "ch7-l3",
      chapter: 7,
      lessonNum: 3,
      title: "今天天氣怎樣？",
      emoji: "🌤️",
      context: "你打電話給在西班牙的筆友，聊到兩地不同的天氣。",
      sentences: [
        { es: "¿Qué tiempo hace ahí?", cn: "你那邊天氣怎樣？" },
        { es: "Hace mucho sol y calor.", cn: "陽光很好，很熱。" },
        { es: "Aquí está lloviendo.", cn: "這裡正在下雨。" },
        { es: "Hace viento y frío.", cn: "有風又寒冷。" },
        { es: "¡Qué envidia! Aquí nieva en invierno.", cn: "好羨慕！我們冬天下雪。" },
      ],
      vocab: [
        { word: "tiempo", phonetic: "/ˈtjem.po/", pos: "n.", gender: "m", cn: "天氣；時間" },
        { word: "sol", phonetic: "/sol/", pos: "n.", gender: "m", cn: "太陽；陽光" },
        { word: "calor", phonetic: "/ka.ˈlor/", pos: "n.", gender: "m", cn: "熱；炎熱" },
        { word: "lluvia", phonetic: "/ˈʎu.βja/", pos: "n.", gender: "f", cn: "雨" },
        { word: "viento", phonetic: "/ˈbjen.to/", pos: "n.", gender: "m", cn: "風" },
        { word: "frío", phonetic: "/ˈfri.o/", pos: "n./adj.", gender: "m", cn: "冷；寒冷" },
        { word: "nivar", phonetic: "/ne.ˈβar/", pos: "v.", gender: null, cn: "下雪" },
        { word: "invierno", phonetic: "/im.ˈbjer.no/", pos: "n.", gender: "m", cn: "冬天" },
      ],
      grammarTip: {
        title: "天氣用 'hace'",
        content: "大多數天氣說法用 hacer（做）：hace sol（晴天）、hace calor（熱天）、hace frío（冷天）、hace viento（有風）。下雨和下雪用 llover 和 nevar：Llueve / Está lloviendo（在下雨）。",
      },
      listening: {
        script: "¿Qué tiempo hace en tu ciudad? — Hoy hace mucho frío y está nevando. Estamos en invierno. ¿Y allí? — Aquí hace sol y calor, son veintiocho grados.",
        question: "說話者那裡的天氣怎樣？",
        options: ["下雨", "下雪", "晴天", "颳風"],
        answer: 1,
      },
      sentenceOrder: {
        words: ["calor.", "hace", "y", "Hace", "sol"],
        answer: ["Hace", "mucho", "sol", "y", "calor."],
      },
    },

    // ── CHAPTER 8 ──────────────────────────────────────────
    {
      id: "ch8-l1",
      chapter: 8,
      lessonNum: 1,
      title: "身體部位",
      emoji: "🧍",
      context: "你在學習西語身體部位，幫助你日後去醫院或運動受傷時能夠表達。",
      sentences: [
        { es: "Me duele la cabeza.", cn: "我頭痛。" },
        { es: "Tengo dolor de espalda.", cn: "我背痛。" },
        { es: "Me he torcido el tobillo.", cn: "我扭傷了腳踝。" },
        { es: "¿Dónde le duele?", cn: "您哪裡痛？" },
        { es: "Me duelen las rodillas.", cn: "我膝蓋痛。" },
      ],
      vocab: [
        { word: "cabeza", phonetic: "/ka.ˈβe.θa/", pos: "n.", gender: "f", cn: "頭" },
        { word: "espalda", phonetic: "/es.ˈpal.da/", pos: "n.", gender: "f", cn: "背部" },
        { word: "rodilla", phonetic: "/ro.ˈði.ʎa/", pos: "n.", gender: "f", cn: "膝蓋" },
        { word: "tobillo", phonetic: "/to.ˈβi.ʎo/", pos: "n.", gender: "m", cn: "腳踝" },
        { word: "mano", phonetic: "/ˈma.no/", pos: "n.", gender: "f", cn: "手" },
        { word: "brazo", phonetic: "/ˈbra.θo/", pos: "n.", gender: "m", cn: "手臂" },
        { word: "pierna", phonetic: "/ˈpjer.na/", pos: "n.", gender: "f", cn: "腿" },
        { word: "doler", phonetic: "/do.ˈler/", pos: "v.", gender: null, cn: "痛；疼" },
      ],
      grammarTip: {
        title: "doler 用法同 gustar",
        content: "doler（痛）的用法和 gustar 一樣，主語是身體部位：Me duele la cabeza.（字面：頭讓我痛）。單個部位用 duele，多個用 duelen：Me duelen las rodillas.（我膝蓋痛）。",
      },
      listening: {
        script: "¿Qué le pasa? — Me duele mucho el estómago desde ayer. También tengo fiebre. — ¿Cuánto tiempo lleva así? — Desde anoche.",
        question: "病人有什麼症狀？",
        options: ["頭痛", "腳痛", "肚子痛和發燒", "背痛"],
        answer: 2,
      },
      sentenceOrder: {
        words: ["la", "Me", "cabeza.", "duele"],
        answer: ["Me", "duele", "la", "cabeza."],
      },
    },
    {
      id: "ch8-l2",
      chapter: 8,
      lessonNum: 2,
      title: "我身體不舒服",
      emoji: "🤒",
      context: "你打電話給老闆，說你今天不舒服，不能上班。",
      sentences: [
        { es: "No me encuentro bien.", cn: "我感覺不舒服。" },
        { es: "Tengo fiebre y tos.", cn: "我發燒和咳嗽。" },
        { es: "Creo que tengo gripe.", cn: "我覺得我得了流感。" },
        { es: "No puedo ir a trabajar hoy.", cn: "我今天不能去上班。" },
        { es: "Voy a pedir cita con el médico.", cn: "我要預約看醫生。" },
      ],
      vocab: [
        { word: "fiebre", phonetic: "/ˈfje.βre/", pos: "n.", gender: "f", cn: "發燒；體溫" },
        { word: "tos", phonetic: "/tos/", pos: "n.", gender: "f", cn: "咳嗽" },
        { word: "gripe", phonetic: "/ˈɡri.pe/", pos: "n.", gender: "f", cn: "流感" },
        { word: "resfriado", phonetic: "/res.frja.ˈðo/", pos: "n.", gender: "m", cn: "感冒" },
        { word: "cita", phonetic: "/ˈθi.ta/", pos: "n.", gender: "f", cn: "預約；約會" },
        { word: "creer", phonetic: "/kre.ˈer/", pos: "v.", gender: null, cn: "相信；覺得" },
        { word: "encontrarse", phonetic: "/en.kon.ˈtrar.se/", pos: "v.", gender: null, cn: "感覺；處於（身體狀況）" },
        { word: "mareado", phonetic: "/ma.re.ˈa.ðo/", pos: "adj.", gender: null, cn: "頭暈的；噁心的" },
      ],
      grammarTip: {
        title: "creo que + 句子",
        content: "creo que（我覺得/我認為）後面接完整句子：Creo que tengo fiebre.（我覺得我發燒了）。這是表達不確定意見的常用結構，比直接說更委婉。",
      },
      listening: {
        script: "Buenos días, ¿en qué le puedo ayudar? — Quería pedir cita con el médico. — ¿Para cuándo? — Lo antes posible, por favor. Tengo mucha fiebre.",
        question: "患者想什麼時候看醫生？",
        options: ["明天", "下週", "越快越好", "下個月"],
        answer: 2,
      },
      sentenceOrder: {
        words: ["bien.", "encuentro", "No", "me"],
        answer: ["No", "me", "encuentro", "bien."],
      },
    },
    {
      id: "ch8-l3",
      chapter: 8,
      lessonNum: 3,
      title: "去看醫生",
      emoji: "🏥",
      context: "你去診所看醫生，醫生問你症狀，給你開了藥方。",
      sentences: [
        { es: "¿Desde cuándo se encuentra mal?", cn: "您從什麼時候開始不舒服？" },
        { es: "Desde hace dos días.", cn: "從兩天前開始。" },
        { es: "Tiene que descansar mucho.", cn: "您必須多休息。" },
        { es: "Le voy a recetar un antibiótico.", cn: "我給您開抗生素。" },
        { es: "Tome las pastillas tres veces al día.", cn: "每天服三次藥片。" },
      ],
      vocab: [
        { word: "recetar", phonetic: "/re.θe.ˈtar/", pos: "v.", gender: null, cn: "開藥方；處方" },
        { word: "antibiótico", phonetic: "/an.ti.ˈβjo.ti.ko/", pos: "n.", gender: "m", cn: "抗生素" },
        { word: "pastilla", phonetic: "/pas.ˈti.ʎa/", pos: "n.", gender: "f", cn: "藥片；片劑" },
        { word: "descansar", phonetic: "/des.kan.ˈsar/", pos: "v.", gender: null, cn: "休息" },
        { word: "tomar", phonetic: "/to.ˈmar/", pos: "v.", gender: null, cn: "服用；喝；拿" },
        { word: "jarabe", phonetic: "/xa.ˈra.βe/", pos: "n.", gender: "m", cn: "糖漿；止咳水" },
        { word: "receta", phonetic: "/re.ˈθe.ta/", pos: "n.", gender: "f", cn: "處方；食譜" },
        { word: "alérgico", phonetic: "/a.ˈler.xi.ko/", pos: "adj.", gender: null, cn: "過敏的" },
      ],
      grammarTip: {
        title: "tener que vs. deber",
        content: "tener que + 動詞原形 = 必須（義務，外部要求）：Tiene que descansar.（您必須休息）。deber + 動詞原形 = 應該（道德或建議）：Debe beber agua.（您應該喝水）。",
      },
      listening: {
        script: "¿Es alérgico a algún medicamento? — No, que yo sepa. — Bien. Le receto un jarabe y unas pastillas. Tómelo tres veces al día durante cinco días.",
        question: "藥要吃幾天？",
        options: ["三天", "四天", "五天", "一週"],
        answer: 2,
      },
      sentenceOrder: {
        words: ["mucho.", "descansar", "que", "Tiene"],
        answer: ["Tiene", "que", "descansar", "mucho."],
      },
    },
  ],
};

export default spanishCourseData;
