const spanishA1Dict = {
  // ── Ch1 L1 ──
  hola: { partOfSpeech: "interj.", zh: "你好", en: "hello", example: "Hola, soy Ana.", exampleZh: "你好，我是 Ana。", level: "A1" },
  soy: { partOfSpeech: "v.", zh: "我是（ser）", en: "I am", example: "Soy de Hong Kong.", exampleZh: "我來自香港。", level: "A1" },
  llamarse: { partOfSpeech: "v.", zh: "叫做（名字）", en: "to be called", example: "Me llamo Carlos.", exampleZh: "我叫 Carlos。", level: "A1" },
  "mucho gusto": { partOfSpeech: "phrase", zh: "很高興認識你", en: "nice to meet you", example: "Mucho gusto, señor García.", exampleZh: "很高興認識你，García 先生。", level: "A1" },
  de: { partOfSpeech: "prep.", zh: "來自；的", en: "from; of", example: "Soy de España.", exampleZh: "我來自西班牙。", level: "A1" },
  "¿cómo?": { partOfSpeech: "adv.", zh: "怎麼；如何", en: "how; what", example: "¿Cómo te llamas?", exampleZh: "你叫什麼名字？", level: "A1" },
  cómo: { partOfSpeech: "adv.", zh: "怎麼；如何", en: "how; what", example: "¿Cómo estás?", exampleZh: "你好嗎？", level: "A1" },
  encantado: { partOfSpeech: "adj.", zh: "很榮幸認識你（男）", en: "pleased to meet you (m)", example: "Encantado de conocerte.", exampleZh: "很高興認識你。", level: "A1" },
  encantada: { partOfSpeech: "adj.", zh: "很榮幸認識你（女）", en: "pleased to meet you (f)", example: "Encantada, ¿cómo estás?", exampleZh: "很榮幸，你好嗎？", level: "A1" },
  // ── Ch1 L2 ──
  "dónde": { partOfSpeech: "adv.", zh: "哪裡", en: "where", example: "¿De dónde eres?", exampleZh: "你從哪裡來？", level: "A1" },
  donde: { partOfSpeech: "adv.", zh: "哪裡；那裡", en: "where", example: "¿Sabes dónde está?", exampleZh: "你知道在哪裡嗎？", level: "A1" },
  eres: { partOfSpeech: "v.", zh: "你是（ser）", en: "you are", example: "¿De dónde eres?", exampleZh: "你從哪裡來？", level: "A1" },
  hablar: { partOfSpeech: "v.", zh: "說話；講", en: "to speak", example: "¿Hablas inglés?", exampleZh: "你說英語嗎？", level: "A1" },
  hablas: { partOfSpeech: "v.", zh: "你說（hablar）", en: "you speak", example: "¿Hablas chino?", exampleZh: "你說中文嗎？", level: "A1" },
  hablo: { partOfSpeech: "v.", zh: "我說（hablar）", en: "I speak", example: "Hablo inglés y chino.", exampleZh: "我說英語和中文。", level: "A1" },
  "sí": { partOfSpeech: "adv.", zh: "是；對", en: "yes", example: "Sí, hablo español.", exampleZh: "是的，我說西班牙語。", level: "A1" },
  si: { partOfSpeech: "conj.", zh: "如果", en: "if", example: "Si quieres, te ayudo.", exampleZh: "如果你想，我幫你。", level: "A1" },
  y: { partOfSpeech: "conj.", zh: "和；與", en: "and", example: "Soy de China y hablo chino.", exampleZh: "我來自中國，說中文。", level: "A1" },
  "años": { partOfSpeech: "n.", zh: "歲；年", en: "years; age", example: "Tengo veinte años.", exampleZh: "我二十歲。", level: "A1" },
  año: { partOfSpeech: "n.", zh: "年；歲", en: "year", example: "Este año aprendo español.", exampleZh: "今年我學西班牙語。", level: "A1" },
  tener: { partOfSpeech: "v.", zh: "有；擁有", en: "to have", example: "Tengo una hermana.", exampleZh: "我有一個姐妹。", level: "A1" },
  tengo: { partOfSpeech: "v.", zh: "我有（tener）", en: "I have", example: "Tengo dos hermanos.", exampleZh: "我有兩個兄弟。", level: "A1" },
  tienes: { partOfSpeech: "v.", zh: "你有（tener）", en: "you have", example: "¿Cuántos años tienes?", exampleZh: "你幾歲？", level: "A1" },
  tiene: { partOfSpeech: "v.", zh: "他/她有（tener）", en: "he/she has", example: "Ella tiene el pelo largo.", exampleZh: "她有長頭髮。", level: "A1" },
  "cuántos": { partOfSpeech: "adj.", zh: "多少（複數）", en: "how many", example: "¿Cuántos hermanos tienes?", exampleZh: "你有幾個兄弟姐妹？", level: "A1" },
  cuantos: { partOfSpeech: "adj.", zh: "多少（複數）", en: "how many", example: "¿Cuántos años tienes?", exampleZh: "你幾歲？", level: "A1" },
  // ── Ch1 L3 ──
  hasta: { partOfSpeech: "prep.", zh: "直到；再見", en: "until; goodbye", example: "Hasta mañana.", exampleZh: "明天見。", level: "A1" },
  luego: { partOfSpeech: "adv.", zh: "之後；稍後", en: "later; then", example: "Hasta luego.", exampleZh: "再見。", level: "A1" },
  "mañana": { partOfSpeech: "adv./n.f.", zh: "明天；早上", en: "tomorrow; morning", example: "Hasta mañana.", exampleZh: "明天見。", level: "A1" },
  manana: { partOfSpeech: "adv./n.f.", zh: "明天；早上", en: "tomorrow; morning", example: "Hasta mañana.", exampleZh: "明天見。", level: "A1" },
  nos: { partOfSpeech: "pron.", zh: "我們（受格）", en: "us; ourselves", example: "Nos vemos.", exampleZh: "我們再見。", level: "A1" },
  ver: { partOfSpeech: "v.", zh: "看見；見面", en: "to see", example: "¿Nos vemos mañana?", exampleZh: "我們明天見？", level: "A1" },
  vemos: { partOfSpeech: "v.", zh: "我們看見（ver）", en: "we see", example: "Nos vemos.", exampleZh: "我們再見。", level: "A1" },
  buen: { partOfSpeech: "adj.", zh: "好的", en: "good", example: "¡Que tengas un buen día!", exampleZh: "祝你有美好的一天！", level: "A1" },
  bueno: { partOfSpeech: "adj.", zh: "好的；良好的", en: "good", example: "Buenos días.", exampleZh: "早上好。", level: "A1" },
  buena: { partOfSpeech: "adj.", zh: "好的（陰性）", en: "good (f)", example: "Buenas tardes.", exampleZh: "下午好。", level: "A1" },
  buenos: { partOfSpeech: "adj.", zh: "好的（複數）", en: "good (pl)", example: "Buenos días.", exampleZh: "早上好。", level: "A1" },
  buenas: { partOfSpeech: "adj.", zh: "好的（陰性複數）", en: "good (f,pl)", example: "Buenas noches.", exampleZh: "晚安。", level: "A1" },
  "día": { partOfSpeech: "n.", zh: "天；日子", en: "day", example: "¿Qué día es hoy?", exampleZh: "今天是幾號？", level: "A1" },
  dia: { partOfSpeech: "n.", zh: "天；日子", en: "day", example: "Buen día.", exampleZh: "美好的一天。", level: "A1" },
  igualmente: { partOfSpeech: "adv.", zh: "同樣地；你也是", en: "likewise; same to you", example: "Igualmente, gracias.", exampleZh: "你也是，謝謝。", level: "A1" },
  // ── Common greetings ──
  "adiós": { partOfSpeech: "interj.", zh: "再見", en: "goodbye", example: "Adiós, hasta luego.", exampleZh: "再見，之後見。", level: "A1" },
  adios: { partOfSpeech: "interj.", zh: "再見", en: "goodbye", example: "Adiós.", exampleZh: "再見。", level: "A1" },
  gracias: { partOfSpeech: "interj.", zh: "謝謝", en: "thank you", example: "Muchas gracias.", exampleZh: "非常感謝。", level: "A1" },
  "por favor": { partOfSpeech: "phrase", zh: "請；麻煩你", en: "please", example: "Un café, por favor.", exampleZh: "一杯咖啡，請。", level: "A1" },
  que: { partOfSpeech: "conj.", zh: "那；因為；（連接詞）", en: "that; which", example: "Creo que hablas bien.", exampleZh: "我覺得你說得很好。", level: "A1" },
  "qué": { partOfSpeech: "pron.", zh: "什麼", en: "what", example: "¿Qué hora es?", exampleZh: "現在幾點？", level: "A1" },
  qui: { partOfSpeech: "pron.", zh: "什麼", en: "what", example: "¿Qué quieres?", exampleZh: "你想要什麼？", level: "A1" },
  es: { partOfSpeech: "v.", zh: "是（ser）", en: "is; it is", example: "Ella es simpática.", exampleZh: "她很友善。", level: "A1" },
  ser: { partOfSpeech: "v.", zh: "是；為（永久性）", en: "to be (permanent)", example: "Soy estudiante.", exampleZh: "我是學生。", level: "A1" },
  estar: { partOfSpeech: "v.", zh: "在；是（臨時性）", en: "to be (temporary/location)", example: "¿Dónde está el museo?", exampleZh: "博物館在哪裡？", level: "A1" },
  esta: { partOfSpeech: "adj./pron.", zh: "這個（陰性）", en: "this (f)", example: "Esta es mi madre.", exampleZh: "這是我媽媽。", level: "A1" },
  este: { partOfSpeech: "adj./pron.", zh: "這個（陽性）", en: "this (m)", example: "Este modelo es bonito.", exampleZh: "這個款式很漂亮。", level: "A1" },
  "está": { partOfSpeech: "v.", zh: "在；是（estar）", en: "is (location/state)", example: "El banco está aquí.", exampleZh: "銀行在這裡。", level: "A1" },
  estoy: { partOfSpeech: "v.", zh: "我在；我是（estar）", en: "I am (location/state)", example: "Estoy bien, gracias.", exampleZh: "我很好，謝謝。", level: "A1" },
  mucho: { partOfSpeech: "adv.", zh: "非常；很多", en: "a lot; very much", example: "Me gusta mucho.", exampleZh: "我非常喜歡。", level: "A1" },
  muy: { partOfSpeech: "adv.", zh: "很；非常", en: "very", example: "Es muy interesante.", exampleZh: "非常有趣。", level: "A1" },
  no: { partOfSpeech: "adv.", zh: "不；沒有", en: "no; not", example: "No hablo italiano.", exampleZh: "我不說義大利語。", level: "A1" },
  // ── Ch2 L1 ──
  familia: { partOfSpeech: "n.", zh: "家庭", en: "family", example: "Esta es mi familia.", exampleZh: "這是我的家人。", level: "A1" },
  madre: { partOfSpeech: "n.", zh: "媽媽；母親", en: "mother", example: "Mi madre se llama Rosa.", exampleZh: "我媽媽叫 Rosa。", level: "A1" },
  padre: { partOfSpeech: "n.", zh: "爸爸；父親", en: "father", example: "Mi padre trabaja aquí.", exampleZh: "我爸爸在這裡工作。", level: "A1" },
  hermano: { partOfSpeech: "n.", zh: "兄弟", en: "brother", example: "Tengo un hermano.", exampleZh: "我有一個兄弟。", level: "A1" },
  hermana: { partOfSpeech: "n.", zh: "姐妹", en: "sister", example: "Mi hermana es mayor.", exampleZh: "我姐姐比較大。", level: "A1" },
  padres: { partOfSpeech: "n.", zh: "父母", en: "parents", example: "Vivo con mis padres.", exampleZh: "我和父母同住。", level: "A1" },
  vivir: { partOfSpeech: "v.", zh: "居住；生活", en: "to live", example: "Vivo en Hong Kong.", exampleZh: "我住在香港。", level: "A1" },
  vivo: { partOfSpeech: "v.", zh: "我住（vivir）", en: "I live", example: "Vivo cerca del centro.", exampleZh: "我住在市中心附近。", level: "A1" },
  trabajar: { partOfSpeech: "v.", zh: "工作", en: "to work", example: "Trabajo en una oficina.", exampleZh: "我在辦公室工作。", level: "A1" },
  trabaja: { partOfSpeech: "v.", zh: "他/她工作（trabajar）", en: "he/she works", example: "Mi madre trabaja mucho.", exampleZh: "我媽媽工作很多。", level: "A1" },
  mi: { partOfSpeech: "adj.", zh: "我的", en: "my", example: "Mi nombre es Ana.", exampleZh: "我的名字是 Ana。", level: "A1" },
  mis: { partOfSpeech: "adj.", zh: "我的（複數）", en: "my (pl)", example: "Mis padres son simpáticos.", exampleZh: "我的父母很友善。", level: "A1" },
  tu: { partOfSpeech: "adj.", zh: "你的", en: "your", example: "¿Cómo se llama tu madre?", exampleZh: "你媽媽叫什麼名字？", level: "A1" },
  su: { partOfSpeech: "adj.", zh: "他的；她的；您的", en: "his/her/your (formal)", example: "Su madre es médica.", exampleZh: "她的媽媽是醫生。", level: "A1" },
  // ── Ch2 L2 ──
  abuelo: { partOfSpeech: "n.", zh: "爺爺；外公", en: "grandfather", example: "Mi abuelo es simpático.", exampleZh: "我爺爺很友善。", level: "A1" },
  abuela: { partOfSpeech: "n.", zh: "奶奶；外婆", en: "grandmother", example: "Mi abuela cocina bien.", exampleZh: "我奶奶很會做飯。", level: "A1" },
  alto: { partOfSpeech: "adj.", zh: "高的", en: "tall; high", example: "Mi abuelo es muy alto.", exampleZh: "我爺爺很高。", level: "A1" },
  alta: { partOfSpeech: "adj.", zh: "高的（陰性）", en: "tall (f)", example: "Ella es muy alta.", exampleZh: "她很高。", level: "A1" },
  "simpático": { partOfSpeech: "adj.", zh: "友善的；可親的", en: "friendly; nice", example: "Es muy simpático.", exampleZh: "他很友善。", level: "A1" },
  "simpática": { partOfSpeech: "adj.", zh: "友善的（陰性）", en: "friendly (f)", example: "Tu amiga es muy simpática.", exampleZh: "你朋友很友善。", level: "A1" },
  pelo: { partOfSpeech: "n.", zh: "頭髮", en: "hair", example: "Tiene el pelo negro.", exampleZh: "他有黑頭髮。", level: "A1" },
  blanco: { partOfSpeech: "adj.", zh: "白色的", en: "white", example: "Ella tiene el pelo blanco.", exampleZh: "她有白頭髮。", level: "A1" },
  blanca: { partOfSpeech: "adj.", zh: "白色的（陰性）", en: "white (f)", example: "La casa es blanca.", exampleZh: "房子是白色的。", level: "A1" },
  "cariñoso": { partOfSpeech: "adj.", zh: "慈愛的；親切的", en: "affectionate", example: "Es muy cariñoso.", exampleZh: "他很慈愛。", level: "A1" },
  joven: { partOfSpeech: "adj.", zh: "年輕的", en: "young", example: "Mi tío es muy joven.", exampleZh: "我叔叔很年輕。", level: "A1" },
  divertido: { partOfSpeech: "adj.", zh: "有趣的；好玩的", en: "fun; amusing", example: "La clase es muy divertida.", exampleZh: "課堂很有趣。", level: "A1" },
  grande: { partOfSpeech: "adj.", zh: "大的", en: "big; large", example: "Tenemos una familia grande.", exampleZh: "我們家庭很大。", level: "A1" },
  pequeño: { partOfSpeech: "adj.", zh: "小的（陽性）", en: "small (m)", example: "El apartamento es pequeño.", exampleZh: "公寓很小。", level: "A1" },
  tío: { partOfSpeech: "n.", zh: "叔叔；舅舅", en: "uncle", example: "Mi tío vive en Madrid.", exampleZh: "我叔叔住在馬德里。", level: "A1" },
  "tía": { partOfSpeech: "n.", zh: "阿姨；姑姑", en: "aunt", example: "Mi tía es profesora.", exampleZh: "我阿姨是老師。", level: "A1" },
  // ── Ch2 L3 ──
  enfermera: { partOfSpeech: "n.", zh: "護士（女）", en: "nurse (f)", example: "Mi madre es enfermera.", exampleZh: "我媽媽是護士。", level: "A1" },
  enfermero: { partOfSpeech: "n.", zh: "護士（男）", en: "nurse (m)", example: "El enfermero me ayuda.", exampleZh: "護士幫助我。", level: "A1" },
  "médico": { partOfSpeech: "n.", zh: "醫生", en: "doctor", example: "El médico habla inglés.", exampleZh: "醫生說英語。", level: "A1" },
  ingeniero: { partOfSpeech: "n.", zh: "工程師", en: "engineer", example: "Mi padre es ingeniero.", exampleZh: "我爸爸是工程師。", level: "A1" },
  profesor: { partOfSpeech: "n.", zh: "老師（男）", en: "teacher (m)", example: "El profesor es simpático.", exampleZh: "老師很友善。", level: "A1" },
  profesora: { partOfSpeech: "n.", zh: "老師（女）", en: "teacher (f)", example: "La profesora habla rápido.", exampleZh: "老師說話很快。", level: "A1" },
  estudiar: { partOfSpeech: "v.", zh: "學習；讀書", en: "to study", example: "Estudio español.", exampleZh: "我學習西班牙語。", level: "A1" },
  estudia: { partOfSpeech: "v.", zh: "他/她讀書（estudiar）", en: "he/she studies", example: "Mi hermana estudia medicina.", exampleZh: "我姐姐學醫。", level: "A1" },
  universidad: { partOfSpeech: "n.", zh: "大學", en: "university", example: "Estudio en la universidad.", exampleZh: "我在大學讀書。", level: "A1" },
  hospital: { partOfSpeech: "n.", zh: "醫院", en: "hospital", example: "El hospital está cerca.", exampleZh: "醫院在附近。", level: "A1" },
  // ── Ch3 L1 ──
  querer: { partOfSpeech: "v.", zh: "想要；愛", en: "to want; to love", example: "¿Qué quieres tomar?", exampleZh: "你想喝什麼？", level: "A1" },
  quiero: { partOfSpeech: "v.", zh: "我想要（querer）", en: "I want", example: "Quiero un café.", exampleZh: "我想要一杯咖啡。", level: "A1" },
  "café": { partOfSpeech: "n.", zh: "咖啡", en: "coffee", example: "Un café con leche, por favor.", exampleZh: "一杯拿鐵，謝謝。", level: "A1" },
  cafe: { partOfSpeech: "n.", zh: "咖啡", en: "coffee", example: "Me gusta el café.", exampleZh: "我喜歡咖啡。", level: "A1" },
  leche: { partOfSpeech: "n.", zh: "牛奶", en: "milk", example: "Café con leche.", exampleZh: "拿鐵。", level: "A1" },
  algo: { partOfSpeech: "pron.", zh: "某些東西；還有", en: "something; anything", example: "¿Algo más?", exampleZh: "還要其他的嗎？", level: "A1" },
  "más": { partOfSpeech: "adv.", zh: "更多；還有", en: "more; else", example: "¿Algo más?", exampleZh: "還有其他的嗎？", level: "A1" },
  mas: { partOfSpeech: "adv.", zh: "更多；還有", en: "more", example: "Quiero más agua.", exampleZh: "我想要更多水。", level: "A1" },
  "también": { partOfSpeech: "adv.", zh: "也；同樣", en: "also; too", example: "Yo también hablo chino.", exampleZh: "我也說中文。", level: "A1" },
  tambien: { partOfSpeech: "adv.", zh: "也；同樣", en: "also", example: "Ella también está aquí.", exampleZh: "她也在這裡。", level: "A1" },
  enseguida: { partOfSpeech: "adv.", zh: "馬上；立刻", en: "right away; immediately", example: "¡Enseguida!", exampleZh: "馬上來！", level: "A1" },
  desear: { partOfSpeech: "v.", zh: "希望；想要（正式）", en: "to wish; to desire", example: "¿Qué desea?", exampleZh: "您想要什麼？", level: "A1" },
  desea: { partOfSpeech: "v.", zh: "您想要（desear）", en: "do you wish (formal)", example: "¿Qué desea?", exampleZh: "您想要什麼？", level: "A1" },
  // ── Ch3 L2 ──
  cuenta: { partOfSpeech: "n.", zh: "帳單；賬", en: "bill; account", example: "La cuenta, por favor.", exampleZh: "結帳，麻煩你。", level: "A1" },
  "cuánto": { partOfSpeech: "adj.", zh: "多少（錢）", en: "how much", example: "¿Cuánto es?", exampleZh: "多少錢？", level: "A1" },
  cuanto: { partOfSpeech: "adj.", zh: "多少", en: "how much", example: "¿Cuánto cuesta?", exampleZh: "多少錢？", level: "A1" },
  total: { partOfSpeech: "n.", zh: "總計；合計", en: "total", example: "¿Cuánto es en total?", exampleZh: "一共多少錢？", level: "A1" },
  euro: { partOfSpeech: "n.", zh: "歐元", en: "euro", example: "Son cinco euros.", exampleZh: "總共是五歐元。", level: "A1" },
  euros: { partOfSpeech: "n.", zh: "歐元（複數）", en: "euros", example: "Cuesta diez euros.", exampleZh: "這要十歐元。", level: "A1" },
  aceptar: { partOfSpeech: "v.", zh: "接受", en: "to accept", example: "¿Aceptan tarjeta?", exampleZh: "你們接受信用卡嗎？", level: "A1" },
  tarjeta: { partOfSpeech: "n.", zh: "信用卡；卡片", en: "card", example: "Pago con tarjeta.", exampleZh: "我用信用卡付款。", level: "A1" },
  cambio: { partOfSpeech: "n.", zh: "找零；零錢", en: "change (money)", example: "Aquí tiene el cambio.", exampleZh: "這是您的找零。", level: "A1" },
  son: { partOfSpeech: "v.", zh: "他們是（ser）；是（金額）", en: "they are; it is (amount)", example: "Son tres euros.", exampleZh: "是三歐元。", level: "A1" },
  aquí: { partOfSpeech: "adv.", zh: "這裡", en: "here", example: "Aquí está.", exampleZh: "在這裡。", level: "A1" },
  aqui: { partOfSpeech: "adv.", zh: "這裡", en: "here", example: "Vivo aquí.", exampleZh: "我住在這裡。", level: "A1" },
  // ── Ch3 L3 ──
  gustar: { partOfSpeech: "v.", zh: "喜歡", en: "to like (indirect)", example: "Me gusta el café.", exampleZh: "我喜歡咖啡。", level: "A1" },
  gusta: { partOfSpeech: "v.", zh: "喜歡（gustar）", en: "like (s)", example: "Me gusta mucho.", exampleZh: "我非常喜歡。", level: "A1" },
  gustan: { partOfSpeech: "v.", zh: "喜歡（複數）", en: "like (pl)", example: "Me gustan las frutas.", exampleZh: "我喜歡水果。", level: "A1" },
  encantar: { partOfSpeech: "v.", zh: "非常喜歡；超愛", en: "to love; to adore", example: "Me encanta la música.", exampleZh: "我超愛音樂。", level: "A1" },
  encanta: { partOfSpeech: "v.", zh: "非常喜歡（encantar）", en: "love (s)", example: "Me encanta el chocolate.", exampleZh: "我超愛巧克力。", level: "A1" },
  preferir: { partOfSpeech: "v.", zh: "比較喜歡；偏好", en: "to prefer", example: "Prefiero el té.", exampleZh: "我比較喜歡茶。", level: "A1" },
  prefiero: { partOfSpeech: "v.", zh: "我比較喜歡（preferir）", en: "I prefer", example: "Prefiero el agua.", exampleZh: "我比較喜歡水。", level: "A1" },
  amargo: { partOfSpeech: "adj.", zh: "苦的", en: "bitter", example: "El café está amargo.", exampleZh: "咖啡是苦的。", level: "A1" },
  picante: { partOfSpeech: "adj.", zh: "辣的", en: "spicy; hot", example: "¿Te gusta la comida picante?", exampleZh: "你喜歡辣食嗎？", level: "A1" },
  dulce: { partOfSpeech: "adj.", zh: "甜的", en: "sweet", example: "Este pastel es muy dulce.", exampleZh: "這個蛋糕很甜。", level: "A1" },
  gas: { partOfSpeech: "n.", zh: "氣體（con gas = 有氣）", en: "gas; fizzy", example: "Agua con gas, por favor.", exampleZh: "氣泡水，謝謝。", level: "A1" },
  comida: { partOfSpeech: "n.", zh: "食物；飯", en: "food; meal", example: "La comida está rica.", exampleZh: "食物很美味。", level: "A1" },
  agua: { partOfSpeech: "n.", zh: "水", en: "water", example: "Quiero agua, por favor.", exampleZh: "我想要水，謝謝。", level: "A1" },
  // ── Ch4 L1 ──
  buscar: { partOfSpeech: "v.", zh: "尋找；找", en: "to look for", example: "Busco un apartamento.", exampleZh: "我在找公寓。", level: "A1" },
  buscando: { partOfSpeech: "gerund", zh: "正在找（buscar）", en: "looking for", example: "Estoy buscando trabajo.", exampleZh: "我正在找工作。", level: "A1" },
  camiseta: { partOfSpeech: "n.", zh: "T 恤", en: "T-shirt", example: "Quiero una camiseta azul.", exampleZh: "我想要一件藍色 T 恤。", level: "A1" },
  talla: { partOfSpeech: "n.", zh: "尺碼；尺寸", en: "size (clothing)", example: "¿Qué talla tienes?", exampleZh: "你穿幾號？", level: "A1" },
  mediana: { partOfSpeech: "adj.", zh: "中等的；中碼", en: "medium", example: "Talla mediana, por favor.", exampleZh: "中碼，謝謝。", level: "A1" },
  probar: { partOfSpeech: "v.", zh: "試；嘗試", en: "to try; to taste", example: "¿Puedo probarlo?", exampleZh: "我可以試試嗎？", level: "A1" },
  ayudar: { partOfSpeech: "v.", zh: "幫助；幫忙", en: "to help", example: "¿Te puedo ayudar?", exampleZh: "我可以幫你嗎？", level: "A1" },
  tienda: { partOfSpeech: "n.", zh: "商店；店舖", en: "shop; store", example: "La tienda está cerrada.", exampleZh: "商店關門了。", level: "A1" },
  probador: { partOfSpeech: "n.", zh: "試衣間", en: "fitting room", example: "El probador está al fondo.", exampleZh: "試衣間在最裡面。", level: "A1" },
  puedo: { partOfSpeech: "v.", zh: "我可以（poder）", en: "I can", example: "¿Puedo ayudarle?", exampleZh: "我可以幫您嗎？", level: "A1" },
  puedes: { partOfSpeech: "v.", zh: "你可以（poder）", en: "you can", example: "Puedes sentarte aquí.", exampleZh: "你可以坐在這裡。", level: "A1" },
  // ── Ch4 L2 ──
  azul: { partOfSpeech: "adj.", zh: "藍色的", en: "blue", example: "El cielo es azul.", exampleZh: "天空是藍色的。", level: "A1" },
  rojo: { partOfSpeech: "adj.", zh: "紅色的", en: "red", example: "Me gusta el rojo.", exampleZh: "我喜歡紅色。", level: "A1" },
  verde: { partOfSpeech: "adj.", zh: "綠色的", en: "green", example: "La planta es verde.", exampleZh: "植物是綠色的。", level: "A1" },
  negro: { partOfSpeech: "adj.", zh: "黑色的", en: "black", example: "Tengo un gato negro.", exampleZh: "我有一隻黑貓。", level: "A1" },
  barato: { partOfSpeech: "adj.", zh: "便宜的", en: "cheap; inexpensive", example: "Este es más barato.", exampleZh: "這個比較便宜。", level: "A1" },
  caro: { partOfSpeech: "adj.", zh: "貴的", en: "expensive", example: "Es demasiado caro.", exampleZh: "太貴了。", level: "A1" },
  modelo: { partOfSpeech: "n.", zh: "款式；型號", en: "model; style", example: "Este modelo es popular.", exampleZh: "這個款式很流行。", level: "A1" },
  llevarse: { partOfSpeech: "v.", zh: "帶走；購買", en: "to take; to buy", example: "Me lo llevo.", exampleZh: "我要買這個。", level: "A1" },
  // ── Ch4 L3 ──
  pagar: { partOfSpeech: "v.", zh: "付款；付錢", en: "to pay", example: "¿Cómo va a pagar?", exampleZh: "您打算怎樣付款？", level: "A1" },
  efectivo: { partOfSpeech: "n.", zh: "現金", en: "cash", example: "Pago en efectivo.", exampleZh: "我用現金付款。", level: "A1" },
  bolsa: { partOfSpeech: "n.", zh: "袋子；手袋", en: "bag", example: "¿Necesita una bolsa?", exampleZh: "您需要袋子嗎？", level: "A1" },
  recibo: { partOfSpeech: "n.", zh: "收據", en: "receipt", example: "¿Puedo tener el recibo?", exampleZh: "可以給我收據嗎？", level: "A1" },
  descuento: { partOfSpeech: "n.", zh: "折扣；優惠", en: "discount", example: "¿Tienen descuento?", exampleZh: "有折扣嗎？", level: "A1" },
  oferta: { partOfSpeech: "n.", zh: "特價；促銷", en: "offer; sale", example: "Está en oferta.", exampleZh: "正在打折。", level: "A1" },
  precio: { partOfSpeech: "n.", zh: "價格", en: "price", example: "¿Cuál es el precio?", exampleZh: "價格是多少？", level: "A1" },
  // ── Ch5 L1 ──
  perdona: { partOfSpeech: "v.", zh: "對不起；打擾一下", en: "excuse me; sorry", example: "Perdona, ¿dónde está...?", exampleZh: "打擾一下，…在哪裡？", level: "A1" },
  perdone: { partOfSpeech: "v.", zh: "對不起（正式）", en: "excuse me (formal)", example: "Perdone, ¿puede ayudarme?", exampleZh: "對不起，您可以幫我嗎？", level: "A1" },
  museo: { partOfSpeech: "n.", zh: "博物館", en: "museum", example: "El museo está lejos.", exampleZh: "博物館很遠。", level: "A1" },
  seguir: { partOfSpeech: "v.", zh: "繼續；跟隨", en: "to continue; to follow", example: "Siga todo recto.", exampleZh: "一直往前走。", level: "A1" },
  siga: { partOfSpeech: "v.", zh: "繼續（命令式）", en: "continue (command)", example: "Siga recto.", exampleZh: "直走。", level: "A1" },
  recto: { partOfSpeech: "adv.", zh: "直；筆直", en: "straight", example: "Todo recto.", exampleZh: "一直往前。", level: "A1" },
  girar: { partOfSpeech: "v.", zh: "轉彎；旋轉", en: "to turn", example: "Gire a la derecha.", exampleZh: "向右轉。", level: "A1" },
  gire: { partOfSpeech: "v.", zh: "轉彎（命令式）", en: "turn (command)", example: "Gire a la izquierda.", exampleZh: "向左轉。", level: "A1" },
  derecha: { partOfSpeech: "n.", zh: "右邊", en: "right side", example: "A la derecha.", exampleZh: "在右邊。", level: "A1" },
  izquierda: { partOfSpeech: "n.", zh: "左邊", en: "left side", example: "Gire a la izquierda.", exampleZh: "向左轉。", level: "A1" },
  calle: { partOfSpeech: "n.", zh: "街道", en: "street", example: "Esta calle es larga.", exampleZh: "這條街很長。", level: "A1" },
  amable: { partOfSpeech: "adj.", zh: "友善的；好心的", en: "kind; friendly", example: "Es muy amable.", exampleZh: "他非常友善。", level: "A1" },
  // ── Ch5 L2 ──
  banco: { partOfSpeech: "n.", zh: "銀行；長椅", en: "bank; bench", example: "El banco está cerca.", exampleZh: "銀行在附近。", level: "A1" },
  parque: { partOfSpeech: "n.", zh: "公園", en: "park", example: "El parque es bonito.", exampleZh: "公園很漂亮。", level: "A1" },
  cerca: { partOfSpeech: "adv.", zh: "近；附近", en: "near; close", example: "Está muy cerca.", exampleZh: "很近。", level: "A1" },
  lejos: { partOfSpeech: "adv.", zh: "遠", en: "far", example: "Está un poco lejos.", exampleZh: "有點遠。", level: "A1" },
  parada: { partOfSpeech: "n.", zh: "站；停靠站", en: "stop; station", example: "La parada de bus.", exampleZh: "公車站。", level: "A1" },
  enfrente: { partOfSpeech: "adv.", zh: "對面；正前方", en: "opposite; in front", example: "Está enfrente.", exampleZh: "在對面。", level: "A1" },
  supermercado: { partOfSpeech: "n.", zh: "超市", en: "supermarket", example: "El supermercado está abierto.", exampleZh: "超市開著。", level: "A1" },
  andando: { partOfSpeech: "gerund", zh: "步行（andar）", en: "walking", example: "A diez minutos andando.", exampleZh: "步行十分鐘。", level: "A1" },
  // ── Ch5 L3 ──
  metro: { partOfSpeech: "n.", zh: "地鐵；公尺", en: "metro; meter", example: "Coge el metro.", exampleZh: "搭地鐵。", level: "A1" },
  "estación": { partOfSpeech: "n.", zh: "站；車站；季節", en: "station; season", example: "La estación está cerca.", exampleZh: "車站在附近。", level: "A1" },
  estacion: { partOfSpeech: "n.", zh: "站；車站", en: "station", example: "¿Dónde está la estación?", exampleZh: "車站在哪裡？", level: "A1" },
  "línea": { partOfSpeech: "n.", zh: "線；路線", en: "line; route", example: "Línea dos, por favor.", exampleZh: "二號線，謝謝。", level: "A1" },
  linea: { partOfSpeech: "n.", zh: "線；路線", en: "line", example: "Coge la línea cuatro.", exampleZh: "搭四號線。", level: "A1" },
  trasbordo: { partOfSpeech: "n.", zh: "轉乘；換乘", en: "transfer; connection", example: "¿Hay que hacer trasbordo?", exampleZh: "需要轉車嗎？", level: "A1" },
  tardar: { partOfSpeech: "v.", zh: "花時間；延遲", en: "to take time; to be late", example: "¿Cuánto tarda?", exampleZh: "需要多長時間？", level: "A1" },
  cambiar: { partOfSpeech: "v.", zh: "換；改變", en: "to change; to switch", example: "Cambia de línea aquí.", exampleZh: "在這裡換線。", level: "A1" },
  "autobús": { partOfSpeech: "n.", zh: "巴士", en: "bus", example: "Cojo el autobús.", exampleZh: "我搭公車。", level: "A1" },
  autobus: { partOfSpeech: "n.", zh: "巴士", en: "bus", example: "El autobús está lleno.", exampleZh: "公車很擠。", level: "A1" },
  taxi: { partOfSpeech: "n.", zh: "計程車", en: "taxi", example: "Voy a coger un taxi.", exampleZh: "我要搭計程車。", level: "A1" },
  // ── Ch6 L1 ──
  levantarse: { partOfSpeech: "v.", zh: "起床", en: "to get up", example: "Me levanto temprano.", exampleZh: "我起床很早。", level: "A1" },
  levanto: { partOfSpeech: "v.", zh: "我起床（levantarse）", en: "I get up", example: "Me levanto a las siete.", exampleZh: "我七點起床。", level: "A1" },
  desayunar: { partOfSpeech: "v.", zh: "吃早餐", en: "to have breakfast", example: "Desayuno a las ocho.", exampleZh: "我八點吃早餐。", level: "A1" },
  desayuno: { partOfSpeech: "v./n.", zh: "我吃早餐；早餐", en: "I have breakfast; breakfast", example: "Desayuno con mi familia.", exampleZh: "我和家人吃早餐。", level: "A1" },
  almorzar: { partOfSpeech: "v.", zh: "吃午餐", en: "to have lunch", example: "Almuerzo a las dos.", exampleZh: "我兩點吃午飯。", level: "A1" },
  cenar: { partOfSpeech: "v.", zh: "吃晚餐", en: "to have dinner", example: "Cenamos juntos.", exampleZh: "我們一起吃晚飯。", level: "A1" },
  salir: { partOfSpeech: "v.", zh: "出去；離開", en: "to go out; to leave", example: "Salgo a las ocho.", exampleZh: "我八點出門。", level: "A1" },
  salgo: { partOfSpeech: "v.", zh: "我出去（salir）", en: "I go out", example: "Salgo tarde hoy.", exampleZh: "我今天出門很晚。", level: "A1" },
  acostarse: { partOfSpeech: "v.", zh: "睡覺；躺下", en: "to go to bed; to lie down", example: "Me acuesto tarde.", exampleZh: "我睡得很晚。", level: "A1" },
  acuesto: { partOfSpeech: "v.", zh: "我睡覺（acostarse）", en: "I go to bed", example: "Me acuesto a las once.", exampleZh: "我十一點睡覺。", level: "A1" },
  ducharse: { partOfSpeech: "v.", zh: "洗澡", en: "to shower", example: "Me ducho por la mañana.", exampleZh: "我早上洗澡。", level: "A1" },
  siempre: { partOfSpeech: "adv.", zh: "總是；永遠", en: "always", example: "Siempre llego tarde.", exampleZh: "我總是遲到。", level: "A1" },
  // ── Ch6 L2 ──
  hora: { partOfSpeech: "n.", zh: "小時；時間", en: "hour; time", example: "¿Qué hora es?", exampleZh: "現在幾點？", level: "A1" },
  cuarto: { partOfSpeech: "n.", zh: "一刻（15分）；房間", en: "quarter; room", example: "Son las tres y cuarto.", exampleZh: "三點一刻。", level: "A1" },
  media: { partOfSpeech: "adj.", zh: "一半；半", en: "half", example: "Es la una y media.", exampleZh: "一點半。", level: "A1" },
  menos: { partOfSpeech: "adv.", zh: "差；減", en: "minus; to (time)", example: "Son las diez menos cinco.", exampleZh: "差五分十點。", level: "A1" },
  punto: { partOfSpeech: "n.", zh: "點；整（時間）", en: "point; sharp (time)", example: "A las ocho en punto.", exampleZh: "八點整。", level: "A1" },
  quedar: { partOfSpeech: "v.", zh: "約好見面；安排", en: "to meet up; to arrange", example: "¿Quedamos mañana?", exampleZh: "我們明天見面？", level: "A1" },
  tarde: { partOfSpeech: "adv./n.f.", zh: "晚；下午", en: "late; afternoon", example: "Llego tarde.", exampleZh: "我來晚了。", level: "A1" },
  temprano: { partOfSpeech: "adv.", zh: "早；提早", en: "early", example: "Me levanto temprano.", exampleZh: "我很早起床。", level: "A1" },
  // ── Ch6 L3 ──
  lunes: { partOfSpeech: "n.", zh: "星期一", en: "Monday", example: "El lunes tengo clase.", exampleZh: "星期一我有課。", level: "A1" },
  martes: { partOfSpeech: "n.", zh: "星期二", en: "Tuesday", example: "El martes hay reunión.", exampleZh: "星期二有會議。", level: "A1" },
  "miércoles": { partOfSpeech: "n.", zh: "星期三", en: "Wednesday", example: "El miércoles trabajo.", exampleZh: "星期三我工作。", level: "A1" },
  jueves: { partOfSpeech: "n.", zh: "星期四", en: "Thursday", example: "El jueves voy al cine.", exampleZh: "星期四我去看電影。", level: "A1" },
  viernes: { partOfSpeech: "n.", zh: "星期五", en: "Friday", example: "El viernes salgo pronto.", exampleZh: "星期五我早點下班。", level: "A1" },
  "sábado": { partOfSpeech: "n.", zh: "星期六", en: "Saturday", example: "El sábado descansamos.", exampleZh: "星期六我們休息。", level: "A1" },
  sabado: { partOfSpeech: "n.", zh: "星期六", en: "Saturday", example: "El sábado hay mercado.", exampleZh: "星期六有市場。", level: "A1" },
  domingo: { partOfSpeech: "n.", zh: "星期日", en: "Sunday", example: "El domingo como con la familia.", exampleZh: "星期日我和家人吃飯。", level: "A1" },
  enero: { partOfSpeech: "n.", zh: "一月", en: "January", example: "En enero hace frío.", exampleZh: "一月很冷。", level: "A1" },
  febrero: { partOfSpeech: "n.", zh: "二月", en: "February", example: "Mi cumpleaños es en febrero.", exampleZh: "我生日在二月。", level: "A1" },
  marzo: { partOfSpeech: "n.", zh: "三月", en: "March", example: "En marzo empieza la primavera.", exampleZh: "三月春天開始。", level: "A1" },
  abril: { partOfSpeech: "n.", zh: "四月", en: "April", example: "Las flores de abril.", exampleZh: "四月的花。", level: "A1" },
  mayo: { partOfSpeech: "n.", zh: "五月", en: "May", example: "En mayo hace buen tiempo.", exampleZh: "五月天氣很好。", level: "A1" },
  junio: { partOfSpeech: "n.", zh: "六月", en: "June", example: "Las vacaciones son en junio.", exampleZh: "假期在六月。", level: "A1" },
  julio: { partOfSpeech: "n.", zh: "七月", en: "July", example: "Julio es muy caluroso.", exampleZh: "七月很熱。", level: "A1" },
  agosto: { partOfSpeech: "n.", zh: "八月", en: "August", example: "En agosto voy a la playa.", exampleZh: "八月我去海灘。", level: "A1" },
  septiembre: { partOfSpeech: "n.", zh: "九月", en: "September", example: "Las clases empiezan en septiembre.", exampleZh: "九月上課。", level: "A1" },
  octubre: { partOfSpeech: "n.", zh: "十月", en: "October", example: "Octubre es bonito.", exampleZh: "十月很美。", level: "A1" },
  noviembre: { partOfSpeech: "n.", zh: "十一月", en: "November", example: "En noviembre llueve mucho.", exampleZh: "十一月下很多雨。", level: "A1" },
  diciembre: { partOfSpeech: "n.", zh: "十二月", en: "December", example: "La Navidad es en diciembre.", exampleZh: "聖誕節在十二月。", level: "A1" },
  "cumpleaños": { partOfSpeech: "n.", zh: "生日", en: "birthday", example: "¡Feliz cumpleaños!", exampleZh: "生日快樂！", level: "A1" },
  cumpleanos: { partOfSpeech: "n.", zh: "生日", en: "birthday", example: "¿Cuándo es tu cumpleaños?", exampleZh: "你生日是什麼時候？", level: "A1" },
  verdad: { partOfSpeech: "n.", zh: "真相；真的", en: "truth; really", example: "¿Verdad que es bonito?", exampleZh: "很漂亮，對嗎？", level: "A1" },
  hoy: { partOfSpeech: "adv.", zh: "今天", en: "today", example: "¿Qué día es hoy?", exampleZh: "今天是幾號？", level: "A1" },
  // ── Ch7 L1 ──
  "fin de semana": { partOfSpeech: "n.", zh: "週末", en: "weekend", example: "¿Qué haces el fin de semana?", exampleZh: "你週末做什麼？", level: "A1" },
  pensar: { partOfSpeech: "v.", zh: "打算；思考", en: "to think; to plan", example: "Pienso ir al cine.", exampleZh: "我打算去看電影。", level: "A1" },
  pensamos: { partOfSpeech: "v.", zh: "我們打算（pensar）", en: "we think; we plan", example: "Pensamos ir a la playa.", exampleZh: "我們打算去海灘。", level: "A1" },
  playa: { partOfSpeech: "n.", zh: "海灘；海邊", en: "beach", example: "Vamos a la playa.", exampleZh: "我們去海灘。", level: "A1" },
  nosotros: { partOfSpeech: "pron.", zh: "我們", en: "we; us", example: "Nosotros somos amigos.", exampleZh: "我們是朋友。", level: "A1" },
  invitar: { partOfSpeech: "v.", zh: "邀請", en: "to invite", example: "Te invito a cenar.", exampleZh: "我邀請你吃晚飯。", level: "A1" },
  plan: { partOfSpeech: "n.", zh: "計劃；安排", en: "plan", example: "¿Tienes plan?", exampleZh: "你有計劃嗎？", level: "A1" },
  planes: { partOfSpeech: "n.", zh: "計劃（複數）", en: "plans", example: "¿Qué planes tienes?", exampleZh: "你有什麼計劃？", level: "A1" },
  venir: { partOfSpeech: "v.", zh: "來", en: "to come", example: "¿Quieres venir?", exampleZh: "你想來嗎？", level: "A1" },
  quieres: { partOfSpeech: "v.", zh: "你想要（querer）", en: "you want", example: "¿Qué quieres hacer?", exampleZh: "你想做什麼？", level: "A1" },
  // ── Ch7 L2 ──
  jugar: { partOfSpeech: "v.", zh: "玩；運動", en: "to play", example: "Juego al tenis.", exampleZh: "我打網球。", level: "A1" },
  "fútbol": { partOfSpeech: "n.", zh: "足球", en: "football; soccer", example: "Me gusta el fútbol.", exampleZh: "我喜歡足球。", level: "A1" },
  futbol: { partOfSpeech: "n.", zh: "足球", en: "football", example: "Juego al fútbol.", exampleZh: "我踢足球。", level: "A1" },
  "natación": { partOfSpeech: "n.", zh: "游泳", en: "swimming", example: "La natación es saludable.", exampleZh: "游泳很健康。", level: "A1" },
  natacion: { partOfSpeech: "n.", zh: "游泳", en: "swimming", example: "Practico natación.", exampleZh: "我游泳。", level: "A1" },
  practicar: { partOfSpeech: "v.", zh: "練習；從事", en: "to practice; to play (sports)", example: "Practico yoga.", exampleZh: "我練習瑜珈。", level: "A1" },
  equipo: { partOfSpeech: "n.", zh: "團隊；隊伍", en: "team; equipment", example: "El equipo juega bien.", exampleZh: "隊伍踢得很好。", level: "A1" },
  "televisión": { partOfSpeech: "n.", zh: "電視", en: "television", example: "Veo la televisión.", exampleZh: "我看電視。", level: "A1" },
  television: { partOfSpeech: "n.", zh: "電視", en: "television", example: "¿Ves televisión?", exampleZh: "你看電視嗎？", level: "A1" },
  escuchar: { partOfSpeech: "v.", zh: "聽；聆聽", en: "to listen", example: "Escucho música.", exampleZh: "我聽音樂。", level: "A1" },
  "música": { partOfSpeech: "n.", zh: "音樂", en: "music", example: "Me gusta la música.", exampleZh: "我喜歡音樂。", level: "A1" },
  musica: { partOfSpeech: "n.", zh: "音樂", en: "music", example: "Escucho música.", exampleZh: "我聽音樂。", level: "A1" },
  leer: { partOfSpeech: "v.", zh: "閱讀；看書", en: "to read", example: "Me gusta leer.", exampleZh: "我喜歡閱讀。", level: "A1" },
  // ── Ch7 L3 ──
  tiempo: { partOfSpeech: "n.", zh: "天氣；時間", en: "weather; time", example: "¿Qué tiempo hace?", exampleZh: "天氣怎樣？", level: "A1" },
  sol: { partOfSpeech: "n.", zh: "太陽；陽光", en: "sun; sunshine", example: "Hace sol hoy.", exampleZh: "今天陽光很好。", level: "A1" },
  calor: { partOfSpeech: "n.", zh: "熱；炎熱", en: "heat; warmth", example: "Hace mucho calor.", exampleZh: "很熱。", level: "A1" },
  lluvia: { partOfSpeech: "n.", zh: "雨", en: "rain", example: "Hay mucha lluvia hoy.", exampleZh: "今天雨很多。", level: "A1" },
  lloviendo: { partOfSpeech: "gerund", zh: "正在下雨（llover）", en: "raining", example: "Está lloviendo.", exampleZh: "正在下雨。", level: "A1" },
  viento: { partOfSpeech: "n.", zh: "風", en: "wind", example: "Hace mucho viento.", exampleZh: "風很大。", level: "A1" },
  "frío": { partOfSpeech: "n./adj.", zh: "冷；寒冷", en: "cold", example: "Hace frío hoy.", exampleZh: "今天很冷。", level: "A1" },
  frio: { partOfSpeech: "n./adj.", zh: "冷；寒冷", en: "cold", example: "Tengo frío.", exampleZh: "我很冷。", level: "A1" },
  invierno: { partOfSpeech: "n.", zh: "冬天", en: "winter", example: "En invierno hace frío.", exampleZh: "冬天很冷。", level: "A1" },
  verano: { partOfSpeech: "n.", zh: "夏天", en: "summer", example: "En verano voy a la playa.", exampleZh: "夏天我去海灘。", level: "A1" },
  primavera: { partOfSpeech: "n.", zh: "春天", en: "spring", example: "La primavera es bonita.", exampleZh: "春天很美。", level: "A1" },
  "otoño": { partOfSpeech: "n.", zh: "秋天", en: "autumn; fall", example: "En otoño caen las hojas.", exampleZh: "秋天落葉。", level: "A1" },
  // ── Ch8 L1 ──
  cabeza: { partOfSpeech: "n.", zh: "頭", en: "head", example: "Me duele la cabeza.", exampleZh: "我頭痛。", level: "A1" },
  espalda: { partOfSpeech: "n.", zh: "背部", en: "back", example: "Tengo dolor de espalda.", exampleZh: "我背痛。", level: "A1" },
  rodilla: { partOfSpeech: "n.", zh: "膝蓋", en: "knee", example: "Me duelen las rodillas.", exampleZh: "我膝蓋痛。", level: "A1" },
  tobillo: { partOfSpeech: "n.", zh: "腳踝", en: "ankle", example: "Me he torcido el tobillo.", exampleZh: "我扭傷了腳踝。", level: "A1" },
  mano: { partOfSpeech: "n.", zh: "手", en: "hand", example: "Me duele la mano.", exampleZh: "我手痛。", level: "A1" },
  brazo: { partOfSpeech: "n.", zh: "手臂", en: "arm", example: "Me he roto el brazo.", exampleZh: "我手臂骨折了。", level: "A1" },
  pierna: { partOfSpeech: "n.", zh: "腿", en: "leg", example: "Me duele la pierna.", exampleZh: "我腿痛。", level: "A1" },
  doler: { partOfSpeech: "v.", zh: "痛；疼", en: "to hurt; to ache", example: "¿Dónde te duele?", exampleZh: "你哪裡痛？", level: "A1" },
  duele: { partOfSpeech: "v.", zh: "痛（doler）", en: "hurts; aches", example: "Me duele la cabeza.", exampleZh: "我頭痛。", level: "A1" },
  duelen: { partOfSpeech: "v.", zh: "痛（複數）", en: "hurt; ache (pl)", example: "Me duelen los pies.", exampleZh: "我腳痛。", level: "A1" },
  // ── Ch8 L2 ──
  fiebre: { partOfSpeech: "n.", zh: "發燒；體溫", en: "fever", example: "Tengo fiebre.", exampleZh: "我發燒了。", level: "A1" },
  tos: { partOfSpeech: "n.", zh: "咳嗽", en: "cough", example: "Tengo mucha tos.", exampleZh: "我咳嗽很厲害。", level: "A1" },
  gripe: { partOfSpeech: "n.", zh: "流感", en: "flu; influenza", example: "Creo que tengo gripe.", exampleZh: "我覺得我得了流感。", level: "A1" },
  resfriado: { partOfSpeech: "n.", zh: "感冒", en: "cold (illness)", example: "Tengo un resfriado.", exampleZh: "我感冒了。", level: "A1" },
  cita: { partOfSpeech: "n.", zh: "預約；約會", en: "appointment; date", example: "Tengo cita con el médico.", exampleZh: "我有醫生預約。", level: "A1" },
  creer: { partOfSpeech: "v.", zh: "相信；覺得", en: "to believe; to think", example: "Creo que sí.", exampleZh: "我覺得是。", level: "A1" },
  creo: { partOfSpeech: "v.", zh: "我覺得（creer）", en: "I think; I believe", example: "Creo que tengo razón.", exampleZh: "我覺得我是對的。", level: "A1" },
  encontrarse: { partOfSpeech: "v.", zh: "感覺（身體狀況）", en: "to feel (health)", example: "No me encuentro bien.", exampleZh: "我感覺不舒服。", level: "A1" },
  mareado: { partOfSpeech: "adj.", zh: "頭暈的；噁心的", en: "dizzy; nauseous", example: "Estoy mareado.", exampleZh: "我頭暈。", level: "A1" },
  // ── Ch8 L3 ──
  recetar: { partOfSpeech: "v.", zh: "開藥方；處方", en: "to prescribe", example: "El médico me receta antibióticos.", exampleZh: "醫生給我開抗生素。", level: "A1" },
  "antibiótico": { partOfSpeech: "n.", zh: "抗生素", en: "antibiotic", example: "Tome el antibiótico.", exampleZh: "服用抗生素。", level: "A1" },
  antibiotico: { partOfSpeech: "n.", zh: "抗生素", en: "antibiotic", example: "Necesito antibióticos.", exampleZh: "我需要抗生素。", level: "A1" },
  pastilla: { partOfSpeech: "n.", zh: "藥片；片劑", en: "tablet; pill", example: "Tome dos pastillas.", exampleZh: "服兩片藥。", level: "A1" },
  descansar: { partOfSpeech: "v.", zh: "休息", en: "to rest", example: "Tiene que descansar.", exampleZh: "您必須休息。", level: "A1" },
  tomar: { partOfSpeech: "v.", zh: "服用；喝；拿", en: "to take; to drink", example: "Tome las pastillas.", exampleZh: "服用藥片。", level: "A1" },
  jarabe: { partOfSpeech: "n.", zh: "糖漿；止咳水", en: "syrup; cough medicine", example: "El jarabe es amargo.", exampleZh: "糖漿很苦。", level: "A1" },
  receta: { partOfSpeech: "n.", zh: "處方；食譜", en: "prescription; recipe", example: "Tengo la receta.", exampleZh: "我有處方。", level: "A1" },
  "alérgico": { partOfSpeech: "adj.", zh: "過敏的", en: "allergic", example: "Soy alérgico a la penicilina.", exampleZh: "我對青黴素過敏。", level: "A1" },
  alergico: { partOfSpeech: "adj.", zh: "過敏的", en: "allergic", example: "¿Es alérgico?", exampleZh: "您過敏嗎？", level: "A1" },
  // ── Common function words ──
  un: { partOfSpeech: "art.", zh: "一個（陽性不定冠詞）", en: "a; an (m)", example: "Un café, por favor.", exampleZh: "一杯咖啡，謝謝。", level: "A1" },
  una: { partOfSpeech: "art.", zh: "一個（陰性不定冠詞）", en: "a; an (f)", example: "Una pregunta.", exampleZh: "一個問題。", level: "A1" },
  el: { partOfSpeech: "art.", zh: "這個（陽性定冠詞）", en: "the (m)", example: "El café está rico.", exampleZh: "咖啡很好喝。", level: "A1" },
  la: { partOfSpeech: "art.", zh: "這個（陰性定冠詞）", en: "the (f)", example: "La cuenta, por favor.", exampleZh: "結帳，麻煩你。", level: "A1" },
  los: { partOfSpeech: "art.", zh: "這些（陽性複數）", en: "the (m,pl)", example: "Los libros son interesantes.", exampleZh: "這些書很有趣。", level: "A1" },
  las: { partOfSpeech: "art.", zh: "這些（陰性複數）", en: "the (f,pl)", example: "Las tiendas están cerradas.", exampleZh: "商店關門了。", level: "A1" },
  con: { partOfSpeech: "prep.", zh: "和；帶著", en: "with", example: "Café con leche.", exampleZh: "拿鐵。", level: "A1" },
  en: { partOfSpeech: "prep.", zh: "在；用", en: "in; on; at", example: "Estoy en casa.", exampleZh: "我在家。", level: "A1" },
  por: { partOfSpeech: "prep.", zh: "為了；因為；經過", en: "for; because of; through", example: "Por favor.", exampleZh: "請。", level: "A1" },
  para: { partOfSpeech: "prep.", zh: "為了；對於", en: "for; in order to", example: "Es para ti.", exampleZh: "這是給你的。", level: "A1" },
  a: { partOfSpeech: "prep.", zh: "到；在（地點/時間）", en: "to; at; in", example: "Voy a la tienda.", exampleZh: "我去商店。", level: "A1" },
  al: { partOfSpeech: "prep.", zh: "到；往（a + el）", en: "to the (a + el)", example: "Voy al banco.", exampleZh: "我去銀行。", level: "A1" },
  del: { partOfSpeech: "prep.", zh: "的（de + el）", en: "of the (de + el)", example: "Cerca del parque.", exampleZh: "公園附近。", level: "A1" },
  o: { partOfSpeech: "conj.", zh: "或者", en: "or", example: "¿Café o té?", exampleZh: "咖啡還是茶？", level: "A1" },
  pero: { partOfSpeech: "conj.", zh: "但是", en: "but", example: "Es barato pero bonito.", exampleZh: "便宜但漂亮。", level: "A1" },
  porque: { partOfSpeech: "conj.", zh: "因為", en: "because", example: "Lo hago porque quiero.", exampleZh: "我做這個因為我想做。", level: "A1" },
  me: { partOfSpeech: "pron.", zh: "我（受格）", en: "me; myself", example: "Me llamo Ana.", exampleZh: "我叫 Ana。", level: "A1" },
  te: { partOfSpeech: "pron.", zh: "你（受格）", en: "you (direct/indirect)", example: "¿Cómo te llamas?", exampleZh: "你叫什麼名字？", level: "A1" },
  lo: { partOfSpeech: "pron.", zh: "它（陽性受格）", en: "it; him (direct obj)", example: "Lo quiero.", exampleZh: "我想要它。", level: "A1" },
  le: { partOfSpeech: "pron.", zh: "給您/他（間接受格）", en: "to you/him (indirect obj)", example: "¿En qué le puedo ayudar?", exampleZh: "我可以怎樣幫您？", level: "A1" },
  "yo": { partOfSpeech: "pron.", zh: "我", en: "I", example: "Yo soy estudiante.", exampleZh: "我是學生。", level: "A1" },
  "tú": { partOfSpeech: "pron.", zh: "你", en: "you (informal)", example: "¿Y tú?", exampleZh: "你呢？", level: "A1" },
  "él": { partOfSpeech: "pron.", zh: "他", en: "he", example: "Él es mi padre.", exampleZh: "他是我父親。", level: "A1" },
  ella: { partOfSpeech: "pron.", zh: "她", en: "she", example: "Ella es simpática.", exampleZh: "她很友善。", level: "A1" },
  usted: { partOfSpeech: "pron.", zh: "您（正式第二人稱）", en: "you (formal)", example: "¿Cómo está usted?", exampleZh: "您好嗎？", level: "A1" },
  // ── Numbers ──
  uno: { partOfSpeech: "num.", zh: "一", en: "one", example: "Quiero uno.", exampleZh: "我想要一個。", level: "A1" },
  dos: { partOfSpeech: "num.", zh: "二", en: "two", example: "Tengo dos hermanas.", exampleZh: "我有兩個姐妹。", level: "A1" },
  tres: { partOfSpeech: "num.", zh: "三", en: "three", example: "Son las tres.", exampleZh: "三點了。", level: "A1" },
  cuatro: { partOfSpeech: "num.", zh: "四", en: "four", example: "Cuatro cafés.", exampleZh: "四杯咖啡。", level: "A1" },
  cinco: { partOfSpeech: "num.", zh: "五", en: "five", example: "Son cinco euros.", exampleZh: "是五歐元。", level: "A1" },
  seis: { partOfSpeech: "num.", zh: "六", en: "six", example: "A las seis en punto.", exampleZh: "六點整。", level: "A1" },
  siete: { partOfSpeech: "num.", zh: "七", en: "seven", example: "Me levanto a las siete.", exampleZh: "我七點起床。", level: "A1" },
  ocho: { partOfSpeech: "num.", zh: "八", en: "eight", example: "Son las ocho.", exampleZh: "八點了。", level: "A1" },
  nueve: { partOfSpeech: "num.", zh: "九", en: "nine", example: "A las nueve tengo clase.", exampleZh: "九點我有課。", level: "A1" },
  diez: { partOfSpeech: "num.", zh: "十", en: "ten", example: "Son las diez.", exampleZh: "十點了。", level: "A1" },
  veinte: { partOfSpeech: "num.", zh: "二十", en: "twenty", example: "Tengo veinte años.", exampleZh: "我二十歲。", level: "A1" },
  treinta: { partOfSpeech: "num.", zh: "三十", en: "thirty", example: "Son treinta euros.", exampleZh: "是三十歐元。", level: "A1" },
};

export default spanishA1Dict;
