const vocabData = {
  "學術教育": [
    { word: "curriculum", phonetic: "/kəˈrɪk.jʊ.ləm/", pos: "n.", cn: "課程", example: "The school revised its curriculum last year.", exampleCn: "學校去年修訂了課程。", level: 4 },
    { word: "assignment", phonetic: "/əˈsaɪn.mənt/", pos: "n.", cn: "作業；任務", example: "Please submit your assignment by Friday.", exampleCn: "請在星期五前提交作業。", level: 4 },
    { word: "lecture", phonetic: "/ˈlek.tʃər/", pos: "n.", cn: "講課；演講", example: "The professor gave an interesting lecture on history.", exampleCn: "教授給了一堂關於歷史的有趣講課。", level: 4 },
    { word: "semester", phonetic: "/sɪˈmes.tər/", pos: "n.", cn: "學期", example: "The new semester begins in September.", exampleCn: "新學期在九月開始。", level: 4 },
    { word: "graduate", phonetic: "/ˈɡræd.ju.ɪt/", pos: "v./n.", cn: "畢業；畢業生", example: "She will graduate from university next year.", exampleCn: "她明年將從大學畢業。", level: 4 },
    { word: "literacy", phonetic: "/ˈlɪt.ər.ə.si/", pos: "n.", cn: "讀寫能力", example: "Improving literacy is a key education goal.", exampleCn: "提高讀寫能力是一個主要的教育目標。", level: 4 },
    { word: "tuition", phonetic: "/tjuːˈɪʃ.ən/", pos: "n.", cn: "學費；補習", example: "University tuition fees have increased significantly.", exampleCn: "大學學費大幅增加。", level: 4 },
    { word: "scholarship", phonetic: "/ˈskɒl.ə.ʃɪp/", pos: "n.", cn: "獎學金", example: "He received a scholarship to study abroad.", exampleCn: "他獲得了出國留學的獎學金。", level: 4 },
    { word: "comprehend", phonetic: "/ˌkɒm.prɪˈhend/", pos: "v.", cn: "理解；領會", example: "It can be hard to comprehend complex theories.", exampleCn: "要理解複雜的理論可能很困難。", level: 4 },
    { word: "academic", phonetic: "/ˌæk.əˈdem.ɪk/", pos: "adj.", cn: "學術的", example: "He has an impressive academic record.", exampleCn: "他有出色的學業成績。", level: 4 },
    { word: "research", phonetic: "/rɪˈsɜːtʃ/", pos: "n./v.", cn: "研究", example: "Scientists conduct research to find new treatments.", exampleCn: "科學家進行研究以尋找新的治療方法。", level: 4 },
    { word: "campus", phonetic: "/ˈkæm.pəs/", pos: "n.", cn: "校園", example: "The university campus is very beautiful in autumn.", exampleCn: "大學校園在秋天非常美麗。", level: 4 },
    { word: "certificate", phonetic: "/səˈtɪf.ɪ.kət/", pos: "n.", cn: "證書；證明", example: "She received a certificate after completing the course.", exampleCn: "她完成課程後獲得了證書。", level: 4 },
    { word: "evaluate", phonetic: "/ɪˈvæl.ju.eɪt/", pos: "v.", cn: "評估；評價", example: "Teachers evaluate students through exams and projects.", exampleCn: "教師透過考試和專題來評估學生。", level: 6 },
    { word: "thesis", phonetic: "/ˈθiː.sɪs/", pos: "n.", cn: "論文", example: "She spent two years writing her thesis.", exampleCn: "她花了兩年時間撰寫論文。", level: 6 },
    { word: "discipline", phonetic: "/ˈdɪs.ɪ.plɪn/", pos: "n.", cn: "學科；紀律", example: "Science is a broad academic discipline.", exampleCn: "科學是一個廣泛的學術學科。", level: 6 },
    { word: "faculty", phonetic: "/ˈfæk.əl.ti/", pos: "n.", cn: "院系；全體教職員", example: "The faculty members voted on the new policy.", exampleCn: "全體教職員對新政策進行了投票。", level: 6 },
    { word: "syllabus", phonetic: "/ˈsɪl.ə.bəs/", pos: "n.", cn: "教學大綱", example: "The syllabus outlines all topics for the course.", exampleCn: "教學大綱列出了課程的所有主題。", level: 6 },
    { word: "hypothesis", phonetic: "/haɪˈpɒθ.ɪ.sɪs/", pos: "n.", cn: "假設；假說", example: "The scientist tested her hypothesis through experiments.", exampleCn: "科學家通過實驗驗證了她的假說。", level: 6 },
    { word: "methodology", phonetic: "/ˌmeθ.əˈdɒl.ə.dʒi/", pos: "n.", cn: "研究方法；方法論", example: "The paper explains the research methodology clearly.", exampleCn: "論文清楚地闡明了研究方法。", level: 6 },
    { word: "plagiarism", phonetic: "/ˈpleɪ.dʒər.ɪ.z(ə)m/", pos: "n.", cn: "抄襲；剽竊", example: "Plagiarism can result in expulsion from university.", exampleCn: "抄襲可能導致被大學開除。", level: 6 },
  ],

  "科技": [
    { word: "digital", phonetic: "/ˈdɪdʒ.ɪ.təl/", pos: "adj.", cn: "數位的", example: "Digital technology has transformed communication.", exampleCn: "數位技術改變了通訊方式。", level: 4 },
    { word: "network", phonetic: "/ˈnet.wɜːk/", pos: "n.", cn: "網絡", example: "Our office has a fast wireless network.", exampleCn: "我們辦公室有一個快速的無線網絡。", level: 4 },
    { word: "software", phonetic: "/ˈsɒft.weər/", pos: "n.", cn: "軟件", example: "You need to update your software regularly.", exampleCn: "你需要定期更新軟件。", level: 4 },
    { word: "wireless", phonetic: "/ˈwaɪə.ləs/", pos: "adj.", cn: "無線的", example: "Wireless charging is now common in smartphones.", exampleCn: "無線充電現在在智能手機中很普遍。", level: 4 },
    { word: "gadget", phonetic: "/ˈɡædʒ.ɪt/", pos: "n.", cn: "電子小工具", example: "He loves buying the latest gadgets.", exampleCn: "他喜歡購買最新的小工具。", level: 4 },
    { word: "database", phonetic: "/ˈdeɪ.tə.beɪs/", pos: "n.", cn: "資料庫", example: "The company stores customer data in a secure database.", exampleCn: "公司將客戶資料儲存在安全的資料庫中。", level: 4 },
    { word: "innovation", phonetic: "/ˌɪn.əˈveɪ.ʃən/", pos: "n.", cn: "創新", example: "Innovation in technology improves daily life.", exampleCn: "科技創新改善了日常生活。", level: 4 },
    { word: "interface", phonetic: "/ˈɪn.tə.feɪs/", pos: "n.", cn: "介面", example: "The app has a user-friendly interface.", exampleCn: "這個應用程式有一個用戶友好的介面。", level: 4 },
    { word: "download", phonetic: "/ˈdaʊn.ləʊd/", pos: "v./n.", cn: "下載", example: "It only takes a minute to download the app.", exampleCn: "下載這個應用程式只需一分鐘。", level: 4 },
    { word: "device", phonetic: "/dɪˈvaɪs/", pos: "n.", cn: "設備；裝置", example: "This device can connect to the internet.", exampleCn: "這台設備可以連接互聯網。", level: 4 },
    { word: "platform", phonetic: "/ˈplæt.fɔːm/", pos: "n.", cn: "平台", example: "The company launched its services on a new platform.", exampleCn: "該公司在新平台上推出了服務。", level: 4 },
    { word: "algorithm", phonetic: "/ˈæl.ɡə.rɪ.ðəm/", pos: "n.", cn: "演算法", example: "The search engine uses a complex algorithm.", exampleCn: "搜尋引擎使用複雜的演算法。", level: 6 },
    { word: "artificial", phonetic: "/ˌɑː.tɪˈfɪʃ.əl/", pos: "adj.", cn: "人工的；人造的", example: "Artificial intelligence is changing many industries.", exampleCn: "人工智能正在改變許多行業。", level: 6 },
    { word: "bandwidth", phonetic: "/ˈbænd.wɪdθ/", pos: "n.", cn: "頻寬", example: "Streaming video requires a lot of bandwidth.", exampleCn: "串流視頻需要大量頻寬。", level: 6 },
    { word: "encryption", phonetic: "/ɪnˈkrɪp.ʃən/", pos: "n.", cn: "加密", example: "Encryption protects your personal information online.", exampleCn: "加密保護你的個人網絡資料。", level: 6 },
    { word: "automation", phonetic: "/ˌɔː.təˈmeɪ.ʃən/", pos: "n.", cn: "自動化", example: "Automation has replaced many factory jobs.", exampleCn: "自動化取代了許多工廠工作。", level: 6 },
    { word: "prototype", phonetic: "/ˈprəʊ.tə.taɪp/", pos: "n.", cn: "原型", example: "The engineers built a prototype of the new device.", exampleCn: "工程師建造了新裝置的原型。", level: 6 },
    { word: "cybersecurity", phonetic: "/ˌsaɪ.bəsɪˈkjʊər.ɪ.ti/", pos: "n.", cn: "網絡安全", example: "Cybersecurity is a growing concern for businesses.", exampleCn: "網絡安全是企業日益關注的問題。", level: 6 },
    { word: "virtual", phonetic: "/ˈvɜː.tʃu.əl/", pos: "adj.", cn: "虛擬的", example: "Virtual meetings have become common since the pandemic.", exampleCn: "自疫情以來，虛擬會議變得普遍。", level: 6 },
  ],

  "環境": [
    { word: "carbon", phonetic: "/ˈkɑː.bən/", pos: "n.", cn: "碳", example: "Cars release carbon dioxide into the atmosphere.", exampleCn: "汽車向大氣層釋放二氧化碳。", level: 4 },
    { word: "climate", phonetic: "/ˈklaɪ.mɪt/", pos: "n.", cn: "氣候", example: "Climate change is a major global challenge.", exampleCn: "氣候變化是一個重大的全球挑戰。", level: 4 },
    { word: "fossil", phonetic: "/ˈfɒs.əl/", pos: "n./adj.", cn: "化石；化石燃料的", example: "We must reduce our reliance on fossil fuels.", exampleCn: "我們必須減少對化石燃料的依賴。", level: 4 },
    { word: "greenhouse", phonetic: "/ˈɡriːn.haʊs/", pos: "n./adj.", cn: "溫室；溫室效應的", example: "Greenhouse gases trap heat in the atmosphere.", exampleCn: "溫室氣體在大氣層中困住熱量。", level: 4 },
    { word: "habitat", phonetic: "/ˈhæb.ɪ.tæt/", pos: "n.", cn: "棲息地", example: "Polar bears are losing their natural habitat.", exampleCn: "北極熊正在失去其自然棲息地。", level: 4 },
    { word: "pollution", phonetic: "/pəˈluː.ʃən/", pos: "n.", cn: "污染", example: "Air pollution is a serious health risk in big cities.", exampleCn: "空氣污染在大城市是嚴重的健康風險。", level: 4 },
    { word: "recycle", phonetic: "/ˌriːˈsaɪ.kəl/", pos: "v.", cn: "回收；循環再用", example: "We should recycle paper, glass, and plastic.", exampleCn: "我們應該回收紙張、玻璃和塑料。", level: 4 },
    { word: "renewable", phonetic: "/rɪˈnjuː.ə.bəl/", pos: "adj.", cn: "可再生的", example: "Solar and wind are renewable energy sources.", exampleCn: "太陽能和風能是可再生能源。", level: 4 },
    { word: "sustainable", phonetic: "/səˈsteɪ.nə.bəl/", pos: "adj.", cn: "可持續的", example: "Sustainable farming protects the environment.", exampleCn: "可持續農業保護環境。", level: 4 },
    { word: "wildlife", phonetic: "/ˈwaɪld.laɪf/", pos: "n.", cn: "野生動植物", example: "National parks protect local wildlife.", exampleCn: "國家公園保護當地野生動植物。", level: 4 },
    { word: "energy", phonetic: "/ˈen.ə.dʒi/", pos: "n.", cn: "能源；能量", example: "We need to use cleaner sources of energy.", exampleCn: "我們需要使用更清潔的能源。", level: 4 },
    { word: "drought", phonetic: "/draʊt/", pos: "n.", cn: "乾旱", example: "The drought caused crop failures across the region.", exampleCn: "乾旱導致該地區農作物歉收。", level: 4 },
    { word: "flood", phonetic: "/flʌd/", pos: "n./v.", cn: "洪水；淹沒", example: "Heavy rains caused floods in several cities.", exampleCn: "大雨在多個城市引發洪水。", level: 4 },
    { word: "biodiversity", phonetic: "/ˌbaɪ.əʊ.daɪˈvɜː.sɪ.ti/", pos: "n.", cn: "生物多樣性", example: "Rainforests are important for biodiversity.", exampleCn: "熱帶雨林對生物多樣性很重要。", level: 6 },
    { word: "deforestation", phonetic: "/ˌdiː.fɒr.ɪˈsteɪ.ʃən/", pos: "n.", cn: "砍伐森林", example: "Deforestation destroys animal habitats.", exampleCn: "砍伐森林破壞了動物的棲息地。", level: 6 },
    { word: "ecosystem", phonetic: "/ˈiː.kəʊ.sɪs.təm/", pos: "n.", cn: "生態系統", example: "The coral reef is a delicate ecosystem.", exampleCn: "珊瑚礁是一個脆弱的生態系統。", level: 6 },
    { word: "emission", phonetic: "/ɪˈmɪʃ.ən/", pos: "n.", cn: "排放（物）", example: "Governments aim to reduce carbon emissions.", exampleCn: "各國政府致力於減少碳排放。", level: 6 },
    { word: "extinction", phonetic: "/ɪkˈstɪŋk.ʃən/", pos: "n.", cn: "滅絕", example: "Many species face extinction due to habitat loss.", exampleCn: "許多物種因棲息地喪失而面臨滅絕。", level: 6 },
    { word: "conservation", phonetic: "/ˌkɒn.səˈveɪ.ʃən/", pos: "n.", cn: "保護；保育", example: "Wildlife conservation efforts have saved many species.", exampleCn: "野生動物保育工作已拯救了許多物種。", level: 6 },
    { word: "contamination", phonetic: "/kənˌtæm.ɪˈneɪ.ʃən/", pos: "n.", cn: "污染；污染物", example: "Water contamination is a serious public health issue.", exampleCn: "水源污染是嚴重的公共健康問題。", level: 6 },
  ],

  "健康": [
    { word: "infection", phonetic: "/ɪnˈfek.ʃən/", pos: "n.", cn: "感染", example: "Wash your hands to avoid infection.", exampleCn: "洗手以避免感染。", level: 4 },
    { word: "nutrition", phonetic: "/njuːˈtrɪʃ.ən/", pos: "n.", cn: "營養", example: "Good nutrition is essential for children's growth.", exampleCn: "良好的營養對兒童成長至關重要。", level: 4 },
    { word: "symptom", phonetic: "/ˈsɪmp.təm/", pos: "n.", cn: "症狀", example: "Fever is a common symptom of the flu.", exampleCn: "發燒是流感的常見症狀。", level: 4 },
    { word: "therapy", phonetic: "/ˈθer.ə.pi/", pos: "n.", cn: "治療；療法", example: "Physical therapy helped him recover from injury.", exampleCn: "物理治療幫助他從受傷中恢復。", level: 4 },
    { word: "vaccination", phonetic: "/ˌvæk.sɪˈneɪ.ʃən/", pos: "n.", cn: "接種疫苗", example: "Vaccination is the best way to prevent measles.", exampleCn: "接種疫苗是預防麻疹的最佳方法。", level: 4 },
    { word: "mental", phonetic: "/ˈmen.təl/", pos: "adj.", cn: "精神的；心理的", example: "Mental health is just as important as physical health.", exampleCn: "心理健康與身體健康同樣重要。", level: 4 },
    { word: "surgery", phonetic: "/ˈsɜː.dʒər.i/", pos: "n.", cn: "外科手術", example: "He underwent surgery to remove the tumour.", exampleCn: "他接受了切除腫瘤的外科手術。", level: 4 },
    { word: "fitness", phonetic: "/ˈfɪt.nəs/", pos: "n.", cn: "健康；體適能", example: "Regular exercise improves physical fitness.", exampleCn: "定期運動改善身體健康。", level: 4 },
    { word: "diet", phonetic: "/ˈdaɪ.ət/", pos: "n.", cn: "飲食；節食", example: "A balanced diet is important for good health.", exampleCn: "均衡飲食對健康很重要。", level: 4 },
    { word: "stress", phonetic: "/stres/", pos: "n.", cn: "壓力；緊張", example: "Work-related stress affects many employees.", exampleCn: "工作壓力影響許多員工。", level: 4 },
    { word: "hospital", phonetic: "/ˈhɒs.pɪ.təl/", pos: "n.", cn: "醫院", example: "She was taken to hospital after the accident.", exampleCn: "她在事故後被送往醫院。", level: 4 },
    { word: "antibiotic", phonetic: "/ˌæn.ti.baɪˈɒt.ɪk/", pos: "n.", cn: "抗生素", example: "The doctor prescribed antibiotics for the infection.", exampleCn: "醫生開了抗生素來治療感染。", level: 6 },
    { word: "chronic", phonetic: "/ˈkrɒn.ɪk/", pos: "adj.", cn: "慢性的；長期的", example: "Chronic back pain affects millions of people.", exampleCn: "慢性背痛影響數以百萬計的人。", level: 6 },
    { word: "diagnosis", phonetic: "/ˌdaɪ.əɡˈnəʊ.sɪs/", pos: "n.", cn: "診斷", example: "Early diagnosis of cancer improves survival rates.", exampleCn: "癌症的早期診斷提高了存活率。", level: 6 },
    { word: "epidemic", phonetic: "/ˌep.ɪˈdem.ɪk/", pos: "n.", cn: "傳染病流行；疫情", example: "The flu epidemic affected millions of people.", exampleCn: "流感疫情影響了數百萬人。", level: 6 },
    { word: "hygiene", phonetic: "/ˈhaɪ.dʒiːn/", pos: "n.", cn: "衛生；清潔", example: "Good hygiene helps prevent the spread of disease.", exampleCn: "良好的衛生有助於防止疾病傳播。", level: 6 },
    { word: "immune", phonetic: "/ɪˈmjuːn/", pos: "adj.", cn: "免疫的", example: "Vaccines help the body become immune to diseases.", exampleCn: "疫苗幫助身體對疾病產生免疫力。", level: 6 },
    { word: "obesity", phonetic: "/əʊˈbiː.sɪ.ti/", pos: "n.", cn: "肥胖症", example: "Obesity increases the risk of heart disease.", exampleCn: "肥胖症增加了患心臟病的風險。", level: 6 },
    { word: "rehabilitation", phonetic: "/ˌriː.həˌbɪl.ɪˈteɪ.ʃən/", pos: "n.", cn: "康復；復健", example: "He needed months of rehabilitation after the accident.", exampleCn: "他在事故後需要數月的康復治療。", level: 6 },
    { word: "prescription", phonetic: "/prɪˈskrɪp.ʃən/", pos: "n.", cn: "處方；藥方", example: "You need a prescription to buy this medication.", exampleCn: "你需要處方才能購買這種藥物。", level: 6 },
  ],

  "商業經濟": [
    { word: "budget", phonetic: "/ˈbʌdʒ.ɪt/", pos: "n.", cn: "預算", example: "The project was completed within budget.", exampleCn: "該項目在預算內完成。", level: 4 },
    { word: "consumer", phonetic: "/kənˈsjuː.mər/", pos: "n.", cn: "消費者", example: "Consumers are spending less during the recession.", exampleCn: "消費者在經濟衰退期間減少了支出。", level: 4 },
    { word: "contract", phonetic: "/ˈkɒn.trækt/", pos: "n.", cn: "合約；合同", example: "Both parties signed the contract.", exampleCn: "雙方簽署了合約。", level: 4 },
    { word: "economy", phonetic: "/ɪˈkɒn.ə.mi/", pos: "n.", cn: "經濟；經濟體", example: "The economy grew by 3% last year.", exampleCn: "去年經濟增長了3%。", level: 4 },
    { word: "export", phonetic: "/ˈek.spɔːt/", pos: "v./n.", cn: "出口；輸出", example: "China exports goods to countries worldwide.", exampleCn: "中國向全球各國出口商品。", level: 4 },
    { word: "investment", phonetic: "/ɪnˈvest.mənt/", pos: "n.", cn: "投資", example: "Property is a popular long-term investment.", exampleCn: "房地產是一種受歡迎的長期投資。", level: 4 },
    { word: "marketing", phonetic: "/ˈmɑː.kɪ.tɪŋ/", pos: "n.", cn: "市場營銷", example: "Effective marketing can boost sales significantly.", exampleCn: "有效的市場營銷可以大幅提升銷售額。", level: 4 },
    { word: "profit", phonetic: "/ˈprɒf.ɪt/", pos: "n.", cn: "利潤；盈利", example: "The company made a large profit this quarter.", exampleCn: "公司本季度獲得了豐厚利潤。", level: 4 },
    { word: "trade", phonetic: "/treɪd/", pos: "n./v.", cn: "貿易；交易", example: "International trade benefits many countries.", exampleCn: "國際貿易惠及許多國家。", level: 4 },
    { word: "salary", phonetic: "/ˈsæl.ər.i/", pos: "n.", cn: "薪水；薪金", example: "She negotiated a higher salary with her employer.", exampleCn: "她與僱主協商了更高的薪水。", level: 4 },
    { word: "demand", phonetic: "/dɪˈmɑːnd/", pos: "n./v.", cn: "需求；要求", example: "Demand for electric cars has risen sharply.", exampleCn: "對電動車的需求急劇上升。", level: 4 },
    { word: "supply", phonetic: "/səˈplaɪ/", pos: "n./v.", cn: "供應；提供", example: "The supply of fresh water is limited in dry regions.", exampleCn: "乾旱地區的淡水供應十分有限。", level: 4 },
    { word: "corporation", phonetic: "/ˌkɔː.pərˈeɪ.ʃən/", pos: "n.", cn: "公司；企業", example: "The corporation has offices in 30 countries.", exampleCn: "該公司在30個國家設有辦事處。", level: 6 },
    { word: "inflation", phonetic: "/ɪnˈfleɪ.ʃən/", pos: "n.", cn: "通貨膨脹", example: "High inflation makes everyday goods more expensive.", exampleCn: "高通膨使日常商品更加昂貴。", level: 6 },
    { word: "negotiate", phonetic: "/nɪˈɡəʊ.ʃi.eɪt/", pos: "v.", cn: "談判；協商", example: "They negotiated a better deal with the supplier.", exampleCn: "他們與供應商談判達成了更好的交易。", level: 6 },
    { word: "revenue", phonetic: "/ˈrev.ɪ.njuː/", pos: "n.", cn: "收入；收益", example: "The government's tax revenue increased last year.", exampleCn: "政府去年的稅收增加了。", level: 6 },
    { word: "enterprise", phonetic: "/ˈen.tə.praɪz/", pos: "n.", cn: "企業；事業", example: "Small enterprises are the backbone of the economy.", exampleCn: "小型企業是經濟的支柱。", level: 6 },
    { word: "strategy", phonetic: "/ˈstræt.ɪ.dʒi/", pos: "n.", cn: "策略；戰略", example: "The company developed a new marketing strategy.", exampleCn: "公司制定了新的市場策略。", level: 6 },
    { word: "monopoly", phonetic: "/məˈnɒp.ə.li/", pos: "n.", cn: "壟斷；壟斷企業", example: "The government broke up the telecommunications monopoly.", exampleCn: "政府打破了電信壟斷。", level: 6 },
    { word: "fiscal", phonetic: "/ˈfɪs.kəl/", pos: "adj.", cn: "財政的", example: "The government announced its fiscal policy for next year.", exampleCn: "政府公布了明年的財政政策。", level: 6 },
  ],

  "社會": [
    { word: "community", phonetic: "/kəˈmjuː.nɪ.ti/", pos: "n.", cn: "社區；社群", example: "The community came together to help flood victims.", exampleCn: "社區齊心協力幫助洪水災民。", level: 4 },
    { word: "diversity", phonetic: "/daɪˈvɜː.sɪ.ti/", pos: "n.", cn: "多元化；多樣性", example: "Our school celebrates cultural diversity.", exampleCn: "我們的學校慶祝文化多樣性。", level: 4 },
    { word: "equality", phonetic: "/ɪˈkwɒl.ɪ.ti/", pos: "n.", cn: "平等", example: "Many people fight for gender equality.", exampleCn: "很多人為性別平等而奮鬥。", level: 4 },
    { word: "freedom", phonetic: "/ˈfriː.dəm/", pos: "n.", cn: "自由", example: "Freedom of speech is a fundamental right.", exampleCn: "言論自由是一項基本權利。", level: 4 },
    { word: "justice", phonetic: "/ˈdʒʌs.tɪs/", pos: "n.", cn: "公正；司法", example: "The protesters demanded justice for the victims.", exampleCn: "抗議者要求為受害者伸張正義。", level: 4 },
    { word: "poverty", phonetic: "/ˈpɒv.ə.ti/", pos: "n.", cn: "貧困；貧窮", example: "Many charities work to reduce global poverty.", exampleCn: "許多慈善機構致力於減少全球貧困。", level: 4 },
    { word: "protest", phonetic: "/ˈprəʊ.test/", pos: "n./v.", cn: "抗議", example: "Thousands joined the protest against the new law.", exampleCn: "數千人加入了反對新法律的抗議。", level: 4 },
    { word: "tradition", phonetic: "/trəˈdɪʃ.ən/", pos: "n.", cn: "傳統", example: "This festival is an important local tradition.", exampleCn: "這個節日是一個重要的本地傳統。", level: 4 },
    { word: "welfare", phonetic: "/ˈwel.feər/", pos: "n.", cn: "福利；幸福", example: "The government increased social welfare payments.", exampleCn: "政府增加了社會福利金。", level: 4 },
    { word: "volunteer", phonetic: "/ˌvɒl.ənˈtɪər/", pos: "n./v.", cn: "義工；自願做", example: "Many people volunteer at local food banks.", exampleCn: "很多人在本地食物銀行做義工。", level: 4 },
    { word: "urban", phonetic: "/ˈɜː.bən/", pos: "adj.", cn: "城市的；都市的", example: "Urban areas often have better access to services.", exampleCn: "城市地區通常能更方便地獲取服務。", level: 4 },
    { word: "migration", phonetic: "/maɪˈɡreɪ.ʃən/", pos: "n.", cn: "移民；遷徙", example: "Economic migration brings people to cities.", exampleCn: "經濟移民帶動人們湧入城市。", level: 4 },
    { word: "prejudice", phonetic: "/ˈpredʒ.ʊ.dɪs/", pos: "n.", cn: "偏見；歧視", example: "We must work to overcome racial prejudice.", exampleCn: "我們必須努力克服種族偏見。", level: 6 },
    { word: "refugee", phonetic: "/ˌref.jʊˈdʒiː/", pos: "n.", cn: "難民", example: "The country accepted thousands of refugees.", exampleCn: "該國接收了數千名難民。", level: 6 },
    { word: "minority", phonetic: "/maɪˈnɒr.ɪ.ti/", pos: "n.", cn: "少數族裔；少數群體", example: "The law protects the rights of minorities.", exampleCn: "法律保護少數群體的權利。", level: 6 },
    { word: "discrimination", phonetic: "/dɪˌskrɪm.ɪˈneɪ.ʃən/", pos: "n.", cn: "歧視", example: "Discrimination in the workplace is illegal.", exampleCn: "職場歧視是違法的。", level: 6 },
    { word: "inequality", phonetic: "/ˌɪn.ɪˈkwɒl.ɪ.ti/", pos: "n.", cn: "不平等；不均等", example: "Income inequality is a growing problem in many countries.", exampleCn: "收入不平等在許多國家日益嚴重。", level: 6 },
    { word: "philanthropy", phonetic: "/fɪˈlæn.θrə.pi/", pos: "n.", cn: "慈善；博愛", example: "The billionaire is known for his philanthropy.", exampleCn: "這位億萬富翁以其慈善事業而聞名。", level: 6 },
    { word: "demographics", phonetic: "/ˌdem.əˈɡræf.ɪks/", pos: "n.", cn: "人口統計（學）", example: "The demographics of the city have changed significantly.", exampleCn: "該城市的人口結構已發生重大變化。", level: 6 },
  ],

  "文化": [
    { word: "ceremony", phonetic: "/ˈser.ɪ.mə.ni/", pos: "n.", cn: "儀式；典禮", example: "The opening ceremony attracted millions of viewers.", exampleCn: "開幕式吸引了數百萬名觀眾。", level: 4 },
    { word: "ethnic", phonetic: "/ˈeθ.nɪk/", pos: "adj.", cn: "民族的；種族的", example: "The city has many ethnic restaurants.", exampleCn: "這座城市有許多民族餐廳。", level: 4 },
    { word: "festival", phonetic: "/ˈfes.tɪ.vəl/", pos: "n.", cn: "節日；節慶", example: "The Lunar New Year festival is celebrated worldwide.", exampleCn: "農曆新年節日在世界各地慶祝。", level: 4 },
    { word: "heritage", phonetic: "/ˈher.ɪ.tɪdʒ/", pos: "n.", cn: "文化遺產；遺產", example: "The ancient temple is a UNESCO World Heritage site.", exampleCn: "這座古廟是聯合國教科文組織的世界遺產。", level: 4 },
    { word: "legend", phonetic: "/ˈledʒ.ənd/", pos: "n.", cn: "傳說；傳奇人物", example: "The legend of the dragon is common in Asia.", exampleCn: "龍的傳說在亞洲很普遍。", level: 4 },
    { word: "symbol", phonetic: "/ˈsɪm.bəl/", pos: "n.", cn: "象徵；符號", example: "The dove is a symbol of peace.", exampleCn: "鴿子是和平的象徵。", level: 4 },
    { word: "literature", phonetic: "/ˈlɪt.ər.ɪ.tʃər/", pos: "n.", cn: "文學", example: "She studied English literature at university.", exampleCn: "她在大學學習英國文學。", level: 4 },
    { word: "cuisine", phonetic: "/kwɪˈziːn/", pos: "n.", cn: "烹飪；料理", example: "Japanese cuisine is known for its fresh ingredients.", exampleCn: "日本料理以新鮮食材著稱。", level: 4 },
    { word: "folklore", phonetic: "/ˈfəʊk.lɔːr/", pos: "n.", cn: "民間傳說；民俗", example: "The story comes from local folklore.", exampleCn: "這個故事來自當地民間傳說。", level: 4 },
    { word: "custom", phonetic: "/ˈkʌs.təm/", pos: "n.", cn: "習俗；慣例", example: "It is a custom to bow when greeting in Japan.", exampleCn: "在日本，鞠躬問候是一種習俗。", level: 4 },
    { word: "religion", phonetic: "/rɪˈlɪdʒ.ən/", pos: "n.", cn: "宗教；信仰", example: "Religion plays an important role in many cultures.", exampleCn: "宗教在許多文化中扮演重要角色。", level: 4 },
    { word: "mythology", phonetic: "/mɪˈθɒl.ə.dʒi/", pos: "n.", cn: "神話", example: "Greek mythology features many gods and heroes.", exampleCn: "希臘神話有許多神明和英雄。", level: 4 },
    { word: "architecture", phonetic: "/ˈɑː.kɪ.tek.tʃər/", pos: "n.", cn: "建築；建築學", example: "The city is famous for its Gothic architecture.", exampleCn: "這座城市以其哥特式建築而聞名。", level: 6 },
    { word: "dialect", phonetic: "/ˈdaɪ.ə.lekt/", pos: "n.", cn: "方言", example: "Many dialects are spoken in southern China.", exampleCn: "中國南方有許多方言。", level: 6 },
    { word: "indigenous", phonetic: "/ɪnˈdɪdʒ.ɪ.nəs/", pos: "adj.", cn: "土著的；原住民的", example: "Indigenous peoples have lived here for centuries.", exampleCn: "原住民在這裡已經生活了幾個世紀。", level: 6 },
    { word: "artifact", phonetic: "/ˈɑː.tɪ.fækt/", pos: "n.", cn: "文物；人工製品", example: "The museum displays ancient artifacts from Egypt.", exampleCn: "博物館展示來自埃及的古代文物。", level: 6 },
    { word: "globalization", phonetic: "/ˌɡləʊ.bəl.aɪˈzeɪ.ʃən/", pos: "n.", cn: "全球化", example: "Globalization has spread Western culture worldwide.", exampleCn: "全球化已將西方文化傳播到世界各地。", level: 6 },
    { word: "sculpture", phonetic: "/ˈskʌlp.tʃər/", pos: "n.", cn: "雕塑；雕刻", example: "The museum has a large collection of sculptures.", exampleCn: "博物館收藏了大量雕塑。", level: 6 },
  ],

  "政治": [
    { word: "authority", phonetic: "/ɔːˈθɒr.ɪ.ti/", pos: "n.", cn: "權威；當局", example: "The police have the authority to arrest suspects.", exampleCn: "警察有逮捕嫌疑人的權力。", level: 4 },
    { word: "campaign", phonetic: "/kæmˈpeɪn/", pos: "n./v.", cn: "競選；活動", example: "The candidate ran a successful election campaign.", exampleCn: "候選人進行了一場成功的選舉競選。", level: 4 },
    { word: "citizen", phonetic: "/ˈsɪt.ɪ.zən/", pos: "n.", cn: "公民", example: "Every citizen has the right to vote.", exampleCn: "每個公民都有投票的權利。", level: 4 },
    { word: "debate", phonetic: "/dɪˈbeɪt/", pos: "n./v.", cn: "辯論；討論", example: "Politicians debated the new tax policy.", exampleCn: "政治家們就新的稅收政策進行了辯論。", level: 4 },
    { word: "democracy", phonetic: "/dɪˈmɒk.rə.si/", pos: "n.", cn: "民主；民主制度", example: "Democracy gives citizens a voice in government.", exampleCn: "民主制度讓公民在政府中有發言權。", level: 4 },
    { word: "election", phonetic: "/ɪˈlek.ʃən/", pos: "n.", cn: "選舉", example: "The general election will be held in November.", exampleCn: "大選將於11月舉行。", level: 4 },
    { word: "govern", phonetic: "/ˈɡʌv.ən/", pos: "v.", cn: "統治；管理", example: "The prime minister governs the country.", exampleCn: "首相治理這個國家。", level: 4 },
    { word: "minister", phonetic: "/ˈmɪn.ɪ.stər/", pos: "n.", cn: "部長；大臣", example: "The Finance Minister announced new tax cuts.", exampleCn: "財政部長宣布了新的減稅措施。", level: 4 },
    { word: "parliament", phonetic: "/ˈpɑː.lə.mənt/", pos: "n.", cn: "議會；國會", example: "The new law was passed by parliament.", exampleCn: "新法律獲得議會通過。", level: 4 },
    { word: "policy", phonetic: "/ˈpɒl.ɪ.si/", pos: "n.", cn: "政策", example: "The government introduced a new housing policy.", exampleCn: "政府推出了新的房屋政策。", level: 4 },
    { word: "republic", phonetic: "/rɪˈpʌb.lɪk/", pos: "n.", cn: "共和國", example: "France is a republic with an elected president.", exampleCn: "法國是一個有民選總統的共和國。", level: 4 },
    { word: "treaty", phonetic: "/ˈtriː.ti/", pos: "n.", cn: "條約；協議", example: "The two nations signed a peace treaty.", exampleCn: "兩國簽署了和平條約。", level: 4 },
    { word: "constitution", phonetic: "/ˌkɒn.stɪˈtjuː.ʃən/", pos: "n.", cn: "憲法", example: "The constitution protects basic human rights.", exampleCn: "憲法保護基本人權。", level: 6 },
    { word: "diplomatic", phonetic: "/ˌdɪp.ləˈmæt.ɪk/", pos: "adj.", cn: "外交的", example: "The two countries have strong diplomatic ties.", exampleCn: "兩國擁有緊密的外交關係。", level: 6 },
    { word: "sanction", phonetic: "/ˈsæŋk.ʃən/", pos: "n./v.", cn: "制裁；批准", example: "The UN imposed sanctions on the country.", exampleCn: "聯合國對該國實施了制裁。", level: 6 },
    { word: "sovereignty", phonetic: "/ˈsɒv.rɪn.ti/", pos: "n.", cn: "主權", example: "Every country has the right to sovereignty.", exampleCn: "每個國家都有主權。", level: 6 },
    { word: "legislation", phonetic: "/ˌledʒ.ɪˈsleɪ.ʃən/", pos: "n.", cn: "立法；法規", example: "New legislation was introduced to protect workers.", exampleCn: "新法規的推出是為了保護工人。", level: 6 },
    { word: "ideology", phonetic: "/ˌaɪ.diˈɒl.ə.dʒi/", pos: "n.", cn: "意識形態；主義", example: "The two parties differ greatly in ideology.", exampleCn: "兩個政黨在意識形態上有很大差異。", level: 6 },
    { word: "referendum", phonetic: "/ˌref.ərˈen.dəm/", pos: "n.", cn: "公民投票", example: "The country held a referendum on independence.", exampleCn: "該國就獨立問題舉行了公民投票。", level: 6 },
  ],

  "旅遊交通": [
    { word: "destination", phonetic: "/ˌdes.tɪˈneɪ.ʃən/", pos: "n.", cn: "目的地", example: "Paris is a popular tourist destination.", exampleCn: "巴黎是一個受歡迎的旅遊目的地。", level: 4 },
    { word: "accommodation", phonetic: "/əˌkɒm.əˈdeɪ.ʃən/", pos: "n.", cn: "住宿；住所", example: "We booked accommodation near the city centre.", exampleCn: "我們在市中心附近預訂了住宿。", level: 4 },
    { word: "passport", phonetic: "/ˈpɑːs.pɔːt/", pos: "n.", cn: "護照", example: "Make sure your passport is valid before travelling.", exampleCn: "出行前確保你的護照有效。", level: 4 },
    { word: "departure", phonetic: "/dɪˈpɑː.tʃər/", pos: "n.", cn: "出發；離開", example: "Our departure time is 8 AM tomorrow.", exampleCn: "我們明天的出發時間是早上8點。", level: 4 },
    { word: "arrival", phonetic: "/əˈraɪ.vəl/", pos: "n.", cn: "到達；抵達", example: "Please proceed to the arrivals hall.", exampleCn: "請前往到達大廳。", level: 4 },
    { word: "luggage", phonetic: "/ˈlʌɡ.ɪdʒ/", pos: "n.", cn: "行李", example: "You are allowed one piece of hand luggage.", exampleCn: "你可以攜帶一件手提行李。", level: 4 },
    { word: "transport", phonetic: "/ˈtræn.spɔːt/", pos: "n./v.", cn: "交通；運輸", example: "Public transport is cheaper than driving.", exampleCn: "公共交通比自駕便宜。", level: 4 },
    { word: "reservation", phonetic: "/ˌrez.əˈveɪ.ʃən/", pos: "n.", cn: "預訂；預約", example: "I made a reservation at the restaurant.", exampleCn: "我在餐廳預訂了位子。", level: 4 },
    { word: "route", phonetic: "/ruːt/", pos: "n.", cn: "路線；路徑", example: "The bus takes a scenic route through the mountains.", exampleCn: "巴士途經一條穿越山區的風景路線。", level: 4 },
    { word: "journey", phonetic: "/ˈdʒɜː.ni/", pos: "n.", cn: "旅程；旅途", example: "The train journey from London to Edinburgh takes five hours.", exampleCn: "從倫敦到愛丁堡的火車旅程需要五個小時。", level: 4 },
    { word: "customs", phonetic: "/ˈkʌs.təmz/", pos: "n.", cn: "海關", example: "All passengers must pass through customs on arrival.", exampleCn: "所有旅客抵達時都必須通過海關。", level: 4 },
    { word: "itinerary", phonetic: "/aɪˈtɪn.ər.ər.i/", pos: "n.", cn: "行程；旅行計劃", example: "The tour guide handed out the itinerary.", exampleCn: "導遊分發了行程計劃。", level: 6 },
    { word: "immigration", phonetic: "/ˌɪm.ɪˈɡreɪ.ʃən/", pos: "n.", cn: "移民；入境管理", example: "All passengers must go through immigration control.", exampleCn: "所有乘客都必須通過入境管理。", level: 6 },
    { word: "currency", phonetic: "/ˈkʌr.ən.si/", pos: "n.", cn: "貨幣；通貨", example: "You should exchange currency before your trip.", exampleCn: "你應該在出發前兌換貨幣。", level: 6 },
    { word: "embassy", phonetic: "/ˈem.bə.si/", pos: "n.", cn: "大使館", example: "You can apply for a visa at the embassy.", exampleCn: "你可以在大使館申請簽證。", level: 6 },
    { word: "expedition", phonetic: "/ˌek.spɪˈdɪʃ.ən/", pos: "n.", cn: "探險；遠征", example: "The team set off on an expedition to the Arctic.", exampleCn: "團隊出發進行北極探險。", level: 6 },
    { word: "infrastructure", phonetic: "/ˈɪn.frə.strʌk.tʃər/", pos: "n.", cn: "基礎設施", example: "Good transport infrastructure boosts the local economy.", exampleCn: "良好的交通基礎設施促進地方經濟。", level: 6 },
  ],

  "媒體傳播": [
    { word: "broadcast", phonetic: "/ˈbrɔːd.kɑːst/", pos: "v./n.", cn: "廣播；播出", example: "The news was broadcast live on television.", exampleCn: "新聞在電視上進行了現場直播。", level: 4 },
    { word: "journalist", phonetic: "/ˈdʒɜː.nə.lɪst/", pos: "n.", cn: "記者；新聞工作者", example: "The journalist interviewed the prime minister.", exampleCn: "記者採訪了首相。", level: 4 },
    { word: "audience", phonetic: "/ˈɔː.di.əns/", pos: "n.", cn: "觀眾；讀者；聽眾", example: "The show attracted a large audience.", exampleCn: "該節目吸引了大批觀眾。", level: 4 },
    { word: "publish", phonetic: "/ˈpʌb.lɪʃ/", pos: "v.", cn: "出版；發表", example: "She published her first novel at age 25.", exampleCn: "她在25歲時出版了第一部小說。", level: 4 },
    { word: "headline", phonetic: "/ˈhed.laɪn/", pos: "n.", cn: "頭條新聞；標題", example: "The story made headlines around the world.", exampleCn: "這個故事登上了全球頭條。", level: 4 },
    { word: "interview", phonetic: "/ˈɪn.tə.vjuː/", pos: "n./v.", cn: "採訪；面試", example: "The celebrity gave an exclusive interview.", exampleCn: "這位名人接受了獨家採訪。", level: 4 },
    { word: "advertisement", phonetic: "/ədˈvɜː.tɪs.mənt/", pos: "n.", cn: "廣告", example: "The advertisement ran on television for three months.", exampleCn: "這個廣告在電視上播放了三個月。", level: 4 },
    { word: "influence", phonetic: "/ˈɪn.flu.əns/", pos: "n./v.", cn: "影響；影響力", example: "Social media has a strong influence on young people.", exampleCn: "社交媒體對年輕人有強大的影響力。", level: 4 },
    { word: "content", phonetic: "/ˈkɒn.tent/", pos: "n.", cn: "內容", example: "Good content is essential for a successful website.", exampleCn: "優質內容對成功的網站至關重要。", level: 4 },
    { word: "subscribe", phonetic: "/səbˈskraɪb/", pos: "v.", cn: "訂閱；訂購", example: "Millions of people subscribe to streaming services.", exampleCn: "數百萬人訂閱串流服務。", level: 4 },
    { word: "propaganda", phonetic: "/ˌprɒp.əˈɡæn.də/", pos: "n.", cn: "宣傳；政治宣傳", example: "The government used propaganda to control public opinion.", exampleCn: "政府利用宣傳手段操控公眾輿論。", level: 6 },
    { word: "censorship", phonetic: "/ˈsen.sə.ʃɪp/", pos: "n.", cn: "審查制度", example: "Censorship of the press is common in some countries.", exampleCn: "新聞審查制度在某些國家很普遍。", level: 6 },
    { word: "coverage", phonetic: "/ˈkʌv.ər.ɪdʒ/", pos: "n.", cn: "報道；覆蓋範圍", example: "The event received extensive media coverage.", exampleCn: "這次活動獲得了廣泛的媒體報道。", level: 6 },
    { word: "transparency", phonetic: "/trænsˈpær.ən.si/", pos: "n.", cn: "透明度；透明性", example: "The public demands greater transparency from politicians.", exampleCn: "公眾要求政客提高透明度。", level: 6 },
    { word: "rhetoric", phonetic: "/ˈret.ər.ɪk/", pos: "n.", cn: "修辭；花言巧語", example: "His speech was full of political rhetoric.", exampleCn: "他的演講充滿了政治修辭。", level: 6 },
    { word: "algorithm", phonetic: "/ˈæl.ɡə.rɪ.ðəm/", pos: "n.", cn: "演算法（社媒推薦）", example: "The platform's algorithm decides what content you see.", exampleCn: "平台的演算法決定你看到什麼內容。", level: 6 },
    { word: "circulation", phonetic: "/ˌsɜː.kjʊˈleɪ.ʃən/", pos: "n.", cn: "發行量；流通", example: "The newspaper has a daily circulation of one million.", exampleCn: "該報紙每日發行量達一百萬份。", level: 6 },
  ],

  "科學研究": [
    { word: "experiment", phonetic: "/ɪkˈsper.ɪ.mənt/", pos: "n./v.", cn: "實驗；試驗", example: "Scientists conducted an experiment to test the theory.", exampleCn: "科學家進行了一個實驗來驗證理論。", level: 4 },
    { word: "evidence", phonetic: "/ˈev.ɪ.dəns/", pos: "n.", cn: "證據；證明", example: "There is strong evidence that exercise is beneficial.", exampleCn: "有強有力的證據顯示運動有益。", level: 4 },
    { word: "theory", phonetic: "/ˈθɪə.ri/", pos: "n.", cn: "理論；學說", example: "Darwin proposed the theory of evolution.", exampleCn: "達爾文提出了進化論。", level: 4 },
    { word: "biology", phonetic: "/baɪˈɒl.ə.dʒi/", pos: "n.", cn: "生物學", example: "She is studying biology at university.", exampleCn: "她在大學修讀生物學。", level: 4 },
    { word: "chemistry", phonetic: "/ˈkem.ɪ.stri/", pos: "n.", cn: "化學", example: "Chemistry is essential for developing new medicines.", exampleCn: "化學是開發新藥物的基礎。", level: 4 },
    { word: "physics", phonetic: "/ˈfɪz.ɪks/", pos: "n.", cn: "物理學", example: "Physics helps us understand how the universe works.", exampleCn: "物理學幫助我們了解宇宙的運作。", level: 4 },
    { word: "laboratory", phonetic: "/ləˈbɒr.ə.tər.i/", pos: "n.", cn: "實驗室", example: "Researchers work in the laboratory every day.", exampleCn: "研究人員每天在實驗室工作。", level: 4 },
    { word: "observe", phonetic: "/əbˈzɜːv/", pos: "v.", cn: "觀察；遵守", example: "Scientists observe animal behaviour in the wild.", exampleCn: "科學家在野外觀察動物行為。", level: 4 },
    { word: "discovery", phonetic: "/dɪˈskʌv.ər.i/", pos: "n.", cn: "發現；發覺", example: "The discovery of penicillin saved millions of lives.", exampleCn: "青黴素的發現拯救了數百萬條生命。", level: 4 },
    { word: "data", phonetic: "/ˈdeɪ.tə/", pos: "n.", cn: "數據；資料", example: "The researchers analysed a large amount of data.", exampleCn: "研究人員分析了大量數據。", level: 4 },
    { word: "analysis", phonetic: "/əˈnæl.ɪ.sɪs/", pos: "n.", cn: "分析；分析結果", example: "A careful analysis of the data revealed new findings.", exampleCn: "對數據的仔細分析揭示了新發現。", level: 4 },
    { word: "phenomenon", phonetic: "/fɪˈnɒm.ɪ.nən/", pos: "n.", cn: "現象；奇事", example: "Scientists are studying this unusual natural phenomenon.", exampleCn: "科學家正在研究這個不尋常的自然現象。", level: 6 },
    { word: "correlation", phonetic: "/ˌkɒr.əˈleɪ.ʃən/", pos: "n.", cn: "相關性；關聯", example: "There is a clear correlation between diet and health.", exampleCn: "飲食與健康之間有明確的相關性。", level: 6 },
    { word: "empirical", phonetic: "/ɪmˈpɪr.ɪ.kəl/", pos: "adj.", cn: "經驗性的；實証的", example: "The theory is supported by empirical evidence.", exampleCn: "這個理論得到了實証證據的支持。", level: 6 },
    { word: "genome", phonetic: "/ˈdʒiː.nəʊm/", pos: "n.", cn: "基因組", example: "Scientists have successfully mapped the human genome.", exampleCn: "科學家已成功繪製出人類基因組圖譜。", level: 6 },
    { word: "variable", phonetic: "/ˈveər.i.ə.bəl/", pos: "n./adj.", cn: "變數；可變的", example: "The experiment controlled all variables except temperature.", exampleCn: "實驗控制了除溫度以外的所有變數。", level: 6 },
    { word: "catalyst", phonetic: "/ˈkæt.ə.lɪst/", pos: "n.", cn: "催化劑；誘因", example: "This chemical acts as a catalyst in the reaction.", exampleCn: "這種化學物質在反應中起催化劑作用。", level: 6 },
  ],

  "法律犯罪": [
    { word: "crime", phonetic: "/kraɪm/", pos: "n.", cn: "犯罪；罪行", example: "The police are working hard to reduce crime.", exampleCn: "警察正在努力減少犯罪。", level: 4 },
    { word: "trial", phonetic: "/ˈtraɪ.əl/", pos: "n.", cn: "審判；試驗", example: "The murder trial lasted three weeks.", exampleCn: "謀殺案審判持續了三個星期。", level: 4 },
    { word: "victim", phonetic: "/ˈvɪk.tɪm/", pos: "n.", cn: "受害者；犧牲者", example: "The police interviewed the victim of the attack.", exampleCn: "警察採訪了襲擊的受害者。", level: 4 },
    { word: "suspect", phonetic: "/ˈsʌs.pekt/", pos: "n./v.", cn: "嫌疑人；懷疑", example: "Police have identified a suspect in the robbery.", exampleCn: "警察已確認搶劫案的嫌疑人。", level: 4 },
    { word: "arrest", phonetic: "/əˈrest/", pos: "v./n.", cn: "逮捕；拘留", example: "The officer arrested the thief.", exampleCn: "警員逮捕了小偷。", level: 4 },
    { word: "prison", phonetic: "/ˈprɪz.ən/", pos: "n.", cn: "監獄；監禁", example: "He was sentenced to five years in prison.", exampleCn: "他被判處五年監禁。", level: 4 },
    { word: "innocent", phonetic: "/ˈɪn.ə.sənt/", pos: "adj.", cn: "無辜的；清白的", example: "The defendant was found innocent of all charges.", exampleCn: "被告被裁定所有罪名不成立。", level: 4 },
    { word: "guilty", phonetic: "/ˈɡɪl.ti/", pos: "adj.", cn: "有罪的；內疚的", example: "The jury found him guilty of theft.", exampleCn: "陪審團裁定他盜竊罪名成立。", level: 4 },
    { word: "judge", phonetic: "/dʒʌdʒ/", pos: "n./v.", cn: "法官；判斷", example: "The judge sentenced the criminal to ten years.", exampleCn: "法官判處罪犯十年監禁。", level: 4 },
    { word: "penalty", phonetic: "/ˈpen.əl.ti/", pos: "n.", cn: "處罰；刑罰", example: "There is a heavy penalty for drunk driving.", exampleCn: "醉駕有嚴重刑罰。", level: 4 },
    { word: "witness", phonetic: "/ˈwɪt.nəs/", pos: "n./v.", cn: "目擊者；證人", example: "The witness saw the accident happen.", exampleCn: "目擊者親眼看到事故發生。", level: 4 },
    { word: "prosecution", phonetic: "/ˌprɒs.ɪˈkjuː.ʃən/", pos: "n.", cn: "起訴；檢察", example: "The prosecution presented strong evidence against the defendant.", exampleCn: "控方呈上了對被告的有力證據。", level: 6 },
    { word: "jurisdiction", phonetic: "/ˌdʒʊər.ɪˈsdɪk.ʃən/", pos: "n.", cn: "司法管轄權", example: "This matter falls outside the court's jurisdiction.", exampleCn: "此事超出法院的司法管轄範圍。", level: 6 },
    { word: "testimony", phonetic: "/ˈtes.tɪ.mə.ni/", pos: "n.", cn: "證詞；證言", example: "The witness gave testimony in court.", exampleCn: "證人在法庭上作出證詞。", level: 6 },
    { word: "verdict", phonetic: "/ˈvɜː.dɪkt/", pos: "n.", cn: "裁決；判決", example: "The jury delivered a not-guilty verdict.", exampleCn: "陪審團作出了無罪裁決。", level: 6 },
    { word: "surveillance", phonetic: "/səˈveɪ.ləns/", pos: "n.", cn: "監視；監控", example: "The police used surveillance cameras to catch the criminal.", exampleCn: "警察使用監控攝像機抓獲了罪犯。", level: 6 },
    { word: "extradition", phonetic: "/ˌek.strəˈdɪʃ.ən/", pos: "n.", cn: "引渡", example: "The government requested the extradition of the suspect.", exampleCn: "政府要求引渡嫌疑人。", level: 6 },
  ],

  "心理情感": [
    { word: "emotion", phonetic: "/ɪˈməʊ.ʃən/", pos: "n.", cn: "情緒；情感", example: "It is important to express your emotions healthily.", exampleCn: "以健康方式表達情緒非常重要。", level: 4 },
    { word: "anxiety", phonetic: "/æŋˈzaɪ.ə.ti/", pos: "n.", cn: "焦慮；憂慮", example: "Many students experience anxiety before exams.", exampleCn: "許多學生在考試前感到焦慮。", level: 4 },
    { word: "confidence", phonetic: "/ˈkɒn.fɪ.dəns/", pos: "n.", cn: "信心；自信", example: "Public speaking can boost your confidence.", exampleCn: "公開演講可以增強你的自信心。", level: 4 },
    { word: "mood", phonetic: "/muːd/", pos: "n.", cn: "心情；情緒", example: "Exercise can improve your mood significantly.", exampleCn: "運動能顯著改善你的心情。", level: 4 },
    { word: "memory", phonetic: "/ˈmem.ər.i/", pos: "n.", cn: "記憶；記憶力", example: "Playing chess is good for your memory.", exampleCn: "下棋對記憶力有好處。", level: 4 },
    { word: "behaviour", phonetic: "/bɪˈheɪ.vjər/", pos: "n.", cn: "行為；舉止", example: "The teacher praised the student for good behaviour.", exampleCn: "老師表揚了學生的良好行為。", level: 4 },
    { word: "attitude", phonetic: "/ˈæt.ɪ.tjuːd/", pos: "n.", cn: "態度；看法", example: "A positive attitude helps you overcome challenges.", exampleCn: "積極的態度幫助你克服挑戰。", level: 4 },
    { word: "personality", phonetic: "/ˌpɜː.sənˈæl.ɪ.ti/", pos: "n.", cn: "性格；個性", example: "She has a warm and friendly personality.", exampleCn: "她有溫暖友善的性格。", level: 4 },
    { word: "fear", phonetic: "/fɪər/", pos: "n./v.", cn: "恐懼；害怕", example: "Many people have a fear of public speaking.", exampleCn: "許多人對公開演講感到恐懼。", level: 4 },
    { word: "motivation", phonetic: "/ˌməʊ.tɪˈveɪ.ʃən/", pos: "n.", cn: "動機；積極性", example: "Motivation is essential for achieving your goals.", exampleCn: "動機對實現目標至關重要。", level: 4 },
    { word: "depression", phonetic: "/dɪˈpreʃ.ən/", pos: "n.", cn: "抑鬱；消沉", example: "Depression is one of the most common mental health conditions.", exampleCn: "抑鬱症是最常見的心理健康狀況之一。", level: 4 },
    { word: "trauma", phonetic: "/ˈtrɔː.mə/", pos: "n.", cn: "創傷；心理創傷", example: "Many soldiers suffer from trauma after war.", exampleCn: "許多士兵在戰後飽受創傷之苦。", level: 6 },
    { word: "phobia", phonetic: "/ˈfəʊ.bi.ə/", pos: "n.", cn: "恐懼症；恐懼", example: "She has a phobia of enclosed spaces.", exampleCn: "她患有密閉空間恐懼症。", level: 6 },
    { word: "resilience", phonetic: "/rɪˈzɪl.i.əns/", pos: "n.", cn: "復原力；韌性", example: "Children show great resilience in difficult situations.", exampleCn: "兒童在困難情況下表現出極大的復原力。", level: 6 },
    { word: "empathy", phonetic: "/ˈem.pə.θi/", pos: "n.", cn: "同理心；共情", example: "Good leaders show empathy towards their team members.", exampleCn: "好的領導者對團隊成員表現出同理心。", level: 6 },
    { word: "cognitive", phonetic: "/ˈkɒɡ.nɪ.tɪv/", pos: "adj.", cn: "認知的；認識的", example: "Cognitive development is rapid in early childhood.", exampleCn: "認知發展在幼兒期非常迅速。", level: 6 },
    { word: "perception", phonetic: "/pəˈsep.ʃən/", pos: "n.", cn: "感知；看法", example: "Our perception of the world is shaped by experience.", exampleCn: "我們對世界的感知由經歷所塑造。", level: 6 },
  ],

  "家居生活": [
    { word: "apartment", phonetic: "/əˈpɑːt.mənt/", pos: "n.", cn: "公寓；住宅", example: "She rents a small apartment near the city centre.", exampleCn: "她在市中心附近租了一間小公寓。", level: 4 },
    { word: "rent", phonetic: "/rent/", pos: "v./n.", cn: "租用；租金", example: "The rent for this flat is very expensive.", exampleCn: "這間公寓的租金非常昂貴。", level: 4 },
    { word: "furniture", phonetic: "/ˈfɜː.nɪ.tʃər/", pos: "n.", cn: "家具", example: "They bought new furniture for their living room.", exampleCn: "他們為客廳購買了新家具。", level: 4 },
    { word: "neighbor", phonetic: "/ˈneɪ.bər/", pos: "n.", cn: "鄰居", example: "My neighbor helps me with shopping when I am ill.", exampleCn: "當我生病時，我的鄰居幫我購物。", level: 4 },
    { word: "mortgage", phonetic: "/ˈmɔː.ɡɪdʒ/", pos: "n.", cn: "按揭；抵押貸款", example: "They took out a mortgage to buy their first home.", exampleCn: "他們辦了按揭貸款購買第一套房子。", level: 4 },
    { word: "electricity", phonetic: "/ɪˌlek.ˈtrɪs.ɪ.ti/", pos: "n.", cn: "電；電力", example: "Our electricity bill has increased this month.", exampleCn: "我們這個月的電費增加了。", level: 4 },
    { word: "appliance", phonetic: "/əˈplaɪ.əns/", pos: "n.", cn: "家電；器具", example: "Modern appliances make housework much easier.", exampleCn: "現代家電使家務輕鬆很多。", level: 4 },
    { word: "maintenance", phonetic: "/ˈmeɪn.tɪ.nəns/", pos: "n.", cn: "維修；保養", example: "Regular maintenance keeps the building in good condition.", exampleCn: "定期維護使大廈保持良好狀態。", level: 4 },
    { word: "facility", phonetic: "/fəˈsɪl.ɪ.ti/", pos: "n.", cn: "設施；設備", example: "The apartment block has excellent facilities.", exampleCn: "這幢公寓大廈設施優良。", level: 4 },
    { word: "property", phonetic: "/ˈprɒp.ə.ti/", pos: "n.", cn: "房產；財產", example: "Property prices have risen sharply this year.", exampleCn: "今年房價急劇上漲。", level: 4 },
    { word: "lease", phonetic: "/liːs/", pos: "n./v.", cn: "租約；租賃", example: "The lease for the apartment runs for one year.", exampleCn: "公寓的租約期限為一年。", level: 4 },
    { word: "renovation", phonetic: "/ˌren.əˈveɪ.ʃən/", pos: "n.", cn: "裝修；翻新", example: "The kitchen renovation cost more than expected.", exampleCn: "廚房裝修的費用超出預期。", level: 6 },
    { word: "sustainability", phonetic: "/səˌsteɪ.nəˈbɪl.ɪ.ti/", pos: "n.", cn: "可持續性", example: "Sustainability is a key consideration in modern housing design.", exampleCn: "可持續性是現代住宅設計的重要考慮因素。", level: 6 },
    { word: "amenity", phonetic: "/əˈmiː.nɪ.ti/", pos: "n.", cn: "便利設施", example: "The apartment complex offers many amenities.", exampleCn: "公寓大廈提供許多便利設施。", level: 6 },
    { word: "dwelling", phonetic: "/ˈdwel.ɪŋ/", pos: "n.", cn: "住所；住宅", example: "The survey counted all dwellings in the area.", exampleCn: "調查統計了該地區所有住所。", level: 6 },
    { word: "subsidy", phonetic: "/ˈsʌb.sɪ.di/", pos: "n.", cn: "補貼；津貼", example: "The government offers housing subsidies to low-income families.", exampleCn: "政府向低收入家庭提供住房補貼。", level: 6 },
  ],
};

export default vocabData;
